### ISSUE TITLE
Template is missing source_ami_id in the variables section

### ISSUE THREAD

**Issue by rickard-von-essen** [awslabs/amazon-eks-ami#1]
The template reference ```{{ user `source_ami_id`}}``` but no such user variable is declared. The `Makefile` also passes this as a variable.

**Comment by rickard-von-essen** [comment]
Hmm, this seems like a bug in packer...

**Comment by rickard-von-essen** [comment]
Packer issue hashicorp/packer#6473

**Comment by mbartsch** [comment]
It works for me, with packer 1.2.4, which version of packer are you running?

**Comment by rickard-von-essen** [comment]
Yeah, I realise it works, but it shouldn't, hence I filed hashicorp/packer#6473. When that is fixed this won't work.

**Comment by mbartsch** [comment]
Awesome, I'm not an expert on github, but I added the fix to my previous PR , see issue #2 for details.
