### ISSUE TITLE
Node fails to connect to master if cluster name is a number

### ISSUE THREAD

**Issue by rdavison** [awslabs/amazon-eks-ami#102]
There is a subtle bug in the `bootstrap.sh` script.

The template located at `files/kubelet-kubeconfig` correctly wraps the arguments to `aws-iam-authenticator` with double quotes.  However, when the `bootstrap.sh` replaces the placeholders in the template, it does so by first calling `kubectl config` to set the server endpoint, and then calling `sed` to set the cluster name.

In the first step, `kubectl` deserializes the YAML file, applies the change, and then serializes it back to disk.  Since the name of the placeholder  for the cluster name is `"CLUSTER_NAME"`, when it serializes back to disk, it realizes it is a string, and strips off the double quotes.

Next, when the `sed` script runs, it replaces `CLUSTER_NAME` with the (numerical) name of the cluster.  However, a number without quotes is later deserialized as a number, not as a string, and the node is unable to connect to the EKS master.

I propose swapping the order of the `kubectl config` command and the `sed` command.

**Comment by micahhausler** [comment]
Thanks!
