### ISSUE TITLE
Upgrade API VERSION from client.authentication.k8s.io/v1alpha1 to client.authentication.k8s.io/v1beta1

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#1020]
### What would you like to be added
Upgrade the API version from `client.authentication.k8s.io/v1alpha1` to `client.authentication.k8s.io/v1beta1`. The API version is referenced [here](https://github.com/awslabs/amazon-eks-ami/blob/v20220824/files/kubelet-kubeconfig#L18) and used by the [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) version currently used in the AMI - `0.5.0`. More details below.

### Why is this needed
The alpha API version is no longer supported in Kubernetes version 1.24.

### `aws-iam-authenticator` Note

This change requires upgrading the aws-iam-authenticator to `0.5.9` or any version with [this commit](https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/0221afb8e2a5d14a20a93473edc4c2aa7676ce95). After upgrading the API version, you'll see the following error if the `aws-iam-authenticator` is not upgraded as well:

```
getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1
```

If you're building your own AMI and not vending the `aws-iam-authenticator` from the EKS buckets, you'll need to update it. As of 9/14/2022, the `0.5.0` authenticator is stored in the binary buckets, but we'll update that as part of resolving this issue.

**Future Improvement:**

[This PR](https://github.com/awslabs/amazon-eks-ami/pull/653) makes a change that would allow us to remove the dependency on the `aws-iam-authenticator` entirely by using the AWS CLI to call `aws eks get-token` instead of calling the authenticator. However, as of 9/14/2022, the AmazonLinux yum repos use an older version of the AWS CLI that doesn't include [this change](https://github.com/aws/aws-cli/commit/99d0fa1c96f7e76a570fe671f099163ec859cde7), which is required for resolving this issue. Once the CLI is updated, we should be able to remove the dependency altogether.

**Comment by cartermckinnon** [comment]
This was addressed in https://github.com/awslabs/amazon-eks-ami/releases/tag/v20221112.
