### ISSUE TITLE
Remove Docker from AMI for Kubernetes version 1.24+

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#1025]
**What would you like to be added**:
[Per this issue](https://github.com/awslabs/amazon-eks-ami/issues/1024), we're removing docker support for Kubernetes version 1.24+. As a follow up to that change, we should branch all docker-related logic to be ignored for 1.24+, including not installing it.

**Why is this needed**:
We can reduce the size of the AMI and the vulnerability surface area by removing unnecessary bits needed for supporting docker for 1.24+ AMIs. Once 1.23 is deprecated, we can remove all Docker log entirely.

**Comment by abhinesh-nn** [comment]
Did we make any changes for not installing docker? The changes which are there are mostly related to ignoring docker-related changes.
