### ISSUE TITLE
Update AMI to include kernel 5.4.191 (duplicate)

### ISSUE THREAD

**Issue by y0zg** [awslabs/amazon-eks-ami#1047]
Cloned: https://github.com/awslabs/amazon-eks-ami/issues/943

When running Spring 2.6.3 we are still seeing this error.

```
Duplicate accept detected. 
This is a known OS bug. 
Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
--
stacktrace | 

java.io.IOException: 
Duplicate accept detected. 
This is a known OS bug. 
Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298 	

at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:545) 	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) 	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) 	at java.base/java.lang.Thread.run(Unknown Source)
The thread linked in the exception indicates there is a kernel fix for this, which has been backported to the LTS kernels.
```

5.4.191 includes the fix (https://www.spinics.net/lists/stable-commits/msg244651.html) , https://lwn.net/Articles/892814/

and it was added into https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220610 but I seems it's not included into the latest AMIs like `amazon-eks-node-1.23-v20220914`

**Comment by cartermckinnon** [comment]
I reached out to Amazon Linux to determine whether this patch is included in their kernel builds; I'll relay the response here.

**Comment by cartermckinnon** [comment]
This patch *is* included in recent kernel builds, but you need to also update Tomcat to  8.5.75+, more info here: https://tomcat.apache.org/tomcat-8.5-doc/changelog.html

An internal user ran into the same thing and this resolved it for them. Let us know if that doesn't work!
