### ISSUE TITLE
About contributing EFS CSI Driver

### ISSUE THREAD

**Issue by khacminh** [awslabs/amazon-eks-ami#105]
Hi,

Currently, Kubernetes (and EKS) doesn't support EFS mounting using **amazon-efs-utils** package. The only way to connect to EFS is using NFS Persistent Volume. In this way, the advances of EFS cannot be used, such as **TLS** connection.

It would be great if AWS can contribute an EFS CSI Driver for Kubernetes.

Thanks

**Comment by leakingtapan** [comment]
Hi @khacminh,

Thanks for reaching out. We are planning on adding EFS CSI driver. Would like to understand more use cases from  you. Seems TLS connection is one.

**Comment by khacminh** [comment]
Hi @leakingtapan,

It's great to hear about that. I think the EFS CSI driver should support:
- TLS connection (with TLS healthcheck as efs-utils). This is the main different with normal NFS.
- The Multi-AZ mount targets. I hope the driver could connect to the mount target in the same AZ or subnet (for fastest latency when deploying Multi-AZ cluster)

Thanks

**Comment by gregsidelinger** [comment]
TLS is the use case I currently care about as my security group says I need to have it.

**Comment by micahhausler** [comment]
I'm going to close this issue as there is not any actionable request for the AMI

**Comment by leakingtapan** [comment]
@khacminh @gregsidelinger if you have any further requests regarding CSI drivers or kubernetes on AWS in general, you could also post it in kubernetes/community github repo, and tag is with sig-aws. [Here](https://github.com/kubernetes/community/tree/master/sig-aws) is the home page of our open source projects that are owned by AWS

**Comment by khacminh** [comment]
Hi @leakingtapan,

Do I need to copy this feature request to `kubernetes/community`

**Comment by leakingtapan** [comment]
@khacminh Please do. thx

**Comment by healyje** [comment]
I'd second the call for a CSI driver and maybe make it so you could use ENS FSx via CSI.
