### ISSUE TITLE
runc, containerd and docker versions are locked and vulnerable to ALASDOCKER-2022-020 / ALASDOCKER-2022-021

### ISSUE THREAD

**Issue by d-koppenhagen** [awslabs/amazon-eks-ami#1052]
The packages `runc`, `containerd` and `docker` versions are locked and vulnerable according to the Amazon Linux 2 Security Advisory:

- https://alas.aws.amazon.com/AL2/ALASDOCKER-2022-020.html
- https://alas.aws.amazon.com/AL2/ALASDOCKER-2022-021.html

checking the packages inside the AMI gave us the information that the versions are locked:

```bash
$ yum versionlock
Loaded plugins: priorities, update-motd, versionlock
0:runc-1.1.3-1.amzn2.*
0:containerd-1.6.6-1.amzn2.*
0:docker-20.10.17-1.amzn2.*
versionlock list done
```

**Question**

As far as we understand, we need to wait for a new AMI version to fix ALASDOCKER-2022-020 / ALASDOCKER-2022-021 permanently, is this correct?
Is there ETA for the next release?
Or is there another (better) solution that we could implement (see workaround below)

**Workaround**

```bash
yum versionlock delete runc containerd docker
yum update
```

However this workaround introduces the risk of getting incompatible versions in the future.

**Environment**:
- AWS Region: eu-central-1
- Instance Type(s): N/A
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `eks.2`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): `1.23`
- AMI Version: `amazon-eks-node-1.23-v20220926`
- Kernel (e.g. `uname -a`): `5.4.214-120.368.amzn2.x86_64 #1 SMP Thu Sep 29 01:07:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-02dd04850de58599e"
BUILD_TIME="Mon Sep 26 21:54:23 UTC 2022"
BUILD_KERNEL="5.4.209-116.367.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by TrentPetersen04** [comment]
The PRs https://github.com/awslabs/amazon-eks-ami/pull/1056 and https://github.com/awslabs/amazon-eks-ami/pull/1055 seem to have addressed these findings. @mmerkes @cartermckinnon Would it be possible to get a tagged release that contains these package updates?

**Comment by cartermckinnon** [comment]
These changes will be included in the next AMI build, which is working its way through our release process now. I'll update this issue when it ships 👍

**Comment by nmangalia** [comment]
Hello, I am facing the same issue. What is the recommendation here :

1. Applying the work around which in future my create version mismatch/compatibility problems if updated all the docker repo packages individually.

yum versionlock delete runc containerd docker
yum update

or 

2. wait for the new EKS AMIs to be built and released. Also, do we know when new EKS AMIs will be built, released. 

--
Naresh Mangalia

**Comment by jaypipes** [comment]
Recommendation is to wait for the next AMI release, which is currently making its way through the release pipelines, as @cartermckinnon mentioned above.

**Comment by nmangalia** [comment]
> Recommendation is to wait for the next AMI release, which is currently making its way through the release pipelines, as @cartermckinnon mentioned above.

Great, thank you.

**Comment by d-koppenhagen** [comment]
A new version was released recently: 
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220926

**Comment by d-koppenhagen** [comment]
Oh,Link was wrong: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20221027 ... but I've seen the release has been recalled, so I reopen this issue for now.

**Comment by mmerkes** [comment]
We're working on another AMI release that will address these CVEs. There was a regression in the Linux kernel, and we're working with AmazonLinux to address it as well. The next AMI release will be pinned to a known good kernel version.

**Comment by jaypipes** [comment]
New AMI released: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20221101
