### ISSUE TITLE
pache Log4j Unsupported Version Detection(Amazon Linux 2)

### ISSUE THREAD

**Issue by noorins** [awslabs/amazon-eks-ami#1053]
Hi, 

I am looking into some of the vulnerabilities showing up on our secure state finder and see that many of our instances have the following issue showing up:

_Apache Log4j Unsupported Version Detection_

- **The version of amazon linux2 being used is as below:**

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

- **When I check for java version i don't see anything installed:**

# rpm -qi java

package java is not installed
# yum info "java"
Loaded plugins: priorities, update-motd, versionlock
Error: No matching Packages to list

- **Currentl log4j verison:**

/var/lib/docker/overlay2/4ac68109d1f2c5de9c7c628a24edaded469a7ed9c91514d76f90d7e018034723/diff/opt/spark/jars/log4j-1.2.17.jar
  Installed version : 1.2.17
  
 Taking this into account is it still vulnerable to attack and if so which version of log4j is recommended and what command would be advisable to use to fix the same.

**Comment by cartermckinnon** [comment]
Your scanning tool is finding a log4j JAR *within* a container namespace on your node; you need to exclude it from your Spark classpath (or update it).
