### ISSUE TITLE
Can you install the slack integration so we can get release notifications?

### ISSUE THREAD

**Issue by dmcnaught** [awslabs/amazon-eks-ami#1054]
**What would you like to be added**:
Github slack integration
https://github.com/integrations/slack

**Why is this needed**:
So we can get release notifications in our slack channels

Current output
`/github subscribe awslabs/amazon-eks-ami`
![Screen Shot 2022-10-20 at 10 35 58 AM](https://user-images.githubusercontent.com/5974394/197007295-6be96f3c-40a9-4701-b1ae-5d4f900ecaf3.png)

**Comment by cartermckinnon** [comment]
I would love to! We have to go through an internal approval process for this integration; I can't give you an ETA, unfortunately -- but I'll update here as things progress.

**Comment by dmcnaught** [comment]
Sounds good, thanks @cartermckinnon

**Comment by ad-m-ss** [comment]
No need to install any apps to Slack / GitHub, you can also use `/feed subscribe https://github.com/awslabs/amazon-eks-ami/releases.atom` to get notification about new releases. See also https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack . 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/99484706/199608566-850fb03e-d4cd-4235-a715-ea181d19d46f.png">

**Comment by dmcnaught** [comment]
Added, thanks!
