### ISSUE TITLE
Cleanup old docker images

### ISSUE THREAD

**Issue by dpankros** [awslabs/amazon-eks-ami#107]
**What would you like to be added**:
Over time our EKS node disks start to fill up because old containers are not being cleaned periodically (or at least I've never seen them get cleaned).  I can cleanup a good deal of space by running `docker rmi ${docker images -q)` manually, but it would be great if periodically (maybe a daily cronjob?) the old images could be removed.

This feature is [available for ECS](https://aws.amazon.com/premiumsupport/knowledge-center/container-image-cleanup-ecs/).

**Why is this needed**:
It could prevent out of disk-space errors, which is my primary concern.

**Comment by deiwin** [comment]
Should be managed by kubelet: https://v1-10.docs.kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

**Comment by dpankros** [comment]
Gotcha.  Since the kubelet config is somewhat hidden in EKS, I missed that part.  Ops.
