### ISSUE TITLE
Build custom EKS AMI using Red Hat source AMI

### ISSUE THREAD

**Issue by ericwongwh** [awslabs/amazon-eks-ami#1084]
I want to run Red Hat on EKS work nodes. I wonder if I can apply this script on my existing Red Hat AMI. Is this script `https://github.com/awslabs` designed to support other Linux distro like Red Hat or CentOS? If not, is there any recommendation on building custom EKS AMI using Red Hat distro?

**Comment by cartermckinnon** [comment]
We don't currently support any Linux other than Amazon Linux 2. But, AL2 is a close relative of RHEL7, so it shouldn't be unreasonable to use this template with a Red Hat base.

**Comment by srujankujmar** [comment]
Is it still the same @cartermckinnon that it won't support any other linux or is it resolved?

**Comment by franramvel** [comment]
> Is it still the same @cartermckinnon that it won't support any other linux or is it resolved?

Just for the record, there are other repositories for another linux distributions, for example RH:

https://github.com/aws-samples/amazon-eks-ami-rhel

**Comment by cartermckinnon** [comment]
That repository is a sample template. There are no official builds distributed that use that template, there is no integration with the EKS service, and the AMI produced by the template is not subject to any automated testing.

We don't have any plans today to provide official EKS AMIs that are based on any distro other than Amazon Linux, so I don't think this repository is the right place to add template(s) intended for other distros.
