### ISSUE TITLE
Use external cloud provider instead of aws

### ISSUE THREAD

**Issue by vpineda1996** [awslabs/amazon-eks-ami#1096]
**What would you like to be added**:
I would like the `kubelet` to be initialized & use the external cloud provider rather than AWS. We should provide the user an option to customize which provider it uses on the worker node. 

**Why is this needed**:
Using an external cloud provider is the default way that EKS creates clusters post 1.22. We should give the option to customers to use the external cloud provider rather than the in-tree aws provider.

**Comment by cartermckinnon** [comment]
We're targeting 1.25 to switch to the external cloud provider, but we don't currently plan to make this configurable. It'll just toggle based on the k8s version.
