### ISSUE TITLE
 Question about MaxPods limits

### ISSUE THREAD

**Issue by mlespiau** [awslabs/amazon-eks-ami#11]
Why does r4.16xlarge instance have a higher MaxPods limit than the x1.32xlarge instance?

**Comment by bshelton229** [comment]
@mlespiau these limits come from the number of enis and ip addresses per eni that can be attached to each instance type. [You can find the chart from AWS here.]
(https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html).

The AWS vpc cni plugin allocates a real vpc ip address to each pod by attaching enis to the instance, hence these limits being subject to the current eni configurations available for each instance type.

**Comment by micahhausler** [comment]
@bshelton229 is correct, you can see the formula we use to calculate this here:

https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml#L107-L114
