### ISSUE TITLE
Add nvidia debug script to EKS Log Collect Script

### ISSUE THREAD

**Issue by sidewinder12s** [awslabs/amazon-eks-ami#1113]
**What would you like to be added**:

Add the `nvidia-bug-report.sh` script to the EKS Log Collect Script, check and run it when on GPU nodes.

**Why is this needed**:

If you need to collect logs on a GPU node with GPU issues, this output is required.

**Comment by cartermckinnon** [comment]
Does that script ship with the nvidia drivers? Running it if it's present and including the output in the log archive sounds fine to me; feel free to open a PR.

**Comment by sidewinder12s** [comment]
Yup, its in `/usr/bin`

**Comment by cartermckinnon** [comment]
This has since been added 👍
