### ISSUE TITLE
root user executing bootstrap.sh 

### ISSUE THREAD

**Issue by abolduc10** [awslabs/amazon-eks-ami#1117]
**Environment**: dev
- AWS Region: us-east-1
- Instance Type(s): any
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): any, but using EKS 1.22
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version: using custom ami, but the bootstrap.sh is the same in ami-07e6147adfae7f7b3
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
Can you add more details to this issue? Is this a question, a bug report, etc?
