### ISSUE TITLE
s3 bucket redirect using us-east-1

### ISSUE THREAD

**Issue by mikehalof** [awslabs/amazon-eks-ami#112]
**What happened**:
packer build failed with this error
   amazon-ebs: ./bridge
    amazon-ebs: Downloading binaries from: s3://amazon-eks
    amazon-ebs: --2018-12-07 10:55:27--  https://s3.amazonaws.com/amazon-eks/1.10.3/2018-07-26/bin/linux/amd64/kubelet
    amazon-ebs: Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.237.37
    amazon-ebs: Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.237.37|:443... connected.
    amazon-ebs: HTTP request sent, awaiting response... 301 Moved Permanently
    amazon-ebs: Location: unspecified
    amazon-ebs: ERROR: Redirection (301) without location.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 8
**What you expected to happen**:
New ami to be built
**How to reproduce it (as minimally and precisely as possible)**:
Just clone the repo, modify eks-worker-al2-json to use us-east-1 region and run make

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): m4.large
- EKS Platform version (use `aws eks describe-cluster --name eks-mhausler-11-16-2018 --query cluster.platformVersion`): 1.10
- Kubernetes version (use `aws eks describe-cluster --name eks-mhausler-11-16-2018 --query cluster.version`): 1.10
- AMI Version: N/A
- Kernel (e.g. `uname -a`): N/A
- Release information (run `cat /tmp/release` on a node): N/A

```
```v.1.0

**Comment by micahhausler** [comment]
Thanks for opening this issue. KubeCon is this week and it will take us a few extra days to review this.

**Comment by travcunn** [comment]
@mikehalof Be sure to only change `aws_region` varaible in the `eks-worker-al2.json` file. If you also change the `binary_bucket_region` variable, you will run into problems because currently we host required binaries in an S3 bucket in the us-west-2 region.

I was successfully able to build this AMI in the us-east-1 region with this change to `eks-worker-al2.json`:

```diff --git a/eks-worker-al2.json b/eks-worker-al2.json
index 76a951f..436d9a8 100644
--- a/eks-worker-al2.json
+++ b/eks-worker-al2.json
@@ -1,6 +1,6 @@
 {
   "variables": {
-    "aws_region": "us-west-2",
+    "aws_region": "us-east-1",
     "ami_name": "amazon-eks-node-{{timestamp}}",
     "binary_bucket_name": "amazon-eks",
     "binary_bucket_region": "us-west-2",```

**Comment by mikehalof** [comment]
@travcunn suggestion was great. I was able to run my task
Closing the issue.
MikeH
