### ISSUE TITLE
How should I install the vercmp command by manual 

### ISSUE THREAD

**Issue by keanlee** [awslabs/amazon-eks-ami#1128]
Because I need to build 1.22 custom AMI. after building it can not finish the user data .error message shows no vercmp command found

**Comment by keanlee** [comment]
I use the`Linux version 3.10.0-1160.81.1.el7.x86_64 (mockbuild@x86-vm-38.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )` as kernel version

**Comment by keanlee** [comment]
oh， I saw this https://github.com/awslabs/amazon-eks-ami/tree/master/files/bin. Maybe I need to add this to my local build env? but how to add the file to ami?

**Comment by cartermckinnon** [comment]
Use a Packer `file` provisioner to add resources to the AMI, like: https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L140-L149

And then you can add the utilities to your `PATH` in one of your installation scripts, or with an inline `shell` provisioner.
