### ISSUE TITLE
Systemd reexecuting causes docker start to fail

### ISSUE THREAD

**Issue by xiangyanw** [awslabs/amazon-eks-ami#1130]
**What happened**:
I tried to use overrideBootstrapCommand to customize kubelet parameters. However, after I create the manage node group, docker service of its node fails to start. This issue can be recreated.

From log files I found below info:

1. /etc/eks/bootstrap.sh failed when restarting docker.
```
+ systemctl daemon-reload
+ systemctl enable docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
+ **systemctl restart docker**
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
++ err_report 567
++ echo 'Exited with error on line 567'
Exited with error on line 567
Dec 16 13:01:36 cloud-init[2580]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
```
3. In the system log file (message), I can see that systemd reexecuted itself when docker was starting. Then cloud-init disconnected from D-Bus.
```
Dec 16 13:01:36 ip-192-168-92-84 dockerd: time="2022-12-16T13:01:36.333107248Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 16 13:01:36 ip-192-168-92-84 **systemd: Reexecuting.**
Dec 16 13:01:36 ip-192-168-92-84 systemd: systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN) 
Dec 16 13:01:36 ip-192-168-92-84 systemd: Detected virtualization amazon.
Dec 16 13:01:36 ip-192-168-92-84 systemd: Detected architecture x86-64.
Dec 16 13:01:36 ip-192-168-92-84 cloud-init: Warning! D-Bus connection terminated.
Dec 16 13:01:36 ip-192-168-92-84 cloud-init: Failed to wait for response: Connection reset by peer
Dec 16 13:01:36 ip-192-168-92-84 cloud-init: ++ err_report 567
```
**What you expected to happen**:
Update kubelet configure and start docker & kubelet service successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create a managed node group using eksctl.

eksctl create ng -f overrideBootstrapCommand.conf

Content of the config file is as below:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-northeast-1

managedNodeGroups:
  - name: mng-1
    instanceType: t3.medium
    ami: ami-0e55038b16719eb0b
    desiredCapacity: 1
    minSize: 0
    maxSize: 1 
    ssh:
      allow: true
      publicKeyName: defaultJP
    overrideBootstrapCommand: |
      #!/bin/bash
      set -o xtrace
      set -x
      bash -x /etc/eks/bootstrap.sh eksworkshop-eksctl --kubelet-extra-args '--image-gc-high-threshold=70 --image-gc-low-threshold=50'
```

**Anything else we need to know?**:

If I add below parameters to bootstrap.sh, it would be working fine.
--b64-cluster-ca
--apiserver-endpoint
--dns-cluster-ip

**Environment**:
- AWS Region: ap-northeast-1
- Instance Type(s): OD
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.11
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- AMI Version: ami-0e55038b16719eb0b
- Kernel (e.g. `uname -a`): 5.4.219-126.411.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0c90e1cacda57dac6"
BUILD_TIME="Sat Nov 12 04:15:46 UTC 2022"
BUILD_KERNEL="5.4.219-126.411.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
The eksctl folks should take a look at this first, I would open an issue in weaveworks/eksctl.

**Comment by xiangyanw** [comment]
> The eksctl folks should take a look at this first, I would open an issue in weaveworks/eksctl.

May I know what is the link of the issue in weaveworks/eksctl? Thanks.
