### ISSUE TITLE
No option to use internal ECR repos for add-on images using variable ECR_URI

### ISSUE THREAD

**Issue by nshelke777** [awslabs/amazon-eks-ami#1132]
**What happened**:
In an environment which requires FIPS ./files/bootstrap.sh and ./script/install-worker.sh used the standard ECR URL, There is no option to pass a custom ECR_URI.

This can't be easily set in this code: ./script/install-worker.sh
  `384.  ECR_URI=$(/etc/eks/get-ecr-uri.sh "${BINARY_BUCKET_REGION}" "${AWS_DOMAIN}")`
Basically we should some option/variable to pass a custom ECR_URI to use internal ECR for all image pulls like coredns, pause, kube-proxy, amazon-k8s-cni etc.

**What you expected to happen**:
To use internal fips compliant ECR with all these add-on images to passed.
Update bootstrap.sh with:

- A variable named like `$ECR_URI` which defaults to regional ecr.
- A switch of `--ecr_uri` which can set as a variable.
- Update the line above to use that variable.

**How to reproduce it (as minimally and precisely as possible)**:
Build a new eks cluster without outbound connection:
  Output:
- EKS nodes - will be in Not Ready state
- Pods - aws-node -> Will show Read Timeout errors since it can't reach to public ECR
- Pods - kube-proxy -> Same errors since cannot reach out to public ECR

**Anything else we need to know?**:

**Environment**: Prod(Federal Complaint)
- AWS Region: us-gov-west-2
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 1.22

```
```

**Comment by seanorama** [comment]
This is also another FIPS issue, as there is no way to tell it to use a FIPS ECR (whether that be the AWS default or customer managed).

**Comment by seanorama** [comment]
We may be misunderstanding how the `ECR_URI` field is used.

Is it used at each startup (or 1st launch) of an EKS node? Or is it only used during image build?

**What is being looked for in this ticket is how to change the ECR endpoint for the EKS "add-ons".**

**Comment by cartermckinnon** [comment]
Addons are a separate issue; the only use of ECR in this repository is for the Kubernetes pause/sandbox container image. There was work being done in #1028 to handle that case, but that branch needs some love.

The recent work to [cache container images](https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#container-image-caching) during the build process could also allow pulling from the `ecr-fips` endpoint. Feel free to open a PR!

**Comment by cartermckinnon** [comment]
Pulling the sandbox image from the `ecr-fips` endpoint is now possible: https://github.com/awslabs/amazon-eks-ami/blob/e99201099a3c4752af465c03bd5dedda0a729ca8/files/get-ecr-uri.sh#L113-L117
