### ISSUE TITLE
Better to keep AWS CLI version aligned

### ISSUE THREAD

**Issue by guessi** [awslabs/amazon-eks-ami#1134]
**What would you like to be added**:

Keep the AWS CLI version aligned.

**Why is this needed**:

Recently introduced AWS CLI `v2` into build scripts at #1066 and fix the path issue later on #1102.

However, there are still 2 more scripts will try to setup AWS CLI `v1` if user try to run `log-collector-script` with SSM,

* https://github.com/awslabs/amazon-eks-ami/blob/v20221112/log-collector-script/linux/eks-ssm-content.json#L27-L36
* https://github.com/awslabs/amazon-eks-ami/blob/v20221112/log-collector-script/windows/eks-ssm-content.json#L25-L34

Which might cause inconsistent AWS CLI output if there's some `$PATH` order issue.

After checking commit history, the scripts were introduced 3 years ago
* https://github.com/awslabs/amazon-eks-ami/pull/354/files

**Discussion**:

* Do we need to install AWS CLI if we had already have it installed while baking AMI? maybe we should remove it?

**Comment by cartermckinnon** [comment]
> Do we need to install AWS CLI if we had already have it installed while baking AMI? maybe we should remove it?

The log collector script is intended to be minimally useful on custom AMI's, which may not already have the AWS CLI. Feel free to PR the script to install v2 instead of v1.

**Comment by guessi** [comment]
Will do 👍
