### ISSUE TITLE
Possible ways to support estargz / improve pull speed

### ISSUE THREAD

**Issue by john-zielke-snkeos** [awslabs/amazon-eks-ami#1139]
Is there a way support for estargz could be added to the eks AMI? Especially for large images (~12GB) , e.g. for ML training, pulling a private image from the ECR in the same region can take quite long (~2min).

**Comment by cartermckinnon** [comment]
This seems like the gist of the necessary changes: https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md#install-stargz-snapshotter-for-containerd-with-systemd

@john-zielke-snkeos If you can share your experience using this feature, it'd be helpful.

**Comment by sidewinder12s** [comment]
Looked like AWS was doing some work in this space: https://github.com/awslabs/soci-snapshotter

**Comment by john-zielke-snkeos** [comment]
I have not yet worked with the estargz, but our ML images can be >10GB in size and this will cause them to take >2 minutes to pull from an ecr in the same region. To reduce latency for training runs, we could either optimize images (which every team would have to deal with), or just implement this and enable faster startup times.
Therefore support for this would be nice. 

I saw that AWS is developing soci, but it looks like it's still in an early phase, so I am wondering if that will be ready for use soon. Maybe someone has more insight into how stable that feature is already.

**Comment by cartermckinnon** [comment]
The SOCI snapshotter folks have a doc now that walks through using it on our AL2023 AMI's: https://github.com/awslabs/soci-snapshotter/blob/main/docs/eks.md

We may (eventually) ship the SOCI snapshotter in our AMI, but that's TBD. At this time we have no plans to include the stargz snapshotter.
