### ISSUE TITLE
Add c5n support

### ISSUE THREAD

**Issue by tsmgeek** [awslabs/amazon-eks-ami#115]
Add support for c5n instance type

**Comment by micahhausler** [comment]
Thanks for opening this issue. KubeCon is this week and it will take us a few extra days to review this.

**Comment by craftyc0der** [comment]
any progress on this?

**Comment by micahhausler** [comment]
As stated on other instance type issues, this requires a CNI update first.

**Comment by ishin6** [comment]
@micahhausler could you explain what you mean by CNI update? And Does eks support c5n's?

**Comment by JoshuaOnScale** [comment]
C5Ns appear in the amazon vpc CNI code. Are we ready to roll now?
https://github.com/aws/amazon-vpc-cni-k8s/blob/a7d65e3f8d18a70fe5ec84a03aaeb5e53c102e6b/pkg/awsutils/vpc_ip_resource_limit.go

**Comment by mogren** [comment]
Hi, to be more specific. Support for the c5n instance family was added to the CNI [back in December](https://github.com/aws/amazon-vpc-cni-k8s/commit/d2616b1db2e19674fb0bd0ff0451740a020ba48e#diff-c187f3aa608a63c06b02ff7a89c8111cR222), but the 1.3 branch was cut before that commit and doesn't include the new instances. Building the latest mainline of the CNI and using that should work. 

We plan on getting a 1.4 release out soon. Release milestone here: https://github.com/aws/amazon-vpc-cni-k8s/milestone/5

**Comment by JoshuaOnScale** [comment]
Do you have a ball park for release date? I won't hold you to it, just want an order of magnitude.

**Comment by aaomoware** [comment]
@JoshuaOnScale 

any luck with the c5n suport release?

```
aws-routed-eni/ipamd.log.2019-03-08-17:2019-03-08T17:49:33Z [INFO] Failed to retrieve ENI IP limit: vpc ip resource(eni ip limit): unknown instance type
aws-routed-eni/ipamd.log.2019-03-08-17:2019-03-08T17:49:33Z [ERROR] Failed to get eni limit due to unknown instance type c5n.4xlarge````

**Comment by JoshuaOnScale** [comment]
> @JoshuaOnScale
> 
> any luck with the c5n suport release?
> 
> ```
> aws-routed-eni/ipamd.log.2019-03-08-17:2019-03-08T17:49:33Z [INFO] Failed to retrieve ENI IP limit: vpc ip resource(eni ip limit): unknown instance type
> aws-routed-eni/ipamd.log.2019-03-08-17:2019-03-08T17:49:33Z [ERROR] Failed to get eni limit due to unknown instance type c5n.4xlarge````
> ```

No news yet.

**Comment by mogren** [comment]
Instead of completing and verifying the 1.4.0 milestone, I'll try to get a 1.3.3 release out to fix this really soon:

* Add support for a1 and c5n instance families: [ca500d767b18](https://github.com/aws/amazon-vpc-cni-k8s/commit/ca500d767b188f31fa68be199cc968247940e150)

**Comment by ishin6** [comment]
any updates on the c5n release?

**Comment by aaomoware** [comment]
for those still facing issues with c5n instance family, or any other instance family, and are using AWS EKS, you can upgrade to the latest by apply the current release of CNI

```
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/aws-k8s-cni.yaml
```

see documentation here
```
https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html
```

for CNI version v1.3.3 to work on c5n, or any instance family, the eni-max-pods.txt file needs updating with the instance type and Mapping number.  the mapping numbers for the c5n families is listed below:
```
c5n.large 27
c5n.xlarge 56
c5n.2xlarge 56
c5n.4xlarge 232
c5n.9xlarge 232
```

to work out your own instance family type mapping numbers see [here](# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI
) 

and the calculation is: 
```number of ENI * (number of IPv4 per ENI - 1)  + 2
```
example of c5n.2xlarge mapping number workout will be
```
4×(15−1) = 56
```

**Comment by voxxit** [comment]
If there is an upcoming AMI release for this, that would be prefered so we don't need to change up our user data. See #190

**Comment by voxxit** [comment]
Actually just kidding :) #236

**Comment by mogren** [comment]
Fixed long time ago..
