### ISSUE TITLE
Will EKS support the new Amazon Linux AMI?

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [awslabs/amazon-eks-ami#1151]
Are there plans for the EKS AMIs to be built off of the new Amazon Linux image vs Amazon Linux 2?
The Amazon Linux 2 AMI has many critical CVEs that are not updatable currently via the yum repos that come with the Amazon Linux 2 AMI

We ran a scan against the latest 1.24 EKS AMI and it shows 30 Critical CVEs, that we cannot update with the repos that yum currently has.

**Comment by cartermckinnon** [comment]
Are you referring to Amazon Linux 2022 or just the latest AL2 AMI version? Which tool are you scanning with?

**Comment by lorelei-rupp-imprivata** [comment]
The Amazon Linux 2022. Is that ever going to be supported with EKS? 

We are using lacework, it was showing things like curl out of date and python3 can only upgrade so far with yum etc, many other packages too, that yum believes are fully up to date according to the repos

**Comment by cartermckinnon** [comment]
We plan to support it, yes; but AL2022 is not yet GA.

We use ALAS security bulletins to determine the severity of vulnerabilities in the AMI's packages. From a cursory glance, it looks like Lacework relies on these as well, but I can't vouch for that integration.

I see a handful of `Important` bulletins published on January 18 -- those updates will be included in the next AMI release, which should happen in the next 7 days.
