### ISSUE TITLE
AWS inspector report vulnerabilities on the latest AMI

### ISSUE THREAD

**Issue by omerlh** [awslabs/amazon-eks-ami#1155]
**What happened**:
We are running EKS with the latest AMI version (ami-03a30cc1dda93f173) and we noticed there are vulnerabilities reported (critical and high) by AWS inspector.

**What you expected to happen**:
No vulnerabilities reported 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a cluster and check AWS inspector for vulnerabilities report 

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): t3.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.9
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.22
- AMI Version: ami-03a30cc1dda93f173
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
We have an AMI build working its way through our release process; I currently expect it to be available in all regions on Feb. 1.

**Comment by omerlh** [comment]
Thank you!
