### ISSUE TITLE
Upgrade Containerd to v1.6.9

### ISSUE THREAD

**Issue by ntwkninja** [awslabs/amazon-eks-ami#1159]
[upstream issue](https://github.com/containerd/containerd/issues/7392)

**Comment by dims** [comment]
isn't that for 1.7.x @ntwkninja ... for 1.6 branch it's this one right? https://github.com/containerd/containerd/pull/7438

**Comment by jeff-mccoy** [comment]
It was cherry-picked into 1.6.9: https://github.com/containerd/containerd/releases/tag/v1.6.9

**Comment by cartermckinnon** [comment]
I'm going to close this one as a duplicate of #1162, track progress there 👍
