### ISSUE TITLE
Dynamic ENI limits file

### ISSUE THREAD

**Issue by tsmgeek** [awslabs/amazon-eks-ami#116]
Add ability to specify ENI limits file as URI or B64 encoded file, this could be via an append or replace.
Users could point that if they wished to the github repo or their own location. If anything other than 200 is returned or file does not contain header then revert to locally packaged ENI file.
This would allow people to use newer instances without waiting for updated AMI to be released or packaging their own.

**Comment by micahhausler** [comment]
Thanks for opening this issue. KubeCon is this week and it will take us a few extra days to review this.

**Comment by micahhausler** [comment]
The difficulty with this solution is that even we pulled a file over the network and used it for eifjccglverrulunbjgfbrufjjlubhlrijclvbcidhfj
, our [CNI provider](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/awsutils/vpc_ip_resource_limit.go) still needs to be built with support the new instance type. Unfortunately, our process right now is:

* New instance type announced
* Release new CNI with updated instance types, set new CNI version as default for new EKS clusters
* Release new AMI with updated instance types

I'll close this issue out for now, but this is a process we're investing in making better, more dynamic, and less painful
