### ISSUE TITLE
Make awscli instalation more configurable

### ISSUE THREAD

**Issue by im-wanyama** [awslabs/amazon-eks-ami#1164]
**What would you like to be added**:

Currently we can't run the install-worker.sh script because the base AMI we use is CIS hardened which prevents executable files from running within /tmp.

Could we make the process of installing awscli more configurable?

For example allowing the user to specify where they download/run the install executable or allowing to user to install awscli via yum, irrespective of what binary bucket they've specified.

**Why is this needed**:

This will allow users more flexibility in using the install-worker.sh script and account for variance in setup/requirements.

**Comment by cartermckinnon** [comment]
Feel free to PR a change to the working directory if `/tmp` doesn't work for your use case: https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L130

Just make sure you `rm` the zip archive and extracted installer.

**Comment by ShibraAmin18** [comment]
@cartermckinnon changed `/tmp` to `/home/ec2-user ` and   `--bin-dir /bin/` to `/usr/local/bin` [https://github.com/awslabs/amazon-eks-ami/blob/343e830dc4cbf0b2646026fced4cea7202a345a5/scripts/install-worker.sh#L138](https://github.com/awslabs/amazon-eks-ami/blob/343e830dc4cbf0b2646026fced4cea7202a345a5/scripts/install-worker.sh#L138
)

When used the image created with EKS node groups, caanot exec into or view pod logs. 

`Error from server: error dialing backend: dial tcp 10.10.71.57:10250: i/o timeout`

**Comment by im-wanyama** [comment]
> 

Ah no problem, assign this issue to me and I'll make a PR

**Comment by cartermckinnon** [comment]
Should be resolved by #1231
