### ISSUE TITLE
Failed to create pod sandbox | error loading seccomp filter: errno 524: unknown

### ISSUE THREAD

**Issue by lefterisALEX** [awslabs/amazon-eks-ami#1179]
**What happened**:

We noticed that periodically when new worker nodes are launched in our EKS cluster the pods that are scheduled to the new nodes are not in `Running` status, but instead are in  `Init` or `ContainerCreating`.

For instance:
![image](https://user-images.githubusercontent.com/24940221/217530552-baa1ed1b-5f01-4fe3-b699-a383690fb163.png)

In the events we see:
```
Events:
  Type     Reason                  Age                    From     Message
  ----     ------                  ----                   ----     -------
  Warning  FailedCreatePodSandBox  3m11s (x350 over 88m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown
```

**What you expected to happen**:
Pods that are scheduled to the new worker nodes expected to have status `Running` 

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately don't have specific steps how to reproduce it.  Issue happens sporadically and there is no way for us to trigger it.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): c6i.4xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.5"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.23"
- AMI Version: amazon-eks-node-1.23-v20230105
- Kernel (e.g. `uname -a`): amazon-eks-node-1.23-v20230105
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0a5eade221148fcb0"
BUILD_TIME="Thu Jan  5 02:19:39 UTC 2023"
BUILD_KERNEL="5.4.226-129.415.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by dims** [comment]
@lefterisALEX - could be hitting the limit set by `net.core.bpf_jit_limit` can you please review the following and possibly bump the defaults in your AMI? (especially since you are running cilium which uses ebpf extensively)

- https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1956954
- https://github.com/grpc-ecosystem/grpc-health-probe/issues/34#issuecomment-1225512065

**Comment by lefterisALEX** [comment]
thanks for the quick response.
I see we have indeed limit enabled and set to `264241152`
```
# cat /proc/sys/net/core/bpf_jit_enable 
1
# cat /proc/sys/net/core/bpf_jit_limit
264241152
```

Are there any logs we can check to see if we indeed are hitting the limits?

**Comment by dims** [comment]
@lefterisALEX the second link indicates how to count the total used currently, here's a simplified version with output from one of my boxes.

```
# cat /proc/sys/net/core/bpf_jit_enable
1
# cat /proc/sys/net/core/bpf_jit_limit
398458880
#  cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'
65536
```

**Comment by lefterisALEX** [comment]
ok, just happened again...i see this
```
# cat /proc/sys/net/core/bpf_jit_enable
1
# cat /proc/sys/net/core/bpf_jit_limit
264241152
# cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'
352595968
```

do you recommend to increase the value of ` /proc/sys/net/core/bpf_jit_limit` then?

**Comment by dims** [comment]
@lefterisALEX yep!

**Comment by lefterisALEX** [comment]
**just an update:**
when issue happened i update the limit on the fly to a higher value and containers started running immediately.
```
sysctl net.core.bpf_jit_limit=452534528
```

**Comment by codechirag123** [comment]
> **just an update:** when issue happened i updated the limit on the fly to a higher value and containers started running immediately.
> 
> ```
> sysctl net.core.bpf_jit_limit=452534528
> ```

Hi, but how can we do this on a node scheduled by karpenter in EKS?
As it is a spot node and might be soon disrupted is there a scalable way which can increase the limit of this value throughout all nodes?
