### ISSUE TITLE
Is logrotate of json included as part of the AMI

### ISSUE THREAD

**Issue by nitin302** [awslabs/amazon-eks-ami#118]
Hello,

I see the current release is v25 (amazon-eks-node-v25 (ami-0a0b913ef3249b655)). Does this include logrotate of docker logs by default?

I see as commit : https://github.com/awslabs/amazon-eks-ami/blob/master/files/docker-daemon.json but this does not seem to part of the v25 release.

Is there a more latest release which has logrotate?

**Comment by max-rocket-internet** [comment]
It's in `amazon-eks-node-1.10-v20181210` AMI

**Comment by nitin302** [comment]
Can we use this for production ?

**Comment by max-rocket-internet** [comment]
It's an official AMI released by AWS so I would hope so haha
