### ISSUE TITLE
feat: Write detailed output from bootstrap.sh to log file

### ISSUE THREAD

**Issue by jebbens** [awslabs/amazon-eks-ami#1183]
**What would you like to be added**:
Write detailed output from bootstrap.sh to a log file, e.g.   
```bash
exec > >(tee /var/log/bootstrap.log|logger -t user-data -s 2>/dev/console) 2>&1
set -x
```
Needs to be done in a way that does not overwrite user-provided user-data from custom launch template.

**Why is this needed**:
When dealing with custom launch templates, e.g. to configure for use with a proxy, it is useful to have the complete output of all user data in a log file for troubleshooting.

**Comment by cartermckinnon** [comment]
The bootstrap logs should be present in `/var/log/cloud-init-output.log`, but adding more details (in a more uniform format) sounds like a great idea to me. Is there any information in particular you're looking for?

**Comment by jebbens** [comment]
I don't see very much in `cloud-init-output.log`. I think if we added the two lines of code I referenced above (per recommendation from [here](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-log-user-data/), we'd get more useful output. Also, if a user provides their own user-data in a different MIME message part that runs before the `bootstrap.sh`, and outputs it to that same file, it may get overwritten by the user-data behind it (if it writes to the same file). So, we could output logs from bootstrap.sh to a separate file, e.g. `/var/log/bootstrap.log` to avoid that conflict.

**Comment by cartermckinnon** [comment]
Any stdout from user data will appear in `cloud-init-output.log`. We recently added more logging to the bootstrap script, so I'm going to close this issue. Let me know if #1276 doesn't meet your needs.

**Comment by jebbens** [comment]
Looking at nodes I just launched, my `cloud-init-output.log` looks nothing like my `user-data.log`. All i see in the former is a short log of network interfaces and routing information. Not sure why I'm not seeing all of the output from the user-data that I see in the latter. Note these are self-managed nodes.
