### ISSUE TITLE
option to add shared security groups with amazon-eks-nodegroup.yaml

### ISSUE THREAD

**Issue by kagahehk01** [awslabs/amazon-eks-ami#119]
**What would you like to be added**:
option to add shared security groups in the cloudformation `amazon-eks-nodegroup.yaml`

**Why is this needed**:
in order to allow communication between nodes, i saw the created security group allow all traffic from itself 

however, when i try to use this cloudformation to create multiple node groups, each of them create the security group themselves but they cannot communicate between groups. 

my approach is to attach an predefined security group, which allows all traffic from itself, to all node groups, so I wish this can be done with official cloudformation too, or any better approaches? 

thank you!

**Comment by fcervantes2** [comment]
A solution that worked for us which is similar to yours, but allows for additinal SGs to be attached; we made changes to the template to allow adding the SGs, such as the ones you mentioned, and any more if needed. 

I'll see if I can get a PR showing this.

**Comment by gacopl** [comment]
i dropped the CF and handle launch configurations manually, all you need for a node to join cluster properly is correct launch configuration for your ASG, user-data and proper tags in ASG that's all is needed

**Comment by acesir** [comment]
How did you manage to acomplish this. Currently we will have 3 CF stacks of eks nodes that will be part of the eks cluster. And because every stack deployment creates it's own security group we have to script associating security group communication between them otherwise pod communication does not work.

Is there a way to pass in a single SG into the amazon-eks-nodegroup.yaml?

**Comment by whereisaaron** [comment]
An alternative is to create nodegroup CF stacks with [`eksctl`](https://github.com/weaveworks/eksctl) which will add a shared security group (by default) and custom groups (`eksctl create nodegroup --node-security-groups`) to the CF stacks for you.
