### ISSUE TITLE
Update to Kubernetes 1.11

### ISSUE THREAD

**Issue by aly-aurea** [awslabs/amazon-eks-ami#120]
**What would you like to be added**:
Update the Kubernetes version of the worker AMI to 1.11

**Why is this needed**:
To support the latest release of the EKS cluster version 1.11

**Comment by micahhausler** [comment]
Hi, this was released yesterday. You can find the AMI IDs here: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by aly-aurea** [comment]
@micahhausler this repo still uses v1.10 binaries, any plans to update it? because I bake my AMI and I do not use the pre-baked AMIs listed in the user guide.

**Comment by micahhausler** [comment]
The binaries are in the S3 Bucket, you can see them by running `aws s3 ls --recusive s3://amazon-eks/`

**Comment by aly-aurea** [comment]
Thank you, I can see it now.
