### ISSUE TITLE
Additional Documentation: launch template user data guidance

### ISSUE THREAD

**Issue by adgantt** [awslabs/amazon-eks-ami#1200]
**Environment**: All
- AWS Region: All
- AMI Version: AMI Release v20230217

Understanding that we want to keep README files thin, requesting additional documentation or a link in the README to the [AWS Launch Template Support](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami) as a post AMI deployment hint or nudge in order to make the repository more user friendly. This post deployment activity is a requirement to use the custom AMI produced from this repository and could help mitigate end-users troubleshooting activities if they are pointed in this direction.

**Comment by cartermckinnon** [comment]
@adgantt let me know your thoughts on #1201 . 👍
