### ISSUE TITLE
kernel versions are locked and vulnerable to ALAS2KERNEL-5.4-2023-042

### ISSUE THREAD

**Issue by d-koppenhagen** [awslabs/amazon-eks-ami#1217]
The package `kernel`s version is locked and it's vulnerable according to the Amazon Linux 2 Security Advisory:

- https://alas.aws.amazon.com/AL2/ALASKERNEL-5.4-2023-042.html

checking the packages inside the AMI gave us the information that the versions are locked:

```bash
$ yum versionlock list
Loaded plugins: priorities, update-motd, versionlock
0:kernel-5.4.228-132.418.amzn2.*
0:runc-1.1.4-1.amzn2.*
0:containerd-1.6.6-1.amzn2.0.2.*
0:docker-20.10.17-1.amzn2.0.1.*
versionlock list done
```

**Question**

As far as I understand, I need to wait for a new AMI version to fix ALAS2KERNEL-5.4-2023-042 permanently.
Is there ETA for the next release?
Or is there another (better) solution that we could implement (see workaround below)

**Workaround**

```bash
yum versionlock delete kernel
yum update
```

However this workaround introduces the risk of getting incompatible versions in the future.

**Comment by cartermckinnon** [comment]
We have an AMI staged for imminent release that will address this CVE.

You can unlock the package and upgrade at your discretion; but as you mention, this has the risk of introducing instability. We have a user guide section about package version locks; let me know if we can add any clarifications: https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#version-locked-packages
