### ISSUE TITLE
Use 5.10 kernel in GPU AMI

### ISSUE THREAD

**Issue by cartermckinnon** [awslabs/amazon-eks-ami#1222]
**What would you like to be added**:

We should use the 5.10 kernel for GPU AMI types. We're working to address compatibility issues with `kernel-5.10` and other packages specific to the GPU AMI (such as `nvidia-driver-latest-dkms`).

**Comment by stevehipwell** [comment]
Does Bottlerocket not use the same drivers with `kernel-5.10`?

**Comment by cartermckinnon** [comment]
Bottlerocket rolls their own driver RPM's.

We expect this to be addressed when we update to the 535 series drivers shortly.

**Comment by zekena2** [comment]
With the release of network policies in aws-vpc-cni this is needed in order to use the network policy with gpu nodes as it needs kernel 5.10 as mentioned in the perquisites [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html).

**Comment by XciD** [comment]
I think this PR should stay open.

https://github.com/awslabs/amazon-eks-ami/pull/1439/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR43


From a host with `ami-001b78ba700c199b7`
```
uname -a
Linux ip-10-4-37-210.ec2.internal 5.4.254-170.358.amzn2.x86_64 #1 SMP Wed Sep 6 21:10:58 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
