### ISSUE TITLE
Why kernel version locked from EKS 1.25

### ISSUE THREAD

**Issue by alpana17** [awslabs/amazon-eks-ami#1248]
Till Amazon EKS 1.24, there was no version lock for kernel.
But in Amazon EKS 1.25, file vi /etc/yum/pluginconf.d/versionlock.list has lock for kernel.
As a result, I am not able to install any other kernel.

What is the reason to add version lock for kernel package

**Comment by dims** [comment]
@alpana17 please see the PR for the change here:
https://github.com/awslabs/amazon-eks-ami/pull/1191

there was a kernel version lock during update which caused issues, so it was moved to install-worker itself.

**Comment by cartermckinnon** [comment]
@alpana17 one example is #1071 (`5.4.217-126.408.amzn2`). Each kernel release contains patches which may impact performance and stability. Depending on your workload, the impact may be subtle or critical. Additionally, If you install the latest kernel at runtime, as you scale your nodegroup up and down, the kernel version used in the nodegroup becomes heterogeneous.

The version lock is intended to prevent unintentional updates of the kernel. You can remove the version lock with the instructions in the user guide: https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#version-locked-packages
