### ISSUE TITLE
Add Support for A1 Instance type

### ISSUE THREAD

**Issue by realAndyLuo** [awslabs/amazon-eks-ami#125]
**What would you like to be added**:
EKS Optimized AMI for A1 Instance 
**Why is this needed**:

- Explore possibilities to optimize cost/performance

**Comment by micahhausler** [comment]
We plan on supporting this soon, but we don't yet. In addition to building the AMI, we'll need to have container images for our CNI and kube-proxy at a minimum, and probably CoreDNS too. Would you want to run ARM only clusters or mixed arm64/x86_64 clusters?

**Comment by realAndyLuo** [comment]
Likely mixed as a start. 

I am not expecting all our applications would support multi-arch images. Like you guys, we will focus on getting multi-arch ready only for a minimum starting set, necessary daemonsets pods and a few piloting applications. Then we will integrate a dedicated ARM only nodegroup into existing EKS and use taints to control scheduling.

**Comment by dawidmalina** [comment]
In theory (as I didn't test it) cluster components (kube-proxy, cni, core-dns) can be deployed in two versions in the same time (preferable if we could configure it from the eks console) with different node selector based on this label: `beta.kubernetes.io/arch`.

**Comment by left4taco** [comment]
Badly need an AMI for Arm machine. 

@micahhausler Do you foresee any difficulty if I'd like to build my own AMI with scripts in this repository? 
Thanks.

**Comment by ab77** [comment]
for [posterity](https://github.com/aws/containers-roadmap/issues/264#issuecomment-656873325)
