### ISSUE TITLE
`amazon-eks-node-1.24-v20230322` is missing eni-max-pods entries for `*6in.metal` types

### ISSUE THREAD

**Issue by snorlaX-sleeps** [awslabs/amazon-eks-ami#1254]
**What happened**:
The latest version of the `1.24-v20230322` AMI does not have an updated entry in the `eni-max-pods.txt` file for any `*6in.metal` types.
This was added in https://github.com/awslabs/amazon-eks-ami/pull/1226 but does not appear in the entries on the host.
This is required to calculate reservedMemory when using [memory-manager](https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/) in Kubernetes, as well as for other potential usecases.

Unsure if this is due to the timing of the build, but it leaves any instances using this AMI + instance-type in an unready state so no pods are scheduled onto it.

**What you expected to happen**:
The latest AMI would have an entry for this in the `eni-max-pods.txt` file for any new instance types

**How to reproduce it (as minimally and precisely as possible)**:
- Create an instance using any `*6in.metal` instance-type and the `amazon-eks-node-1.24-v20230322` AMI.
- Check for an entry in `/etc/eks/eni-max-pods.txt`

**Anything else we need to know?**:
We have not tested this with another K8s version, only v1.24
Without MAX_PODS set, this may affect other kubelet functionality

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): `*6in.metal`
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.4
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.24
- AMI Version: ami-0733d88d7fb98418c
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
cat /etc/eks/release
BASE_AMI_ID="ami-0705aa17fc133fc96"
BUILD_TIME="Wed Mar 22 01:17:59 UTC 2023"
BUILD_KERNEL="5.10.173-154.642.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
The max pod values for these instance types will be present in the next release. There's a fallback mechanism to calculate the value at runtime: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L461

Is that not working as expected?

**Comment by snorlaX-sleeps** [comment]
Hey @cartermckinnon - we use Karpenter node-templates with the `AL2` configuration, so we have to make any changes to the kubelet config (via the `kubelet-config.json` file) before the bootstrap is run, only recently finding out about the `CUSTOM` configuration.

Thank you for pointing out this backup line, I will add it to our userdata to cover eventualities like this!
