### ISSUE TITLE
Why kernel version 5.4.238-148.346.amzn2 not installable using yum on AL2 EKS-1.22 GPU ami?

### ISSUE THREAD

**Issue by vanshikw** [awslabs/amazon-eks-ami#1262]
https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md

In this changelog kernel - 5.4.238-148.346.amzn2 is given for EKS-1.23 and below.
I am taking a older ami from September 2022.
ami name - amazon-eks-gpu-node-1.22-v20220926
here I am not able to install this kernel version from yum. Why?

and when I am doing 
`yum list available kernel --showduplicates`

it is giving me 5.4.238-148.347.amzn2  kernel which is higher than my requested kernel

**Comment by cartermckinnon** [comment]
This is a result of the removal of this version of the `kernel-5.4` package. More info here: https://github.com/awslabs/amazon-eks-ami/issues/1266#issuecomment-1515110366
