### ISSUE TITLE
Requesting accelerated-ami release with CUDA >=11.8 and user guide improvement

### ISSUE THREAD

**Issue by TaylorZowtuk** [awslabs/amazon-eks-ami#1282]
**What would you like to be added**:
- Release AMI with >=CUDA 11.8
- Improve the [user guide](https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md) to indicate how users can build custom accelerated AMIs

**Why is this needed**:
- TensorFlow's latest release (2.12.0) requires a CUDA version >=11.8 [as noted here](https://www.tensorflow.org/install/source#gpu)
  - Although similar requests (#915) have been made in the past, I felt that there might be a large number of consumers of this AMI who use it to run TensorFlow with GPU support. The current releases of the accelerated-ami cannot be used with the most recent release of TensorFlow.
- The docs currently do not mention considerations for building the accelerated AMI. I believe this should be improved for the same reasons outlined in #529.

**Comment by alexlatchford** [comment]
Any progress updates on this one?

**Comment by cartermckinnon** [comment]
@Issacwww what version of CUDA will we have with the 535 drivers?

**Comment by Issacwww** [comment]
We will have cuda-12 for 535 drivers

**Comment by alexlatchford** [comment]
Thanks @cartermckinnon and @Issacwww for the update, so sounds like you're skipping CUDA v11 and going straight to CUDA v12.2 (and 535 means the CUDA Linux Drivers I presume, from [this doc](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html))?

Is there any slated release that'd include this target?

**Comment by XciD** [comment]
Any update on this ?

**Comment by alexlatchford** [comment]
One question I've got here is whether there are plans to support CUDA v11.8 or v11.7. For PyTorch v2.0 seems like they require those versions (see [this FAQ](https://pytorch.org/get-started/pytorch-2.0/#faqs)) and looks like they don't support CUDA v12.2 (see [this thread](https://github.com/pytorch/pytorch/issues/91122)) is there a goal to get a shorter term solution out that'd work with PyTorch?

We also have significant usage internal to Zillow of Tensorflow and looks like newer versions of that framework need CUDA v11.8 too, see [this doc](https://www.tensorflow.org/install/pip#software_requirements). Seems like newer versions of CUDA work though (see [this upstream issue](https://github.com/tensorflow/tensorflow/issues/60206)) so seems like that is resolved.

**Comment by ptailor1193** [comment]
With Kubernetes version 1.28 or later, the EKS optimized Accelerated AMIs support NVIDIA 535 series or later drivers and cuda-12 out of box.

**Comment by alexlatchford** [comment]
Sweet, thanks @ptailor1193. For anyone that needs a backport of this to EKS < 1.28 see: https://github.com/awslabs/amazon-eks-ami/issues/1448

**Comment by cartermckinnon** [comment]
I'm going to close this issue now that 1.28 is GA -- we'll continue tracking our backporting in #1448. 👍
