### ISSUE TITLE
bootstrap.sh does'nt support kubelet config file

### ISSUE THREAD

**Issue by langavriel** [awslabs/amazon-eks-ami#1289]
**What would you like to be added**: The bootstrap.sh file only supports the --kubelet-extra-args  flag that is deprecated on eks 1.26, and does not support the kubelet --config flag that allows to pass kubelet configuration files to kubelet.

**Why is this needed**: As of eks 1.26, passing arguments to the kubelet is deprecated and is only supported via a config file, as stated here: https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#removal-of-dynamic-kubelet-configuration

**Comment by stevehipwell** [comment]
@langavriel the deprecation you've linked to isn't related to the `--kubelet-extra-args` flag as the flag is part of `bootstrap.sh` and not Kubernetes. The `--kubelet-extra-args` bootstrap flag is used to define `KUBELET_EXTRA_ARGS` which is a [convention](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd) to allow for the static customisation of kubelet.

**Comment by td-devops-user** [comment]
Hi @stevehipwell , Is this env var supported on eks 1.26?
I tested this flag on eks 1.26 and it did not apply the configuration (and it did apply this changes on eks 1.25), so i dont think this is supported on eks 1.26+.
Anyways, there is no flag that supports passing a kubeket config file which could be very helpful.

**Comment by langavriel** [comment]
Hi @stevehipwell , Is this env var supported on eks 1.26?
I tested this flag on eks 1.26 and it did not apply the configuration (and it did apply this changes on eks 1.25), so i dont think this is supported on eks 1.26+.
Anyways, there is no flag that supports passing a kubeket config file which could be very helpful.

**Comment by stevehipwell** [comment]
@langavriel the answer to your questions can be found in the [kubelet systemd unit](https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet.service); the config is defined as part of the AMI (`/etc/kubernetes/kubelet/kubelet-config.json`) and the `KUBELET_EXTRA_ARGS` are supported (they're added to the unit spec in [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/e4dd2abb52a43477f9aa32134fa6683dcc8de048/files/bootstrap.sh#L618)).

Please note that if you're using MNGs then you'll need to work around the limitations of cloud-init (e.g. patching bootstrap.sh for persistence).

**Comment by cartermckinnon** [comment]
@langavriel sorry for the late reply, I've been out of the office. This bootstrap flag is intended to pass arbitrary args to the kubelet command line. You can use it to define an alternative kubelet config file, and it should "just work" -- kubelet should use the last value for a given flag (if only one value is allowed). I'd recommend trying that instead of modifying the existing kubelet config file in-place, because the bootstrap script may overwrite your changes.
