### ISSUE TITLE
kernel wrong in v20230501 in us-gov* regions

### ISSUE THREAD

**Issue by paleozogt** [awslabs/amazon-eks-ami#1297]
**What happened**:

Create an EC2 instance from the `amazon-eks-node-1.24-v20230501` AMI.  Shell into it and check the kernel version:
```bash
$ uname -r
5.10.177-158.645.amzn2.x86_64
```

**What you expected to happen**:

The [release notes](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230501) say `Kubernetes 1.24 and above: 5.10.178-162.673.amzn2`, which isn't the kernel being used.

**How to reproduce it (as minimally and precisely as possible)**:

Create an EC2:
```bash
aws ec2 run-instances --image-id "resolve:ssm:/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id"
```

From the web console, connect thru SSM and check the kernel with:
```bash
uname -r
```

**Anything else we need to know?**:

Oddly this unexpected kernel version (`5.10.177-158.645.amzn2`) isn't in https://github.com/amazonlinux/linux, but the expected one is (`5.10.178-162.673.amzn2`). 😕 

At the very least this is a documentation bug, but its absence in the kernel repo makes me think the problem is deeper.  Though if the kernel isn't what you think it is, it probably isn't fixing the bugs you think it is, such as when the release notes state that `Kernel version upgrade to 5.10.178-162.673.amzn2 fixes the https://github.com/awslabs/amazon-eks-ami/issues/1219 issue`.

**Environment**:
- AWS Region: us-gov-west-1
- AMI Version:
- Kernel (e.g. `uname -a`): 5.10.177-158.645.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0b3baa49e13264f06"
BUILD_TIME="Mon May  1 20:18:40 UTC 2023"
BUILD_KERNEL="5.10.177-158.645.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by mmerkes** [comment]
I've verified that `us-west-2` is as expected:

```
 aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id --region us-west-2
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-056ee4835381fce55",
        "Version": 14,
        "LastModifiedDate": "2023-05-03T19:06:36.828000-07:00",
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}
```

Then, I created an instance with the AMI ID and got the following:

```
$ uname -r
5.10.178-162.673.amzn2.x86_64
```

I'll check `us-gov-west-1` next.

**Comment by mmerkes** [comment]
```
$ aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id --region us-gov-west-1
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-068e35e7161e72c7e",
        "Version": 14,
        "LastModifiedDate": "2023-05-03T17:54:34.861000-07:00",
        "ARN": "arn:aws-us-gov:ssm:us-gov-west-1::parameter/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}
```

I created an instance with that AMI and got the following:

```
$ uname -r
5.10.177-158.645.amzn2.x86_64
```

Looks like the kernel wasn't released in GovCloud when we build the AMIs. I've verified that `5.10.178-162.673.amzn2.x86_64` is available now, and that our next AMI release will include that kernel, which is scheduled to go out by the end of the week.

**Comment by cartermckinnon** [comment]
This is resolved in the latest release: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230509
