### ISSUE TITLE
ecr-credential-provider Binary

### ISSUE THREAD

**Issue by ArchitKhanna** [awslabs/amazon-eks-ami#1303]
**Environment**: All
- AWS Region: us-west-2
- Instance Type(s):
- EKS Platform version: eks.3
- Kubernetes version: 1.25.9
- AMI Version: Custom
- Kernel: amd64

I would like to know how I can fetch the ecr-credential-provider binary from s3 the way it is done for the official EKS AMIs. Is there an official public source for someone who is building their custom AMI?

Issue: I tried to build the ecr-credential-provider and placed it in the required location, however the plugin fails to fetch credentials. With the following error: ```failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden" image="602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.11.4"``` 

I believe that the plugin I am building using the ecr-credential-provider files from cloud-provider-aws is not built correctly and would like to use the binary provided by AWS.

**Comment by cartermckinnon** [comment]
We publish this binary in the `amazon-eks` S3 bucket as well, for example:
```
aws s3 cp s3://amazon-eks/1.27.1/2023-04-19/bin/linux/amd64/ecr-credential-provider .
```

To resolve the `403` make sure your instance profile/temp creds/etc. can hit `ecr.GetLoginPassword`. You can verify that with the AWS CLI.

**Comment by ArchitKhanna** [comment]
Great, thank you so much!

**Comment by ArchitKhanna** [comment]
@cartermckinnon is there is list of Binaries and their s3 paths I can refer to for older versions?

**Comment by cartermckinnon** [comment]
We publish it for every k8s version + build date since 1.20, e.g.:
```
aws s3 ls --recursive s3://amazon-eks/1. | grep "ecr-credential-provider$"
```

**Comment by ArchitKhanna** [comment]
Thank you once again!
