### ISSUE TITLE
After eks upgrade to v1.24, image pull fails from ecr

### ISSUE THREAD

**Issue by rootrahulagr** [awslabs/amazon-eks-ami#1304]
I have upgraded EKS cluster to v1.24. As dockershim is not available anymore, I have setup containerd as container runtime. But looks like kubelet is still looking for .dockercfg for credentials to connect to ECR. As a result, all image pulls are failing. 

See snippet from kubelet logs below - 

Refreshing cache for provider: ***credentialprovider.defaultDockerConfigProvider**
Docker config file not found: **couldn't find valid .dockercfg after checking in [/var/lib/kubelet   /]**
2023-05-16T08:08:56.495576397Z" level=info msg="PullImage /amazon-k8s-cni:v1.10.4\""
2023-05-16T08:08:56.511217958Z" level=info msg="trying next host" error="failed to do request: Head \"dial tcp xx.xx.xx.xx:443: connect:connection refused" 
08:56.516631    9623 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"
08:56.516844    9623 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"aws-node\" with ErrImagePull: \"rpc error: cod
08:58.581442    9623 kubelet.go:2374] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady 

I also tried to configure external image-credential-provider but it didn't help either. Please advise.

**Comment by rootrahulagr** [comment]
Thanks @cartermckinnon for your reply.
Did you mean the first 2 lines about credential provider and docker config are irrelevant?

I was trying to investigate the connection refused error but I am not sure what's that IP where connection is getting refused. Any idea?

And yes, I had modified that line to avoid sharing any sensitive data accidentally. Thanks.

**Comment by cartermckinnon** [comment]
The docker config line is not relevant; the kubelet still has the ability to pick up credentials from the docker config if it's available (because it remains convenient -- but is deprecated). This functionality is orthogonal to dockershim. https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/config.go

My best guess is you don't have a route to ECR from your node; due to egress rules, lack of a VPC endpoint, etc. Are you able to pull the image manually on the node?

**Comment by rootrahulagr** [comment]
Docker config is not available on the node so anyway it's going to fail.

Yes, I can pull image manually on the node.

**Comment by cartermckinnon** [comment]
You're able to pull *the same image* manually on the node as kubelet gets a `connection refused` for? If you think it's an issue with your kubelet config, can you share the credential provider config file?

**Comment by cartermckinnon** [comment]
Closing this due to lack if details; let me know if you're still facing this issue.

**Comment by whereisaaron** [comment]
I used eksctl to add an EKS v1.23 node group using containerd runtime to an existing v1.23 cluster (using dockerd node) and the new containerd nodes could no longer pull container images from ECR.

Error says not found, but container image is there and pulls fine on all the dockerd nodes. Exact same config except container runtime. Exact same container image. I checked the node group role for both dockerd and containerd and they both had the ECR pull permissions.

Deleted the node group and created a dockerd one, no other change, and same image pulled fine.

This cluster has been upgrades from ~1.16 over time. Anything I should check that would explain why containerd nodes can't pull ECR image in the same cluster that dockerd nodes can?

```
Pulling image "XXXXXX.dkr.ecr.ap-southeast-2.amazonaws.com/mycontainer:1.0.1"
  Warning  Failed     8s (x3 over 47s)   kubelet            Failed to pull image "XXXXXX.dkr.ecr.ap-southeast-2.amazonaws.com/mycontainer:1.0.1": rpc error: code = NotFound desc = failed to pull and unpack image "XXXXXXX.dkr.ecr.ap-southeast-2.amazonaws.com/mycontainer:1.0.1": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:d713dedd5b37c3ffea46d23c7933cc173c7755c789eab3bc60ea374cb5af740f (application/vnd.docker.distribution.manifest.v1+json) from remote: not found
```
