### ISSUE TITLE
Calls to EKS API in bootstrap.sh will not work in private clusters without access to Internet. Should docs be updated?

### ISSUE THREAD

**Issue by jebbens** [awslabs/amazon-eks-ami#1312]
In doing some testing with private clusters with and without access to the Internet, I've realized there are some calls to the EKS API in the bootstrap.sh (granted, they are in a conditional block) that will not work without a route to the Internet. So, my questions are: 1) Is my understanding correct, and 2) if so, should the [private clusters](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html) page in the user guide be updated to note this as a consideration (I would submit the PR/feedback) and recommend deploying the new EKS PrivateLink endpoint into the user VPC?
```
```

**Comment by cartermckinnon** [comment]
That doc already covers this scenario; the recommendation is to specify the cluster CA and endpoint so access to the EKS API is not required:
> Self-managed Linux and Windows nodes must include the following bootstrap arguments before they're launched. These arguments bypass Amazon EKS introspection and don't require access to the Amazon EKS API from within the VPC.
