### ISSUE TITLE
storage for containerd service

### ISSUE THREAD

**Issue by HenryXie1** [awslabs/amazon-eks-ami#1318]
**Environment**:
- AWS Region: ap-southeast-2
- Instance Type(s): c6a.2xlarge
- EKS Platform version : eks.8
- Kubernetes version :1.23
- AMI Version: ami-096bbff3218b493cc
- Kernel (e.g. `uname -a`): 5.14
- Release information (run `cat /etc/eks/release` on a node):

```
```
I find the root of containerd service in /var/lib/containerd , but it is under `/`  which is only 50G
As for production, we are concerned that the `/` may be filled up and causes panic

we want to attach a dedicated gp3 ebs storage for containerd, I see your feedback on what is the recommended approach for containerd storage?

**Comment by zhan9san** [comment]
Hi @HenryXie1 

I am glad to share some experiences on this issue.

In EC2 Instance Userdata, we add the following commands.

```shell
systemctl stop containerd
mv /var/lib/containerd /mnt/data/
ln -s /mnt/data/containerd /var/lib/
systemctl start containerd
```
