### ISSUE TITLE
log-collector-script Improvement

### ISSUE THREAD

**Issue by berry2012** [awslabs/amazon-eks-ami#1322]
EKS Log collector - Improvement

**What would you like to be added**:

- Include list of unused containers
- Include list of unused images
- Include checks for layers occupying most storage

**Why is this needed**:
To help in troubleshooting DIsk Pressure and Garbage Collection Issues

**Comment by cartermckinnon** [comment]
@berry2012 if you have an implementation in mind, feel free to open a PR. 😄

**Comment by cartermckinnon** [comment]
I'm going to close this; we shouldn't track feature requests for the log collection script without an implementation plan. Please open a PR if want. 👍
