### ISSUE TITLE
Switch to containerd config version 2 in GPU AMI

### ISSUE THREAD

**Issue by chiragjn** [awslabs/amazon-eks-ami#1329]
**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): g4dn.*
- EKS Platform version: eks.3
- Kubernetes version: 1.25
- AMI Version: amazon-eks-gpu-node-1.25-v20230607
- Kernel (e.g. `uname -a`): `Linux ip-10-2-56-80.eu-west-1.compute.internal 5.4.242-156.349.amzn2.x86_64 #1 SMP Tue May 23 18:48:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-03a6fab5b8d8bfd7b"
BUILD_TIME="Wed Jun  7 16:18:14 UTC 2023"
BUILD_KERNEL="5.4.242-156.349.amzn2.x86_64"
ARCH="x86_64"
```

I am trying to configure options for nvidia-container-runtime, specifically

```
accept-nvidia-visible-devices-as-volume-mounts = true
accept-nvidia-visible-devices-envvar-when-unprivileged = false
```

To do this I started using nvidia's gpu-operator because that allows me to configure these easily via environment variables to the container toolkit component. Normally, the `nvidia-container-toolkit` component of the `gpu-operator` patches containerd config on the host and changes the default runtime to `nvidia` with custom binary location which configures the above-mentioned settings. But because the AMI is using containerd config version 1 and comes with `plugins.cri.containerd.default_runtime.options` configured, the changes made by `nvidia-container-toolkit` are ineffective and the AMI continues to use its own nvidia-container-runtime-hook, nvidia-container-cli and prestart hooks

Context here: https://github.com/NVIDIA/nvidia-container-toolkit/issues/64#issuecomment-1597236350

Are there any plans to make it version 2 by default?

I know I can go the custom userData script route (to edit one of  `/etc/nvidia-container-runtime/config.toml`, `/etc/containerd/config.toml`, `usr/share/docker-runtime-nvidia/hook-config.json`) or custom AMI to pass a custom container config file path to `bootstrap.sh`, but I would really prefer not to go that way.

**Comment by cartermckinnon** [comment]
We're doing some work in the GPU AMI (such as upgrading the NVIDIA drivers); I'll try to get this addressed as well. My recollection is our `containerd` config was mostly a directive from NVIDIA's docs way back when; so we should realign with the current recommendations 👍.

@Issacwww

**Comment by chiragjn** [comment]
Any updates on this? We would like to get rid of userdata script hacks we do to get around this issue

**Comment by chiragjn** [comment]
This seems to have been addressed in newer AMIs, closing
