### ISSUE TITLE
what is responsible for log rotation in EKS AMI (EKS v1.24+)? kubelet? docker? containerd? logrotate?

### ISSUE THREAD

**Issue by ravikiran-talluri** [awslabs/amazon-eks-ami#1332]
Hello I would like to know, what is responsible for log rotation in EKS AMI (EKS v1.24+)? kubelet? docker? containerd? logrotate? 
and also Can we able to change these log rotation rules like filesize limit or rotation time?

**Comment by cartermckinnon** [comment]
The `kubelet` rotates the logs of your containers (see: [code](https://github.com/kubernetes/kubernetes/blob/47aeec63a839703e962ebd97e26edbc86fe6d99c/pkg/kubelet/logs/container_log_manager.go), [docs](https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-rotation)). Everything outside a container is handled by `logrotate`.
