### ISSUE TITLE
Update Kubelet patch version - resolve EBS PVC attaching for a long time

### ISSUE THREAD

**Issue by ilia-medvedev-codefresh** [awslabs/amazon-eks-ami#1348]
**What happened**:
We are experiencing the issue from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302 where it takes PVC a long time to attach when attaching a PV that was previously attached to another node.

**What you expected to happen**:
Volumes should attach quicker

According to this https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302#issuecomment-1598428800 
The solution has been introduced in Kubelet patches that are not yet incorporated in AL2 EKS AMI's (for example it has been fixed in Kubelet 1.24.14 and the latest AMI includes 1.24.13).

**Comment by cartermckinnon** [comment]
We're aware of this issue and the kubelet should be updated in the next AMI release.

**Comment by cartermckinnon** [comment]
The updated kubelet's are available in the latest release, 20230711.
