### ISSUE TITLE
bootstrap.sh exists with error but still attaches nodes if CIDR is not 10.0.0.0/16

### ISSUE THREAD

**Issue by Ohadbasan** [awslabs/amazon-eks-ami#136]
**What happened**:

bootstrap.sh exists with error on line 110 if the node subnet is not 10.0.0.0/16, yet the nodes still attach to the cluster.
(my subnet is 172.31.0.0/16)

**What you expected to happen**:

either the nodes should fail to connect to the cluster or shouldn't fail or a  subnet that starts with 10.* should not be hardcoded.

**How to reproduce it (as minimally and precisely as possible)**:

set up an eks subnets where the nodes run in a subnet different from 10.0.0.0/16

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): t3.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version: 1.11
- Kernel (e.g. `uname -a`):Linux ip-172-31-2-61 4.14.77-81.59.amzn2.x86_64 #1 SMP Mon Nov 12 21:32:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by micahhausler** [comment]
So the script was not actually exiting, but the trap caught an err or and _thought_ that it exited. This is fixed in #139
