### ISSUE TITLE
RAID 0 Configuration Breaks certain configurations of Log Collectors

### ISSUE THREAD

**Issue by sidewinder12s** [awslabs/amazon-eks-ami#1361]
**What happened**:

When we migrated to Contianerd with the `--local-disks raid0` option, it broke our log collection agent.

Our agent creates hard links from the log files it is reading to ensure that the files do not get deleted while it is still processing them. You cannot create hard links across devices, which bind mounts are considered even when they are mapping to the same physical device.

**What you expected to happen**: 

This appears to be in line with how everything (kubelet, hardlinks, etc) are designed to work. At minimum, the RAID0 docs should call out that it also moves `/var/log/pods` to the NVME device.

**How to reproduce it (as minimally and precisely as possible)**: Attempt to create hard links between `/var/log/pods/*` files and another location outside the `/var/log/pods` directory. 

Secondarily, we could not create the hard links on the `/var/log/pods` directory to keep the links on the same device as the Kubelet appears to take full ownership of this directory and ended up deleting/rotating our links/directory structure. It appears to do this to any files within the directory

https://github.com/kubernetes/kubernetes/blob/v1.23.17/pkg/kubelet/logs/container_log_manager.go

**Anything else we need to know?**:

A few questions if anyone here might know better:

- Is it possible to change the kubelet configuration for where it writes pod logs?
- We thought about just not moving the `/var/log/pods` directory to NVME.
  - Is the main downside to not moving the `/var/log/pods` directory to the NVME device while moving `/var/lib/contianerd` and `/var/lib/kubelet` that the Kubelet will no longer have a 100% accurate view of its available storage space when it comes under disk pressure?

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): -
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.10"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.23
- AMI Version: v20230501
- Kernel (e.g. `uname -a`): `5.4.241-150.347.amzn2.x86_64 #1 SMP Mon Apr 24 23:27:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
sh-4.2$ cat /etc/eks/release
BASE_AMI_ID="ami-0bcd0806c369290a2"
BUILD_TIME="Mon May  1 20:17:59 UTC 2023"
BUILD_KERNEL="5.4.241-150.347.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
Is your log agent a custom thing or something we can play around with?

cc: @bwagner5

**Comment by sidewinder12s** [comment]
It is fully custom/closed source. 

We were going to play with not mounting `/var/log/pods` to the NVME drive when I get a chance. Mainly wanted to then thrash the disk a bit and see how DiskPressure events behaved, but it appeared to us that the kubelet already will not mess with container logs during DiskPressure events.

**Comment by sidewinder12s** [comment]
It appears not moving `/var/log/pods` may work for our use case.
