### ISSUE TITLE
SSM agent v3.2.x support

### ISSUE THREAD

**Issue by vincentmrg** [awslabs/amazon-eks-ami#1369]
Hello,

**What would you like to be added**:
It seems that the amazon-ssm-agent version is frozen at 3.1.1732.0 for the latest releases.
Do you think it would be possible to update the installed version of amazon-ssm-agent to 3.2.x?

**Why is this needed**:
Installing a version of amazon-ssm-agent higher than 3.2.582.0 would allow us to manage eks instances automatically by configuring [Default Host Management Configuration](https://docs.aws.amazon.com/systems-manager/latest/userguide/managed-instances-default-host-management.html).

**Comment by cartermckinnon** [comment]
We install the latest package provided by Amazon Linux: https://github.com/awslabs/amazon-eks-ami/blob/55cbc55f69a029dc821d16081a7c75c206a5d1cd/scripts/install-worker.sh#L476

We should probably switch to the S3 installation method to get newer versions: https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-al2.html#quick-install-al2

**Comment by vincentmrg** [comment]
Hello @cartermckinnon ,

I have opened a PR on this subject.
I took the opportunity to make the version configurable, let me know if it suits you this way or if you prefer that I put the latest version.
