### ISSUE TITLE
Release date logic for each month

### ISSUE THREAD

**Issue by HenryXie1** [awslabs/amazon-eks-ami#1374]
We are looking for the first release date of each month. Any logic for it? i.e. first Monday of the month

Sometimes I saw 3 releases in a month, sometimes twice. If you can give full logic of release time, it would be helpful.

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by bryantbiggs** [comment]
any particular reason for your interest in the release date? 

In general, most release processes at Amazon do not post a date and/or cadence due to a number of varying factors

**Comment by cartermckinnon** [comment]
We’re working on a predictable release cadence, to deliver updated packages more frequently and to make it easier to plan upgrades. I’ll share more when I can.
