### ISSUE TITLE
AWS EKS (1.27) node failing to join the cluster 

### ISSUE THREAD

**Issue by jitensingh12** [awslabs/amazon-eks-ami#1376]
I'm facing same issue with EKS managed AMI : ami-0bc4534a93057f9fb... EKS: 1.27 (Latest)
I've also disabled DNS hostname in VPC level and launched new EKS cluster (1.27) error is still same.
Relaunched the after enabling VPC DNS hostname and I'm using default DHCP set in AWS, no custom domain.

EKS Node release:
cat /etc/eks/release 
BASE_AMI_ID="ami-018ae0f2e02aab38b"
BUILD_TIME="Fri Jul 28 04:18:51 UTC 2023"
BUILD_KERNEL="5.10.184-175.749.amzn2.x86_64"
ARCH="x86_64"

- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.4"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.27"
- AMI release version: 1.27.3-20230728

Kubelet Error Logs: Aug 4 2023

Aug 04 18:56:15 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:15.163680 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:16 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:16.156733 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.177825 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.266792 2998 kubelet_node_status.go:352] "Setting node annotation to enable volume controller attach/detach"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267838 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasSufficientMemory"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267880 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasNoDiskPressure"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267895 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasSufficientPID"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267922 2998 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-10-4-144.ec2.internal"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: E0804 18:56:17.343482 2998 controller.go:146] "Failed to ensure lease exists, will retry" err="Unauthorized" interval="7s"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: E0804 18:56:17.343876 2998 kubelet_node_status.go:92] "Unable to register node with API server" err="Unauthorized" node="ip-10-10-4-144.ec2.internal"

**Comment by jitensingh12** [comment]
@cartermckinnon new case is created.

**Comment by cartermckinnon** [comment]
This is not the same issue as #1263, `Unauthorized` just indicates an issue with your node role.

**Comment by jitensingh12** [comment]
Below policy attached with node group role and all AWS managed . ( Trusted by ec2 opted while creating role )

AmazonEC2ContainerRegistryReadOnly
AmazonEKS_CNI_Policy
AmazonEKSWorkerNodePolicy

Below is trusted policy conctent

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}

post this this is giving the same issue.

**Comment by irparajababu** [comment]
Aug 26 05:35:32 ip-172-31-38-249 kubelet: W0826 05:35:32.956113    3942 reflecto                                                                             r.go:533] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.R                                                                             untimeClass: Unauthorized
Aug 26 05:35:32 ip-172-31-38-249 kubelet: E0826 05:35:32.956167    3942 reflecto                                                                             r.go:148] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.                                                                             RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized
Aug 26 05:35:33 ip-172-31-38-249 kubelet: I0826 05:35:33.629881    3942 csi_plug                                                                             in.go:913] Failed to contact API server when waiting for CSINode publishing: Una                                                                             uthorized
Aug 26 05:35:34 ip-172-31-38-249 kubelet: E0826 05:35:34.457446    3942 eviction                                                                             _manager.go:262] "Eviction manager: failed to get summary stats" err="failed to                                                                              get node info: node \"ip-172-31-38-249.ap-southeast-1.compute.internal\" not fou                                                                             nd"
Aug 26 05:35:34 ip-172-31-38-249 kubelet: I0826 05:35:34.630398    3942 csi_plug                                                                             in.go:913] Failed to contact API server when waiting for CSINode publishing: Una                                                                             uthorized
Aug 26 05:35:35 ip-172-31-38-249 kubelet: I0826 05:35:35.631467    3942 csi_plug                                                                             in.go:913] Failed to contact API server when waiting for CSINode publishing: Una                                                                             uthorized
Aug 26 05:35:36 ip-172-31-38-249 kubelet: I0826 05:35:36.630146    3942 csi_plug                                                                             in.go:913] Failed to contact API server when waiting for CSINode publishing: Una                                                                             uthorized

I am still getting the above error even added the above permission to node role

**Comment by yoplait** [comment]
We are facing same issue here
https://github.com/eksctl-io/eksctl/issues/7062

**Comment by jitensingh12** [comment]
No it's not resolved @yoplait

**Comment by yoplait** [comment]
We are really having a bad time on this, we have our own packer template and using eksctl to check the eks cluster and really against a wall on this

**Comment by cartermckinnon** [comment]
@yoplait your nodes are missing the labels that the managed nodegroup service uses to associate a Kubernetes node with a nodegroup.

**Comment by yoplait** [comment]
Thanks for your comment @cartermckinnon  but as you can check I am following that on the open issue with eksctl project 
on https://github.com/eksctl-io/eksctl/issues/7062

and I would say its kind of the same as when restarting the kubelet the node joins, missing the public ip as pointed there but joins, and missing the labels ... so in some hand has some pieces, pods are provisioned, but not the coredns , for example .... 

Thanks!

**Comment by cartermckinnon** [comment]
The public IP of the Node object is added by the external cloud provider in EKS 1.26+. Make sure you're using `--cloud-provider=external` on your kubelets. Once you resolve the label issue, things should work.

**Comment by cartermckinnon** [comment]
For future readers: please open a new issue with the specifics of your environment.
