### ISSUE TITLE
Support Amazon Linux 2023

### ISSUE THREAD

**Issue by gtirloni** [awslabs/amazon-eks-ami#1385]
**What would you like to be added**:
[Amazon Linux 2023](https://aws.amazon.com/linux/amazon-linux-2023/)

**Why is this needed**:
Support for more recent kernel and tools.

**Comment by dsalaza4** [comment]
Hi! Are there any plans on releasing the AMIs?

**Comment by stewartsmith** [comment]
Other related issues:
- We've been tracking this in the Amazon Linux 2023 github tracker for more than a year now: https://github.com/amazonlinux/amazon-linux-2023/issues/200
- https://github.com/awslabs/amazon-eks-ami/issues/1151 was from Jan 2023 also asking

I'm going to ensure that on the Amazon Linux issue we direct people here for any ETAs, and keep the AL issue open purely as a tracker.

**Comment by cartermckinnon** [comment]
> AL2023 support has already been merged but no official images are being generated at the moment.

I want to clarify that this is experimental, and not representative of a production implementation. It's currently used to provide a basic compatibility signal in some CI jobs.

We currently plan to add this support, along with official AMI builds, in early 2024. The development will happen in this repo, and we'll update this issue as things progress.

**Comment by BwL1289** [comment]
Very interested. Looking forward to release.

**Comment by cartermckinnon** [comment]
Our first AL2023-based AMIs were released yesterday!

**Comment by dims** [comment]
yes, both the older AL2 based AMI(s) and the newer AL2023 will be published. Note Al2023 is only a tech preview! (see details here https://github.com/awslabs/amazon-eks-ami/issues/1672)
