### ISSUE TITLE
Containred is failed to pull the image with harbour.

### ISSUE THREAD

**Issue by khushboo121** [awslabs/amazon-eks-ami#1389]
While upgrade EKS 1.23 to EKS 1.24 ,once we moved from Docker to Containred, containred failed to pull the images by giving  EOF  imagepullerror.

**What happened**: `Failed to pull image "projects.registry***": rpc error: code = Unknown desc = failed to pull and unpack image "projects.registry.***": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://projects.registry.****94df67f226b623622ccac83bf2cea5024eab532cf930fc6f888011906a1fa": EOF
  Warning  Failed                  5m5s (x4 over 6m41s)   kubelet            Error: ErrImagePull`

**What you expected to happen**: After upgrade no image pull issues, containred should works as docker pull image.

**Environment**: DEV, Staging and Production
- AWS Region: us-west-2, us-west-1, us-east-1, eu-central-1, all the region.
- Instance Type(s): m5.4xlarge, c5.xlarge
EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.9
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.24
- AMI Version: 1.24-v20230621-fe69a15
- Kernel (e.g. `uname -a`): 5.10.179-171.711.amzn2.aarch64 #1 SMP Tue Jun 6 01:59:12 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node): 
BASE_AMI_ID="ami-07ab31284fc9859da"
BUILD_TIME="Wed Jun 21 12:32:54 UTC 2023"
BUILD_KERNEL="5.10.179-171.711.amzn2.aarch64"
ARCH="aarch64"

```
do I need to update images char byte limit of the containred, if so where to update.
```

```[tasklist]
### Tasks
```

**Comment by cartermckinnon** [comment]
Looks like a config issue. How are you pulling the image? Do you have auth configured?

**Comment by khushboo121** [comment]
@cartermckinnon there is no changes before the EKS 1.24 upgrade harbour image pull is working as we are using the harbour from last 3 year and it is working with docker EKS version < 1.24.

**Comment by dims** [comment]
@khushboo121 i'd recommend reaching out through AWS support channels. "last 3 year and it is working with docker EKS version < 1.24" does not really help make the case as there is a switch from docker to containerd and something seems to have gone wrong there.

**Comment by sidewinder12s** [comment]
We're on Kubernetes 1.24, more recent AMI and on Harbor v2.7.2 and we're not having any issues like this FYI.

**Comment by cartermckinnon** [comment]
Closing as this does not appear to be related to the AMI.
