### ISSUE TITLE
why is p5 max 100 pods while p4d.24xlarge 737 ?

### ISSUE THREAD

**Issue by elgalu** [awslabs/amazon-eks-ami#1392]
https://github.com/awslabs/amazon-eks-ami/blob/865f9f2b6990e8acc407f4d0456411c16cf90964/files/eni-max-pods.txt#L508C13-L508C13

why is p5 max 100 pods while p4d.24xlarge 737 ?

**Comment by cartermckinnon** [comment]
These values are extrapolated from the limitations of the VPC CNI, which can only utilize the primary network card of the instance. The VPC CNI team is working on removing this limitation.

Of course, not everyone uses the VPC CNI, and they may have prefix delegation enabled which makes this a non-issue; so an override was created for `p4de.24xlarge`: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/gen_vpc_ip_limits.go#L204. We may create a similar override for `p5` types -- we're still working on support for that instance type. For now, this value is just auto-generated with the standard formula: `primaryNetworkCard.maxENI's * ipv4AddressesPerENI`.
