### ISSUE TITLE
amazon-eks-gpu-node-1.27-v20230816 not able to join EKS cluster

### ISSUE THREAD

**Issue by strangeman** [awslabs/amazon-eks-ami#1398]
**What happened**:

Nodes with AMI `amazon-eks-gpu-node-1.27-v20230816` isn't able to join the EKS cluster. 
Kubelet fails with `"command failed" err="failed to parse kubelet flag: unknown flag: --container-runtime"`

BTW `amazon-eks-node-1.27-v20230816` working ok.

Can reproduce that behavior in us-east-1 and us-west-2 regions with g5.xlarge instances.

**What you expected to happen**:

Node, based on  `amazon-eks-gpu-node-1.27-v20230816` AMI should successfully join the cluster.

**Anything else we need to know?**:

`/etc/systemd/system/kubelet.service` differs in `amazon-eks-gpu-node-1.27-v20230816` and `amazon-eks-node-1.27-v20230816` 

```
[amazon-eks-gpu-node-1.27-v20230816]# kubelet --version
Kubernetes v1.27.3-eks-a5565ad

[amazon-eks-gpu-node-1.27-v20230816]# cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=docker.service iptables-restore.service
Requires=docker.service

[Service]
ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5
ExecStart=/usr/bin/kubelet \
    --config /etc/kubernetes/kubelet/kubelet-config.json \
    --kubeconfig /var/lib/kubelet/kubeconfig \
    --container-runtime docker \                                                         <------------------ it cause the error
    --network-plugin cni \
    --image-credential-provider-config /etc/eks/image-credential-provider/config.json \
    --image-credential-provider-bin-dir /etc/eks/image-credential-provider \
    $KUBELET_ARGS \
    $KUBELET_EXTRA_ARGS

Restart=always
RestartSec=5
KillMode=process

[Install]
WantedBy=multi-user.target
```

```
[amazon-eks-node-1.27-v20230816]# kubelet --version
Kubernetes v1.27.3-eks-a5565ad

[amazon-eks-node-1.27-v20230816]# cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service sandbox-image.service
Requires=containerd.service sandbox-image.service

[Service]
Slice=runtime.slice
ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5
ExecStart=/usr/bin/kubelet \
    --config /etc/kubernetes/kubelet/kubelet-config.json \
    --kubeconfig /var/lib/kubelet/kubeconfig \
    --container-runtime-endpoint unix:///run/containerd/containerd.sock \
    --image-credential-provider-config /etc/eks/image-credential-provider/config.json \
    --image-credential-provider-bin-dir /etc/eks/image-credential-provider \
    $KUBELET_ARGS \
    $KUBELET_EXTRA_ARGS

Restart=on-failure
RestartForceExitStatus=SIGPIPE
RestartSec=5
KillMode=process
CPUAccounting=true
MemoryAccounting=true

[Install]
WantedBy=multi-user.target
```

**Comment by strangeman** [comment]
My bad, sorry for the inconvenience. I messed up with the bootstrap parameters. :(

**Comment by villapx-path** [comment]
@cartermckinnon I saw you thumbs-up'd his comment. Do you happen to know the answer to my question? I'm curious why I need to specify bootstrap parameters when using the accelerated AMI ID in my launch template; nothing else is different in the launch template from before.

Just seeking to understand, thanks in advance if you can help!

**Comment by cartermckinnon** [comment]
The two AMI variants use the same bootstrap script, the requirements are the same. If you're using managed nodegroups and specify an AMI ID in your launch template, you have to define the bootstrap command. https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html

**Comment by villapx-path** [comment]
Thank you!! I submitted feedback on the "Amazon EKS optimized Amazon Linux AMIs" page suggesting an improvement to make it more clear that this is a requirement

**Comment by villapx-path** [comment]
> The two AMI variants use the same bootstrap script, the requirements are the same. If you're using managed nodegroups and specify an AMI ID in your launch template, you have to define the bootstrap command. https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html

Thank you!! I submitted feedback on the "Amazon EKS optimized Amazon Linux AMIs" page suggesting an improvement to make it more clear that this is a requirement

**Comment by cartermckinnon** [comment]
I’ll bring it up with the doc folks, thanks for the feedback!

**Comment by strangeman** [comment]
@villapx-path I incorrectly described the problem. In my case, I build a custom AMI based on amazon-eks-gpu-node (with some preloaded docker images etc). For those manipulations I install, use, and then delete the aws-cli. In older releases, it worked correctly but k8s 1.27 AMIs use aws-cli in bootstrap.sh, so that script started to fail. After log investigation, I figured that out and fixed the build script.

But also I pass some parameters to the bootstrap script, yeah, for example, I override some kubelet args.
