### ISSUE TITLE
Shiped AWS CLI doesn't know EKS service 

### ISSUE THREAD

**Issue by aruetten** [awslabs/amazon-eks-ami#14]
Hi,

the current `eks-worker-v20` AMI (`ami-dea4d5a1` in us-east-1 (Copied `ami-73a6e20b` from us-west-2)) ships version `1.15.31` of the AWS CLI

EKS was introduced with version `1.15.32` which means first step each worker does is to teach his local AWS CLI what EKS is:

```
[root@ip-10-128-8-14 eks]# aws eks
Invalid choice: 'eks', maybe you meant:
  * es
[root@ip-10-128-8-14 eks]# aws configure add-model --service-model file://eks-2017-11-01.normal.json --service-name eks
[root@ip-10-128-8-14 eks]# aws eks
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```

Please either update the shipped AWS CLI or move that step into the AMI build process.

**Comment by micahhausler** [comment]
Yep! It was released before the CLI had eks in it. We'll be releasing a new worker AMI soon with an updated awscli
