### ISSUE TITLE
EKS 1.27:  systemd dependency tree not updating when launching new pods? 

### ISSUE THREAD

**Issue by mhaynesvci** [awslabs/amazon-eks-ami#1404]
As a part of our upgrade to eks 1.27 / containerd, we have been attempting to migrate an existing custom "node drain" service to our new nodes. This is a bit of a hack, but it's worked quite well for us for a couple years - basically what it does is load a service on startup which sits in front of the dockerd/containerd and kubelet, and prevents pod shutdown on system halt for a period of time (for the replacement node to come online) and then does a `kubectl node drain <self>` to gracefully evict the running pods. More info here: https://faun.pub/graceful-draining-secret-to-node-rotation-in-eks-4d85e1882720

This all worked well enough in our previous 1.23 cluster under dockerd, however I've noticed some strange behaviour in 1.27/containerd. 

Basically, the service works as expected (after updating to be dependent on `containerd.service`) in the sense it prevents containerd/kubelet from stopping, _however_, the pods themselves still stop (and go to a `Completed` state), upon node halt.

Eventually I realized that if I issued a `systemctl daemon-reload`, it would "grab" the running pods, and they would stay running until the service exited as expected. However, any _new_ pods added to the host would be again exempt from the process. For the time being, I've added a cron to do the daemon-reload every minute and things are working, but it's a hack and I'd like to understand what's actually going on. 

Have I missed a new dependency? I attempted to hook the service into `kubepod.slice`, `kubepods-burstable.slice` and `kubepods-besteffort.slice` to no avail. Attempting to determine the exact dependencies via `systemctl list-dependencies` hasn't really illuminated anything for me, the processes that appear to be stopping prematurely (as per the console output on shutdown) are the `cri-containerd-<uid>.scope` objects, and they don't appear live beneath anything? Obviously I'm not a systemd expert, so I might be missing something obvious here. 

Any insight appreciated! TIA 

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): t3a.medium
- EKS Platform version: eks.4
- Kubernetes version: 1.27
- AMI Version: amazon-eks-node-1.27-v20230816
- Kernel: 5.10.186-179.751.amzn2.x86_64 
- Release information:

```
BASE_AMI_ID="ami-0a6c4ce5a4a59e9e2"
BUILD_TIME="Wed Aug 16 02:57:51 UTC 2023"
BUILD_KERNEL="5.10.186-179.751.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
I probably can't do much to debug your custom hook, but I would consider moving that logic off of the node. Kubelet's graceful shutdown behavior would help to some degree, but the older `systemd` we have on AL2 doesn't support it -- that will come with AL2023 in the medium term.
