### ISSUE TITLE
AWS EC2 Image Builder support

### ISSUE THREAD

**Issue by sega19** [awslabs/amazon-eks-ami#1409]
My customer has standardized on EC2 Image Builder and would like to use that over Packer. I can provide a sample EC2 Image Builder Cloudformation YAML or CDK if it will help.

**Comment by cartermckinnon** [comment]
If there's a way to support Image Builder with a thin, low-maintenance wrapper/entrypoint, feel free to open a PR; but we currently intend to stick with Packer for the official builds.
