### ISSUE TITLE
Nodes can't join with amazon-eks-node-1.25-v20230825

### ISSUE THREAD

**Issue by thejosephstevens** [awslabs/amazon-eks-ami#1412]
**What happened**:
We upgraded nodes on a cluster earlier today to amazon-eks-node-1.25-v20230825. Following that update, newly created EC2's did not join the cluster at all, resulting in a full outage as nodes rolled over time.

**What you expected to happen**:
We expected the nodes would join the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create an EKS v1.25.12-eks-2d98532 cluster (I don't know how specific this is tot he issue, but this is what we have)
Launch an EC2 with the following userdata template in a subnet with access to the cluster backend (values need to be populated):
```
#!/bin/bash
set -ex

sudo yum install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm

# Bootstrap and join the cluster
API_SERVER_URL=https://REDACTED.gr7.us-east-1.eks.amazonaws.com

/etc/eks/bootstrap.sh $CLUSTER_NAME --b64-cluster-ca '$BASE64_CLUSTER_CA' --kubelet-extra-args '--node-labels=aws=$CLUSTER_NAME-default-pool,node.kubernetes.io/lifecycle=on-demand,eks.amazonaws.com/nodegroup=$CLUSTER_NAME-default,pool=default --register-with-taints=ignore-taint.cluster-autoscaler.kubernetes.io/cilium-agent-not-ready=true:NoExecute --registry-qps=10 --registry-burst=30' --apiserver-endpoint $API_SERVER_URL --container-runtime containerd --use-max-pods false
```

**Anything else we need to know?**:
Based on [this issue](https://github.com/awslabs/amazon-eks-ami/issues/1410), my assumption is that this is related to the runc update, so I'm concerned that new AMIs with the new runc also won't work for us.

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): One of the instances was r5n.4xlarge, but it happened across all types
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.6
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.25
- AMI Version: amazon-eks-node-1.25-v20230825 ([ami-02759925ad596a5f9](https://us-east-1.console.aws.amazon.com/ec2/home?AMICatalog%3A=&region=us-east-1#ImageDetails:imageId=ami-02759925ad596a5f9))
- Kernel (e.g. `uname -a`): 5.10.186-179.751.amzn2
- Release information (run `cat /etc/eks/release` on a node):

```
I can try to get this if needed, that'll require some setup to obtain
```

**Comment by cartermckinnon** [comment]
You'd need to look at the cloud-init log to see what failed in your user data, `/var/log/cloud-init-output.log`.

**Comment by cartermckinnon** [comment]
The `runc` issue would not cause this. That would only impact you if you happen to be relying on relative PATH lookups for executables in your containers.

**Comment by cartermckinnon** [comment]
My guess is this is your problem:
```
sudo yum install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
```

We already install the SSM agent from S3 in recent AMI releases. You should remove this from your user data.

**Comment by thejosephstevens** [comment]
Ahhhh, wonderful, thanks for responding so quickly! I'll do a quick test to verify if this fixes it.

**Comment by thejosephstevens** [comment]
Just tested and confirmed that you are correct, it was caused by the ssm-agent install in the userdata. After removing that extra line nodes joined just fine. Thanks for the help!

**Comment by cartermckinnon** [comment]
Glad to hear it! 👍
