### ISSUE TITLE
max pods ceiling value is overridden by --show-max-allowed

### ISSUE THREAD

**Issue by HenryXie1** [awslabs/amazon-eks-ami#1414]
**What happened**:
We use EKS opt AMI with node type c5.18xlarge

max pods value is overridden by 
1. --show-max-allowed is used in 
 https://github.com/awslabs/amazon-eks-ami/blob/7c168c0e473a504f4a485651d45fd8f0fa5a8c1f/files/bootstrap.sh#L514
 It should not be used here

it shows 737

**What you expected to happen**:
refer https://docs.aws.amazon.com/eks/latest/userguide/choosing-instance-type.html#determine-max-pods
max pods should be 250 

**How to reproduce it (as minimally and precisely as possible)**:
/etc/eks/max-pods-calculator.sh  --instance-type c5.18xlarge --show-max-allowed --cni-version 1.10.0

--> it returns 737

/etc/eks/max-pods-calculator.sh  --instance-type c5.18xlarge  --cni-version 1.10.0

--> it returns 250

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-southeast-2
- Instance Type(s): c5.18xlarge
- EKS Platform version : eks.11
- Kubernetes version : 1.23
- AMI Version: ami-018ae0f2e02aab38b
- Kernel (e.g. `uname -a`): Linux ANL10233355 5.4.249-163.359.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-018ae0f2e02aab38b"
BUILD_TIME="Fri Jul 28 04:19:03 UTC 2023"
BUILD_KERNEL="5.4.249-163.359.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
The `--show-max-allowed` flag is used here so that the output matches what *would* be in `eni-max-pods.txt`. If an instance type isn't found in that file, without this flag the calculator would return 250. When the instance type is added to the file, the value would increase to 737.
