### ISSUE TITLE
Include EFA Drivers

### ISSUE THREAD

**Issue by bwagner5** [awslabs/amazon-eks-ami#1415]
**What would you like to be added**:

EFA drivers included in the AMI.

**Why is this needed**:

Need to run an involved installation process in user-data to install EFA drivers today. 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable

**Additional Info**:

The EFA installer supports a minimal install which only includes the kernel module and rdma-core or a minimal install which includes openmpi and libfabric. 

The disk space required for the install options are:

drivers + libfabric + openmpi: 608.45 MiB
minimal (only drivers): 495.42 MiB

**Sample Install  Script**

```
## Setup
EFA_VERSION="1.25.1" # or latest
mkdir -p /tmp/efa-installer
cd /tmp/efa-installer

## Download Installer
curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_VERSION}.tar.gz

## Signature verification
curl -O https://efa-installer.amazonaws.com/aws-efa-installer.key
curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_VERSION}.tar.gz.sig
KEY=$(gpg --import aws-efa-installer.key 2>&1 | grep -o 'key [0-9A-Z]\+' | cut -d' ' -f2)
EXPECTED_FP=$(gpg --fingerprint "${KEY}" 2>&1 | grep -o 'Key fingerprint = [0-9A-Z ]\+' | cut -d'=' -f2 | tr -d " ")
gpg --verify ./aws-efa-installer-${EFA_VERSION}.tar.gz.sig &> siginfo
if [[ $? -ne 0 ]]; then
    echo "EFA Installer signature failed verification!"
    exit 2
fi
ACTUAL_FP=$(cat siginfo  | grep -o 'Primary key fingerprint: [0-9A-Z ]\+' | cut -d':' -f2 | tr -d " ")
if [[ "${EXPECTED_FP}" != "${ACTUAL_FP}" ]]; then
    echo "EFA Installer fingerprints do not match!"
    exit 2
fi

## Extract and Install
tar -xf aws-efa-installer-${EFA_VERSION}.tar.gz && cd aws-efa-installer
sudo ./efa_installer.sh --yes --no-verify

## Cleanup
cd /
rm -rf /tmp/efa-installer
```

**Comment by Issacwww** [comment]
> curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_VERSION}.tar.gz
Will this be the unified URL to get this package in all partitions? Especially would like to check it for MVP regions.
