### ISSUE TITLE
Kubernetes Legacy Package Repositories Will Be Frozen On September 13, 2023

### ISSUE THREAD

**Issue by samof76** [awslabs/amazon-eks-ami#1420]
**Environment**:
- AWS Region: us-east-1
- Instance Type(s): r6gd.8xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.4
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.27
- AMI Version: custom AMI from latest EKS optimized AMI
- Kernel (e.g. `uname -a`):  NA
- Release information (run `cat /etc/eks/release` on a node): NA

** Question **

Hi there is shift of repositories community repositories, as mentioned [here](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/). Has this change been implemented? If not when?

**Comment by cartermckinnon** [comment]
The EKS AMI has no dependency on those package repositories.
