### ISSUE TITLE
How to Change temporary security  with Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups?

### ISSUE THREAD

**Issue by Sandeepsac** [awslabs/amazon-eks-ami#1421]
How to Change temporary security  with Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups?
@cartermckinnon 
if temporary  security groups  create allow all [0.0.0.0/0] . its getting security breach , so we have request for have our own security group how to change that?

 
`2023-09-04T10:26:34Z: ==> amazon-ebs: Creating temporary security group for this instance: packer_64f-#####
2023-09-04T10:26:34Z: ==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
2023-09-04T10:26:34Z: ==> amazon-ebs: Launching a source AWS instance...
2023-09-04T10:26:34Z:     amazon-ebs: Adding tag: "creator": "ec2-user"
`

**Comment by cartermckinnon** [comment]
You probably want to create your own security group beforehand and pass in the ID. Refer to the Packer docs: https://developer.hashicorp.com/packer/integrations/hashicorp/amazon/latest/components/builder/ebs
