### ISSUE TITLE
Hostname Registration Bug with Dual DHCP Domains

### ISSUE THREAD

**Issue by JacobAmar** [awslabs/amazon-eks-ami#1428]
***What happened:***
While using an EKS AMI in an environment with VPC custom DHCP option set with two domains to populate the resolv.conf, the node's /etc/hostname creates incorrect entries. Specifically, rather than registering as <ip-name>.ec2.internal, it is registering as <ip-name>.ec2.internalec2customdomain.info. In other words, the two domain-names from the DHCP option set (ec2.internal and ec2customdomain.info) are being concatenated rather than being treated as separate entities.

***What you expected to happen:***
I expected that only the first domain-name from the DHCP option set (in this case, ec2.internal) would be used to construct the hostname (<ip-name>.ec2.internal). Furthermore, I expected that the kubernetes.io/hostname label would match the hostname as registered by the instance.

***How to reproduce it:***

- Set up a VPC custom DHCP option set with two domain-names: ec2.internal and ec2customdomain.info.
- Launch an instance in this VPC using an EKS AMI.
- Check the /etc/hostname on the instance.

***Anything else we need to know?:*** 
The problem does not appear to occur when using other AMIs, such as Ubuntu.

***Environment:***

AWS Region: us-east-1
Instance Type(s): Occurs on any instance type
EKS Platform version: `eks.10`
Kubernetes version: `1.24`
AMI Version: Tried on the latest release, release version: `1.24.16-20230825`, ami id: `ami-0520c6ee8495b7794`, image name: `amazon-eks-node-1.24-v20230825`
Kernel (e.g. uname -a): `5.10.186-179.751.amzn2.x86_64`
Release information:
```
BASE_AMI_ID="ami-0f2b325398f933a81"
BUILD_TIME="Fri Aug 25 20:04:37 UTC 2023"
BUILD_KERNEL="5.10.186-179.751.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
This isn't specific to the EKS AMI, it's a behavior documented here: https://docs.aws.amazon.com/vpc/latest/userguide/DHCPOptionSet.html#CreatingaDHCPOptionSet

> Some Linux operating systems accept multiple domain names separated by spaces. However, other Linux operating systems and Windows treat the value as a single domain, which results in unexpected behavior. If your DHCP option set is associated with a VPC that contains instances that are not all running the same operating systems, specify only one domain name.

If you really need to use multiple domains in your DHCP options set, you could possibly hack around in the cloud-init config -- but YMMV.
