### ISSUE TITLE
Build failing 

### ISSUE THREAD

**Issue by amol-mali** [awslabs/amazon-eks-ami#1438]
**What happened**:  When I tried to build this AMI it is failing in intsall-worker.sh where it is getting this error 
**mv: cannot stat 'tmp/worker/configure-clocksource.service': No such file or directory**

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:   I just used command 
make 1.27 aws_region=$AWS_REGION source_ami_id=$AMI_ID source_ami_owners=$AMI_OWNER_ACCOUNT_ID source_ami_filter_name="$AMI_NAME" subnet_id="$SUBNET_ID"

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-west-1
- Instance Type(s): 
- AMI Version: CIS Amazon Linux 2 Benchmark - Level 2

**Comment by cartermckinnon** [comment]
can you provide the complete make command that you used?

**Comment by amol-mali** [comment]
@cartermckinnon thanks for quick response,
I am following steps provided in https://aws.amazon.com/blogs/containers/building-amazon-linux-2-cis-benchmark-amis-for-amazon-eks/

make 1.27 aws_region=$AWS_REGION source_ami_id=$AMI_ID source_ami_owners=$AMI_OWNER_ACCOUNT_ID source_ami_filter_name="$AMI_NAME" subnet_id="$SUBNET_ID"

**Comment by amol-mali** [comment]
[Makefile.txt](https://github.com/awslabs/amazon-eks-ami/files/12697501/Makefile.txt)

**Comment by cartermckinnon** [comment]
Can you give me the actual values you’re using? I can’t reproduce this issue with the default values, so I need a complete repro to get to the bottom of it

**Comment by cartermckinnon** [comment]
Can you give me a complete repro with the variables you’re overriding? I can’t reproduce this with the default values.

**Comment by amol-mali** [comment]
Is it a good idea to privide the details publicly here??

**Comment by cartermckinnon** [comment]
If you can’t share the details publicly, please open a case with AWS Support and I can track it down.
