### ISSUE TITLE
Property --cgroup-root was not specified

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#146]
**What happened**:
`--cgroup-root` property was not specified

**What you expected to happen**:
Configure `--cgroup-root=/` and remove noise in the kubelet log

**How to reproduce it (as minimally and precisely as possible)**:
Run regular node and check kubelet logs

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
Jan 11 11:39:20 ip-10-10-11-171 kubelet: I0111 11:39:20.188327    4997 server.go:648] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
```

**Comment by micahhausler** [comment]
I'd be happy to accept a PR with this change
