### ISSUE TITLE
Nvidia device plugin pods failed to start

### ISSUE THREAD

**Issue by HenryXie1** [awslabs/amazon-eks-ami#1470]
**What happened**:
We are using an AMI based on EKS Optimized GPU AMI (ami-00705365e84fe29ac) which is amazon-eks-gpu-node-1.24-v20231002

we started a new node with instance type : ` inf1.xlarge`  It joins cluster well.

we follow the guide to install nvidia device plugin daemonset
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

But after we apply nvidia device plugin via 
https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.1/nvidia-device-plugin.yml

The pods failed with error

```
Oct 13 09:23:21 ANL10235144 kubelet[7155]: E1013 09:23:21.828725    7155 remote_runtime.go:453] "StartContainer from runtime service failed" err=<
Oct 13 09:23:21 ANL10235144 kubelet[7155]: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: runc create failed: unable to start containe
Oct 13 09:23:21 ANL10235144 kubelet[7155]: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
```

**What you expected to happen**:
pods start well
**How to reproduce it (as minimally and precisely as possible)**:
start a node with instance type: `inf1.xlarge` and ami: `ami-00705365e84fe29ac`
apply the yaml of https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.1/nvidia-device-plugin.yml

**Anything else we need to know?**:
The cuda drivers info is here

```
[root@APL12312558 ~]# yum list installed |grep -i cuda
cuda.x86_64                      11.4.0-1               @amzn2-nvidia-470-branch
cuda-11-4.x86_64                 11.4.0-1               @amzn2-nvidia-470-branch
cuda-cccl-11-4.x86_64            11.4.43-1              @amzn2-nvidia-470-branch
```
we also hit this error when running nvida-smi
```
[root@APL12312558 ~]# nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Environment**:
- AWS Region:ap-southeast-2
- Instance Type(s): inf1.xlarge
- EKS Platform version: (eks.10):
- Kubernetes version: (1.24):
- AMI Version: ami-00705365e84fe29ac
- Kernel (e.g. `uname -a`): Linux APL12312558 5.4.254-170.358.amzn2.x86_64 
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by HenryXie1** [comment]
we suspect CUDA 11.4 in the AMI was old (released on Jun 2021)

**Comment by cartermckinnon** [comment]
Inferentia instances don’t have NVIDIA hardware: https://aws.amazon.com/machine-learning/inferentia/
