### ISSUE TITLE
Is cpu throttling issue fixed in Kernel version 5.10.192-183.736.amzn2.x86_64?

### ISSUE THREAD

**Issue by agile6v** [awslabs/amazon-eks-ami#1471]
related issues: https://github.com/awslabs/amazon-eks-ami/issues/372

**Comment by cartermckinnon** [comment]
Are you just asking if this commit is in the tree? https://github.com/torvalds/linux/commit/de53fd7aedb100f03e5d2231cfce0e4993282425

AFAICT, yes. It was merged upstream for the 5.4 release. I'm not aware of any reverts in AL2 builds.
