### ISSUE TITLE
Flag --resource-container has been deprecated

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#148]
**What happened**:
`deprecated` log entries appears during kube-proxy startup

**What you expected to happen**:
Remove deprecated flag

**How to reproduce it (as minimally and precisely as possible)**:
Run regular node and check kube-proxy logs

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
Flag --resource-container has been deprecated, This feature will be removed in a later release.
```

**Comment by micahhausler** [comment]
This has been [deprecated for 3 years](https://github.com/kubernetes/kubernetes/pull/17621/), but I don't seen any indication the flag is going away any time soon. The default value is `kube-proxy`, but since kube-proxy runs in a container we need to set the value to an empty string

**Comment by dawidmalina** [comment]
Hmm that's interesting. We are not setting this in our clusters and it's working and looks like kubeadm is not setting this as well: https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L81

Can you tell me why "we need to set the value"? Maybe I'm not aware about some issue.

**Comment by micahhausler** [comment]
The flag comes from when kube-proxy was run as a host process, not in a container. It was used to specify a cgroup. I tried removing the flag and wasn't able to immediately discern a difference, but given that setting the flag to an empty string is the default upstream configuration, I'd rather not modify a known-working configuration that happens to have a deprecated log message.

**Comment by dawidmalina** [comment]
Wow did you saw "Deprecation Notice" on https://github.com/kubernetes/kubernetes/tree/v1.11.5/cluster

If you really need "default upstream configuration" go here: https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L81

**Comment by dawidmalina** [comment]
Do you think I should create ticket for this in container-roadmap project?
