### ISSUE TITLE
How will EKS extended support impact the health of this project?

### ISSUE THREAD

**Issue by stevehipwell** [awslabs/amazon-eks-ami#1491]
Given that a number of improvements to this project have been pushed back waiting for the deprecation of EKS v1.24 and the removal of Docker I'd like to understand what the introduction of [EKS extended support](https://aws.amazon.com/blogs/containers/amazon-eks-extended-support-for-kubernetes-versions-available-in-preview/) mean in the context of the EKS AMI?

**Comment by cartermckinnon** [comment]
We'll do what cleanup we can while supporting all the covered EKS versions (and avoiding breaking changes if at all possible). Some things that we've considered frozen/in maintenance mode will inevitably have to change throughout the extended support period.

**Comment by stevehipwell** [comment]
@cartermckinnon I think that #1220 should be reconsidered given this new context and the expected life of EKS v1.23.

As for the bigger picture; maybe each LTS version should be captured as a configuration snapshot (repo fork or subdirectory) when it becomes LTS with only specific changes being backported? Otherwise I can't see how managing this many K8s versions as a single unit is going to be scalable.

Alternatively something like the Bottlerocket composition pattern would be a scalable solution? It wouldn't be too complex to modify the existing scripts to work in this way and would be similar to what I suggested in #1221 but for build instead of bootstrap.
