### ISSUE TITLE
Update to `containerd` 1.7.x

### ISSUE THREAD

**Issue by cartermckinnon** [awslabs/amazon-eks-ami#1503]
**What would you like to be added**:

We should update from 1.6.x to 1.7.x.

**Why is this needed**:

Eventually, the `--pod-infra-container-image` flag will be removed, and we'll require the pinned-image support in `containerd` 1.7 to avoid the sandbox image being garbage-collected.

- [Clean up dockershim flags in the kubelet](https://github.com/kubernetes/kubernetes/issues/106893)

**Comment by msporleder-work** [comment]
I am suspicious that we are hitting https://github.com/containerd/containerd/issues/4604 and https://github.com/containerd/containerd/pull/6478 in our EKS environment so 👍  from me

**Comment by cartermckinnon** [comment]
@msporleder-work this issue: https://github.com/containerd/containerd/issues/4604

Was resolved before the initial containerd 1.6 release AFAICT, shouldn’t require 1.7: https://github.com/containerd/containerd/commit/c2cb589221de30eb12882a2a83b6f8441209352a

**Comment by msporleder-work** [comment]
Oh it says "Fixed by https://github.com/containerd/containerd/pull/6478"  so maybe I was confused.  Anyway I am hopeful that this helps with some, at least, very similar hangs and errors messages :)
