### ISSUE TITLE
Volume is not mounted to kube-proxy

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#151]
**What happened**:
`/lib/modules` volume is not mounted to kube-proxy

**What you expected to happen**:
Properly configure kube-proxy daemonset

**How to reproduce it (as minimally and precisely as possible)**:
Run regular node and check kube-proxy logs

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
E0111 11:35:10.732497       5 proxier.go:459] Failed to read file /lib/modules/4.14.88-88.76.amzn2.x86_64/modules.builtin with error open /lib/modules/4.14.88-88.76.amzn2.x86_64/modules.builtin: no such file or directory
W0111 11:35:10.733252       5 proxier.go:472] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0111 11:35:10.733911       5 proxier.go:472] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0111 11:35:10.734515       5 proxier.go:472] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0111 11:35:10.735100       5 proxier.go:472] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0111 11:35:10.735711       5 proxier.go:472] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
```

**Comment by micahhausler** [comment]
Reading the last 5 log lines:

> ...You can ignore this message when kube-proxy is running inside container without mounting /lib/modules

This is just noise in the logs.

**Comment by dawidmalina** [comment]
> This is just noise in the logs.

Seriously?

**Comment by micahhausler** [comment]
> Seriously?

Yes, is there something breaking here for you? EKS runs kube-proxy in a container.

**Comment by dawidmalina** [comment]
Yes, as without this you can't enable ipvs mode and I really hope you are working on ipvs :). Based on experience from different ticket do you want me to create ticket in container-roadmap project?

**Comment by micahhausler** [comment]
yes, please do!
