### ISSUE TITLE
boostrap.sh --dns-cluster-ip not being picked up by the kubelet

### ISSUE THREAD

**Issue by saiyen2002** [awslabs/amazon-eks-ami#1522]
**What happened**:
When spinning up a new self managed eks node group with the  launch config containing boothstrap.sh configuraiton of `--dns-cluster-ip` (found [here](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L29C9-L29C25))this does not seem to be passed on to the kubelet

**What you expected to happen**:
new pods being scheduled in the nodegroup should have dns settings in `/etc/resolve.conf` that respect `--dns-cluster-ip` config that was passed to the bootstrap.sh script

**How to reproduce it (as minimally and precisely as possible)**:
spin up a new self managed node group via whichever method you wish with the the launch config below.
i used terraform with eks module, which generated the launch config below.

```
#!/bin/bash
set -e
B64_CLUSTER_CA=LS0tLS1CRU
API_SERVER_URL=https://4someidgr7.eu-west-1.eks.amazonaws.com
/etc/eks/bootstrap.sh myblue1_26 --kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot,nodegroup-name=spot-6 --register-with-taints=sbclustering=sbclustering:NoSchedule' --dns-cluster-ip '169.254.20.10,172.20.0.10'  --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL

```

after spinning up new self managed node group, schedule a pod into that group and check the `/etc/resolv.conf`
**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1 
- Instance Type(s):
- EKS Platform version  "eks.8"
- Kubernetes version : 1.26
- AMI Version: amazon-eks-node-1.26-v20231027
- Kernel (e.g. `uname -a`): 5.10.198-187.748.amzn2.x86_64 
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0fe9073bb890001f8"
BUILD_TIME="Thu Nov 16 03:12:15 UTC 2023"
BUILD_KERNEL="5.10.198-187.748.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
This is probably caused by passing multiple IP's separated by a comma:
```
--dns-cluster-ip '169.254.20.10,172.20.0.10'
```

Because of this: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L29C9-L29C25

You would end up with a kubelet config file that contains:
```
"clusterDNS": [
  "169.254.20.10,172.20.0.10"
]
```

You probably have a log line like this from kubelet: https://github.com/kubernetes/kubernetes/blob/1f07da7575452353354a544d22264923bc4236b8/pkg/kubelet/kubelet.go#L494
