### ISSUE TITLE
Upgrade EKS AMI Kernel

### ISSUE THREAD

**Issue by ahmedihabb2** [awslabs/amazon-eks-ami#1525]
**Environment**:
- AWS Region: Ireland
- Instance Type(s): t3a.xlarge
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.24
- AMI Version: 1.24.17-20231116
- Kernel (e.g. `uname -a`): 5.10.198-187.748.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

I am running Kubernetes version 1.24, and I employed AWS Inspector to examine the nodes in the cluster. The inspection revealed significant vulnerabilities in the kernel-headers and kernel-devel, and the recommended fix necessitates upgrading to kernel version 5.15. However, the current kernel version is 5.10. I attempted to follow this [document](https://repost.aws/knowledge-center/amazon-linux-2-kernel-upgrade) for kernel upgrade, but upon reboot, the system reverted to the previous kernel version.

Any help with how to upgrade the kernel?

**Comment by cartermckinnon** [comment]
Please open a ticket with AWS support for security-related issues.

**Comment by ahmedihabb2** [comment]
> Have you checked the Amazon Linux Security Center for kernel remediations?
> 
> https://alas.aws.amazon.com/alas2.html
> 
> Example: https://alas.aws.amazon.com/AL2/ALASKERNEL-5.15-2023-030.html
> 
> You may have to remove the versionlock as the kernel is typically locked to prevent accidental upgrade.
> 
> To remove the versionlock, run the following command:
> 
> $Sudo yum versionlock delete
> 
> As usual, restart the node afterwards for the kernel update to take effect.

Thanks a lot, it worked
