### ISSUE TITLE
Update containerd in yum repos to the latest patch

### ISSUE THREAD

**Issue by jahoward** [awslabs/amazon-eks-ami#1526]
**What would you like to be added**:

The only version of containerd available from AL2 yum repos is  1.6.19-1.amzn2.0.5. This was released in Feb this year

containerd is up to 1.6.25, can you publish the latest patched version to yum

**Why is this needed**:

To address CVEs

**Comment by dbasden** [comment]
1.6.25 also includes a fix to https://github.com/containerd/containerd/issues/9103 which causes deadlocks when exiting short running containers under load.

This bug has significant impact creating k8s Pods with a fast running initContainer, as kubelet cannot start the main Pod containers until containerd has guaranteed the initContainer has been fully terminated. 

  The bug leads to delays of 1 to 2 minutes in starting new Pods while waiting for the deadlock to be resolved cleaning up the  containerd's internal state for the initContainer. (normally when the node is under load or starting multiple pods at once with fast init containers)

It would be very useful to have the fix in the EKS image (patched in containerd 1.16.25)

**Comment by jahoward** [comment]
This is pretty serious, I am having to go to clients and ask for an exception for CVEs, the explanation will be, we cannot update because the package has not been updated by AWS for 9 months.

I tried the epel version as well this requires SELinix packages which are not available

**Comment by austinarbor-wk** [comment]
is there any ETA on getting the containerd version updated?

**Comment by dims** [comment]
See latest AMI ( https://github.com/awslabs/amazon-eks-ami/releases/tag/v20231201 )

We are on containerd **`1.7.2-1.amzn2.0.1`** now

<img width="657" alt="image" src="https://github.com/awslabs/amazon-eks-ami/assets/23304/2de63fcf-a577-4c3e-a7ba-d06576f86827">

**Comment by austinarbor-wk** [comment]
@dims 1.7.2 is also 6 months old (1.7.11 is latest). both containerd 1.6.x and 1.7.x are being actively developed and should be updated to the latest versions https://github.com/containerd/containerd/releases

**Comment by dims** [comment]
@austinarbor-wk yep!

**Comment by minosmlee** [comment]
Hello, My customer is experiencing the exactly same issue.
Would you provide any ETA of this Container version upgrading please?

**Comment by cartermckinnon** [comment]
We've just updated to 1.7.11
