### ISSUE TITLE
Can i use g5.4xlarge on EKS ?

### ISSUE THREAD

**Issue by reconlabs-luke** [awslabs/amazon-eks-ami#1530]
**What happened**:
![image](https://github.com/awslabs/amazon-eks-ami/assets/147128088/40422769-e3fc-4f21-930e-988647900bf2)
- I was operating EKS on Rancher. and I tried to add g5.4xlarge type but there wasn't the type.
- So I tried to add the type on EKS Dashboard. But it was just above err.

**What you expected to happen**:
- I want to add node group using g5.4xlarge type. Can i add it ?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-northeast-1
- Instance Type(s): g5.4large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):1.26
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by bryantbiggs** [comment]
The instance type isn't supported in the AZ you've specified. This is not related yo EKS but instead EC2 availability in supported AZs
