### ISSUE TITLE
failed to get node address from cloud provider

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#154]
**What happened**:
nodes occasionally do not register itself

**What you expected to happen**:
update kubernetes to 1.11.6 which contains fix for this: https://github.com/kubernetes/kubernetes/pull/70154

**How to reproduce it (as minimally and precisely as possible)**:
Not always reproducible but it's connected mentioned pull request

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
Jan 11 11:33:17 ip-10-10-10-225 kubelet: W0111 11:33:17.775258    3675 kubelet_node_status.go:1114] Failed to set some node status fields: failed to get node address from cloud provider: Timeout after 10s
```

**Comment by kaduev13** [comment]
@dawidmalina how did you fix the issue? We faced exactly the same problem with `t2.medium` instances:

Environment:
- AWS Region: `eu-central-1`
- Instance Type(s): `t2.medium`
- EKS Platform version: `eks.1`
- Kubernetes version: `v1.11.5-eks-6bad6d`
- AMI Version: `amazon-eks-node-1.11-v20190109 (ami-010caa98bae9a09e2)`
- Some logs (`journalctl -u kubelet`):

```
ip-10-0-0-49.eu-central-1.compute.internal kubelet[4355]: W0130 11:08:34.347754    4355 kubelet_node_status.go:1114] Failed to set some node status fields: failed to get node address from cloud provider: Timeout after 10s
ip-10-0-0-49.eu-central-1.compute.internal kubelet[4355]: W0130 11:08:53.319501    4355 kubelet_node_status.go:1114] Failed to set some node status fields: failed to get node address from cloud provider that matches ip: 10.0.0.49
```

**Comment by dawidmalina** [comment]
I've updated kubelet to v1.11.6 (from the official kubernetes repo) and then I couldn't reproduce this error. With 1.11.5 I can see this issue from time to time (this is not permanent issue in my case rather occasionally).

**Comment by kaduev13** [comment]
Thanks, I'll try to update `kubelet` to 1.11.6. Btw, it's not a permanent issue in our case as well, but it happened twice during the last 7 days.

**Comment by micahhausler** [comment]
Yep, this looks like its an issue in 1.11.5. We'll keep this issue open until we have a newer version of 1.11 available

**Comment by kaduev13** [comment]
Hey! I just wanted to ask – are there any updates (or plan of updates) regarding this issue?

**Comment by moseb** [comment]
I see there is 1.11.9 at https://github.com/awslabs/amazon-eks-ami/blob/88ca2ac5990773fb30034dbb5fc04ed192d08075/Makefile#L71 by now.

**Comment by cartermckinnon** [comment]
I'm going to close this issue, as it should be resolved in all versions of Kubernetes currently-supported by this AMI.
