### ISSUE TITLE
Can't use ListObjectsV2 on amazon-eks bucket

### ISSUE THREAD

**Issue by wesbrownfavor** [awslabs/amazon-eks-ami#1541]
**What happened**:
Attempting to run the make 1.24 command fails due to not being able to get **kubernetes_build_date** and **kubernetes_version** which appears to be populated by the script  **hack/latest-binaries.sh**

```
make 1.24

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
/Applications/Xcode.app/Contents/Developer/usr/bin/make k8s 
packer validate -var-file /Users/me/dev/infrastructure/aws-eks-custom-amis/amazon-eks-ami/eks-worker-al2-variables.json  -var arch='x86_64' -var instance_type='m5.large' -var docker_version='none' -var ami_component_description='(k8s: {{ user `kubernetes_version` }}, containerd: {{ user `containerd_version` }})' -var ami_name='amazon-eks-node-.-v20231208' /Users/me/dev/infrastructure/aws-eks-custom-amis/amazon-eks-ami/eks-worker-al2.json
Warning: Bundled plugins used

This template relies on the use of plugins bundled into the Packer binary.
The practice of bundling external plugins into Packer will be removed in an
upcoming version.

To remove this warning and ensure builds keep working you can install these
external plugins with the 'packer plugins install' command

* packer plugins install github.com/hashicorp/amazon

Alternatively, if you upgrade your templates to HCL2, you can use 'packer init'
with a 'required_plugins' block to automatically install external plugins.

You can try HCL2 by running 'packer hcl2_upgrade
/Users/me/dev/infrastructure/aws-eks-custom-amis/amazon-eks-ami/eks-worker-al2.json'

Error: 

2 errors occurred:
        * required variable not set: kubernetes_build_date
        * required variable not set: kubernetes_version




make[1]: *** [validate] Error 1
make: *** [1.24] Error 2
```

If I run the s3 command explicitly I get the same ListObjectV2 Access Denied error.
```
AWS_REGION=us-east-2 aws s3api list-objects-v2 --bucket amazon-eks --prefix "1.24" --query 'Contents[*].[Key]' --output text           

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

I am able to list other buckets and this was working for me yesterday so I'm not sure whats changed?

**What you expected to happen**:
I would expect to be able to list this bucket

**How to reproduce it (as minimally and precisely as possible)**:
Try this command out
```
AWS_REGION=us-east-2 aws s3api list-objects-v2 --bucket amazon-eks --prefix "1.24" --query 'Contents[*].[Key]' --output text           
```

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): n/a
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): n/a
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): n/a
- AMI Version: n/a
- Kernel (e.g. `uname -a`): n/a
- Release information (run `cat /etc/eks/release` on a node): n/a

**Comment by wesbrownfavor** [comment]
I can run the command if I use a different AWS account.  I think I've been banned or rate limited 😰

**Comment by cartermckinnon** [comment]
This works for me, so I think it's related to your speciic IAM creds.

**Comment by wesbrownfavor** [comment]
@cartermckinnon It works from one of my AWS accounts but not this specific AWS account and it worked earlier today.  Do you all have rate limiting on this bucket or ban based on account id? I've been building a pipeline and maybe it went a bit too hard.

**Comment by cartermckinnon** [comment]
We don't configure anything like that for this bucket, so you'd need to open a support ticket with S3 if this isn't a transient thing.
