### ISSUE TITLE
Add EFA version to CHANGELOG output

### ISSUE THREAD

**Issue by bryantbiggs** [awslabs/amazon-eks-ami#1543]
**What would you like to be added**:
- Add the version of EFA used to the CHANEGLOG entries

**Why is this needed**:
- Make it easy for consumers to see which version is installed per a given release

**Comment by cartermckinnon** [comment]
Was there an unstable EFA release?

**Comment by bryantbiggs** [comment]
After discussing from EFA team - installing using `latest` is recommended when installing in an AMI - its not recommend to use `latest` when dynamically installing (i.e. - installing in instance user data - this leads to various versions used across nodes which is not recommended)

No action required on installation but adding the version installed on the release is still nice to have

**Comment by cartermckinnon** [comment]
We added this a while back 👍
