### ISSUE TITLE
Add kubectl binary

### ISSUE THREAD

**Issue by yongzhang** [awslabs/amazon-eks-ami#1557]
**What would you like to be added**:
Add `kubectl` binary to the AMI:
https://github.com/awslabs/amazon-eks-ami/blob/e4e596d0d410083f7c49b63e0cbdd48cd24a8bcc/scripts/install-worker.sh#L292-L295

**Why is this needed**:
`kubectl` binary is very useful to allow users do some custom tasks.

**Comment by cartermckinnon** [comment]
What do you intend to do with `kubectl`?

**Comment by yongzhang** [comment]
> What do you intend to do with `kubectl`?

I basically have below use cases:
- Run scripts in user data to add dynamic labels, annoatations, etc...
- I have a shutdown script to run `kubectl drain node` when recycling eks nodes.
- Troubleshooting purpose. It seems it's also better to have kubectl in place in [this script](https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh)?

And it's a tiny and harmless change to the code or AMI, why not adding it?

**Comment by cartermckinnon** [comment]
Sounds legit to me. Feel free to open a PR 👍

**Comment by yongzhang** [comment]
> Sounds legit to me. Feel free to open a PR 👍

Cool, https://github.com/awslabs/amazon-eks-ami/pull/1558 submitted.

**Comment by cartermckinnon** [comment]
I've chatted with the team about this, and we don't think `kubectl` actually adds much value. We already ship `crictl` in the AMI, and things like this:
> I have a shutdown script to run kubectl drain node when recycling eks nodes.

Have better solutions, such as `kubelet`'s `GracefulNodeShutdown` feature.

Adding software to the AMI that isn't necessary increases the surface for CVE's, so without a compelling use-case I don't think we should make this change.
