### ISSUE TITLE
Send kube-proxy logs to stdout/stderr

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#156]
**What would you like to be added**:
Is it possible that kube-proxy logs will be sent directly to stderr/stdout instead to node file.

**Why is this needed**:
Having approach with limited (or even no) access to compute node it would be much more easier to check kube proxy logs via kubectl logs command instead need to login to node.

**Comment by micahhausler** [comment]
This was a leftover setting from when we didn't have docker log rotation enabled. Now that docker log rotation is enabled, we'll update this to not log to a file for new versions of Kubernetes. It is enough of a change that we don't want to break compatibility for existing versions of Kubernetes, but I'll keep this open until we release the change

**Comment by mogren** [comment]
This issue has been resolved.
