### ISSUE TITLE
Enable live-restore for docker daemon

### ISSUE THREAD

**Issue by someword** [awslabs/amazon-eks-ami#157]
**What would you like to be added**:
The provided docker configuration does not enable live-restore for docker (https://docs.docker.com/config/containers/live-restore/).  

**Why is this needed**:
 Live restore comes in handy when the docker daemon crashes/restarts.    The running containers keep running.   With the current configuration when docker restarts/dies all of the containers die as well.

**Comment by micahhausler** [comment]
Closed with #158
