### ISSUE TITLE
Announcement: NVIDIA 535 series drivers will be backported to EKS optimized Accelerated AMIs for EKS versions 1.23 & 1.24 by late April 2024

### ISSUE THREAD

**Issue by ptailor1193** [awslabs/amazon-eks-ami#1580]
With Kubernetes version 1.25 or later, the EKS optimized Accelerated AMIs support NVIDIA 535 series or later drivers out of box. We plan to back port these drivers to older Kubernetes versions 1.23 and 1.24 by late March 2024.

**Comment by RamaNarayan** [comment]
Hey folks,

Just wanted to confirm if we are still tracking feb release and is there a specific release date set? I see 2-3 releases every month. Would this be available in the next release?

**Comment by wwvela** [comment]
We have unpinned the kernel for 1.29, 1.28 & 1.27
We are tracking 4/16 to release an AMI with kernel unpinned for 1.26
On 4/23 we will unpin for 1.25

**Comment by cartermckinnon** [comment]
We've delayed this process as we addressed a handful of issues with the NVIDIA drivers in later Kubernetes versions. Those issues have been resolved and we expect to complete the updates for 1.24 and 1.23 by the end of April. We will update one version per release.

**Comment by dgoupil** [comment]
Hi @cartermckinnon, are you still targeting before end of April? Thank you.

**Comment by cartermckinnon** [comment]
The ongoing release (`v20240425`) includes this change for 1.25. The next release (week of May 6) will include 1.24, and the release after that (week of May 13) will include 1.23.

**Comment by dgoupil** [comment]
Hi @cartermckinnon , 
Am I missing something or the nvidia driver 535 is already on the latest AMI release for k8s 1.23?

<img width="617" alt="image" src="https://github.com/awslabs/amazon-eks-ami/assets/70238543/5da322b9-f138-4366-ad76-6e11470bdac5">

Does that mean this issue is fixed?
Thanks

**Comment by cartermckinnon** [comment]
Yes, the 535-series drivers have been backported to 1.23+. I'm going to close this tracking issue. 👍
