### ISSUE TITLE
Current code does not support EKS 1.29

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [awslabs/amazon-eks-ami#1592]
Need manifests updated to support 1.29

**What would you like to be added**:

Support for EKS 1.29

**Why is this needed**:

EKS 1.29 is now generally available.

**Comment by rsavage-nozominetworks** [comment]
```shell
~/code/amazon-eks-ami (master ✔) ᐅ make 1.29
make: *** No rule to make target `1.29'.  Stop.
```

**Comment by cartermckinnon** [comment]
@rsavage-nozominetworks we're not going to create stub targets for each k8s version going forward, you can just do:
```
make k8s=1.29
```
