### ISSUE TITLE
New nodes getting errors and not connecting to cluster

### ISSUE THREAD

**Issue by gmoulindan** [awslabs/amazon-eks-ami#1625]
**What happened**:
Worker nodes are not connecting to EKS after using the latest release

**What you expected to happen**:
Nodes connecting and appearing in k8s api

**How to reproduce it (as minimally and precisely as possible)**:
I simply updated the AMI version to the latest in my cluster and it didn't connect.

**Anything else we need to know?**:
I saw this errors on instance logs:
```
[  115.367839] cloud-init[2498]: Job for sandbox-image.service failed because the control process exited with error code. See "systemctl status sandbox-image.service" and "journalctl -xe" for details.
[  115.368077] cloud-init[2498]: Exited with error on line 581
```
I saw that the latest AMI release had some sandbox related code and looking at `bootstrap.sh` file seems that this is where it try to start `sandbox-image` service
https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L581

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): all
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.12
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.26
- AMI Version: amazon-eks-node-1.26-v20240202

**Comment by cartermckinnon** [comment]
Can you fetch the logs for this service unit?
```
journalctl -u sandbox-image
```

**Comment by aaronmell** [comment]
Found the issue 

https://github.com/awslabs/amazon-eks-ami/pull/1605/files#diff-57a6aadbbb1d3df65f4675ae80c562f7e406bcb11e41f6afb974043a2ede0aa0R28

Line 28 is missing the region flag.

**Comment by cartermckinnon** [comment]
Are you installing the AWS CLI in your user data, with `yum`?

We install the v2 CLI in the AMI, but the AL2 repo still uses v1. The v2 CLI will detect the region from IMDS, while the v1 CLI does not.

**Comment by aaronmell** [comment]
Looks like we are installing the awscli

**Comment by cartermckinnon** [comment]
Removing that will get you going 👍 The AMI has always provided the AWS CLI.

**Comment by aaronmell** [comment]
I get the feeling that this is going to cause downtime for people as they don't realize its a breaking change if you installed v1 of the cli at some point (either accidently, or on purpose.

**Comment by cartermckinnon** [comment]
@ii-jswoods I've just verified that that AMI (in `us-west-2`) does have the AWS CLI v2, and I was able to run the `pull-sandbox-image.sh` script successfully. What else is going on in your user data?

**Comment by cartermckinnon** [comment]
@aaronmell I added a note about this to the release a few days ago, and my hope (and assumption) is that it isn't common practice to re-install the AWS CLI in user data.

**Comment by ii-jswoods** [comment]
> @ii-jswoods I've just verified that that AMI (in `us-west-2`) does have the AWS CLI v2, and I was able to run the `pull-sandbox-image.sh` script successfully. What else is going on in your user data?

Nothing outside of setting the max pods on the bootstrap script. Digging in to it we're installing `awslogs` in a packer build using the latest EKS AMI as the source, `awslogs` installs v1 of `awscli` as a dependency. Something to move away from on our side.
