### ISSUE TITLE
bootstrap.sh should try to read labels and taints from cluster-autoscaler instance tags

### ISSUE THREAD

**Issue by devkid** [awslabs/amazon-eks-ami#164]
**What would you like to be added**:
* The `bootstrap.sh` script that comes with this AMI should try to read the tags of the EC2 instance and use tags starting with `k8s.io/cluster-autoscaler/node-template/label/` and `k8s.io/cluster-autoscaler/node-template/taint/` and pass these as `--node-labels <labels>` and `--register-with-taints <taints>` to kubelet.
* Bonus points for reading the a tag like `eks.amazonaws.com/kubelet-extra-args` and passing this like `--kubelet-extra-args`.

**Why is this needed**:
This would simplify creating multiple stacks with different properties and different sets of labels and taints in conjunction with the cluster-autoscaler, as it would be sufficient to add these tag to the CloudFormation stack (because this automatically tags the auto scaling group and thus the instances).

If the maintainers would deem this a desirable feature, I would implement it myself.

**Comment by max-rocket-internet** [comment]
Related: https://github.com/awslabs/amazon-eks-ami/issues/85

**Comment by micahhausler** [comment]
I think a central controller is the way to go with node taints and labels based on tags. This lets us scope down the IAM permissions required on nodes, and reduces the number of components updating node labels.
