### ISSUE TITLE
Docker 18 upgrade

### ISSUE THREAD

**Issue by aly-aurea** [awslabs/amazon-eks-ami#165]
What is the plan to update the AMI with Docker 18?

**Comment by kinghajj** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md

"The validated docker versions are the same as for v1.10: 1.11.2 to 1.13.1 and 17.03.x."

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md

"The list of validated docker versions was updated to 1.11.1, 1.12.1, 1.13.1, 17.03, 17.06, 17.09, 18.06."

Unless AWS independently validates Docker 18.06 on K8s 1.11, I'd guess they'll wait until releasing 1.12+ on EKS.

**Comment by dawidmalina** [comment]
We are working on 18.06 and k8s 1.11 without any issues. But docker version should be user decision so I think the best approach would be to allow to define docker version during build. See: https://github.com/awslabs/amazon-eks-ami/pull/144

**Comment by micahhausler** [comment]
As @kinghajj stated, the supported version of docker for Kuberentes 1.10 and 1.11 is 17.03, and  EKS has validated docker 17.06 for those versions of Kubernetes.

In Kubernetes 1.12, [18.06 is supported](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies), and we'll be updating our AMI to use the newer version.  #144 does provide a configurable option for using a different version of docker, once that reverts to the same CNI version we can merge the PR.

You can follow along on aws/containers-roadmap#24 for Kubernetes 1.12 on EKS, and watch issues in that repo for other versions.
