### ISSUE TITLE
Pods in StartError state with 'unable to create new parent process' during worker node startup

### ISSUE THREAD

**Issue by VLZZZ** [awslabs/amazon-eks-ami#1651]
**What happened**:

We're on the latest AMI but however we still encountering sporadic errors during pod startup. 
Pod resulted in `StartError` state with
```
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/0/ns/ipc: no such file or directory: unknown
```
```
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/0/ns/ipc: no such file or directory: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Mon, 12 Feb 2024 07:06:06 +0100
```
Other pods have this message as well:
```
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: context canceled: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Mon, 05 Feb 2024 07:18:14 +0100
```

I'm also concerned about `Started:      Thu, 01 Jan 1970 01:00:00 +0100` 🧐

---

We've assumed that latest AMI with a `containerd 1.7.11-1` version will fix this (relates to the https://github.com/aws/amazon-vpc-cni-k8s/issues/2743) but unfortunately it wan't the case.
<img width="1418" alt="image" src="https://github.com/awslabs/amazon-eks-ami/assets/9082481/3100c8e9-29c4-434d-a958-22e7df9ccc23">
Cloudwatch query
```
fields @timestamp, @message, @logStream, @log
| sort @timestamp desc
| filter requestObject.status.containerStatuses.0.lastState.terminated.reason == 'StartError'
| filter @message like /OCI runtime create failed: runc create failed: unable to create new parent process: namespace path/
| stats count(*) as count by bin(1d)
| sort count desc
| limit 20
```

We deep dived a little and our current assumption that during node startup docker images being pull for each pod and resulted in Disk throughput as a bottleneck - so `iotime` is growing (as we see exact correlation between node LA and pods in `StartError` state)
We're using slightly increased `--registry-qps=10 --registry-burst=15` as we have 200+ nodes and a lot of pods in a cluster.
![image](https://github.com/awslabs/amazon-eks-ami/assets/9082481/77285720-86b6-42e8-b27b-5cc1223eb220)

We've increased EBS throughput 125MB/s -> 200MB/s and it looks like it getting better, but we still reaching the throughput limit while too many Pods are Pending during the node startup.

![image](https://github.com/awslabs/amazon-eks-ami/assets/9082481/feb3f491-cadf-4e54-b9c9-962923f3bf7d)

**What you expected to happen**:

I'd expect that `failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/0/ns/ipc: no such file or directory: unknown` is gone, as it might be unrelated to node load only (**not sure**)

**How to reproduce it (as minimally and precisely as possible)**:

Assumption: Schedule many pods to node or lower the EBS throughput to create artificial bottleneck.

**Anything else we need to know?**:

**Environment**:
- AWS Region: `us-west-2`
- Instance Type(s): `m6a.2xlarge`, `m6i.2xlarge`
- EKS Platform version: `eks.13`
- Kubernetes version: `1.25`
- AMI Version: `amazon-eks-node-1.25-v20240202`
- Kernel: `Linux ip-10-100-19-146.us-west-2.compute.internal 5.10.205-195.807.amzn2.x86_64 #1 SMP Tue Jan 16 18:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-059705a71ed021143"
BUILD_TIME="Fri Feb  2 16:46:39 UTC 2024"
BUILD_KERNEL="5.10.205-195.807.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
It certainly sounds like EBS throttling. You can continue increasing the provisioned throughput to match your usage pattern, or you can try using an instance type with local NVMe storage: https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#ephemeral-storage

If you need us to take a closer look, please open a case with AWS Support.
