### ISSUE TITLE
Errors in kubelet logs: "kubelet_node_status.go:377] Error updating node status, will retry: error getting node "ip-172-30-2-180.ec2.internal": Unauthorized"

### ISSUE THREAD

**Issue by brycecarman** [awslabs/amazon-eks-ami#166]
**What happened**:

In the kubelet logs, I see errors like:

```
Errors in kubelet logs: "kubelet_node_status.go:377] Error updating node status, will retry: error getting node "ip-172-30-2-180.ec2.internal": Unauthorized"
```
The errors do not appear to impact cluster operation - we have seen no errors in the health of the cluster, services, deployments, etc. They will hinder incident investigation by causing false positives and we aren't actually certain as to the impact.

"kubectl get node" shows all nodes as Ready - even when the errors are occurring the nodes appear to be shown as "Ready" and are capable of having pods scheduled.. We have not seen any nodes going from "Ready" to "Not Ready" or anything similar.

**What you expected to happen**:
No log messages if there are no issues affecting normal operation

**How to reproduce it (as minimally and precisely as possible)**:
All kubelet logs should show these types of error messages after running for some time.

**Comment by brycecarman** [comment]
It looks like this change to the aws iam authenticator should address this.

https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/981ecbeef8ead2720c42a62fc41d40ed6a145421

**Comment by cartermckinnon** [comment]
Please reopen this issue if you are still experiencing this on currently-supported AMI's.
