### ISSUE TITLE
Amazon Linux 2023 (AL2023) is now available for testing in Tech Preview

### ISSUE THREAD

**Issue by ptailor1193** [awslabs/amazon-eks-ami#1672]
Amazon Linux 2023 (AL2023) is now available for testing in Tech Preview for self managed nodes, and for Managed Node Groups (MNG) and Karpenter nodes via a custom AMI. AL2023 is a new Linux-based operating system designed to provide a secure, stable, high-performance environment to develop and run your cloud applications. It is the next generation of Amazon Linux from Amazon Web Services and is available across all supported EKS versions including EKS versions 1.23 and 1.24 in extended support. The AL2023 Tech Preview is available across all regions except Amazon Dedicated Cloud (ADC). Amazon EKS accelerated AMIs based on AL2023 will be available at a later date. Customers with accelerated workloads should continue to use the Amazon Linux 2 accelerated AMI or Bottlerocket.

To retrieve the AMI ID, use the following command and edit the highlighted portions with the appropriate values. For the AL2023 ARM based AMI use: `amazon-linux-2023/arm64/standard`.
```
 aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.29/amazon-linux-2023/x86_64/standard/recommended/image_id  --region region-code --query "Parameter.Value" --output text
```
You can use the AMI ID from above to create a self managed node group with AL2023. If you are interested in trying the AL2023 Tech Preview AMI with MNG or Karpenter via custom AMI support, you can do so by specifying the AMI ID. If you would like to build a custom AMI based on AL2023 from scratch, see [here](https://github.com/awslabs/amazon-eks-ami) for more information. 

Out of box support for MNG and Karpenter will be coming at a later date. At that time, you will be able to select AL2023 from a drop down via the console or SSM paramater via the CLI. 

**Considerations**:
Amazon Linux 2023 (AL2023) offers several improvements over Amazon Linux 2 (AL2). For a full comparison, see [Comparing Amazon Linux 2 and Amazon Linux 2023](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html).  Several packages have been added, upgraded, and removed from AL2. It is highly recommended to test your applications with AL2023 before upgrading. For a list of all package changes in AL2023, refer to [Package changes in Amazon Linux 2023](https://docs.aws.amazon.com/linux/al2023/release-notes/compare-packages.html). For a list of all kernel changes, see [Amazon Linux 2023 Kernel changes from AL2](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2-kernel.html). In addition to these changes, customers should be aware of the following:

* AL2023 introduces a new node initialization process nodeadm that uses a YAML configuration schema. If you are using self-managed node groups or an AMI with a launch template will now need to provide additional cluster metadata explicitly when creating a new node group. An exampleof the minimum required parameters is as follows, where `apiServerEndpoint`, `certificateAuthority`, and service `cidr` are now required:
```
---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: my-cluster
    apiServerEndpoint: https://example.com
    certificateAuthority: Y2VydGlmaWNhdGVBdXRob3JpdHk=
    cidr: 10.100.0.0/16
```
In AL2, the metadata from these parameters was discovered from the Amazon EKS DescribeCluster API call. With AL2023, this behavior has changed since the additional API call risks throttling during large node scale ups. This change does not affect customers that are using MNG without a launch template or Karpenter. For more information on `certificateAuthority` and service `cidr`, see [DescribeCluster](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html).

* Docker is not supported in AL2023 for all supported EKS versions. Support for Docker has ended and been removed with EKS version 1.24 or greater in AL2. For more information on deprecation, see [Amazon EKS ended support for Dockershim](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html) . 
* VPC CNI v1.16.2 or greater is required for AL2023
* If you are using instance types with local disks, they will automatically be mounted as `raid0`. `raid0` offers the benefit of evenly splitting data across two or more disks, and prioritizes performance and low latency. 
* AL2023 requires IMDSv2 by default. IMDSv2 has several benefits that help improve security posture. It uses a session-oriented authentication method that requires the creation of a secret token in a simple HTTP PUT request to start the session. A session’s token can be valid for anywhere between 1 second and 6 hours. For more information on how to transition from IMDSv1 to IMDSv2, see [Transition to using Instance Metadata Service Version 2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-transition-to-version-2.html) and [Get the full benefits of IMDSv2 and disable IMDSv1 across your AWS infrastructure](https://aws.amazon.com/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/). If you would like to use IMDSv1, you can still do so by manually overriding the settings using Instance Metadata option launch properties. 
* AL2023 features the next generation of Unified Control Group hierarchy (cgroupv2). cgroupv2 is used to implement a container runtime, and by systemd. While AL2023 still includes code that can make the system run using cgroupv1, this is not a recommended or supported configuration, and will be completely removed in a future major release of Amazon Linux.

**Comment by Alexhha** [comment]
@ptailor1193 

> AL2023 introduces a new node initialization process nodeadm that uses a YAML configuration schema. If you are using self-managed node groups or an AMI with a launch template will now need to provide additional cluster metadata explicitly when creating a new node group. An exampleof the minimum required parameters is as follows, where apiServerEndpoint, certificateAuthority, and service cidr are now required:

could you share what command we should run to automatically join a node to a cluster ? Previously we run `/etc/eks/bootstrap.sh CLUSTER_NAME`

Should we run `/usr/bin/nodeadm init` and pass node configuration via user data ?

**Comment by ndbaker1** [comment]
@Alexhha to have `nodeadm` join your node to the cluster there's no explicit invocation needed. It runs as a startup process and reads the `NodeConfig` you've provided in user data. 

The updated documentation at https://awslabs.github.io/amazon-eks-ami/nodeadm/ should help clarify usage for `nodeadm`

**Comment by Alexhha** [comment]
Thx for the info. 

```
---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: my-cluster
    apiServerEndpoint: https://example.com
    certificateAuthority: Y2VydGlmaWNhdGVBdXRob3JpdHk=
    cidr: 10.100.0.0/16
```
Last question - `cidr: 10.100.0.0/16` is that the same value as we provide in `service_ipv4_cidr` parameter of `aws_eks_cluster` terraform resource ?
```
resource "aws_eks_cluster" "sandbox" {
    name     = "eks-sandbox"
    version  = "1.29"

    kubernetes_network_config {
        service_ipv4_cidr = "192.168.128.0/24"
        ip_family         = "ipv4"
    }
}
```
I'm referring to the - https://docs.aws.amazon.com/cli/latest/reference/eks/describe-cluster.html
```
kubernetesNetworkConfig -> (structure)

    The Kubernetes network configuration for the cluster.

    serviceIpv4Cidr -> (string)

        The CIDR block that Kubernetes Pod and Service object IP addresses are assigned from.
Kubernetes assigns addresses from an IPv4 CIDR block assigned to a subnet that the node is in. 
If you didn't specify a CIDR block when you created the cluster, then Kubernetes assigns
addresses from either the 10.100.0.0/16 or 172.20.0.0/16 CIDR blocks. If this was specified, then it was specified
when the cluster was created and it can't be changed.
```

**Comment by youwalther65** [comment]
When I want to use IPv6 , what is the attribute for ip_family , it is just camel case  ipFamily? Just providing the IPv6 CIDR doe snot work for me.
