### ISSUE TITLE
AL2023 AMI(s) built using `main` branch missing CNI binaries

### ISSUE THREAD

**Issue by dims** [awslabs/amazon-eks-ami#1677]
We do the following in `master` for both AL2 and AL2023:
https://github.com/awslabs/amazon-eks-ami/blob/202ea4c304b8ac95fbc2db67be46c8d7e48f754c/scripts/install-worker.sh#L324-L346

However in the `main` branch, the AL2 provisioner [install_worker.sh](https://github.com/awslabs/amazon-eks-ami/blob/main/templates/al2/provisioners/install-worker.sh#L298-L320) has the same script bits to pull down CNI, but the Al2023 provisioner's copy [install_worker.sh](https://github.com/awslabs/amazon-eks-ami/blob/main/templates/al2023/provisioners/install-worker.sh) is missing the same.

Folks depend on the base set of CNI binaries to be present in the AMI, so can we please add it back? thanks!

**Comment by dims** [comment]
cc @ndbaker1 @cartermckinnon

**Comment by dims** [comment]
xref: https://github.com/awslabs/amazon-eks-ami/issues/1672

**Comment by bryantbiggs** [comment]
@dims FYI - https://github.com/awslabs/amazon-eks-ami/pull/1610

**Comment by dims** [comment]
@bryantbiggs yep! i'd prefer having those binaries back :)

**Comment by cartermckinnon** [comment]
We decided to remove the reference plugins because they aren't usually needed, and it's one less thing to distribute and maintain compatibility for. If this is causing issues in a CI job, can we just pull them at runtime on the CI node?

**Comment by dims** [comment]
@cartermckinnon not worried about CI jobs, it's already taken care of https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/286/files - let me sure we telegraph this explicitly for different folks who may try CNI(s) from different vendors (who may or may not know that we took this decision).

thanks

**Comment by jdn5126** [comment]
fwiw, the AWS VPC CNI does bundle and install the upstream CNI plugins itself
