### ISSUE TITLE
clusterDNS is overwritten via bootstrap.sh and does not support multiple IPs

### ISSUE THREAD

**Issue by ajohnstone** [awslabs/amazon-eks-ami#1684]
**What happened**:
clusterDNS is overwritten via bootstrap.sh

**What you expected to happen**:
support multiple IPs passing in the arg for cluster-dns.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
This has been implemented.
