### ISSUE TITLE
nodeadm fails to parse user data

### ISSUE THREAD

**Issue by nimaft** [awslabs/amazon-eks-ami#1701]
**What happened**:
When running `nodeadm init` it throws the error below:
```
{"level":"info","ts":1709500289.7936778,"caller":"init/init.go:49","msg":"Checking user is root.."}
{"level":"info","ts":1709500289.7966185,"caller":"init/init.go:57","msg":"Loading configuration..","configSource":"imds://user-data"}
{"level":"fatal","ts":1709500289.8128433,"caller":"nodeadm/main.go:36","msg":"Command failed","error":"yaml: line 4: could not find expected ':'","stacktrace":"main.main\n\t/workdir/cmd/nodeadm/main.go:36\nruntime.main\n\t/root/sdk/go1.21.7/src/runtime/proc.go:267"}
```
My user data looks this (with proper value):
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="
--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
/etc/eks/bootstrap.sh ipv4-prefix-delegation \
    --b64-cluster-ca LS0tLS1CRUdJT... \
    --apiserver-endpoint https://D247F... \
    --dns-cluster-ip 172.20.0.10 \
    --container-runtime containerd

--==MYBOUNDARY==
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: mycluster
    apiServerEndpoint: https://D247F...
    certificateAuthority: LS0tLS1CR...
    cidr: 172.20.0.0/16

--==MYBOUNDARY==--[
```

The reason I have data for both AL2 and AL23 is because I'm using it as a part of automation that handles both versions based on user input.

I know that the definition is correct because if I take below part and pass it on to `nodeadm` manually as my config file, it runs with no issues:
```yaml
---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: mycluster
    apiServerEndpoint: https://D247F...
    certificateAuthority: LS0tLS1CR...
    cidr: 172.20.0.0/16
```
**What you expected to happen**:
I expect nodeadm to pars the user data properly and use the information to add the instance to my cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create an EC2 instance with EKS-Optimized AL23 and pass the user data included above. Connect to the instance and run `nodeadm init`

**Anything else we need to know?**:

**Environment**: EKS 1.29 with VPC CNI v1.16.3-eksbuild.2
- AWS Region: US-WEST-2
- Instance Type(s): t2.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.29
- AMI Version:
- Kernel (e.g. `uname -a`): 6.1.77-99.164.amzn2023.x86_64 
- Release information (run `cat /etc/eks/release` on a node): ARCH="x86_64"

```
```

**Comment by ndbaker1** [comment]
Looks like parsing is failing when the line breaks aren't structed as expected. `nodeadm` parses the MIME multipart with standard libs like [`mime/multipart` and `net/mail`](https://github.com/awslabs/amazon-eks-ami/blob/main/nodeadm/internal/configprovider/userdata.go#L9-L10), so you'll have to follow [the nitty gritty details on the MIME spec](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). 
 
I'm able to set up an instance on the latest al2023 ami with the bootstrap excerpt from your userdata plus some additional line-breaks between headers and content, and get a successful `nodeadm init`:
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
set -ex
/etc/eks/bootstrap.sh ipv4-prefix-delegation \
    --b64-cluster-ca LS0tLS1CRUdJT \
    --apiserver-endpoint https://D247F \
    --dns-cluster-ip 172.20.0.10 \
    --container-runtime containerd

--==MYBOUNDARY==
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: test-cluster
    apiServerEndpoint: ...
    certificateAuthority: ...
    cidr: ...

--==MYBOUNDARY==--
```

**Comment by nimaft** [comment]
Thank you so much Nick! I will implement and keep you posted. I'm gonna close this issue because you got it working and I'm sure its gonna work for me too. Thanks again!

**Comment by znedw** [comment]
Sorry to bump a closed issue, I can't get a node to bootstrap
```
2024-03-22 05:07:34,902 - __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: 'b'---\\r'...
```

**Comment by ndbaker1** [comment]
@znedw it's fine that the data is unhandled, it just acts as a data source
can you take a look at the execution of the nodeadm unit by running
```
journalctl -u nodeadm-config
```

**Comment by znedw** [comment]
'''
Starting nodeadm-config.service - EKS Nodeadm Config...
{"level":"info","ts":1711089818.4551878,"caller":"init/init.go:49","msg":"Checking user is root.."}
{"level":"info","ts":1711089818.4622667,"caller":"init/init.go:57","msg":"Loading configuration..","configSource":"imds://user-data"}
{"level":"info","ts":1711089819.5107644,"caller":"init/init.go:66","msg":"Loaded configuration","config":{"metadata":{"creationTimestamp":null},"spec":{"cluster":{"nam>
{"level":"info","ts":1711089819.5115047,"caller":"init/init.go:68","msg":"Enriching configuration.."}
{"level":"info","ts":1711089819.5115254,"caller":"init/init.go:147","msg":"Fetching instance details.."}
{"level":"info","ts":1711089819.5197103,"caller":"init/init.go:153","msg":"Instance details populated","details":{"id":"i-xxxxxx","region":"ap-southeast-2",>
{"level":"info","ts":1711089819.519779,"caller":"init/init.go:154","msg":"Fetching default options..."}
{"level":"info","ts":1711089819.5217273,"caller":"init/init.go:162","msg":"Default options populated","defaults":{"sandboxImage":"602401143452.dkr.ecr.ap-southeast-2.a>
{"level":"info","ts":1711089819.5221477,"caller":"init/init.go:73","msg":"Validating configuration.."}
{"level":"info","ts":1711089819.5221589,"caller":"init/init.go:78","msg":"Creating daemon manager.."}
{"level":"info","ts":1711089819.5264494,"caller":"init/init.go:95","msg":"Configuring daemons..."}
{"level":"info","ts":1711089819.5264802,"caller":"init/init.go:102","msg":"Configuring daemon...","name":"containerd"}
{"level":"info","ts":1711089819.526518,"caller":"containerd/config.go:38","msg":"Writing containerd config to file..","path":"/etc/containerd/config.toml"}
{"level":"info","ts":1711089819.5347922,"caller":"init/init.go:106","msg":"Configured daemon","name":"containerd"}
{"level":"info","ts":1711089819.5348399,"caller":"init/init.go:102","msg":"Configuring daemon...","name":"kubelet"}
{"level":"info","ts":1711089820.7177713,"caller":"kubelet/config.go:298","msg":"Detected kubelet version","version":"v1.29.0"}
{"level":"info","ts":1711089820.7202582,"caller":"kubelet/config.go:218","msg":"Setup IP for node","ip":"10.230.41.209"}
{"level":"info","ts":1711089820.7211678,"caller":"kubelet/config.go:370","msg":"Writing kubelet config to file..","path":"/etc/kubernetes/kubelet/config.json"}
{"level":"info","ts":1711089820.988205,"caller":"init/init.go:106","msg":"Configured daemon","name":"kubelet"}
nodeadm-config.service: Deactivated successfully.
Finished nodeadm-config.service - EKS Nodeadm Config.
'''

**Comment by znedw** [comment]
it seems like the kubelet service isn't enabled, if i manually do this, and start the service, then the node shows up
![image](https://github.com/awslabs/amazon-eks-ami/assets/592153/6177deba-042c-41a7-94c5-33fa3ccdfb88)

it is not ready because the pod sandbox fails to pull the image (`http_put_response_hop_limit` maybe?)

should kubelet service be enabled by default?

**Comment by ndbaker1** [comment]
figured this was failing in config phase but also go ahead and take at 
```
journalctl -u nodeadm-run
```

this is where kubelet would actually get kicked off and where we also try to cache the sandbox image

**Comment by znedw** [comment]
thank-you! it was failing because `AmazonEC2ContainerRegistryReadOnly` was not attached to the node role.. not related to user-data... sorry about that

**Comment by orlra** [comment]
for anyone looking at this ticket because of al2 -> al2023 migration. make sure your nodeconfig.spec.cluster contains CIDR config and the user data.type is set to EKS_NODEADM.
cidr was not needed for al2, its mandatory for al2023.
