### ISSUE TITLE
Install the 2.12.0 ENA driver in the AMI

### ISSUE THREAD

**Issue by HenryXie1** [awslabs/amazon-eks-ami#1704]
**What happened**:
 We recently upgraded our cluster, to version 1.28 using the AMI based at https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202

we did a few peak load tests, we encountered several kernel errors: Frequent instances of ENA (Elastic Network Adapter) error, such as

- "TX hasn't completed, qid 3, index 314. 15328 msecs since last interrupt, 4712 msecs since last napi execution, napi scheduled: 1", followed by automatic ENA resets as a part of its self-healing mechanism.
**What you expected to happen**:
expect no such error

**How to reproduce it (as minimally and precisely as possible)**:
our team ran peak load test
**Anything else we need to know?**:
Upon further investigation, we identified that the ENA driver version 2.12.0, available at https://github.com/amzn/amzn-drivers/releases, includes bug fixes that could potentially address the issues we've experienced.

However, we observed that the latest AMI for version 1.28, as https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240227, incorporates the ENA driver version 2.11.1, which precedes the updates found in version 2.12.0.

**Environment**:
- AWS Region: ap-southeast-2
- Instance Type(s): any
- EKS Platform version: eks.7
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.28
- AMI Version: 1.28
- Kernel (e.g. `uname -a`): Linux ANL21657850 5.10.205-195.807.amzn2.x86_64 
- Release information (run `cat /etc/eks/release` on a node):
-  BASE_AMI_ID="ami-059705a71ed021143"
BUILD_TIME="Fri Feb  2 16:55:50 UTC 2024"
BUILD_KERNEL="5.10.205-195.807.amzn2.x86_64"
ARCH="x86_64"

We ask to install the 2.12.0 ENA driver in the 1.28 or all AMI releases

```
```

**Comment by cartermckinnon** [comment]
We use the latest version of the EFA installer at build time; so this will land whenever the installer provides it 👍

**Comment by sidewinder12s** [comment]
Looks like at least version `v20240409` of the AMI on 1.29 includes the updated driver:

```bash
$ modinfo ena
filename:       /lib/modules/5.10.213-201.855.amzn2.aarch64/kernel/drivers/amazon/net/ena/ena.ko
version:        2.12.0g
```

**Comment by cartermckinnon** [comment]
great! 🚀
