### ISSUE TITLE
setup-local-disks - add flag to disable using the mounted path for kubelet and containerd

### ISSUE THREAD

**Issue by primeroz** [awslabs/amazon-eks-ami#1706]
I am willing to do the change and open a PR but i wanted to check first if this is something that would be accepted 

**What would you like to be added**:

In some cases i want to use the [setup-local-disks](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bin/setup-local-disks) script to create the `md0` and mount it to a path but i don't want to use it for `kubelet` , `containerd` and `pod logs` 

this cannot be disabled right now, as far as i can see , https://github.com/awslabs/amazon-eks-ami/blob/master/files/bin/setup-local-disks#L81-L129 

I wanted to add a new flag to disable ( so enabled by default ) , then i would run with `userData` as part of my nodepool karpenter definition

**Why is this needed**:

I would like to use the NVME disks with MD0 raid for some hostpath mounts

**Comment by cartermckinnon** [comment]
I don't think this is unreasonable, but hostpath mounts are a bit of a red flag IMO 😄 Feel free to open a PR.

**Comment by primeroz** [comment]
> Feel free to open a PR.

Will do :+1: 

>  are a bit of a red flag IMO

you are preaching to the choir :angel:  :) i wish it was my decision

**Comment by sidewinder12s** [comment]
We had to write our own copy of the scripts because we wanted to mount kubelet and containerd but could not mount pod logs. Would be useful if it was generically made more configurable.

**Comment by primeroz** [comment]
@cartermckinnon even though i have not fully tested https://github.com/awslabs/amazon-eks-ami/pull/1723 is it possible to unlock workflows on it ?

**Comment by primeroz** [comment]
PR is ready for review, added testing a fixed a couple of things :pray:

**Comment by ndbaker1** [comment]
merged in https://github.com/awslabs/amazon-eks-ami/pull/1723, thanks for the additions 😀

**Comment by primeroz** [comment]
closing this :pray:
