### ISSUE TITLE
Ability to provide custom ami during build.

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#172]
**What would you like to be added**:
It would be nice to have ability to provide custom ami during build. So we can override:
- `name` (should points by default to `amzn2-ami-minimal-hvm-*`)
- `owners` (should points by default to `137112412989`)

Currently it's looks like this:
```
      "source_ami": "{{user `source_ami_id`}}",
      "source_ami_filter": {
        "filters": {
          "architecture": "x86_64",
          "name": "amzn2-ami-minimal-hvm-*",
          "root-device-type": "ebs",
          "state": "available",
          "virtualization-type": "hvm"
      },
      "owners": [ "137112412989" ],
```
But this `source_ami_id` only allows to extend filters not fully override.

> If you set this in conjunction with source_ami, the source_ami will be added to the filter. 

**Why is this needed**:
To allow end user to use custom ami (for example hardened one) without need to keep own fork of this repository.

**Comment by mogren** [comment]
Fix merged
