### ISSUE TITLE
Monitoring Memory and Disk Metrics

### ISSUE THREAD

**Issue by nicholasgcoles** [awslabs/amazon-eks-ami#173]
**What would you like to be added**:
Seeing as we specify an AMI for the worker nodes I think it would be great if the official eks ami supported exporting of memory and disk metrics. Instead of having to create a custom AMI and then following this guide below.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Why is this needed**:
If using Cloudwatch, these are super useful for alerts and monitoring. Perhaps this is an unreasonable request but I think it would be great.

**Comment by micahhausler** [comment]
This is definitely something we're interested in doing, but it most likely won't be a part of the AMI. This will likely be a daemonset installed on EKS clusters. Can you create an issue on https://github.com/aws/containers-roadmap?

**Comment by nicholasgcoles** [comment]
Thanks @micahhausler
