### ISSUE TITLE
nodeadm doesn't support userdata content-encoded with gzip

### ISSUE THREAD

**Issue by FireballDWF** [awslabs/amazon-eks-ami#1734]
nodeadm fails with an error message about control characters in userdata when the userdata has content-encoded with gzip, while cloud-init uncompresses the userdata just fine.  Disabling gzip of userdata allowed nodeadm to work as expected.

**Comment by cartermckinnon** [comment]
Do you compress your complete user data or individual parts of a MIME multi-part document?

#1762 covers the former but the latter is tricky; we need the `Content-Type` to determine if the MIME part contains our API types, and we won't know what the `Content-Type` is for the decompressed data. `cloud-init` just tries to guess based on what the decompressed data starts with (e.g. a shebang for `text/x-shellscript`), which probably isn't a road we want to go down. https://github.com/canonical/cloud-init/blob/596266ac13ef6e73ce0f1905871e736d8f78973e/cloudinit/user_data.py#L123-L134

**Comment by FireballDWF** [comment]
individual parts, workaround was easy in terraform, just set "gzip = false" instead of "gzip = true" for the "application/node.eks.aws" part.  If not easy to support, then at least update https://awslabs.github.io/amazon-eks-ami/nodeadm/ to document that gzipping the part is not supported.
