### ISSUE TITLE
Custom AMI Build

### ISSUE THREAD

**Issue by IgorKurylo** [awslabs/amazon-eks-ami#1756]
I have a general question regarding building custom AMIs. In my exploration, I've noticed that the source_ami_filter_name is set to `al2023-ami-minimal-2023.*-kernel-6.1*.` However, I need to create some custom AMIs based on `al2023-ami-2023.*.` 
These custom AMIs are developed by our Cloud Platform team, incorporating a significant number of elements for CIS hardening.

My query pertains to whether it's feasible to build custom EKS AMIs based on al2023-ami-2023.*, or if this approach isn't suitable for EKS.

**Comment by cartermckinnon** [comment]
You may run into some trivial issues if a package we try to install is already present, etc.; but yes in general that will work fine.
