### ISSUE TITLE
How do I configure Kube controller?

### ISSUE THREAD

**Issue by ChrisCooney** [awslabs/amazon-eks-ami#176]
We're looking into how to make our pod eviction timeout shorter so that our cluster can respond to dead nodes quicker. At present, I can't see a single place to inject the `--pod-eviction-timeout` flag. 

Is this a feature that hasn't been implemented yet or am I missing something?

**Comment by devkid** [comment]
In EKS, the kube-controller-manager is managed by AWS (along with the other components) and you cannot modify its parameters.

This AMI is only meant for the worker nodes; you can only modify the parameters of the kubelet here.

**Comment by ChrisCooney** [comment]
Understood - was hoping there might be something that I'd missed. Given it's not relevant, happy to close the issue.

**Comment by srinivasrk** [comment]
Is this still not supported ? I had a similar configuration to add (HPA scale down delay --horizontal-pod-autoscaler-downscale-delay) @ChrisCooney  Did you find a workaround? 
Thanks,
Srini

**Comment by ChrisCooney** [comment]
Afraid not! There is an open issue on the AWS container road map repository for it though.

**Comment by thangbn** [comment]
> Is this still not supported ? I had a similar configuration to add (HPA scale down delay --horizontal-pod-autoscaler-downscale-delay) @ChrisCooney Did you find a workaround?
> Thanks,
> Srini

I'm looking for the same thing. default value is 5m is way too long for my use case

**Comment by thangbn** [comment]
> Afraid not! There is an open issue on the AWS container road map repository for it though.

Can u pls point me to this?

**Comment by dbirks** [comment]
@thangbn - Looks like it's:
https://github.com/aws/containers-roadmap/issues/159

**Comment by thangbn** [comment]
> @thangbn - Looks like it's:
> [aws/containers-roadmap#159](https://github.com/aws/containers-roadmap/issues/159)

thanks
