### ISSUE TITLE
Wrong link in the documentation

### ISSUE THREAD

**Issue by efueyo** [awslabs/amazon-eks-ami#1760]
Only documentation on AWS https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html has a link to the changelog to view the latest images.

However the link points to branch "master" and the new updated branch is "main" (as stated in https://github.com/awslabs/amazon-eks-ami/issues/1656 )
The link should be updated from 
https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md
to 
https://github.com/awslabs/amazon-eks-ami/blob/main/CHANGELOG.md

![image](https://github.com/awslabs/amazon-eks-ami/assets/2970863/7de13d12-a327-4bc0-ae17-fd2432fc3d1e)

**Comment by cartermckinnon** [comment]
This has been updated.
