### ISSUE TITLE
AL2023 NodeConfig docs for KubeletConfiguration point to the wrong document

### ISSUE THREAD

**Issue by stevehipwell** [awslabs/amazon-eks-ami#1763]
**What happened**:
When clicking on the [KubeletConfiguration ](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/) I get the `v1` docs which doesn't contain the configuration options I'd expect.

**What you expected to happen**:
I'd expect to get the [v1beta1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) docs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The [docs](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for configuring Kubelet via a configuration file refer to the `v1beta1` version.

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by romapi** [comment]
I had similar experience when adjusting user_data for AL2023. Just took v1beta1 spec docs and it worked.
