### ISSUE TITLE
CHANGELOG.md not being updated

### ISSUE THREAD

**Issue by juweeks** [awslabs/amazon-eks-ami#1768]
CHANGELOG.md not being updated with current releases since 2/27

```
```

**Comment by juweeks** [comment]
didn't see the change from master to main

**Comment by cartermckinnon** [comment]
The changelog file is just a copy of our release notes, which you can always view here: https://github.com/awslabs/amazon-eks-ami/releases

**Comment by juweeks** [comment]
saw that. it's just we had something pointing to the master branch which now is main.
