### ISSUE TITLE
EKS Logs Collector script Update

### ISSUE THREAD

**Issue by AbeOwlu** [awslabs/amazon-eks-ami#1790]
**What would you like to be added**:
The log scraping script should start pulling netfilter ipvs virtual endpoint to associated destination endpoint mapping, along with the [iptables-legacy information](https://github.com/awslabs/amazon-eks-ami/blob/fbfa1bc129f57f514b0fb04ab77dbb5d726364a3/log-collector-script/linux/eks-log-collector.sh#L331) relied on for nat re-routing to destination kube-svc IPs

Unless there is a reason why this is not needed in the script?

**Why is this needed**:

For troubleshooting clusters with kube-proxy ipvs mode enabled.

**Comment by cartermckinnon** [comment]
Feel free to open a PR.

**Comment by AbeOwlu** [comment]
will do...

**Comment by AbeOwlu** [comment]
PR for review: https://github.com/awslabs/amazon-eks-ami/pull/1795

**Comment by AbeOwlu** [comment]
Hi @cartermckinnon , following up on this PR for reviews...
Let me know if any changes to the [command pattern](https://github.com/AbeOwlu/amazon-eks-ami/blob/e54f50f3185766a3f2f92febfc3e14ac1c5a943b/log-collector-script/linux/eks-log-collector.sh#L348) is required

**Comment by sidewinder12s** [comment]
I think this can be closed as completed?
