### ISSUE TITLE
libnvidia-ml library not found in GPU AL2023 AMIs

### ISSUE THREAD

**Issue by nirroz93** [awslabs/amazon-eks-ami#1817]
**What happened**:
Ran latest GPU AMI of al2023 (ami-0b6c374ba4ea637cc amazon-eks-node-al2023-x86_64-standard-1.29-v20240514) with nvidia-device-plugin and got the following logs:
```I0519 11:02:49.799272       1 main.go:279] Retrieving plugins.
W0519 11:02:49.799372       1 factory.go:31] No valid resources detected, creating a null CDI handler
I0519 11:02:49.799461       1 factory.go:104] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0519 11:02:49.799500       1 factory.go:104] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0519 11:02:49.799506       1 factory.go:112] Incompatible platform detected
E0519 11:02:49.799510       1 factory.go:113] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0519 11:02:49.799515       1 factory.go:114] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0519 11:02:49.799520       1 factory.go:115] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0519 11:02:49.799525       1 factory.go:116] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
E0519 11:02:49.802763       1 main.go:132] error starting plugins: error creating plugin manager: unable to create plugin manager: platform detection failed
```
And crashLoopBack (and node not registering GPU as resources).

Tried to upgrade nvidia-device-plugin from 0.14 to latest (0.15), didn't help. At the end, I used different AMI, of AL2 (ami-0d1cec73170ec5a05) with all the same config of nvidia plugin and it worked.
**What you expected to happen**:
Nvidia-device-plugin should work
**How to reproduce it (as minimally and precisely as possible)**:
See related issue See https://github.com/awslabs/amazon-eks-ami/issues/1744, which is similar issue on AL2. I guess something similar happens here.

**Anything else we need to know?**:
See https://github.com/awslabs/amazon-eks-ami/issues/1744, which is similar issue on AL2. Tagging @cartermckinnon as you handled the AL2 issue (hopefully it's the same issue here :-) )

If you want anymore data, I can provide
**Environment**:
- AWS Region: us-east-1
- Instance Type(s): g5.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.6
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.29
- AMI Version: ami-0b6c374ba4ea637cc (amazon-eks-node-al2023-x86_64-standard-1.29-v20240514)
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by bryantbiggs** [comment]
it looks like you are trying to use the AL2023 AMI which does not have the NVIDIA drivers/components installed - you should use the AL2 GPU AMI 

The AMI ID can be retried from the SSM parameter `/aws/service/eks/optimized-ami/1.26/amazon-linux-2-gpu/recommended/image_id` or by setting the AMI type to `AL2_x86_64_GPU` when using EKS node group

**Comment by nirroz93** [comment]
oh, weird, karpenter started a regular ami. Sorry, my bad
