### ISSUE TITLE
public bucket throwing error while pullnig the kubelet binaries

### ISSUE THREAD

**Issue by anoopsingh** [awslabs/amazon-eks-ami#1830]
**What happened**:
Trying to pull the binary from the public bucket amazon-eks, it's throwing error access denied
**What you expected to happen**:
It should pull/fetch the binary without erroring out for access
**How to reproduce it (as minimally and precisely as possible)**:
just run the aws s3 ls command on the public amazon-eks bucket
**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
Which AWS partition are you using?

**Comment by cartermckinnon** [comment]
I'm going to assume this is in `aws-us-gov` -- the `amazon-eks` bucket isn't public in that partition (yet). This is expected behavior.
