### ISSUE TITLE
Bootstrap.sh not running

### ISSUE THREAD

**Issue by sebastianserrano** [awslabs/amazon-eks-ami#1833]
**What happened**:
Bootstrap script is not running on `amazon-eks-node-1.30-v20240522` or `amazon-eks-node-1.30-v20240531`

**What you expected to happen**:
Expected `kubelet` to be up and running upon image booting up

**How to reproduce it (as minimally and precisely as possible)**:
Simply run `amazon-eks-node-1.30-v20240522` or `amazon-eks-node-1.30-v20240531` and check `systemctl status kubelet`. If I manually run:

1. `/etc/eks/bootstrap.sh`
2. `systemctl start kubelet` 

Then `kubelet` boots up successfully

**Anything else we need to know?**:

**Environment**:
- AWS Region: 
  - `eu-north-1`
- Instance Type(s): 
  - `r5.2xlarge`
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 
  - `eks.2`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 
  - `1.30`
- AMI Version:
  - `1.30.0-20240531`, `1.30.0-20240522`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-013937053a388b1f5"
BUILD_TIME="Wed May 22 20:34:48 UTC 2024"
BUILD_KERNEL="5.10.216-204.855.amzn2.x86_64"
ARCH="x86_64"
```

<img width="1728" alt="Screen Shot 2024-06-05 at 10 09 39 AM" src="https://github.com/awslabs/amazon-eks-ami/assets/19766755/a3b4551e-4aef-4290-83c1-888c3f2572c8">

<img width="871" alt="Screen Shot 2024-06-05 at 10 09 54 AM" src="https://github.com/awslabs/amazon-eks-ami/assets/19766755/27d0f9dd-c8c9-4236-9f57-aa871e622904">

<img width="927" alt="Screen Shot 2024-06-05 at 10 10 02 AM" src="https://github.com/awslabs/amazon-eks-ami/assets/19766755/40029c32-b838-4330-9b1c-9cdf6608478c">

**Comment by cartermckinnon** [comment]
I'm not able to reproduce this, can you open an AWS Support case? We'll need you to provide a more complete snapshot of the logs from your instances.
