### ISSUE TITLE
EKS AMI shouldn't restart Kubelet when containerd is restarted

### ISSUE THREAD

**Issue by abeer91** [awslabs/amazon-eks-ami#1846]
**What happened**:
If containerd is restarted, Kubelet also gets restarted. Other popular open source projects like Kops and kubeadm have not configured systemd configuration as such.

1. KOPS doesn't configure this behavior, Kops just ensures that containerd has started up before Kubelet - https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kubelet.go#L389
2. Kubeadm doesn't configure either- https://github.com/kubernetes/release/blob/cd53840/cmd/krel/templates/latest/kubelet/kubelet.service
 

**What you expected to happen**:

I would expect Kubelet to fail to communicate, but once containerd restarts it should automatically recover.

This is confirmed by my discussion on Slack with folks from sig-node: https://kubernetes.slack.com/archives/C0BP8PW9G/p1718063064902389

There are risks to restarting the Kubelet - 
1. Features like https://kubernetes.io/blog/2023/04/21/node-log-query-alpha/ , which don't depend on CRI should still work even if containerd is crashing.
2. In-case of a catastrophic failure mode where multiple Kubelets get stuck in a restart loop due to containerd crashing (ooms, panics, etc), it can cause availability issues for the control plane, as many Kubelets booting up together has historically resulted in higher load on the control plane. 

**How to reproduce it (as minimally and precisely as possible)**:

Launch an instance with the AMI
```
# Check Kubelet is running and check process start time
sudo systemctl status kubelet 
sudo systemctl status containerd
#Copy PID
sudo kill -9 <PID_OF_CONTAINERD>
# Check Kubelet restarted by checking the process start time
sudo systemctl status kubelet
```

**Comment by cartermckinnon** [comment]
Hey, long time no see! 👋 

I agree, we should remove the `Requires` option here: https://github.com/awslabs/amazon-eks-ami/blob/f509713f3e2bec0bd9d6a8e7a2dc3598f8daf880/templates/al2/runtime/kubelet-containerd.service#L5

The systemd docs recommend `Wants=` over `Require=`:
- https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Wants=
- https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Requires=
