### ISSUE TITLE
Unable to create an EKS cluster with al2023 when FIPS is enabled 

### ISSUE THREAD

**Issue by LochanRn** [awslabs/amazon-eks-ami#1863]
**What happened**:
Unable to create an EKS cluster with al2023 with FIPS enabled AMI. 

**What you expected to happen**:
To be able to create an EKS cluster with al2023 with FIPS enabled AMI. 

**How to reproduce it (as minimally and precisely as possible)**:

- Build an AL2023 FIPS enabled to AMI. 
- Use the same AMI to create an EKS cluster worker node group.   

**Anything else we need to know?**:

The nodes get created but unable to join the cluster. 

After I logged into the vm and checked the cloud-init logs i see the bootstrap.sh file is missing.
I built the AMI using the official upstream repo.
Used the al2023 template https://github.com/awslabs/amazon-eks-ami/tree/main/templates/al2023
The template does not have the bootstrap.sh script.

![Screenshot 2024-06-19 at 5 31 26 PM](https://github.com/awslabs/amazon-eks-ami/assets/25365962/f677dd99-cb5d-4365-bacb-fe296b2d6a44)

**Environment**:
- AWS Region: east-us-2
- Instance Type(s): m5.2xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.7
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.29
- AMI Version: AL2023
- Kernel (e.g. `uname -a`):  
```
Linux ip-10-0-10-16.us-east-2.compute.internal 6.1.92-99.174.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jun  4 15:43:46 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0bfa2fb693fc2aeb2"
BUILD_TIME="Fri Jun 14 08:44:55 UTC 2024"
BUILD_KERNEL="6.1.92-99.174.amzn2023.x86_64"
ARCH="x86_64"
```

**Comment by KrisJohnstone** [comment]
I suggest you read the following [blog post](https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-amis-now-available/) as al2023 doesn't use bootstrap.sh, the code in this repo also has pretty good documentation in how nodeadm works:
https://github.com/awslabs/amazon-eks-ami/blob/main/nodeadm/README.md

**Comment by LochanRn** [comment]
@KrisJohnstone Is is anyway or anywhere possible to create an EKS cluster with al2023 ami with FIPS enabled ?

**Comment by farvour** [comment]
Really? Closed as not planned, despite AL2023 going through a FIPS certification?
