### ISSUE TITLE
Document source AMI and version in GH release

### ISSUE THREAD

**Issue by stevehipwell** [awslabs/amazon-eks-ami#1879]
**What would you like to be added**:
I'd like the source AMI to be captured as part of the build process and for AL2023 the version. It'd also be really useful to have the the actual build date.

**Why is this needed**:
When reviewing the composition of the EKS nodes knowing the starting point for a specific node makes it far easier to figure this out.

**Comment by Issacwww** [comment]
Latest release note contains the source AMI name: 
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240729
closing this
