### ISSUE TITLE
/etc/eks/bootstrap.sh not found in the latest AWS AMI

### ISSUE THREAD

**Issue by Swisk** [awslabs/amazon-eks-ami#1885]
**What happened**:

The bootstrap script cannot be found at /etc/eks. This causes the EKS nodes to be unable to work properly, especially when custom kubelet arguments need to be passed.

![image](https://github.com/user-attachments/assets/1a5c6a96-6ee4-4c0b-aa06-0798467095e1)

(Currently using amazon-eks-node-al2023-x86_64-standard-1.30-v20240703)

**What you expected to happen**:

bootstrap.sh should be present at /etc/eks

**How to reproduce it (as minimally and precisely as possible)**:

No config required, using the current latest public AMI image: ami-0801925bef3126494

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-southeast-1
- Instance Type(s): t3-medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.5
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.30
- AMI Version: ```1.30.0-20240703```
- Kernel (e.g. `uname -a`): 
```
Linux ip-100-64-119-30.ap-southeast-1.compute.internal 6.1.94-99.176.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jun 18 14:57:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-07abf5a3675e9b4d6"
BUILD_TIME="Wed Jul  3 05:03:36 UTC 2024"
BUILD_KERNEL="6.1.94-99.176.amzn2023.x86_64"
ARCH="x86_64"
```

**Comment by ndbaker1** [comment]
The ami you're referencing is for AL2023, which uses the [nodeadm](https://github.com/awslabs/amazon-eks-ami/tree/main/nodeadm#nodeadm) bootstrap  instead of bootstrap.sh
