### ISSUE TITLE
Support CrowdStrike for amazon-eks-node-al2023-x86_64-standard-1.30

### ISSUE THREAD

**Issue by rajeevpnair** [awslabs/amazon-eks-ami#1891]
CrowdStrike for amazon-eks-node-al2023-x86_64-standard-1.30 is rfm-state=true
--rfm-state=true indicating whether the sensor is in Reduced Functionality Mode
 rfm-reason=The kernel backend does not support the running kernel, code=0xC0000225.
Any idea when EKS 1.30 amd64 supports CrowdStrike falconSensor ?

**Environment**: EKS
- AWS Region: Any
- Instance Type(s): t2micro
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.30
- AMI Version: amazon-eks-node-al2023-x86_64-standard-1.30-v20240703
- Kernel (e.g. `uname -a`):  6.1.94-99.176.amzn2023.x86_64 
- Release information (run `cat /etc/eks/release` on a node):

```
sh-5.2$ cat /etc/eks/release
BASE_AMI_ID="ami-07abf5a3675e9b4d6"
BUILD_TIME="Wed Jul  3 05:03:36 UTC 2024"
BUILD_KERNEL="6.1.94-99.176.amzn2023.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
That's a question for CrowdStrike (though they're probably a bit busy today!)

**Comment by dims** [comment]
🙃 @cartermckinnon

**Comment by billnbell3** [comment]
???
