### ISSUE TITLE
GLIBC_2.27 not found - Amazon-eks-gpu-node-1.29-v20240703

### ISSUE THREAD

**Issue by zohebk8s** [awslabs/amazon-eks-ami#1892]
Hi Team,

nvidia operator validator & nvidia cuda validator pods are crashing with GLIBC_2.27 not found.

It’s Aws eks 1.29.3 & ami name is 1.29-v20240703

Fix available for this? Any specific Ami?

**Comment by zohebk8s** [comment]
@cartermckinnon Appreciate your suggestions/inputs on this issue

**Comment by bryantbiggs** [comment]
you shouldn't need to use the NVIDIA gpu-operator with the EKS AL2 GPU AMI - the AMI comes with the drivers and container toolkit already installed, you just need to deploy the NVIDIA device plugin in your cluster in order for pods to start requesting and utilizing the GPUs available on nodes

**Comment by cartermckinnon** [comment]
The GPU Operator does not support Amazon Linux 2, and as Bryant points out, it's unnecessary.
