### ISSUE TITLE
Add reboot history to eks-log-collector

### ISSUE THREAD

**Issue by gomesdigital** [awslabs/amazon-eks-ami#1919]
**What would you like to be added**:
Reboot history as part of the eks-log-collector script.

**Why is this needed**:
There are cases where a hard reboot has affected service processes, but this is not clearly evident in the collected logs.

We have been debugging containerd and various other components with AWS Support to determine why they're being restarted. At first approach this was thought to be an issue at the container level (CNI), but looking outside the logs we've discovered that a hard reboot has been interrupting everything:
```
reboot   system boot  6.1.102-108.177. Sun Aug 11 01:16   still running
reboot   system boot  6.1.102-108.177. Sun Aug 11 01:15   still running
```
This isn't clear in the current export via dmesg either because it only tracks the current session.

It would be helpful to have these logs included so that reboots can be quickly correlated with any service interruptions.

**Comment by ndbaker1** [comment]
thanks for the PR, this also ships in release [v20240828](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240828) 👍
