### ISSUE TITLE
v20240817 is a pre-release

### ISSUE THREAD

**Issue by sarahhodne** [awslabs/amazon-eks-ami#1931]
I noticed that [v20240817](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240817) is marked as a pre-release in the GitHub releases, but it's unclear to me why that is, is there something specific in this release that means it's not quite ready yet, or was it marked as such by accident?

Since it's a pre-release, [Renovate](https://docs.renovatebot.com/) didn't generate a PR for us, so we initially missed that this release had been created.

**Comment by cartermckinnon** [comment]
@sarahhodne this is part of our normal release process, the release will be marked as latest once it’s available in all regions.
