### ISSUE TITLE
[Documentation correction] AmazonSSMManagedInstanceCore mentioned as a role  is an AWS managed policy, and it does not have S3:PutObject permission to all S3 resources.

### ISSUE THREAD

**Issue by ryoyanoamazon** [awslabs/amazon-eks-ami#1940]
I discovered 2 documentation errors on the README.md files below.

## Path

/log-collector-script/linux/README.md
/log-collector-script/windows/README.md

## Contents

```
Collect EKS logs using SSM agent
...
Prerequisites
...
Worker Node(s) should have required permissions to communicate with SSM service. IAM managed role AmazonSSMManagedInstanceCore will have all the required permission for SSM agent to run on EC2 instances. The IAM managed role AmazonSSMManagedInstanceCore has S3:PutObject permission to all S3 resources.
```

## Issues

1. "IAM managed role AmazonSSMManagedInstanceCore" is not a role, it is an AWS managed role.
2. The IAM managed role AmazonSSMManagedInstanceCore does not have S3:PutObject permission to all S3 resources.

## Reference

[] AmazonSSMManagedInstanceCore - https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonSSMManagedInstanceCore.html

**What would you like to be added**:

1. Modify `role` into `policy` about AmazonSSMManagedInstanceCore.

[Before]

```
 IAM managed role AmazonSSMManagedInstanceCore
```

[After]

```
 IAM managed policy AmazonSSMManagedInstanceCore
```

2. Delete the documentation of ` The IAM managed role AmazonSSMManagedInstanceCore has S3:PutObject permission to all S3 resources` and add an instruction to have the S3:PutObject permission to all S3 resources.

[Before]

```
The IAM managed role AmazonSSMManagedInstanceCore has S3:PutObject permission to all S3 resources.
```

[After]

```
Worker Node(s) should have S3:PutObject permission to all S3 resources.
```

**Why is this needed**:

- To prevent users from encountering an unintentional permission error by following this instruction due to the wrong information.
- To inform correct information to users. Wrong documentation may leads them to misunderstanding.

**Comment by ndbaker1** [comment]
ah good catch, its seems like when we were urged to move `AmazonEC2RoleforSSM` -> `AmazonSSMManagedInstanceCore` to address https://github.com/awslabs/amazon-eks-ami/issues/1137 we didn't confirm the parity of the permissions.

If you make can a PR with your findings that would be awesome 👍

**Comment by ryoyanoamazon** [comment]
@ndbaker1 
Thank you for your comment.

Oh, I see. I created the PR for this issue.

[Documentation correction] AmazonSSMManagedInstanceCore mentioned as a role is an AWS managed policy, and it does not have S3:PutObject permission to all S3 resources. #1940 #1941
