### ISSUE TITLE
AL2023 AMI: "invalid capacity 0 on image filesystem" kubelet warning

### ISSUE THREAD

**Issue by markusmiliats** [awslabs/amazon-eks-ami#1947]
I'm not sure if this is a bug so I'm filing this as a general question.
During node startup I can see the event "invalid capacity 0 on image filesystem" as a warning from kubelet.
Using `journalctl -u kubelet` I can see additional information for this warning:
`kubelet.go:1440] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"` 
Afterwards, the node starts normally, pods are assigned to the node and I cannot observe any abnormal behaviour.
I'm wondering if anyone else encountered this and if I can safely ignore this warning? (because Stats initialization may not have completed yet as the message already suggests 😄) 

**Environment**:
- AWS Region: eu-central-1
- Instance Type(s): r5a.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.17
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.28
- AMI Version: AL2023 1.28.11-20240828 and 1.28.11-20240817
- Kernel (e.g. `uname -a`): `Linux ip-10-156-75-203.eu-central-1.compute.internal 6.1.102-111.182.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Aug 13 22:23:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):
```
BASE_AMI_ID="ami-0ba8fabdb90841bee"
BUILD_TIME="Wed Aug 28 01:53:55 UTC 2024"
BUILD_KERNEL="6.1.102-111.182.amzn2023.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
You can ignore it.
