### ISSUE TITLE
Custom AMI based on v20240828 using containerd 1.7.20

### ISSUE THREAD

**Issue by jan-ludvik** [awslabs/amazon-eks-ami#1950]
**What happened**:
I built new AL2023 AMI using `v20240828` but it seems to be still running containerd://1.7.20
**What you expected to happen**:
containerd to be downgraded to 1.7.11
**How to reproduce it (as minimally and precisely as possible)**:
Run node from v20240828
**Environment**:
- source AMI: amazon-eks-node-al2023-x86_64-standard-1.29-v20240828
- AWS Region: us-east-2
- Instance Type(s): `c6a.large`
- Cluster Kubernetes version: 1.29
- Node Kubernetes version: 1.29
- AMI Version: v20240828

```
# ctr version
Client:
  Version:  1.7.20
  Revision: 8fc6bcff51318944179630522a095cc9dbf9f353
  Go version: go1.22.5

WARN[0000] DEPRECATION: CRI API v1alpha2 is deprecated since containerd v1.7 and removed in containerd v2.0. Use CRI API v1 instead. 
Server:
  Version:  1.7.20
  Revision: 8fc6bcff51318944179630522a095cc9dbf9f353
  UUID: fa7f7528-e221-4dc0-917a-9c02df79edd4
```

**Comment by cartermckinnon** [comment]
> built new AL2023 AMI using v20240828

What do you mean by that? If you’re doing any sort of package update, I.e. yum update, you would end up with the latest containerd.

**Comment by jan-ludvik** [comment]
We install few things on top but until now we always stayed on the version of containerd the EKS AMI used. 
We do run `dnf update -y` during that but I tried that now on AMI from `v20240729` and that didn't update containerd.

**Comment by cartermckinnon** [comment]
AL2023 uses versioned repositories, this gives similar behavior to the yum versionlock plugin that we use on AL2 to keep certain packages on specific versions. More here: https://docs.aws.amazon.com/linux/al2023/ug/deterministic-upgrades.html

You wouldn’t have seen containerd update before because we always installed the latest available in the revision of the package repository used by our AMI. That isn’t the case right now.

**Comment by jan-ludvik** [comment]
Thanks, I figured it out. Indeed we had `dnf update` which was fine until [2023.5.20240805](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240805.html) where containerd was updated. I removed `dnf update` and now we are getting containerd from AWS EKS AMI.
