### ISSUE TITLE
Convert packer JSON templates to HCL templates

### ISSUE THREAD

**Issue by SoodPrerit** [awslabs/amazon-eks-ami#1953]
It is suggested to use HCL templates instead of JSON for packer builds now in packer documentations. 
Currently this project only contains JSON templates which are used for packer builds. Is it planned to use packer HCL templates instead of JSON ?

**Comment by cartermckinnon** [comment]
We don't have any plans in the short term to rewrite our templates in HCL. It's just not a priority until/unless there's a feature we need that's only available in HCL templates.
