### ISSUE TITLE
Stable version for nodeconfig API

### ISSUE THREAD

**Issue by SoodPrerit** [awslabs/amazon-eks-ami#1967]
In the documentation for nodeconfig API [here](https://awslabs.github.io/amazon-eks-ami/nodeadm/) it has been mentioned that the stable version for the API will be like `v5`. However only available version is v1alpha1. Since alpha/beta are not the stable versions. Is there a plan to release a stable version. I couldn't find this information in the documentation.

Question :

- Is stable version available for nodeConfig API (node.eks.aws/v1alpha1)? If yes, where can I find this information
- If stable version is not available What are the recommendations to use in production level environments ?
- If only alpha versions are available and not recommended to use in production environment. Is there any alternate way for node bootstrapping for al2023 OS

**Comment by cartermckinnon** [comment]
The alpha/beta/stable designation of the API types is solely about **changes in those API types**, it's not related to the "stability" of the software handling those types (`nodeadm`). You can absolutely use `nodeadm` in production, with the current `v1alpha1.NodeConfig`.

The API types will graduate to beta, and then stable, as we continue to incorporate user feedback.
