### ISSUE TITLE
Kubelet cluster-dns parameter is set incorrectly

### ISSUE THREAD

**Issue by Jaykah** [awslabs/amazon-eks-ami#197]
**What happened**: Same as in https://github.com/awslabs/amazon-eks-ami/issues/78 , Cluster-IP of my Coredns is 172.20.0.10, while "ClusterFirst" option on my deployments sets their resolv.conf to nameserver 10.100.0.10

**What you expected to happen**: I would expect to see the correct nameserver in the resolf.conf of my pods

**How to reproduce it (as minimally and precisely as possible)**: Create a VPC in 10.0.0.0/8 network, set up a VPN going to a network with subnets in 172.0.0.0/8 -> deploy a pod 

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): t2.small
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.11
- AMI Version: ubuntu-eks/k8s_1.10/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190122 (ami-0b5f401f6365fb6dc)
- Kernel (e.g. `uname -a`): 4.4.0-1072-aws #82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Release information (run `cat /tmp/release` on a node):

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

**Comment by dawidmalina** [comment]
@Jaykah you are using image provided by Canonical not Amazon. There is already ticket for this particular issue: https://bugs.launchpad.net/cloud-images/+bug/1789248

**Comment by rcj4747** [comment]
@Jaykah For the Ubuntu images a fix is present in the latest images (listing @ https://cloud-images.ubuntu.com/docs/aws/eks/) and for all of the Ubuntu images with a date of 20190212 or later.  Any feedback can be posted to the bug @dawidmalina mentioned, https://bugs.launchpad.net/cloud-images/+bug/1789248

**Comment by micahhausler** [comment]
@Jaykah Can we close this since you're using the Ubuntu AMI?

**Comment by rollcallim** [comment]
Was confirming that the latest image solves the issue, and it indeed does! Thanks everyone!

**Comment by Jaykah** [comment]
Was just confirming that the newest AMI resolves the issue, and it indeed does! Thanks everyone!
