### ISSUE TITLE
bug(GPU): nvidia-container-toolkit CVE

### ISSUE THREAD

**Issue by sidewinder12s** [awslabs/amazon-eks-ami#1979]
What version of the AMI has this CVE fix included for the nvidia-container-toolkit?

https://nvidia.custhelp.com/app/answers/detail/a_id/5582

**Comment by dims** [comment]
Our last release is dated 9/24, the disclosure happened on 9/25. So not yet.

There's support in this repo for building the AL2023 GPU AMI(s) https://github.com/awslabs/amazon-eks-ami/pull/1924 if someone is in a rush.

**Comment by sidewinder12s** [comment]
Thanks, I'll expect next release to have it then (not on 2023 yet)

**Comment by dims** [comment]
@sidewinder12s [v20240928](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240928)

**Comment by Issacwww** [comment]
closing this wi
