### ISSUE TITLE
v1.29.8 binaries missing from s3://amazon-eks

### ISSUE THREAD

**Issue by bitisuvanje** [awslabs/amazon-eks-ami#1986]
Hi team,

The binaries for the latest: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240928 release are not uploaded to s3://amazon-eks

![CleanShot 2024-10-02 at 11 01 35@2x](https://github.com/user-attachments/assets/188c27f4-9456-46b2-88e0-5a0f85b3ca2a)

**Comment by cartermckinnon** [comment]
I'll update here when these are available 👍

**Comment by wwvela** [comment]
We finished the latest binary release in public s3 repo. You should be able to find it now.
