### ISSUE TITLE
Missing dns.yaml file in amazon-eks/cloudformation/2019-02-11

### ISSUE THREAD

**Issue by MMartyn** [awslabs/amazon-eks-ami#199]
**What happened**:
The dns.yaml file referenced here (https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) is missing in the latest set of yaml files in the s3 bucket.

**What you expected to happen**:
Expect the file to exist.

**How to reproduce it (as minimally and precisely as possible)**:
Check the s3 bucket.

**Anything else we need to know?**:
I assumed it was the same as the one found in 2018-12-10 so I am going to use that one for the time being.

**Comment by micahhausler** [comment]
Thanks for reporting this, this was a miss in our release process

**Comment by micahhausler** [comment]
It's been added. Thanks!

```
aws s3 ls s3://amazon-eks/cloudformation/2019-02-11/dns.yaml
```
