### ISSUE TITLE
bug(containerd): 1.7.11 has memory leak for kubectl exec fixed in 1.7.21 

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [awslabs/amazon-eks-ami#1999]
**What happened**:

We observed a memory leak when using kubectl exec >= 1.30 for containerd older then 1.7.21. The upstream bug for this is https://github.com/containerd/containerd/issues/10568. The issue seems to be fixed in https://github.com/containerd/containerd/releases/tag/v1.7.21 and https://github.com/containerd/containerd/releases/tag/v1.6.36. Current AMI is still at 1.7.11.

(See https://github.com/containerd/containerd/issues/10568#issuecomment-2339088456)

**What you expected to happen**:

No memory leak

**How to reproduce it (as minimally and precisely as possible)**:

Repeated kubectl exec

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): c5.large
- Cluster Kubernetes version: 1.29
- Node Kubernetes version: 1.29
- AMI Version:

**Comment by cartermckinnon** [comment]
You can mitigate this issue by using an older `kubectl`. If your control plane is on 1.29, you should be using the latest `kubectl` on that release branch.

We'll be updating `containerd` to `1.7.22` shortly: #1998

**Comment by Issacwww** [comment]
#1998 has been released in [v20241011](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20241011) for AL2 based AMI
#2008 fix for AL23 will be in next release

**Comment by cartermckinnon** [comment]
`containerd` has been updated in all AMI variants as of the latest release.
