### ISSUE TITLE
Port containerd config imports to AL2023

### ISSUE THREAD

**Issue by yndai** [awslabs/amazon-eks-ami#2030]
**What would you like to be added**:

Port the change to import custom containerd overrides from https://github.com/awslabs/amazon-eks-ami/pull/1630 which was done for AL2 for AL2023 AMIs

**Why is this needed**:

Some popular tooling such as Spegel uses the import directory to override settings: https://github.com/spegel-org/spegel/blob/main/docs/COMPATIBILITY.md#eks which is safer than doing something like `sed`

**Comment by cartermckinnon** [comment]
The `NodeConfig` accepts arbitrary additional config for `containerd`, we have an example in the docs for doing this exact thing (changing `discard_unpacked_layers`): https://awslabs.github.io/amazon-eks-ami/nodeadm/doc/examples/#configuring-containerd
