### ISSUE TITLE
Allow to run against custom AMIs + in different regions

### ISSUE THREAD

**Issue by ac-hibbert** [awslabs/amazon-eks-ami#204]
**What would you like to be added**:

Allow to run against custom AMIs + in different regions

**Why is this needed**:

Would like the option to run this against a custom AMI + different regions to us-west-2

**Comment by dawidmalina** [comment]
@hibbert this is duplicate of https://github.com/awslabs/amazon-eks-ami/issues/172

I already opened pull requests for this https://github.com/awslabs/amazon-eks-ami/pull/198 and https://github.com/awslabs/amazon-eks-ami/pull/203

@micahhausler can you take a look on this?
