### ISSUE TITLE
amazon-ebs: ctr: failed to resolve reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5"

### ISSUE THREAD

**Issue by eamon-straughn** [awslabs/amazon-eks-ami#2059]
**What happened**:
Failed to pause 

**What you expected to happen**:
to create ami

**How to reproduce it (as minimally and precisely as possible)**:
make k8s=1.31 arch=arm64 aws_region=eu-north-1 os_distro=al2023

**Environment**:
- AWS Region: eu-north-1
- Instance Type(s): m6g.large
- Cluster Kubernetes version: 1.31
- Node Kubernetes version: 1.31
- AMI Version:

Looks like it is fixed by changing 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5 to public.ecr.aws/eks-distro/kubernetes/pause:v1.31.2-eks-1-31-latest in variables-default.json in templates/al2023/variables-default.json

**Comment by ndbaker1** [comment]
This is expected behavior now on AL2023 builds. Please see https://github.com/awslabs/amazon-eks-ami/blob/main/doc/usage/al2023.md#pause-container-image for details and suggested image URIs.

The image you ought to be using needs the right region: `602401143452.dkr.ecr.eu-north-1.amazonaws.com`

**Comment by Ankitsachdeva** [comment]
@ndbaker1 , but this is not correct, to hardcode the region inside the `pause_container_image` var.

It should be updated with the user-provided region during the ami build.
