### ISSUE TITLE
Worker node fails join cluster with --rotate-certificates=true

### ISSUE THREAD

**Issue by Constantin07** [awslabs/amazon-eks-ami#207]
**What happened**:

I've passed `--kubelet-extra-args --feature-gates=RotateKubeletServerCertificate=true --rotate-certificates=true` to the `bootstrap.sh` script but the nodes fail to join the cluster.

**What you expected to happen**:
Worker nodes to join cluster as per https://kubernetes.io/docs/tasks/tls/certificate-rotation

**How to reproduce it (as minimally and precisely as possible)**:
Spin up worker nodes with the above args.

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): t3.large
- EKS Platform version: eks.1
- Kubernetes version: 1.11
- AMI Version: ami-098fb7e9b507904e7
- Kernel (e.g. `uname -a`): ```Linux ip-10-0-2-116.eu-west-1.compute.internal 4.14.97-90.72.amzn2.x86_64 #1 SMP Tue Feb 5 20:46:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```
- Release information (run `cat /etc/os-release` on a node):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by micahhausler** [comment]
We don't support certificate-based auth for EKS nodes, but we do have server certificates that auto rotate, see [kubelet-config.json](https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet-config.json#L29).

**Comment by Constantin07** [comment]
Thanks @micahhausler Am I correct that the `--rotate-certificates=true` is used for certificate-based auth ?

**Comment by micahhausler** [comment]
Yep. [`{"featureGates": {"RotateKubeletServerCertificate": true}}`](https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet-config.json#L29) in the kubelet config file turns on auto-rotation the kubelet's HTTPS serving certificate.

Can we close this out?

**Comment by Constantin07** [comment]
@micahhausler sure. Many thanks for explanation.
