### ISSUE TITLE
When and where are NVIDIA drivers installed?

### ISSUE THREAD

**Issue by changhyuni** [awslabs/amazon-eks-ami#2071]
**Environment**:
- AWS Region: ap-northeast-2
- Instance Type(s): p4d, g4
- EKS Platform version 1.27
- Kubernetes version 1.27
- AMI Version: latest
- Kernel (e.g. `uname -a`): Linux ip-10-xxxxxx.ap-northeast-2.compute.internal 5.10.220-209.869.amzn2.x86_64 
SMP Wed Jul 17 15:10:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

I would like to install a specific version of the NVIDIA driver. Is this possible?
 Also, when and where are NVIDIA drivers installed?

**Comment by cartermckinnon** [comment]
Our AL2 GPU AMI is not open source at this time. Our AL2023 AMI template (in this repo) can be used to build an AMI with support for NVIDIA devices, more on that here: https://awslabs.github.io/amazon-eks-ami/usage/al2023/#accelerated-images

Otherwise you’d need to refer to NVIDIA’s documentation.
