### ISSUE TITLE
bug(AMI): Worker AMI 1.30.6.-XX Breaks gitlab runner npm install

### ISSUE THREAD

**Issue by kris-Nabis** [awslabs/amazon-eks-ami#2080]
**What happened**:
We are hosting Gitlab-Runner Helm Chart on EKS to Run Gitlab CI/CD jobs. Historically this has always worked as expected. 

After upgrading my Worker Node AMI version from `1.30.4-20241016` -> `1.30.6-20241115` 

Gitlab runners were no longer able to run `npm install` the command would just hang, and never advance. Was not an issue for `yarn` installs `yarn install` . 

Attempted to poke at the CoreDNS on the cluster as well as configure a DNS namespace on the gitlab job to try and resolve hanging `npm install` without any success. 

After downgrading from  `1.30.6-20241115`  ->  `1.30.4-20241016`  Gitlab-runner issues went away. 

**What you expected to happen**:
On Worker node AMI version `1.30.6-20241115` would expecte gitlab-runners to still be functional when running `npm install` 

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy Gitlab Runner Helm Chart
- Register Runner to gitlab.com
- Send Runner gitlab job
  -- Job runs on Alpine Linux
  -- running `npm install` / `npm ci` just hangs. 

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): m4.2xlarge/m5.2xlarge/c5.2xlarge/r5.2xlarge
- Cluster Kubernetes version:  1.30
- Node Kubernetes version: 1.30
- AMI Version: 1.30.6-20241115

**Comment by bryantbiggs** [comment]
See https://github.com/awslabs/amazon-eks-ami/issues/2070#issuecomment-2491668890

**Comment by kris-Nabis** [comment]
Going to close as dup - Looks like issue is being handled here: https://github.com/awslabs/amazon-eks-ami/issues/2070#issuecomment-2491668890
