### ISSUE TITLE
EKS GPU OSS Driver support

### ISSUE THREAD

**Issue by mfortin** [awslabs/amazon-eks-ami#2095]
**What would you like to be added**: Nvidia GPU drivers are now offered in 2 different flavours: OSS and Proprietary. Since the hardware is not supported by both versions, a GPU_OSS AMI with the Nvidia GPU OSS driver installed would be required.

**Why is this needed**: Newer instance type can't be use with the EKS AMI as the Proprietary driver is installed and the OSS driver is now required. https://docs.aws.amazon.com/dlami/latest/devguide/important-changes.html#important-changes-faq-dlc.
Instances of family G4dn, G5, P4, P5 requires the OSS driver.

**Comment by bryantbiggs** [comment]
on our accelerated AMI variants, we dual ship both the NVIDIA open GPU kernel as well as the proprietary - during instance provisioning, we determine which one to use given the instance type (and therefore, the GPU card it provides)

Is there an issue you are seeing with our current accelerated AMIs - are you using the AL2 GPU AMI or the AL2023 NVIDIA AMI?

**Comment by bryantbiggs** [comment]
and to clarify - DLAMI is unrelated to EKS. its an entirely separate AMI; EKS builds its own AMIs and by dual-shipping both driver variants, this removes the need for customers to know the nitty gritty details around driver and GPU card compatibility. For all of the NVIDIA GPU instances available by EC2 today (save for p2 which is a very old card and no longer supported, and g5g which requires ARM) our EKS accelerated AMIs should "just work" for customers. If not, please let us know

**Comment by tonyszhang** [comment]
How come the command `nvidia-smi` works on VMs launched from either AL2-DLAMI-OSS/Proprietary, but not from AL2-EKS-GPU?

**Comment by bryantbiggs** [comment]
it does work on the EKS AL2 GPU AMI - could you share the steps you've taken so I can try to offer guidance or possiblly reproduce on my end?

**Comment by tonyszhang** [comment]
@mfortin Can correct me, but we're using Ansible `ansible.builtin.command: nvidia-smi` with g3s.xlarge (proprietary) and g5.xlarge (OSS), and get `NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

**Comment by bryantbiggs** [comment]
this sounds like you are trying to create a custom AMI from our accelerated AMI - is that correct? any particular reason you need to create a custom AMI?

**Comment by tonyszhang** [comment]
The use case is using Ansible to automate pre-pulling a huge Docker Image using `community.docker.docker_image_pull`, such that node scaling is a lot faster.

**Comment by bryantbiggs** [comment]
ah ok, thank you for that info. yes, that is a pattern we are familiar with, albeit we haven't seen it performed through Packer. Here is the example we typically provide for that use case https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/machine-learning/ml-container-cache/

Just one thing to note - you don't need to create a custom AMI, you only need to create the EBS snapshot. This offers a number of benefits by continuing to use the AMI type with EKS managed node group and simply specifying the snapshot ID that should be used (i.e. - you can continue to use the release version, you don't have to supply the user data to join the node, etc.)

**Comment by tonyszhang** [comment]
> ah ok, thank you for that info. yes, that is a pattern we are familiar with, albeit we haven't seen it performed through Packer. Here is the example we typically provide for that use case https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/machine-learning/ml-container-cache/
> 
> Just one thing to note - you don't need to create a custom AMI, you only need to create the EBS snapshot. This offers a number of benefits by continuing to use the AMI type with EKS managed node group and simply specifying the snapshot ID that should be used (i.e. - you can continue to use the release version, you don't have to supply the user data to join the node, etc.)

Excellent resource, thank you! We'll backlog that with high priority. 

In the meantime, still curious why the simple sanity check `nvidia-smi` works on AL2-DLAMI-OSS/Proprietary but not on AL2-EKS-GPU?

**Comment by mfortin** [comment]
@bryantbiggs there are other requirements to building our own custom AMI, like the need to have endpoint detection and remediation agent pre-installed as our images are immutable.

**Comment by mfortin** [comment]
typically, we create multiple images. 
Your EKS image gets EDR installed, then a new image is created. This image is then re-used to install some of our observability tools (logging, performance metrics) and a new image is created. Finally, that last image is consumed by our application teams for their deployment.

**Comment by bryantbiggs** [comment]
so to back up - have you created an image based off the EKS AL2 GPU AMI and its failing to work in your clusters? Also, any reason to not use the AL2023 NVIDIA AMI (not that it should make a difference for the issue you reported, but its purpose built for NVIDIA GPUs and does not contain Neuron components like the EKS AL2 GPU AMI)

**Comment by cartermckinnon** [comment]
The GPU variants of EKS AMIs have used the OSS driver (when necessary) for the last year or so 👍 We'd need to see additional logs to figure out why `nvidia-smi` isn't working in your setup, please open a case with AWS Support.
