### ISSUE TITLE
Tagging released AMIs in git

### ISSUE THREAD

**Issue by deiwin** [awslabs/amazon-eks-ami#21]
It would be helpful to know which version of the code here was used to create e.g. the `eks-worker-v22` AMI.

**Comment by micahhausler** [comment]
Hey thanks for the feedback. We'll be adding a CHANGELOG shortly. Specifically about v21 and v22, those are essentially the same as v20, but they contain kernel patches for SegmentSmack and Foreshadow CVEs (respectively). 

https://alas.aws.amazon.com/AL2/ALAS-2018-1050.html
https://alas.aws.amazon.com/AL2/ALAS-2018-1058.html

**Comment by deiwin** [comment]
Thanks!
