### ISSUE TITLE
Missing commits in ami-098fb7e9b507904e7

### ISSUE THREAD

**Issue by andytom** [awslabs/amazon-eks-ami#215]
**What happened**:
We updated our test EKS cluster to the latest AMI `ami-098fb7e9b507904e7` which should match https://github.com/awslabs/amazon-eks-ami/releases/tag/v20190220. We used the new `--enable-docker-bridge` flag to setup the docker bridge network, however the network was not enabled.

After further investigation and looking through the recent issues we found https://github.com/awslabs/amazon-eks-ami/issues/183#issuecomment-468459566 which points out that there is a missing commit https://github.com/awslabs/amazon-eks-ami/commit/613fecec8c30c4dfb73675da1eedb079f9889c9a in the AMI. We checked and confirmed this is the case in the nodes in our test cluster.

**What you expected to happen**:

The docker bridge network was configured and enabled when using the `--enable-docker-bridge`.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a new EC2 instance using `ami-098fb7e9b507904e7`
* SSH into the instance and check the `/etc/eks/bootstrap.sh` script doesn't contain the fix from https://github.com/awslabs/amazon-eks-ami/commit/613fecec8c30c4dfb73675da1eedb079f9889c9a
```
[ec2-user@ip-10-10-0-11 ~]$ grep ENABLE_DOCKER_BRIDGE /etc/eks/bootstrap.sh
ENABLE_DOCKER_BRIDGE="${ENABLE_DOCKER_BRIDGE:-false}"
if [[ "$ENABLE_DOCKER_BRIDGE" = "true" ]]; then
[ec2-user@ip-10-10-0-11 ~]$ grep ENABLE_DOCKER_BIDGE /etc/eks/bootstrap.sh
            ENABLE_DOCKER_BIDGE=$2
```

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): Any
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): N/A
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version: `ami-098fb7e9b507904e7`
- Kernel (e.g. `uname -a`): N/A
- Release information (run `cat /tmp/release` on a node): N/A

```
```

**Comment by mcrute** [comment]
This issue shares a root-cause with #233 so I'm going to de-duplicate it into that issue, please follow progress over there. AMIs are immutable once released so you'll need to use the [most recent AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) to have access to the fixes.
