### ISSUE TITLE
why Amazon Linux 2 is ignoring /etc/syscconfig/docker and using very low ulimit for nofile

### ISSUE THREAD

**Issue by benishak** [awslabs/amazon-eks-ami#219]
**Environment**:
- AWS Region: us-east-1
- Instance Type(s): c5.2xlarge

- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.11.x

This is a general questions
I noticed that the Amazon Linux 2 in general is using pretty low ulimit and ignoring configuration in /etc/sysconfig/docker and /etc/sysconfig/docker-storage, is this by design or a bug?
this is also same on ECS optimized and vanilla Amazon Linux 2

**Comment by micahhausler** [comment]
What AMI version are you using?

**Comment by benishak** [comment]
latest

**Comment by drewhemm** [comment]
@benishak Try using the previous version. A ulimits regression was introduced to the latest AMI. It has since been fixed, but a new AMI has not yet been released.

**Comment by drewhemm** [comment]
This is the commit that fixes the issue:

https://github.com/awslabs/amazon-eks-ami/commit/9f2000223d4f081d24419c5af7dd058c4117c945
