### ISSUE TITLE
Support --node-labels in kubelet.service with EC2 instance TAGs

### ISSUE THREAD

**Issue by mtheus** [awslabs/amazon-eks-ami#22]
I would like to use the parameter "--node-labels" in NodeLaunchConfig's UserData in the kubelet.service file with my EC2 instance TAGs to allow me to reserve some resources in the cluster.

https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/amazon-eks-nodegroup.yaml

**Comment by mtheus** [comment]
I realize now that you have created a new ami, but it is not tagged on git or documented any place here, and on this site documentation https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html is still pointing for the previous cloud formation version.

Can you clarify me with version represent your actual master version? 

eks-worker-v22 ami-048486555686d18a0
eks-worker-v20 ami-dea4d5a1

**Comment by max-rocket-internet** [comment]
> Can you clarify me with version represent your actual master version?

Yes it would be great to have some releases in github with details of AMI IDs in each region.

**Comment by mtheus** [comment]
Thank you for your support. When you will release this new AMI version?

**Comment by micahhausler** [comment]
We'll be releasing this next week

**Comment by micahhausler** [comment]
Fixed with #24
