### ISSUE TITLE
s3_url_base after last update in the repo

### ISSUE THREAD

**Issue by anoora17** [awslabs/amazon-eks-ami#237]
**March 27 I was able to build the AMI however today March 29th after pulling from master I am getting error resolving the s3_url_base**:

** amazon-ebs: Downloading binaries from: s3://amazon-eks
    amazon-ebs: AWS cli missing - using wget to fetch binaries from s3. Note: This won't work for privatebucket.
    amazon-ebs: --2019-03-29 20:52:21--  https://s3-us-west-2.amazonaws.com/amazon-eks//kubelet
    amazon-ebs: Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.185.32
    amazon-ebs: Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.185.32|:443... connected.
    amazon-ebs: HTTP request sent, awaiting response... 404 Not Found
    amazon-ebs: 2019-03-29 20:52:21 ERROR 404: Not Found.
    amazon-ebs:
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 8**:

** removed my local repo and cloned new repo just to make sure i can run packer with your basic configuration however this s3 url in not resolving correctly the region used is us-wes-2**:

The problem is binary_bucket_path is not resolving correctly
https://s3-us-west-2.amazonaws.com/amazon-eks//kubelet 

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): m4.large

**Comment by anoora17** [comment]
To work around it I have to copy the binary path to eks-worker-al2.json

**Comment by shyamjvs** [comment]
Can you paste what wget command is being executed by the script? (including the s3 path)

**Comment by shyamjvs** [comment]
@anoora17 Btw - it is `us-west-2` not `us-wes-2`.

**Comment by anoora17** [comment]
@shyamjvs it is west-2 in the eks-worker-al2.json it was typo when I was typing the environment 
```
amazon-ebs: AWS cli missing - using wget to fetch binaries from s3. Note: This won't work for privatebucket.
    amazon-ebs: --2019-03-29 22:10:51--  https://s3-us-west-2.amazonaws.com/amazon-eks//kubelet
    amazon-ebs: Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.224.0
    amazon-ebs: Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.224.0|:443... connected.
    amazon-ebs: HTTP request sent, awaiting response... 404 Not Found
    amazon-ebs: 2019-03-29 22:10:51 ERROR 404: Not Found.
    amazon-ebs:
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 8

**Comment by anoora17** [comment]
however if I modify the eks-worker-al2.json
```"variables": {
    "kubernetes_version": "1.12",
    "aws_region": "us-west-2",
    "ami_name": "amazon-eks-node-{{timestamp}}",
    "binary_bucket_name": "amazon-eks",
    "binary_bucket_region": "us-west-2",
    "binary_bucket_path": "1.10.13/2019-03-27/bin/linux/amd64",
    "docker_version": "18.06",
    "creator": "{{env `USER`}}",
    "instance_type": "m4.large",
    "source_ami_id": "",
    "source_ami_owners": "137112412989",
    "source_ami_filter_name": "amzn2-ami-minimal-hvm-*",
    "encrypted": "false",
    "kms_key_id": "",
    "cni_version": "v0.6.0",
    "cni_plugin_version": "v0.7.1",
    "aws_access_key_id": "{{env `AWS_ACCESS_KEY_ID`}}",
    "aws_secret_access_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
    "aws_session_token": "{{env `AWS_SESSION_TOKEN`}}"
  },

  "builders": [
    {
      "type": "amazon-ebs",
      "region": "{{user `aws_region`}}",
      "source_ami": "{{user `source_ami_id`}}",
      "source_ami_filter": {
        "filters": {
          "architecture": "x86_64",
          "name": "{{user `source_ami_filter_name`}}",
          "root-device-type": "ebs",
          "state": "available",
          "virtualization-type": "hvm"
        },
        "owners": [ "{{user `source_ami_owners`}}" ],
        "most_recent": true
      },
      "instance_type": "{{user `instance_type`}}",
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/xvda",
          "volume_type": "gp2",
          "volume_size": 4,
          "delete_on_termination": true
        }

this works

**Comment by shyamjvs** [comment]
```
https://s3-us-west-2.amazonaws.com/amazon-eks//kubelet
```

^ It seems like you're providing wrong paramters to the packer script. In the above, you should have `1.10.13/2019-03-27/bin/linux/amd64` in between `amazon-eks/` and `/kubelet`.

Please call your packer command properly. For an e.g look at the Makefile.

**Comment by anoora17** [comment]
I was using packer build eks-worker-al2.json  using make solved it will close the ticket and thanks for your help
