### ISSUE TITLE
Enable feature gates TTLAfterFinished

### ISSUE THREAD

**Issue by rverma-nikiai** [awslabs/amazon-eks-ami#238]
**Environment**:
- AWS Region: ap-south-1
- Instance Type(s): r4.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.12
- AMI Version: ami-09c3eb35bb3be46a4

Wondering how can we enable a particular feature gate? Mostly TTLAfterFinished.

**Comment by whereisaaron** [comment]
Hi @rverma-nikiai most managed Kubernetes Control Planes like EKS/GKE/AKE enable only Beta feature gates and do not enable any Alpha feature gates.

TTLAfterFinished is an Alpha feature for 1.12 and I would guess that AWS will not be enabling it until it graduates to be a Beta feature. AFAIK it is still Alpha in 1.14.

TTLAfterFinished is also a control plane feature, so it is not really relevant to the node AMI. You might be better to request it on the AWS containers team road map project.

https://github.com/aws/containers-roadmap

**Comment by micahhausler** [comment]
@rverma-nikiai  @whereisaaron summed it up pretty well. Can you open an issue on the roadmap, since this doesn't affect the AMI?

**Comment by geerlingguy** [comment]
Opened issue in roadmap: https://github.com/aws/containers-roadmap/issues/255
