### ISSUE TITLE
No Changelog for amazon-eks-node-1.11-v20190329

### ISSUE THREAD

**Issue by gokuatkai** [awslabs/amazon-eks-ami#240]
I cannot find any change-log for `amazon-eks-node-1.11-v20190329 (ami-0e82e73403dd69fa3)` which seems to be latest one, more over it seems that critical things has changed that make our cluster fails, something about denying traffic (?).
Please update.

**Comment by mcrute** [comment]
The `amazon-eks-node-1.11-v20190329 (ami-0e82e73403dd69fa3)` was built from git revision fb0c393 of this repo and contains the same changes that are documented for `amazon-eks-node-1.11-v20190327`. The release of `amazon-eks-node-1.11-v20190327` was built off of an older git revision that was missing some of the changes. I'll update the changelog to correct the version numbers.

**Comment by ankon** [comment]
Could you then also create a tag for v20190329 please?
