### ISSUE TITLE
Bootstrap.sh script: registering nodes 

### ISSUE THREAD

**Issue by awouda** [awslabs/amazon-eks-ami#246]
**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): t3.xlarge
- EKS Platform version: eks.1
- Kubernetes version : 1.10
- AMI Version: ami-0c7a4976cb6fafd3a
- Kernel:  Linux ip-10-212-0-25.prd.rsg 4.14.62-70.117.amzn2.x86_64 #1 SMP Fri Aug 10 20:14:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Release information: (there is no release file for eks in etc, see output)
```[ec2-user@ip-10-212-0-25 etc]$ cat /etc/eks/release
cat: /etc/eks/release: No such file or directory
```
Hi,

We are using EKS for a couple of months now. Yesterday we had to update our production nodes with some company specific tools so we updated the nodes. After CFN scripts were done, the scripts show successful in generating the updates resources. 
When I inspected the pods and nodes, I got a "no resources found" for the nodes, and all pods were pending. 

Investigating further I found out that (obviously) the nodes had not registered yet to the master. I found out about the swapfile discussions etc, but we already have that on place (no swap). I found another issue mentioning the DependsOn = "cluster"  in de autoscaling group, but that did not work either. 
Als I donwloaded the kubeadm tools (with are not installed by default on the EKS worker nodes), to reset  / re-init the tooling, as I found out when I started kubelet myself, they would not connect as there was no /etc/kubernetes/pki/car.crt file. But I could not get it to work. 
(There should be pki files as on the other environments I saw they were provisioned).

Then I redeployed again the new stack (without all the manual extra tools). Still not working. We we're doing some other investigations on our dev environment to reproduce. Then I did a check on the PRD env, and voila all was fine.

I noticed the bootstrap.sh script, that creates the /etc/kubernetes/pki files.

Question, this somehow started as recurring script? It tries to connect in an interval?  
Other question: is it normal that in AWS the registration from a node to the master / control plane can take up 30 minutes or more? That's what is happening eventually we found out, but the logging or any other output does not mention that the node is trying to register itself.

thanks in advance for your answer.

regards,

Alex Wouda

**Comment by shyamjvs** [comment]
@awouda Could you clarify if the problem is with registering the node (which means the node doesn't show up in `kubectl get nodes`) or with certificate not issued to the node (which means no cert file in `/etc/kubernetes/pki`)?

**Comment by awouda** [comment]
Hi,

The nodes doen't show up when we issue`kubectl get nodes`.
And when we examined the node, we saw there was no `/etc/kubernetes/pki` (cert) generated.

As mentioned, after a while, it _is_ generated.

**Comment by shishirkhandelwal29** [comment]
Facing a similar problem. 
If I create nodes for the EKS cluster using manged node groups, they start showing up with "kubectl get nodes" within minutes.
But 
If I create nodes for the EKS cluster using CloudFormation, they do not show up with "kubectl get nodes".

I also noticed that on provisioning nodes with cloudformation, my other nodes (from managed nodegroups) also became "NotReady".

**Comment by cartermckinnon** [comment]
I suspect this issue was related to the bootstrap parameters, such as the cluster CA and API server endpoint. Please reopen this issue if you're still experiencing this on current versions of Kubernetes.
