### ISSUE TITLE
AWS_ACCESS_KEY_ID: unbound variable

### ISSUE THREAD

**Issue by kevinfrommelt-wf** [awslabs/amazon-eks-ami#247]
**What happened**:
Updated our version of amazon-eks-ami, ran install-worker.sh and it fails with:
```
install-worker.sh: line 123: AWS_ACCESS_KEY_ID: unbound variable
```

**What you expected to happen**:
Script succeeds without having to set that variable

**How to reproduce it (as minimally and precisely as possible)**:
run install-worker.sh without the environment variable `AWS_ACCESS_KEY_ID` set

**Anything else we need to know?**:
Change introduced by https://github.com/awslabs/amazon-eks-ami/pull/212/files and it conflicts with https://github.com/awslabs/amazon-eks-ami/blob/master/install-worker.sh#L4

**Comment by mogren** [comment]
Similar to https://github.com/aws/amazon-vpc-cni-k8s/pull/382, this would probably be solved by changing to:
```
    if [[ -n "${AWS_ACCESS_KEY_ID:-}" ]]; then
```

**Comment by ravisinha0506** [comment]
This seems to be an old issue for which the fix is already been applied. Resolving this issue. Please free to re-open this if this issue still exists.
