### ISSUE TITLE
Make TSC the default system clock source

### ISSUE THREAD

**Issue by cwhatley** [awslabs/amazon-eks-ami#249]
**What would you like to be added**:

Make the default system clock source "tsc" instead of "xen".

**Why is this needed**:

Docker containers that do frequent system time lookups can be badly affected by the overhead around the xen system clock source.

AWS's own tuning recommendations suggest this switch.

Is there any reason not to switch to tsc as the default for the EKS images?

**Comment by JasonSwindle** [comment]
I have a soon pending PR for this.  I need to test it first.


https://github.com/JasonSwindle/amazon-eks-ami/commit/9d57d76229bd21ab78f827c5668e03b7d6a60621

**Comment by JasonSwindle** [comment]
This issue can be closed.

**Comment by micahhausler** [comment]
Closed in #272

**Comment by cwhatley** [comment]
This doesn't appear to be working anymore. See comments in #321

**Comment by mattbmidigator** [comment]
seeing the same behavior in v1.15.11-eks-065dce

**Comment by cartermckinnon** [comment]
Has anyone continued to experience this issue on currently-supported AMI's?

**Comment by bryantbiggs** [comment]
I don't know if its related, but I usually do not have to open NTP/123 on my NACLs/security groups but with the EKS AMI I am seeing a lot of REJECTs in flow logs 

Per this https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
> The Amazon Time Sync Service is available through NTP at the 169.254.169.123 IPv4 address or the fd00:ec2::123 IPv6 address for any instance running in a VPC. The IPv6 address is only accessible on [Instances built on the Nitro System](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances). Your instance does not require access to the internet, and you do not have to configure your security group rules or your network ACL rules to allow access. The latest versions of Amazon Linux 2 and Amazon Linux AMIs synchronize with the Amazon Time Sync Service by default.

Is there any way to use this service at 169.254.169.123 instead of having to open up NTP/123 to a public route?

**Comment by cartermckinnon** [comment]
Looking into this. I think we should remove the `chrony` config, as the base AL2 AMI should already do what's necessary for TSS.

As for #272  -- that PR was a no-op. It's setting the current clocksource during the AMI build process, and the default is reset upon reboot. I think we're fine to set `clocksource=tsc` on the kernel command line, but I need to verify this doesn't cause issues if/when that clocksource isn't available. I'm also not sure if `tsc` is stable on newer Intels versus `kvm-clock`.

**Comment by cartermckinnon** [comment]
@ybstaked are you using Xen or Nitro-based instance types? FWICT, `tsc` is what's being used on Nitro-based instance types, and the recommendation is to sue `kvm-clock`; whether this could be responsible for the drift is an open question.

**Comment by ybstaked** [comment]
Detecting issues on `c6i.4xlarge` and `m6i2xlarge`

**Comment by cartermckinnon** [comment]
Interesting; those *are* Nitro instance types. If you want to give `kvm-clock` a try, it'd be a good data point.

I'll go ahead and update #1328 to use it, it's the recommendation from EC2 anyway 👍
