### ISSUE TITLE
Add Support for SpotFleets

### ISSUE THREAD

**Issue by tylernisonoff** [awslabs/amazon-eks-ami#25]
It would be great to be able to launch worker nodes as spot fleets.  Any thoughts on the best way to get there?  Seems like we'd want to generalize the NodeGroup section to include a type for SpotFleet.  As for selecting which one to use, it'd seem ideal if one could specify multiple ASGs and they'd each be templated into the final configuration file.

**Comment by pahud** [comment]
@tylernisonoff try this alternative template
https://github.com/pahud/eks-templates

**Comment by micahhausler** [comment]
Thanks for the request! It is possible to run workers in SpotFleet, but for the getting started template included in this repo we'd like to keep it simple. Thanks @pahud for the reference!
