### ISSUE TITLE
add support for t3a instance types

### ISSUE THREAD

**Issue by jhoblitt** [awslabs/amazon-eks-ami#254]
**What would you like to be added**:
Support for t3a instance types.

**Why is this needed**:
As `t3a.*` instance types are generally preferable to `t3.*`.

**Comment by Pluies** [comment]
@jhoblitt hasn't this been fixed by https://github.com/awslabs/amazon-eks-ami/pull/236/files ?

**Comment by jhoblitt** [comment]
It looks like it but I haven't tested.

**Comment by ravisinha0506** [comment]
Closing as this should be fixed by #236. Please feel free to re-open this if there are any concerns.
