### ISSUE TITLE
Support for t3a, m5ad and r5ad instance types is missing

### ISSUE THREAD

**Issue by drewhemm** [awslabs/amazon-eks-ami#262]
**What would you like to be added**:

Support for t3a, m5ad and r5ad instance types.

**Why is this needed**:

AWS had added new instance types, and the AMI does not currently support them.

**Comment by drewhemm** [comment]
Partially related to https://github.com/awslabs/amazon-eks-ami/issues/254

**Comment by max-rocket-internet** [comment]
What happens currently if the CNI is used on one of these instances?

**Comment by drewhemm** [comment]
It is not able to allocate IP addresses to all the pods on the instance (I'll have to get the exact error message).

I thought it was because it does not know what the pod limit should be for these instance types, but curiously, I get the same problem with this PR.

**Comment by max-rocket-internet** [comment]
> It is not able to allocate IP addresses to all the pods 

But some will run? Or none?

**Comment by hakamadare** [comment]
> > It is not able to allocate IP addresses to all the pods
> 
> But some will run? Or none?

i ran into this problem yesterday; i was able to start three pods on a t3a.small, and then no additional pods could be scheduled b/c CNI was unable to give them network interfaces.  switching back to t3.small enabled me to work around the issue.

**Comment by drewhemm** [comment]
> > It is not able to allocate IP addresses to all the pods
> 
> But some will run? Or none?

Sorry for the late response. Same as reported by @hakamadare: It runs a few pods, but then no more, without actually hitting the ENI limit.

**Comment by sc250024** [comment]
I think the CNI version just needs to be updated to v1.5. See my comment here: https://github.com/aws/amazon-vpc-cni-k8s/issues/59#issuecomment-504972238

**Comment by VojtechVitek** [comment]
We're hitting the CNI errors when trying to schedule more pods on `t3a.small` instance too.

I think the number of maxPods `t3a.small 11` (see [eni-max-pods.txt](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt)) doesn't correspond to this table:
 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

I think the number of `--max-pods` on `t3a.small` instance should be less then 11.

Can anyone confirm?

**Comment by dayglojesus** [comment]
According the chart @VojtechVitek references, a `t3a.small` only supports 2 x ENIs, for a total of `8` IP addresses. At that ratio, `--max-pods` needs to be `7` or less, as far as I can discern.

**Comment by VojtechVitek** [comment]
cc @mogren

**Comment by mogren** [comment]
Thanks for reporting, I've created a PR for the CNI, will fix for the AMI build as well.
