### ISSUE TITLE
install-worker script using wrong kubelet config

### ISSUE THREAD

**Issue by apr-1985** [awslabs/amazon-eks-ami#268]
**What happened**: When I am trying to install 1.11.8 worker nodes they are picking up the `kubelet-config-with-secret-polling.json`

**What you expected to happen**: should pickup the `kubelet-config.json`

**How to reproduce it (as minimally and precisely as possible)**: Install an 1.11.8 worker node and check the kubelet config json name

**Anything else we need to know?**:  This is caused by the recent changes to https://github.com/awslabs/amazon-eks-ami/blob/master/install-worker.sh#L149
Where it now uses the `KUBERNETES_VERSION` env var to get the files from the bucket which in my case needs to be `1.11.8` to use `s3://amazon-eks/1.11.8/`
However the `KUBELET_CONFIG` code hasnt been changed at line https://github.com/awslabs/amazon-eks-ami/blob/master/install-worker.sh#L173
to work with these longer kube versions.

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): S3
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.1"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.11"
- AMI Version: home made
- Kernel (e.g. `uname -a`): NA
- Release information (run `cat /etc/eks/release` on a node):

```
NA
```

**Comment by edmorley** [comment]
This was since fixed in #264, so can be closed :-)
