### ISSUE TITLE
Add support for T3

### ISSUE THREAD

**Issue by tomweston** [awslabs/amazon-eks-ami#27]
## Adding T3 Instances failed

Please see the following pull request:
[Adds T3 Instance Types](https://github.com/awslabs/amazon-eks-ami/pull/26)

**Comment by micahhausler** [comment]
There are several things that need to happen to support this:

- [ ] aws/amazon-vpc-cni-k8s#145 needs to be merged
- [ ] [files/eni-max-pods.txt](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) needs to be updated with these instance types
- [ ] The CloudFormation template [amazon-eks-nodegroup.yaml](https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml) needs to add the new instance types

**Comment by delgod** [comment]
also related - https://github.com/kubernetes/autoscaler/pull/1234

**Comment by mbeacom** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/pull/145 has been merged and `1.2.0` is now available.

**Comment by micahhausler** [comment]
Released in v25
