### ISSUE TITLE
Update bootstrap to use IAM Authentification

### ISSUE THREAD

**Issue by sklemmer** [awslabs/amazon-eks-ami#275]
**What happened**:
Yesterday we received a notification that the current cfn-signal script will basically no longer work after May 30. 

**What you expected to happen**:
Use latest cfn scripts with proper authentification

The full text from AWS:

> We identified EC2 instances in your account that have been retrieving resource metadata 
 information from CloudFormation stacks in your account that are outside of the stack from which the instances were created. These resources are listed under the 'Affected resources' tab.

> CloudFormation currently uses instance identity based authentication for calls coming from EC2 instances to access certain stack level APIs, such as DescribeStackResources. These APIs are used by aws-cfn-bootstrap scripts [1], including cfn-init and cfn-hup, which are commonly used to provision EC2 instances created by CloudFormation.

> On March 18, 2019, we limited the scope of calls to these APIs to the stack to which the calling instance belongs. To ensure a smooth transition, we will not apply that limitation to this account or any other account in which instances have been making cross-stack requests until May 30, 2019.

> To continue using aws-cfn-bootstrap scripts across stacks in this account after May 30, 2019, you must migrate those scripts to IAM authentication and grant them permissions to access other stacks. For more information about CloudFormation helper script permissions, please refer to the documentation [2].

> Please note, the affected resources were identified to have made cross-stack requests in the past. Some of the affected instances may have already been terminated and stacks may be deleted. They are provided for debugging purposes. 

> If you have any concerns or questions, please contact AWS Support [3]. 

> [1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html
> [2] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html#cfn-helper-scripts-reference-permissions
> [3] https://aws.amazon.com/support
`

**Comment by micahhausler** [comment]
Hi thanks for reporting this issue, are the Affected Resources in your account EKS nodes using the provided template or for some other stacks?

**Comment by sklemmer** [comment]
Yes we are using the provided nodegroup template to create our autoscaling groups
