### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cdenneen** [awslabs/amazon-eks-ami#286]
Steps for using this to build windows node images as well.

**Comment by abalakersky** [comment]
Would like this as well

**Comment by fbattistella** [comment]
Windows nodes are GA now, this should be made available ASAP.

**Comment by somujay** [comment]
> Windows nodes are GA now, the packer file should be made available ASAP so we're able to customize the windows AMI too.

Hey, we don't have plan to offer packer scripts for Windows AMI as it requires winRM to be enabled.

**Comment by roger-reed** [comment]
Port forwarding doesn't seem to work with Windows nodes.  Is it correct that this is a limitation with the current EKS Windows AMI?  Would it be possible to bake in wincat.exe to enable this functionality? See https://github.com/kubernetes/kubernetes/pull/75479

**Comment by divbell** [comment]
Do you anticipate releasing this in 2021?

**Comment by mikestef9** [comment]
We have recently added steps to our documentation on how to build custom Windows AMIs

https://docs.aws.amazon.com/eks/latest/userguide/eks-custom-ami-windows.html
