### ISSUE TITLE
--kubelet-extra-args may not be applied correctly due to flapping kubelet

### ISSUE THREAD

**Issue by nirnanaaa** [awslabs/amazon-eks-ami#288]
**What happened**:

We have a cloud-init file, that calls `bootstrap.sh` and adds node labels and initial taints

```sh
/etc/eks/bootstrap.sh --kubelet-extra-args '--register-with-taints dedicated=system:NoSchedule --node-labels dedicated=system,node-role.kubernetes.io/system=' ${ClusterName}
```

When we start up nodes we saw that sometimes those labels/taints were not applied. After researching into it we found that sometimes kubelet was starting just after the correct kubeconfig/kubelet config was present, and just before applying the extra args. It was not considered an "initial registration" by the kubelet at that point and the settings, that are only applied upon first registration, were not applied at all.

**What you expected to happen**:

We expected kubelet to only start at the end of the bootstrap script, where `systemctl start kubelet` is called. This ensures all bootstrapping is done before kubelet attempts to start and does not result in such flaky behaviors.

**How to reproduce it (as minimally and precisely as possible)**:
- create an EKS cluster
- Join nodes using bootstrap.sh with kubelet extra args (only the ones that are applied once will show this behavior):
    ```sh
    /etc/eks/bootstrap.sh --kubelet-extra-args '--register-with-taints dedicated=system:NoSchedule --node-labels dedicated=system,node-role.kubernetes.io/system=' ${ClusterName}
    ```

**Anything else we need to know?**:

We did fix this, by stopping the kubelet manually before running `bootstrap.sh` by using `systemctl stop kubelet`. This resulted in consistent behavior across all nodes (tested with > 100 nodes).

**Environment**:
- AWS Region: `eu-west-1`
- Instance Type(s): `m5.2xlarge`
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `eks.2`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): `1.12`
- AMI Version: (`ami-091fc251b67b776c3`)
- Kernel (e.g. `uname -a`): `Linux xxx 4.14.123-111.109.amzn2.x86_64 #1 SMP Mon Jun 10 19:37:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-03f4c9c1a6e99a8ca"
BUILD_TIME="Sat Jun 15 03:31:01 UTC 2019"
BUILD_KERNEL="4.14.123-111.109.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by kevincantu** [comment]
With the `v1.13.11-eks-5876d6` AMIs I've gotten this launch script to set the k8s labels on newly created nodes, using the workaround @nirnanaaa described:
```
#!/bin/bash
set -o xtrace
systemctl stop kubelet
/etc/eks/bootstrap.sh \
  ...
  --kubelet-extra-args '"--allowed-unsafe-sysctls=net.core.somaxconn" "--node-labels=kevin-experiment-1=ok,kevin-experiment-2=ok"' \
  ...
```

As I understand it
* when Packer makes the EKS AMI, [install-worker.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/install-worker.sh#L200) sets up the [/etc/systemd/system/kubelet.service](https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet.service#L14) file which calls kublet with `$KUBELET_EXTRA_ARGS`,
* whenever the AMI's [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L207) is called, it sets up the `/etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf` file which sets that `KUBELET_EXTRA_ARGS` envvar ([like so](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html)), and
* when our worker autoscaling group uses its launch configuration it calls that `bootstrap.sh`.

So (re: https://github.com/awslabs/amazon-eks-ami/issues/29) it's important that where we call bootstrap.sh, we have all the quoting just right (it's sensitive).  And (re: this and https://github.com/awslabs/amazon-eks-ami/issues/184) if anything invokes `kublet.service` before `30-kublet-extra-args.conf` (before it exists, or before it's invoked), none of these extra arguments will be included.

Does that make sense?

**Comment by wongma7** [comment]
It sounds like your cloud-init is racing CloudFormation's cfn-init which already calls bootstrap.sh without the args you want. https://github.com/awslabs/amazon-eks-ami/blob/8c61db5239205b27c4afa687eb4f05738f0b7312/amazon-eks-nodegroup.yaml#L498

Does setting these args in BootstrapArguments of the cloudformation template work?

**Comment by kevincantu** [comment]
I, at least, have been using Terraform..

**Comment by wongma7** [comment]
OK, then I think the fix that would work for everyone is for bootstrap.sh to always call `systemctl stop kubelet`, or replace start with restart.

It seems like for those that do use the CFN template the BootstrapArguments parameter is not super obvious. And whether one uses CFN or not, there is a (totally reasonable) expectation that executing `bootstrap.sh` with the `kubelet-extra-args` arg always actually does something.
