### ISSUE TITLE
maintaining an "latest" S3 folder to contain binaries for each major k8s release

### ISSUE THREAD

**Issue by M00nF1sh** [awslabs/amazon-eks-ami#289]
**What would you like to be added**:
maintains an "latest" s3 folder to contain binaries for each major k8s release.

**Why is this needed**:
currently the amazon-eks bucket is structured like
* `s3://amazon-eks/1.12.7/2019-03-27`
* `s3://amazon-eks/1.13.7/2019-06-11`

Would like to have something like `s3://amazon-eks/1.13/latest` so we don't need to update the build scripts when we release new binaries version. And we can deprecate old binaries(maybe vulnerable be securityIssues/bugs) easily if everyone is moving to use this new folder pattern.

**Comment by whereisaaron** [comment]
Or if not in S3 maybe SSM EKS public parameters automatically generated to reference S3 or ideally HTTPS URLs for the latest binary and also AMIs for each mayor version?

https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html

**Comment by M00nF1sh** [comment]
@whereisaaron 
Hi, the SSM parameter for AMIs is currently in the progress of implementation 😃 

SSM parameter for latest binaries is an good idea, better than maintaining an separate s3 folder actually.

**Comment by cartermckinnon** [comment]
This is available and is documented [here](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html).
