### ISSUE TITLE
Support make ami for 1.13

### ISSUE THREAD

**Issue by monsterxx03** [awslabs/amazon-eks-ami#292]
**What would you like to be added**:

Support: `make 1.13`  to build ami for 1.13 worker node

**Why is this needed**:

We have some customized changes during ami build process(like encrypted ami, pre bake some binaries on host node ...)

Don't known the new s3 location for 1.13 binaries.

**Comment by M00nF1sh** [comment]
make 1.13 is supported:
https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L43

**Comment by monsterxx03** [comment]
Thanks !
