### ISSUE TITLE
EKS-optimized AMI with GPU Support in Mumbai

### ISSUE THREAD

**Issue by jerrylam** [awslabs/amazon-eks-ami#298]
I'm trying to use the image for `EKS-optimized AMI with GPU Support` in Mumbai. However, this ami is not available in the marketplace for Mumbai. Is there a reason why it is not available in the Mumbai region?

**Environment**:
- AWS Region: Mumbai
- Instance Type(s): p2.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.12
- AMI Version: ami-001b8c7e420a9f22a
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

**Comment by mogren** [comment]
Hi @jerrylam, I think it got updated, can you try using `ami-09ad3a49fb13389a0` instead?

**Comment by jerrylam** [comment]
That was the problem! Thank you.
