### ISSUE TITLE
AMI Generated by packer, kubelet report incorrect version

### ISSUE THREAD

**Issue by mbartsch** [awslabs/amazon-eks-ami#3]
When creating and using an AMI created with packer, the version of kubelet report the following version:

[root@ip-172-31-5-73 ~]# kubelet --version
Kubernetes v0.0.0-master+$Format:%h$

It seems to be a cosmetic issue, but would be nice to have the right version on the binary.

**Comment by micahhausler** [comment]
This is actually a build process issue with kubernetes, nothing to do with the packer repo. Its something we're tracking. Thanks!

**Comment by hobbsh** [comment]
This can be fixed by pulling the binaries from https://dl.k8s.io/v1.10.3/kubernetes-node-linux-amd64.tar.gz instead of the S3 bucket

**Comment by choi0** [comment]
I was having the same issue and the solution @hobbsh provided worked for me

**Comment by micahhausler** [comment]
We don't want to take on an outside of AWS dependency, and we've resolved the version/build issue.  Thanks!
