### ISSUE TITLE
'kubernetes.io/hostname' Label in worker nodes does not match the actual node name

### ISSUE THREAD

**Issue by Sakib37** [awslabs/amazon-eks-ami#301]
**What happened**:
Created EKS cluster using [terraform-aws-module ](https://github.com/terraform-aws-modules/terraform-aws-eks) version 2.2.0 

All the worker nodes has a different value for 'kubernetes.io/hostname'  label. 
```
$ k describe node ip-10-23-46-23.eu-west-1.compute.internal
....
Labels:   ...
             kubernetes.io/hostname=ip-10-23-46-23.$MY_DOMAIN
....
```

**What you expected to happen**:
The label value for 'kubernetes.io/hostname'  should match the name at the output of 

`kubectl get node`

ex: **ip-10-23-46-23.eu-west-1.compute.internal**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by petelopez** [comment]
Same behavior here on the latest ami `ami-0392bafc801b7520f`.  `kubectl get nodes` show the name as `ip-10-254-100-127.ec2.internal`. However the hostname label is `kubernetes.io/hostname=ip-10-254-100-239.ec2-internal`. Shouldn't these two match?

**Comment by pre** [comment]
This is also an issue with the EKS Ubuntu AMI (eg. `ami-0cfc8096f1dfd9a2b`).

Node has
*  metadata.name == `ip-10-0-3-5.eu-central-1.compute.internal` 
* metadata.labels -> `kubernetes.io/hostname: ip-10-0-3-5`

**Comment by cartermckinnon** [comment]
Are you still seeing this issue? My guess would be that it's caused by kubelet's in-tree cloud provider, which is feature-frozen in favor of https://github.com/kubernetes/cloud-provider-aws.
