### ISSUE TITLE
Add Support for m5.8xlarge, m5a.8xlarge, m5d.8xlarge instance type

### ISSUE THREAD

**Issue by mailjunze** [awslabs/amazon-eks-ami#302]
**What happened**:
No entry for r5.8xlarge  in /etc/eks/eni-max-pods.txt. Not setting max pods for kubelet
No entry for r5a.8xlarge  in /etc/eks/eni-max-pods.txt. Not setting max pods for kubelet
No entry for r5d.8xlarge  in /etc/eks/eni-max-pods.txt. Not setting max pods for kubelet

**What you expected to happen**:
Use worker nodes m5.8xlarge, m5a.8xlarge, m5d.8xlarge instance type
**How to reproduce it (as minimally and precisely as possible)**:
Create worker nodes with m5.8xlarge, m5a.8xlarge, m5d.8xlarge instance types
**Anything else we need to know?**:
Checked https://github.com/awslabs/amazon-eks-ami/blob/32d2ac42612e6cff05df03e7be8094cfa9250da1/files/eni-max-pods.txt and found latest EKS AMI doesnt support r5.8xlarge,m5a.8xlarge, and m5d.8xlarge instance type currently.
**Environment**:
- AWS Region:eu-west-1
- Instance Type(s):m5.8xlarge, m5a.8xlarge, m5d.8xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):1.13
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:ami-00ac2e6b3cb38a9b9
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by mogren** [comment]
Hi,

I have had a PR open(#287) to add this for a while and will try to get it merged soon.

**Comment by mailjunze** [comment]
@mogren Thanks, I can see the PR has been merged.

**Comment by marcecaro** [comment]
Is this merged PR already released? Any ETA?
Thanks

**Comment by mogren** [comment]
Merged, and new AMIs already released.
