### ISSUE TITLE
Incorporate AWS inspector into AMI

### ISSUE THREAD

**Issue by daniellohausen** [awslabs/amazon-eks-ami#308]
**What would you like to be added**:
I like the AWS inspector to be included in the EKS AMI

**Why is this needed**:
As both EKS and AWS Inspector are AWS services, is is quite likely both are being used. Teams could use the Inspector without the need of a custom AMI.

**Comment by jorihardman** [comment]
While we're waiting for this enhancement, I figured I'd put a workaround here that's quite easy to implement. If you're using the aws-provided cloutformation template to provision your node groups, you can edit the user data in the launch configuration. The path in the yaml is `NodeLaunchConfig.Properties.UserData`. At time of writing, I edited to look as follows:

```yaml
UserData:
  Fn::Base64: !Sub |
    #!/bin/bash
    set -o xtrace
    /etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}
    wget https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install
    bash install
    sudo /etc/init.d/awsagent start
    /opt/aws/bin/cfn-signal --exit-code $? \
             --stack  ${AWS::StackName} \
             --resource NodeGroup  \
             --region ${AWS::Region}
```

This installs the agent and starts it on initial boot of the node.

**Comment by RyPeck** [comment]
@jorihardman why the `wget` from that Cloudfront Distribution instead of `inspector-agent.amazonaws.com` as [documented](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html)?

**Comment by max-rocket-internet** [comment]
I'd rather keep the AMI lean 🏎

> As both EKS and AWS Inspector are AWS services, is is quite likely both are being used

No it's not.

> I figured I'd put a workaround here

That's not a work around, that's exactly what user data is meant for 😃

**Comment by jorihardman** [comment]
> @jorihardman why the `wget` from that Cloudfront Distribution instead of `inspector-agent.amazonaws.com` as [documented](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html)?

@RyPeck I must have been following [this blog post](https://aws.amazon.com/blogs/security/how-to-simplify-security-assessment-setup-using-ec2-systems-manager-and-amazon-inspector/).

**Comment by cartermckinnon** [comment]
We use Inspector v2 to scan our AMI's prior to public release, as it requires only the SSM agent (which is included in the AMI).
