### ISSUE TITLE
Support for containerd

### ISSUE THREAD

**Issue by rverma-nikiai** [awslabs/amazon-eks-ami#309]
**What would you like to be added**:
Support for container, may be publish containerd amis as well. 

**Why is this needed**:
Using DIND has its own vulnerability and one way of safeguarding is to disable docker on hosts. GKS supports containerd natively as well.

A small guide for centos https://medium.com/errnothxbye/centos-7-with-cri-o-on-eks-ae9684aff764. Would be nice to see this part of amazon linux official ami.

Related issue
https://github.com/aws/containers-roadmap/issues/313

**Comment by ravisinha0506** [comment]
Hi,

EKS optimized AMI now supports containerd CRI since [this release](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210716). Resolving this issue. Please free to re-open this or create a new one if you see any issues.
