### ISSUE TITLE
How often AWS updates the EKS AMI

### ISSUE THREAD

**Issue by frederiksf** [awslabs/amazon-eks-ami#311]
Can anyone tell me how often AWS updates the regular AMI? I off course want to keep up with security host updates and for that reason i want to know. Available options;

- Daily build a custom AMI (this project) with the latest sec patches
- Configure AWS System Manager and patch the worker nodes automatically with a standard baseline.
- Just replace AMI ID in the autoscaling group and drain old nodes (in case the update interval is short)
- Introduce something like Ansible (playbooks) and patch nodes with yum. 

What is best practice?

**Comment by frederiksf** [comment]
Nobody?

**Comment by tarrall** [comment]
I had the same question and our AWS contacts were not at all forthcoming about this.

You can however get a pretty good idea of how often they release by looking at past history:
```
aws ec2 describe-images --filters Name=name,Values='amazon-eks-node-1.13-*'
```
I see v20190614, v20190701, v20190814, so it looks like the answer is "roughly every 2 to 6 weeks."  :) 

I went with the "replace AMI ID in the autoscaling group" approach as I prefer immutable infrastructure when possible and was not subject to any stringent "OS must be patched daily" requirement.  I'm hesitant to suggest that's a "best practice" ... the tradeoff is between "I have the most recent patches" and "I am using an AMI which the vendor has tested" so depends on your stability vs compliance (hesitant to say security, but maybe) needs.

**Comment by TiloGit** [comment]
related #324

**Comment by krystan** [comment]
I have previously gone with replacing the AMI, we build our EKS stuff out in terraform and build an ec2 template, our node groups are based off that template, we query the latest AMI id and update the node groups, we have to make sure all our disruption policies are in order etc but they are respected and we get no failures as long as that's in line. There is nothing at all to stop you running a cron based patch with systems manager in addition to this approach, if your build doesn't spin frequently but we have a cron job running our terraform in at least twice a day to avoid that.

**Comment by cartermckinnon** [comment]
We're working to decrease the amount of time between AMI releases, but if your use-case requires *very* frequent patching (e.g. daily), then you'll probably want to own your destiny using one of the options mentioned above.
