### ISSUE TITLE
binaries for 1.13.8 are missing

### ISSUE THREAD

**Issue by ttyS0** [awslabs/amazon-eks-ami#317]
The binaries for the [v20190814](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20190814) release are missing from the `amazon-eks` bucket.

```
aws s3 ls s3://amazon-eks/
                           PRE 1.10.11/
                           PRE 1.10.13/
                           PRE 1.10.3/
                           PRE 1.11.10/
                           PRE 1.11.5/
                           PRE 1.11.8/
                           PRE 1.11.9/
                           PRE 1.12.7/
                           PRE 1.12.9/
                           PRE 1.13.7/
                           PRE cloudformation/
```

**Comment by M00nF1sh** [comment]
@ttyS0 
Hi, we just released the binaries at
* amazon-eks/1.13.8/2019-08-14
* amazon-eks/1.12.10/2019-08-14
* amazon-eks/1.11.10/2019-08-14

It's supposed to be released on Friday, but got delayed by processes. :D
