### ISSUE TITLE
Amazon EKS-optimized AMI from parameter store

### ISSUE THREAD

**Issue by pahud** [awslabs/amazon-eks-ami#32]
Hi

Any plan to get the Amazon  EKS-optimized AMI from parameter store just like Amazon ECS does?

![image](https://user-images.githubusercontent.com/278432/44695853-b9e73d80-aaa7-11e8-95ea-46e6a4b46704.png)

**Comment by micahhausler** [comment]
Thanks for this feature request, I'll add this to our team's backlog.

**Comment by metral** [comment]
@micahhausler By chance, are there any updates on supporting this? Thanks!

**Comment by micahhausler** [comment]
No updates at this point, but it is definitely something we want to do!

**Comment by d-nishi** [comment]
@micahhausler what is the rough timeline for this?

**Comment by mcrute** [comment]
@d-nishi you might want to check out the [containers roadmap issue](https://github.com/aws/containers-roadmap/issues/231) for this feature for more updates on the timeline.

**Comment by d-nishi** [comment]
@mcrute -- great thanks but when will someone be assigned to deliver this and what is the ~timeline for this feature to be delivered?

**Comment by pahud** [comment]
Just noticed it's in container public roadmap now
https://github.com/aws/containers-roadmap/issues/231

**Comment by vipulsabhaya** [comment]
Amazon EKS now supports retrieving EKS-Optimized AMI IDs via SSM parameters.  Please look at the issue referenced above for the announcement!
