### ISSUE TITLE
EKS 1.3.10 is announced but doesn't seem to exist

### ISSUE THREAD

**Issue by jhoblitt** [awslabs/amazon-eks-ami#325]
The official eks docs reference `1.3.10` but eks master instances still seem to be on `1.3.8` and no worker ami's seem to be published. This is both disappointing as `1.3.10` is a security release and frustrating as I've had to waste time "polling" for `1.3.10` to appear.

https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

```
$ aws s3 ls s3://amazon-eks/
                           PRE 1.10.11/
                           PRE 1.10.13/
                           PRE 1.10.3/
                           PRE 1.11.10/
                           PRE 1.11.5/
                           PRE 1.11.8/
                           PRE 1.11.9/
                           PRE 1.12.10/
                           PRE 1.12.7/
                           PRE 1.12.9/
                           PRE 1.13.7/
                           PRE 1.13.8/
                           PRE cloudformation/
```

Related to #323

**Comment by marcincuber** [comment]
Any updates here from EKS team?

**Comment by mjhoffman65** [comment]
> The official eks docs reference `1.3.10` but eks master instances still seem to be on `1.3.8` and no worker ami's seem to be published. This is both disappointing as `1.3.10` is a security release and frustrating as I've had to waste time "polling" for `1.3.10` to appear.
> 
> https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html
> https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation
> https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
> 
> ```
> $ aws s3 ls s3://amazon-eks/
>                            PRE 1.10.11/
>                            PRE 1.10.13/
>                            PRE 1.10.3/
>                            PRE 1.11.10/
>                            PRE 1.11.5/
>                            PRE 1.11.8/
>                            PRE 1.11.9/
>                            PRE 1.12.10/
>                            PRE 1.12.7/
>                            PRE 1.12.9/
>                            PRE 1.13.7/
>                            PRE 1.13.8/
>                            PRE cloudformation/
> ```
> 
> Related to #323

You could watch the releases on this repo, so at least you get notified instead of polling.  I'm anxiously awaiting the 1.13.10 release as well :-).
![image](https://user-images.githubusercontent.com/1480930/64272503-8090ab80-cf0d-11e9-978c-564775c1009c.png)

**Comment by TiloGit** [comment]
btw server is already updated:

cluster info:
Kubernetes Version 1.13
Platform Version eks.3 
```
 kubectl version
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Accroding to https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html a Platform Version eks.4 is just around the corner.

**Comment by mogren** [comment]
1.13 is deprecated by now.
