### ISSUE TITLE
How to mount instance storage automatically

### ISSUE THREAD

**Issue by glapark** [awslabs/amazon-eks-ami#326]
**Environment**:
- AWS Region: ap-northeast-2
- Instance Type(s): m5d.xlarge

Hi,

Our application generates a lot of temporary data, and we would like to take advantage of instance storage to store temporary data. So, I would like to learn how to mount instance storage automatically, so that Pods can use mount points for hostPath volumes. Currently we have to log on to each instance and mount instance storage manually, which is tedious and does not scale.

What I tried is to append the following script to the end of 'files/bootstrap.sh' and create a new AMI.

if [ "$(file -b -s /dev/nvme1n1)" == "data" ]; then
  mkfs -t ext4 /dev/nvme1n1
  mkdir -p /tmp/ephemeral1
  mount /dev/nvme1n1 /tmp/ephemeral1
  chown ec2-user:ec2-user /tmp/ephemeral1
fi

Then, I create an EKS cluster (using eksctl) with the new AMI and an EC2 instance type that comes with instance storage (e.g., m5d.xlarge which has /dev/nvme1n1). Still, /dev/nvme1n1 is not mounted automatically. (I can log on to the EC2 instance and mount it manually.)

I would appreciate any comment on this issue.

--- Sungwoo

**Comment by jpaulodit** [comment]
@glapark did you find a solution to this? Can you share? Thank you.

**Comment by glapark** [comment]
I use preBootstrapCommands to mount instance storage. Here is an example of
YAML:

nodeGroups:
  - name: mr3-worker
    preBootstrapCommands:
      - "mkfs -t ext4 /dev/nvme1n1"
      - "mkdir -p /ephemeral1"
      - "mount /dev/nvme1n1 /ephemeral1"
      - "chown ec2-user:ec2-user /ephemeral1"

--- gla

**Comment by jpaulodit** [comment]
Thank you. That was very helpful.

**Comment by luckymagic7** [comment]
@glapark 
How did you provision the EC2 node, using nvme SSD disk such as `m5d.xlarge`?
I want to make a EKS cluster using `c5d.2xlarge` node, but on the AWS console there's no instance type supporting instance storage.
Did you use `eksctl`?
I am wondering how did you make `m5d.xlarge` type ec2 node.

Thank you.

**Comment by glapark** [comment]
Yes, I used eksctl. For details, please see:
https://mr3docs.datamonad.com/docs/quick/aws/run-eks-autoscaling/

-- gla
