### ISSUE TITLE
Copy amazon-eks-node 1.14 AMIs Failure

### ISSUE THREAD

**Issue by JadCham** [awslabs/amazon-eks-ami#328]
Hi,

It seems like something is missing in the release of the new AMIs for the EKS worker nodes for 1.14 which is causing a failure when copying the AMI.

I tried both the normal AMI and the GPU optimized AMI and they both have the same problem.
 
![image](https://user-images.githubusercontent.com/11646314/64386637-85795c00-cfee-11e9-9377-ef33d0f0ea02.png)

The issue [happenned before](https://github.com/awslabs/amazon-eks-ami/issues/52) .

@micahhausler  I see you fixed the issue before can you provide an input on why it's happening again with the new AMIs ? 

Thank You!

**Comment by bhagwat070919** [comment]
We made a mistake in making the snapshot public .

Now its all public .
