### ISSUE TITLE
Makefile doesn't yet include 1.14

### ISSUE THREAD

**Issue by willthames** [awslabs/amazon-eks-ami#333]
**What would you like to be added**:
Makefile should include a target for 1.14

**Why is this needed**:

So that I can run `make 1.14`. Support for 1.14 seems to otherwise be in the repo, just not in the Makefile

**Comment by GitSandy** [comment]
Can you please let us know when are we merging this change. We would like to use 1.14

**Comment by bmcstdio** [comment]
Could we merge this please?
