### ISSUE TITLE
Where to download the binary files for 1.13.10?

### ISSUE THREAD

**Issue by xuanzhong** [awslabs/amazon-eks-ami#338]
EKS 1.13.10 is officially announced with AMI, but there is no binary files under s3 bucket.
The latest binary files are under 1.13.8.
aws s3 ls s3://amazon-eks/1.13.8/2019-08-14/bin/linux/amd64/

Can you please upload the new files to S3?

**Comment by M00nF1sh** [comment]
Hi, we just released the latest binaries to:
* amazon-eks/1.14.7/2019-09-27
* amazon-eks/1.13.11/2019-09-27
* amazon-eks/1.12.10/2019-09-27
* amazon-eks/1.11.10/2019-09-27
We'll setup some automated process to release these binaries.
