### ISSUE TITLE
worker nodes not adding to cluster

### ISSUE THREAD

**Issue by saravanakumarangamuthu** [awslabs/amazon-eks-ami#342]
**What happened**:
followed : https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
Have tried creating EKS cluster , tried version 1.12,1.13,1.14 in us-east-2 region , I could see the cluster is up and workernodes are up, but it is not adding to cluster.

# kubectl get nodes
No resources found.

 #kubectl get all --all-namespaces
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-754cb4f968-7lkxs   0/1     Pending   0          24m
kube-system   pod/coredns-754cb4f968-qhhz2   0/1     Pending   0          24m

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   172.20.0.1    <none>        443/TCP         24m
kube-system   service/kube-dns     ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   24m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     0         0         0       0            0           <none>          24m
kube-system   daemonset.apps/kube-proxy   0         0         0       0            0           <none>          24m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/2     2            0           24m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-754cb4f968   2         2         0       24m

**What you expected to happen**:
worker nodes to get added on cluster
**How to reproduce it (as minimally and precisely as possible)**:
after creating the worker nodes with below mentioned AMIs and steps it is not adding to cluster
**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-2 
- Instance Type(s):  tried in all these t2.medium, t2.xlarge,m5.large, m5.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): aws eks describe-cluster --name eks-xxxx-cluster --query cluster.platformVersion
eks.1

- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): I have tried deploying 1.12,1.13,1.14
- AMI Version:  amazon-eks-node-1.13-v20190906 (ami-0355b5edf93d47112) , amazon-eks-node-1.14-v20190906 (ami-0f841722be384ed96)

- Kernel (e.g. `uname -a`): 
- Release information (run `cat /etc/eks/release` on a node): 1.12,1.13,1.14

```
```

**Comment by vbasavani** [comment]
@saravanakumarangamuthu can you please provide the logs of the kubelet service on worker nodes. without them it is difficult to tell

**Comment by saravanakumarangamuthu** [comment]
@vbasavani  here it is 

Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.135315    3981 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Unauthorized
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.135400    3981 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Unauthorized
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.199795    3981 kubelet.go:2244] node "ip-10-xx-xx-207.us-east-2.compute.internal" not found
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.300009    3981 kubelet.go:2244] node "ip-10-xx-xx-207.us-east-2.compute.internal" not found
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.400284    3981 kubelet.go:2244] node "ip-10-xx-xx-207.us-east-2.compute.internal" not found
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: I0926 17:00:42.457487    3981 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: I0926 17:00:42.457542    3981 kubelet_node_status.go:331] Adding node label from cloud provider: beta.kubernetes.io/instance-type=t3.xlarge
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: I0926 17:00:42.457558    3981 kubelet_node_status.go:342] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=us-east-2b
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: I0926 17:00:42.457570    3981 kubelet_node_status.go:346] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=us-east-2
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: I0926 17:00:42.459596    3981 kubelet_node_status.go:72] Attempting to register node ip-10-xx-xx-207.us-east-2.compute.internal
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.500437    3981 kubelet.go:2244] node "ip-10-xx-xx-207.us-east-2.compute.internal" not found
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.523228    3981 kubelet_node_status.go:94] Unable to register node "ip-10-xx-xx-207.us-east-2.compute.internal" with API server: Unauthorized
Sep 26 17:00:42 ip-10-xx-xx-207 kubelet: E0926 17:00:42.600628    3981 kubelet.go:2244] node "ip-10-xx-xx-207.us-east-2.compute.internal" not found

**Comment by vbasavani** [comment]
@saravanakumarangamuthu 
You need to create a configmap as below.
```apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```
Replacing the arn with role arn that you provided to your worker nodes.
Then only kubelet will get permissions to talk to control plane as RBAC is enabled by default for all EKS clusters.

**Comment by saravanakumarangamuthu** [comment]
@vbasavani  yes it works here, but when I do the same via terraform module it is not working.  pls help if you could, https://github.com/terraform-aws-modules/terraform-aws-eks/issues/534

**Comment by vbasavani** [comment]
@saravanakumarangamuthu I am not sure of that. but check the configmap that is created in kube-system namespace via the terraform

**Comment by vbasavani** [comment]
@saravanakumarangamuthu you can close this issue  here.

**Comment by saravanakumarangamuthu** [comment]
it is not working when we do the same via terraform module. terraform-aws-modules/terraform-aws-eks#534
