### ISSUE TITLE
CSRs are in PENDING state for the nodes added during scale up

### ISSUE THREAD

**Issue by shray-chadha** [awslabs/amazon-eks-ami#344]
**What happened**:
CSRs generated for the newly added Nodes during a scale up are in PENDING state.

We've created an EKS cluster using *eksctl* utility. When a Node is added to a nodegroup either during a scale-up operation using Cluster Autoscalar or via changing the ASG size manually, the CSRs generated for these nodes are in PENDING state.

The *REQUESTOR* of these CSRs is an IAM role of the node instead of the expected  **system:node:{{EC2 DNS HOSTNAME}}**
```
Name:               csr-sjvjg
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Wed, 11 Sep 2019 07:31:11 -0400
Requesting User:    arn:aws:iam::XXXXXXXXXXXXXXX:role/my-test-role
Status:             Pending
Subject:
  Common Name:    system:node:ip-172-XX-X-XX.us-west-2.compute.internal
  Serial Number:
  Organization:   system:nodes
Subject Alternative Names:
         DNS Names:     ip-172-XX-X-XX.us-west-2.compute.internal
         IP Addresses:  172.XX.X.XX
                        18.XXX.XX.XXX
Events:  <none>
```
After manually approving these CSRs, **kubectl logs/exec** command threw error that the certificate doesn't contain any IP SANs.
```
Error from server: Get https://172.XXX.X.XX:10250/containerLogs/kube-system/container-name: x509: cannot validate certificate for 172.XXX.X.XX because it doesn't contain any IP SANs
```
I checked the certificate generated for the Nodes, and found out it has missing requests SANs

**What you expected to happen**:

The CSRs generated for the Nodes added in the nodegroup after a scale up shall be automatically approved & the corresponding certificates generated should have the requests SANs.

**How to reproduce it (as minimally and precisely as possible)**:

When the Nodegroup is scaled up by Cluster Autoscalar and nodes are added.
or
Add Nodes to a nodegroup by manually changing the size of the ASG 

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): c5.large
- EKS Platform version: eks.1
- Kubernetes version: 1.14.6
- AMI Version: ami-038a987c6425a84ad
- Cluster Autoscalar Version: 1.14.5

```
```

**Comment by M00nF1sh** [comment]
where is these ip addresses came from? like 18.XXX.XX.XXX?
Our server-side certificate signer currently will sign certificate, but it won't put SAN for these ip/host that it cannot verify into the certificate. 
It uses EC2's describeInstance to check whether the domain/ip is provided by EC2(e.g. default ones or via custom vpc DHCP settings).

Also, kubelet will keep retrying creating new CSRs if the SAN doesn't match what it expected. 

A couple of scenario cause this, mostly due to user overrided the ec2 hostname to some custom name.

**Comment by GustavoAdrianGimenez** [comment]
Hi @shray-chadha, any news about this? we are facing the same problem with the pending csr.

Thanks!

**Comment by raunyoliveira-hotmart** [comment]
Hello there,

We are facing the same problem, any update on this? @M00nF1sh
