### ISSUE TITLE
[EKS Windows]: Bootstrap argument not working in Windows nodes

### ISSUE THREAD

**Issue by frejonb** [awslabs/amazon-eks-ami#348]
**What happened**:
I'm following the official documentation for Windows nodes on EKS. When deploying the windows nodes I follow https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html

and set `AssociatePublicIpAddress: 'false'` for the image `/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-EKS_Optimized-1.14/image_id`

If I don't set any bootstrap parameters, I can see the new Windows nodes by running `kubectl get node`.

However, I need to add the following kubelet args to the bootstrap script:
```
--kubelet-extra-args '--register-with-taints os=Win1809:NoSchedule'
```

The result is that `kubectl get node` does not show the windows nodes at all.

**What you expected to happen**:
`kubectl get node` to show windows nodes and with the expected taint

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu west 1
- Instance Type(s): t2.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
"eks.1"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
"1.14"
- AMI Version:
ami-082eddfe14aefde9e
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by johnjeffers** [comment]
Same problem here. I had to remove the `--kubelet-extra-args` flag to get the node to register.

I was attempting to pass the following:

```
--kubelet-extra-args '--node-labels=node-role.kubernetes.io/ondemand-windows-r5-large-green=true'
```

**Comment by somujay** [comment]
> '--register-with-taints os=Win1809:NoSchedule'



> **What happened**:
> I'm following the official documentation for Windows nodes on EKS. When deploying the windows nodes I follow https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html
> 
> and set `AssociatePublicIpAddress: 'false'` for the image `/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-EKS_Optimized-1.14/image_id`
> 
> If I don't set any bootstrap parameters, I can see the new Windows nodes by running `kubectl get node`.
> 
> However, I need to add the following kubelet args to the bootstrap script:
> 
> ```
> --kubelet-extra-args '--register-with-taints os=Win1809:NoSchedule'
> ```
> 
> The result is that `kubectl get node` does not show the windows nodes at all.
> 
> **What you expected to happen**:
> `kubectl get node` to show windows nodes and with the expected taint
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * AWS Region: eu west 1
> * Instance Type(s): t2.medium
> * EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
>   "eks.1"
> * Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
>   "1.14"
> * AMI Version:
>   ami-082eddfe14aefde9e
> * Kernel (e.g. `uname -a`):
> * Release information (run `cat /etc/eks/release` on a node):

Are you passing "--kubelet-extra-args" as well? Remove that and try. If you still face issues let us know.

**Comment by frejonb** [comment]
@somujay I'm setting this in the bootstrap arguments `--kubelet-extra-args '--register-with-taints os=Win1809:NoSchedule'`

**Comment by frejonb** [comment]
bump? This is a huge blocker since I can't taint my Windows nodes and Linux pods are scheduled there. Modifying all Linux manifests to require a Linux node would be too much work.

**Comment by somujay** [comment]
> bump? This is a huge blocker since I can't taint my Windows nodes and Linux pods are scheduled there. Modifying all Linux manifests to require a Linux node would be too much work.

Can you just add '--register-with-taints os=Win1809:NoSchedule' ? I will fix windows bootstrap to match with linux behavior.
