### ISSUE TITLE
Add support for m5n/m5dn/r5n/r5dn instance types

### ISSUE THREAD

**Issue by Jeffwan** [awslabs/amazon-eks-ami#355]
**What would you like to be added**:
r5dn instance types are not supported here.
https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

**Why is this needed**:
Unlock some use case need higher network throughput and high I/O operations.

**Comment by mmazek** [comment]
I was really disappointed when I found out today that I'm not able to use any of those instances with EKS... Is there any timeline for this change to be implemented?

**Comment by mogren** [comment]
Any recent AWS AMI and CNI will support these instance types. Be sure to use CNI v1.5.5 or later.
