### ISSUE TITLE
Makefile targets do not match release versions

### ISSUE THREAD

**Issue by tbp105** [awslabs/amazon-eks-ami#358]
the make targets do not match what is released

e.g.
"make 1.14"
 expands to 
"$(MAKE) k8s kubernetes_version=1.14.6 kubernetes_build_date=2019-08-22" 
But the current release version appears to have been built as
"$(MAKE) k8s kubernetes_version=1.14.7 kubernetes_build_date=2019-09-27"

It is impossible (from this repo) to know how to reproduce the actual release since the official images do not use the targets in the makefile.

**Comment by M00nF1sh** [comment]
we’ll release the binaries we internal use soon.

**Comment by M00nF1sh** [comment]
The binaries is released as below:
* amazon-eks/1.14.7/2019-09-27
* amazon-eks/1.13.11/2019-09-27
* amazon-eks/1.12.10/2019-09-27
* amazon-eks/1.11.10/2019-09-27
We'll add some automation in our AMI release pipeline for these node-side binaries too.
