### ISSUE TITLE
Completely Fair Scheduler?

### ISSUE THREAD

**Issue by stateisbad** [awslabs/amazon-eks-ami#360]
Maybe someone on here can clear this up for my team and I. Some people at my place of employment are under the assumption that the Amazon Linux EKS AMIs do not use the completely fair scheduler (CFS). Can anyone confirm if it is the default scheduler for these AMIs, and if not, what scheduler is used?  Thanks!

**Comment by kinghajj** [comment]
Unlike the I/O scheduler, the standard Linux codebase supports only CFS for the process scheduler; alternatives, like BFS, need to be patched in separately. Considering [Amazon employees are working to improve CFS](https://lwn.net/Articles/764461/), I don't think they're using another scheduler for their Linux distribution.

**Comment by br00tal** [comment]
Yeah, that is my assumption, too. You'd basically have to intentionally not use it, which seems highly unlikely and like something that would be noted pretty obviously.

**Comment by cartermckinnon** [comment]
This AMI utilizes the standard Linux process scheduler.
