### ISSUE TITLE
Specify DNS_CLUSTER_IP via bootstrap.sh

### ISSUE THREAD

**Issue by nickdgriffin** [awslabs/amazon-eks-ami#369]
**What would you like to be added**:
I'd like it to be possible to customise the DNS_CLUSTER_IP value that is put into the kubelet configuration, as the `--cluster-dns` option for the kubelet has been deprecated.

**Why is this needed**:
This is required when adding a node local DNS cache (https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/).

**Comment by whereisaaron** [comment]
Hi @nickdgriffin, this might not be helpful if you are relying on the generic bootstrap process, but if you are using [`eksctl`](https://eksctl.io/) to deploy these AMI then there is a `ClusterDNS` setting available.

https://eksctl.io/usage/vpc-networking/#custom-cluster-dns-address
https://eksctl.io/usage/customizing-the-kubelet/

**Comment by nickdgriffin** [comment]
@whereisaaron I'm not using eksctl, but thanks for mentioning it anyway.
