### ISSUE TITLE
Is it possible to have an EKS worker node also be a NAT instance?

### ISSUE THREAD

**Issue by drewhemm** [awslabs/amazon-eks-ami#370]
```
**Environment**:
- AWS Region: N/A
- Instance Type(s): c5n.9xlarge and larger
- EKS Platform version: eks.4, but question would apply to any version
- Kubernetes version: 1.12
```

Would it be possible to use an EC2 instance as both a NAT instance and also EKS worker node? I'm looking at setting up NAT instances in certain subnets for a particular use case and I would want to run a number of tools on them such as Prometheus Node Exporter and Filebeat. Rather than baking these into the NAT Instance AMI, I wondered about whether I could build an AMI that has the NAT configuration and would also register as a worker node with EKS. I could then taint the node so that only essential daemonsets would ran on it.

**Comment by M00nF1sh** [comment]
Hi there,
This isn't any restrictions to forbid u to use it as an NAT instance, however, you'll need to setup rules for the eth0 yourself :D
