### ISSUE TITLE
EKS --use-max-pods=false not working

### ISSUE THREAD

**Issue by tomkivlin** [awslabs/amazon-eks-ami#374]
**What happened**:
I am using a CF template to manage EKS Node Groups. When I pass --use-max-pods=false into the BootstrapArguments parameter, it appears to be ignored by the bootstrap.sh script, or some other component as there is still a limit being applied to each node.

**What you expected to happen**:
The "allocatable" and "capacity" values for "pods" will not be set for the nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Pass `--use-max-pods=false` into the BootstrapArguments parameter of a CF template for the NodeGroup.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west3
- Instance Type(s): have tried with t3.small and t3.micro and same result for both
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.3"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.13"
- AMI Version: amazon-eks-node-1.13-v20190614 (ami-051015c2c2b73aaea)
- Kernel (e.g. `uname -a`): (I don't have access to the nodes)
- Release information (run `cat /etc/eks/release` on a node): (I don't have access to the nodes)

**Comment by tomkivlin** [comment]
I have also tried "--use-max-pods false" as the input parameter too, same result.

**Comment by chennhsu** [comment]
It took me a whole day to solve this and turns out the ```MAX_PODS``` was set in ```/etc/eksctl/kubelet.local.env```
So if you have ssh access to the instance, just modify it to the number you want then ```sudo service kubelet restart```

**Comment by tomkivlin** [comment]
> It took me a whole day to solve this and turns out the `MAX_PODS` was set in `/etc/eksctl/kubelet.local.env`
> So if you have ssh access to the instance, just modify it to the number you want then `sudo service kubelet restart`

Thanks @chennhsu - I'll give that a go.  However, does this suggest that there is a problem with the bootstrap script, or with the way I've passed the argument to the script as part of my CF template?

**Comment by chennhsu** [comment]
@tomkivlin I just tried to create a new unmanaged node group and pass bootstrap argument to it. It works fine.
So I think the problem is that you cannot pass arguments to a EKS managed node group.

**Comment by tomkivlin** [comment]
@chennhsu I'm not using a managed node group.  For clarity I am using a CF template that has been adapted from the defaults provided in the Getting Started guide.  Here are some relevant snippets:

```
...
  BootstrapArguments:
    Description: Arguments to pass to the bootstrap script. See files/bootstrap.sh in https://github.com/awslabs/amazon-eks-ami
    Type: String
    Default: ""
...
  NodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: NodeInstanceProfile
    Properties:
      LaunchTemplateData:
        ...
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              set -o xtrace
              /etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}
              /opt/aws/bin/cfn-signal --exit-code $? \
                       --stack  ${AWS::StackName} \
                       --resource NodeGroup  \
                       --region ${AWS::Region}
```

Perhaps there is something wrong with my CF template?

**Comment by tomkivlin** [comment]
@chennhsu can you share how you passed the arguments please?

**Comment by chennhsu** [comment]
@tomkivlin I created the node group by following this guide: [https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html](url)
In the parameter section just put ```--use-max-pods false``` in there and it works.
For your case I think you can modify the parameter in CF console but I am not sure.

Have you switch the CNI plugin to weave net or flannel btw? That cloud be limit the max pod numbers either.

**Comment by tomkivlin** [comment]
Ok thanks. I'll give it a go and feedback here.

**Comment by tomiszili** [comment]
I wrote this `--use-max-pods false` parameter into the CFN file, and the worker node (t3.medium) couldn't allocate more than 17 pods. This was my test k8s deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 50
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        -
          image: tutum/hello-world
          name: hello-world
          ports:
            -
              containerPort: 8080
```
This was the error i got from the ContainerCreating pods:
``` 
Warning  FailedCreatePodSandBox  43s                kubelet, ip-10-0-18-246.eu-central-1.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e19318211c5a5d35bfd554aaa35568b8a14c6c33de78321dc8e6a7a9e9c66977" network for pod "hello-world-deployment-66b8c9c96b-m7njz": NetworkPlugin cni failed to set up pod "hello-world-deployment-66b8c9c96b-m7njz_default" network: add cmd: failed to assign an IP address to container
```

Any solution for this issue?
thanks

**Comment by tomkivlin** [comment]
@tomiszili that looks more to be a CNI error. What's the output of `kubectl get nodes -o yaml | grep pods` for you?

@chennhsu I have tried with `--use-max-pods false` in the CF template and it's working.  Previously I had tried `"--use-max-pods false"` and `--use-max-pods=false` neither of which worked. Thanks for the pointers.

**Comment by tomiszili** [comment]
@tomkivlin i got
```
kubectl get nodes -o yaml | grep pods
      pods: "110"
      pods: "110"
```
for the `kubectl get nodes -o yaml | grep pods` command.

**Comment by tomkivlin** [comment]
@tomiszili in that case the `--use-max-pods` flag is working, you'd get way smaller figures if it wasn't. I will close this now as my initial issue was resolved thanks to @chennhsu.

**Comment by tomiszili** [comment]
@tomkivlin good to hear that the --use-max-pods option works properly. Do you have any suggestion how to fix the CNI error, i'm using the default one?

**Comment by tomkivlin** [comment]
@tomiszili only thing I can think of is maybe you have run into an ENI limit in your account or some other bug in the VPC CNI plugin. I think it would be worth raising as an Issue in that repo, as they will have troubleshooting tips I would think: https://github.com/aws/amazon-vpc-cni-k8s

**Comment by tomkivlin** [comment]
@tomiszili oddly I happened upon this very same error today. Some searching led me to find that each instance size also has a limit on the number of ENIs and IP addresses - I was hitting that and so had to use a larger instance size as I couldn't see how to over-ride like we can for pod count.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

**Comment by chennhsu** [comment]
@tomkivlin @tomiszili You have to change the EKS CNI plugin before you set new pod limit.
The pod limit is actually the ENIs and IP addresses limit of the EC2 instance, because the default VPC CNI plugin will assign a secondary IP to each pod. That is where the pod limit comes from.
So remove the default CNI plugin and use Weave Net or Flannel instead.
