### ISSUE TITLE
EKS bootstrap script setting wrong value for Max Pods in kubelet for CNI Custom Networking

### ISSUE THREAD

**Issue by smrutiranjantripathy** [awslabs/amazon-eks-ami#375]
**What happened**:
When we use Custom CNI. The number of interfaces available reduces to N-1 
and accordingly the maximum ips available for pods changes. But currently when we use 
Custom CNI , it still configures the kubelet with the same maximum pods as in this file
https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
eg: For a T3 medium with 3 interfaces and 6 ips per interface.
The maximum pods turn out to be (3*6-3) + 2( aws-node and kube-proxy)=17
For the same node in custom cni the maximum number of pods would be 12 (2*6-2)+2 ( aws-node and kube-proxy)

**What you expected to happen**:
It should configure the max pods to a different number.

**How to reproduce it (as minimally and precisely as possible)**:
Configure Custom CNI  for EKS cluster and check the max pods setting on the kubelet.

**Anything else we need to know?**:
This is causing an issue as the pods get scheduled on node even if there is not sufficient Ip 
 and get stuck in container creating on the node.

The pods get scheduled to node as the controller is not aware of the maximum number of ips.
https://github.com/aws/amazon-vpc-cni-k8s/issues/18
https://github.com/kubernetes/kubernetes/issues/5507

The only way to stop the pod from getting scheduled is with max pods ip setting.
I would suggest to use a separate file for max pods rather than the same file for configuring max pods based on some environment variable.

**Environment**:
- AWS Region: N/A
- Instance Type(s): N/A
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): N/A
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version: N/A
- Kernel (e.g. `uname -a`): N/A
- Release information (run `cat /etc/eks/release` on a node): N/A

```
```

**Comment by mogren** [comment]
We need better documentation on how to work around this issue. Tracked in https://github.com/awsdocs/amazon-eks-user-guide/pull/72

Also related to https://github.com/aws/amazon-vpc-cni-k8s/issues/527
