### ISSUE TITLE
Too old version of iptables

### ISSUE THREAD

**Issue by mogren** [awslabs/amazon-eks-ami#380]
In order to support `--random-fully` we need at least iptables-1.6.2. The latest Amazon Linux 2 supports 1.8.2. We need to update to that version and configure legacy mode in order for things to work well with Kubernetes. 

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by sbkg0002** [comment]
We experience the issues described in https://github.com/aws/amazon-vpc-cni-k8s/issues/516 and need iptables to be >=1.6.2.

**Comment by mogren** [comment]
Latest images have v1.8.2

**Comment by terrych0u** [comment]
I got the same issue on the newest eks 1.16 with CNI 1.6.1 and my kube-proxy 1.16.8 keeps show log :

```Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it```

is there any way to fix it?

**Comment by gregops** [comment]
Still an issue with 1.16.8 and worker AMIs 1.16.8-20200507. Seeing the same message.

**Comment by pdeva** [comment]
we are seeing the same issue on eks 1.16.8. 
```
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
```
please provide some workaround

**Comment by ishaannarang** [comment]
@pdeva update to 1.16.12

**Comment by pierluigilenoci** [comment]
I get this error in EKS with the latest AMI v20201007 v1.18
