### ISSUE TITLE
bootstrap.sh waits up to 20 min for a cluster to be ready and fails

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/amazon-eks-ami#386]
**What happened**: upgraded EKS cluster from 1.13 to 1.14. Cloudformation stack consits of EKS cluster and associated ASG with UpdatePolicy set to AutoScalingRollingUpdate. I updated ami version in launch config and rolling update was initiated by the time EKS was updating kubernetes software version. 
https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L236 fast fails due to set -o options after 20 min. I took more than 20min for my cluster to update.

**What you expected to happen**:
bootstrap waits until EKS is ready.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade EKS from 1.13 to 1.14. Fleet already running bootstrap.sh and waiting for the cluster to be available

**Anything else we need to know?**:

**Environment**:
- AWS Region: all
- Instance Type(s): all
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.6
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.14
- AMI Version: amazon-eks-node-1.14-v20191213 (ami-087a82f6b78a07557)
- Kernel (e.g. `uname -a`): all
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by mogren** [comment]
@lkoniecz Sorry for the late reply. Is this still happening? Has it happened on other clusters? An update should not get stuck for 20 minutes, so there must have been some underlying issue. For example, we have seen cases before where there were no more ENIs available in the account and we were unable to create new cross-account ENIs, preventing the new masters from coming up.

**Comment by lkoniecz** [comment]
@mogren 
I dont know as I applied my own fix.

**Comment by lkoniecz** [comment]
@mogren 
Just an aside not - the upgrade eventually finished, but nodes were left damaged without eks agent installed. All software uprages performen on eu-west-1 region were taking more than 15 minutes. 
Closing it won't fix the problem, but it's your call I guess.

**Comment by mogren** [comment]
@lkoniecz I can see that there is a problem, but I don't think the issue is in the EKS AMI, that's why I closed it. The slow update is a control plane issue and the way to handle delays in other services is better tracked in the related CDK issue you opened at https://github.com/aws/aws-cdk/issues/5477.
