### ISSUE TITLE
Is it possible to retrieve the cluster name on the EKS node/pod without having to pass this as an environment variable to the configuration

### ISSUE THREAD

**Issue by SurbhiAggarwal04** [awslabs/amazon-eks-ami#394]
Is it possible to retrieve the cluster name on the EKS node/pod without having to pass this as an environment variable to the configuration?

**Comment by mogren** [comment]
@SurbhiAggarwal04 Depends on how you created the cluster. `eksctl` for example will label the nodes with `alpha.eksctl.io/cluster-name=<your-cluster-name>`, and EKS will tag your EC2 instances with `kubernetes.io/cluster/<your-cluster-name>` as the key.
