### ISSUE TITLE
Is iptables-save necessary ?

### ISSUE THREAD

**Issue by KV995** [awslabs/amazon-eks-ami#399]
Hi, 

I was wondering there is a absolute need of the [iptables-save](https://github.com/awslabs/amazon-eks-ami/blob/master/install-worker.sh#L97) service? I am using a base AMI that is not Amazon linux eks optimized based and we'd like to know if there might be issue to disable the saving of existing rules for iptables ?

I understand kube-proxy is adding k8s compliant rules for the cluster to work, but some of the existing rules in my base AMI (RHEL images) are having rules that drops all incoming flows from anywhere.

Thanks.

**Comment by mogren** [comment]
@KV995 Just make sure to allow forwarding in your custom AMI:

https://github.com/awslabs/amazon-eks-ami/blob/128a7149b6b50f0392d9a6951e24bd30f19f8e2a/files/kubelet.service#L8

If not, allowed networking won't work correctly. See https://github.com/aws/amazon-vpc-cni-k8s/issues/619 for example.
