### ISSUE TITLE
Docker install fails on default packer script

### ISSUE THREAD

**Issue by mbartsch** [awslabs/amazon-eks-ami#4]
the packer script fails as the way to install docker in amazon linux 2 has changed.

if you the script as it is now , you get the following error, i have put a pr #2 to fix this, also introduce nfs utils, if you want I can remove that PR and create a new one only with the change to the installer.

```
    amazon-ebs: Complete!
    amazon-ebs: Loaded plugins: priorities, update-motd
    amazon-ebs: No package docker available.
    amazon-ebs: Error: Nothing to do
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
make: *** [ami] Error 1
```

**Comment by jhaynes** [comment]
This is related to https://github.com/awslabs/amazon-eks-ami/issues/7. In the LTS AMI, the Docker [extra](https://aws.amazon.com/amazon-linux-2/faqs/#Amazon_Linux_Extras) is enabled by default. In the LTS Candidate AMI, a version of Docker was available in the core repositories.

**Comment by micahhausler** [comment]
This was written just before the official release of AL2, so we'll get this fixed

**Comment by mbartsch** [comment]
@micahhausler , the pull request #2 address this issue.
