### ISSUE TITLE
Actual worker nodes AMI has version mismatch with EKS master version

### ISSUE THREAD

**Issue by excavador** [awslabs/amazon-eks-ami#409]
**What happened**:

prometheus is generating of alerts "different semantic versions of Kubernetes components running"
```
[FIRING] KubeVersionMismatch
[page] There are 2 different semantic versions of Kubernetes components running.
```
- Our EKS master is `eks.6`, it has kubernetes version `1.14.9`
- Latest EKS optimized AMI for eu-west-1 is `amazon-eks-node-1.14-v20191213` - `ami-0b9d2c11b47bd8264`, it has kubernetes version `1.14.8`.

**What you expected to happen**:

EKS optimized AMI should have version upper than kubernetes master.

**Comment by max-rocket-internet** [comment]
I think that's fine: https://kubernetes.io/docs/setup/release/version-skew-policy/

**Comment by mogren** [comment]
Yes, this is fine. The worker nodes can be up to two versions behind the masters.
