### ISSUE TITLE
Tag repo on release

### ISSUE THREAD

**Issue by ewbankkit** [awslabs/amazon-eks-ami#41]
Could you please tag this repository on releases of new AMI versions?
I'm downloading content from the `files` directory to build my own images and would like to have repeatable builds.

Thanks.

**Comment by max-rocket-internet** [comment]
Already requested here: https://github.com/awslabs/amazon-eks-ami/issues/21

I am 1000% for this.

I know there are release notes posted somewhere on the AWS site but many of us are used to watching and getting info from Github repos, it's already part of the work flow. So having a tagged releases here would be amazing.

**Comment by micahhausler** [comment]
Added tags for builds
