### ISSUE TITLE
Bootstrapping: Pass instance tags as node labels

### ISSUE THREAD

**Issue by palsivertsen** [awslabs/amazon-eks-ami#410]
**What would you like to be added**:
Bootstrap script should look for tags matching a prefix, e.g. `eks/node/label/*`, on the current ec2 instance and pass the tag as a node label using the `--node-labels` flag when starting `kubelet` service.

**Why is this needed**:
This would allow label configuration on an Auto Scaling Groups level sharing a single Launch Template.

**Use case**:
We want to launch k8s nodes in a public and a private subnet, and we want to label nodes `network/zone=public` or `network/zone=private`.

**Without automatic labeling**:
* Create "public" Launch Template and pass `--kubelet-extra-args --node-labels=network/zone=public`
* Create "private" Launch Template and pass `--kubelet-extra-args --node-labels=network/zone=private`
* Create ASG using "public" Launch Template
* Create ASG using "private" Launch Template

To update i.e. AMI one would have to remember to update both Launch Templates

**With automatic labeling**:
* Create Launch Template
* Create ASG and add instance tag `eks/node/label/network/zone=public`
* Create ASG and add instance tag `eks/node/label/network/zone=private`

In this scenario the Launch Template is used for node wide config/setup and the ASGs for group specific settings/config.

**Comment by Avik1993** [comment]
Was thinking on same lines, when came across this ticket. This should help great deal!

**Comment by cartermckinnon** [comment]
I think this could be handy; but I think it should be implemented in https://github.com/kubernetes/cloud-provider-aws, because it's similar to the responsibilities of the tagging and node controllers.
