### ISSUE TITLE
Non-Bash Bootstrap script

### ISSUE THREAD

**Issue by errm** [awslabs/amazon-eks-ami#415]
I created and currently maintain an alternative node bootstrap script written in go, with extensive unit tests.

https://github.com/errm/ekstrap

In my current work we are thinking about switching from a custom built AMI to the official AWS ones.

**What would you like to be added**:

If it would be useful, I am happy to donate / help integrate some or all of my work with the official AMI.

**Why is this needed**:

* I noticed some discussion around more complex features that are implemented in the bash bootstrap script e.g. #367 that these might be better implemented in a general purpose language with better testing facilities > https://github.com/awslabs/amazon-eks-ami/pull/367#issuecomment-564767794 ... cc @leakingtapan 
* A general purpose language like go has a lot of facilities that would make the bootstrap more maintainable (like proper templating, cleaner logic, and testing)

**Comment by frimik** [comment]
Not sure. I think both :+1: and :-1: on this. :+1: for tests and whatnot. But :-1: for *more* hidden magic in a "bootstrap" script where maybe you could even argue you should have less.

Perhaps instead increase the documentation options around convincing kubelets (and other services) via "regular" user-data modifications (which *could* involve using various contributed bootstrap "helpers" if operator so chooses).

**Comment by errm** [comment]
> Perhaps instead increase the documentation options around convincing kubelets (and other services) via "regular" user-data modifications (which could involve using various contributed bootstrap "helpers" if operator so chooses).

Interesting idea ... but I am not sure that Kubelet should really do anything extra....

I think having some sort of bootstrap is kindof inevitable, unless you bake a node image for every new cluster.

This approach seems a fairly common way of configuring nodes ... e.g. https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/

**Comment by cartermckinnon** [comment]
This is a cool project! We have had recent discussions around a v2 bootstrap implementation in something other than bash. Bash has served us well given the nature of the problem, but your points stand. I can't provide an ETA on when or if such a rewrite will happen; but we're on the same page 😄 .
