### ISSUE TITLE
Are we still creating releases?

### ISSUE THREAD

**Issue by heydonovan** [awslabs/amazon-eks-ami#422]
The last one was on `Dec 16, 2019`. What's the plan going forward? :)

**Comment by M00nF1sh** [comment]
Hey dude, sorry for the delay. 
[v20200122](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20200122) just out. You can see it's stuck in our pipeline for a month =.=..
We'll have a another more updated one come out pretty soon. (with 1 week or 2)

**Comment by mogren** [comment]
We are, and we are working to improve the process. New releases will be on the way!
