### ISSUE TITLE
Publish AMI Version in SSM Parameters

### ISSUE THREAD

**Issue by bflad** [awslabs/amazon-eks-ami#423]
**What would you like to be added**:

Add an "AMI Version" SSM Parameter, e.g.

```
Name: /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/ami_version
Type: String
Value: 1.14.9-20200122
```

**Why is this needed**:

The [EKS `CreateNodeGroup` API call accepts a parameter named `releaseVersion`](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-releaseVersion) which needs to match the published "AMI Version" names on the [Amazon EKS-Optimized Linux AMI Versions documentation page](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html). e.g. `1.14.8-20191213`

The SSM Parameters published by the release pipeline do not seem to include this information currently:

```console
$ aws ssm get-parameters-by-path --path /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/
{
    "Parameters": [
        {
            "Name": "/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id",
            "Type": "String",
            "Value": "ami-08d5d1a25493f6a71",
            "Version": 6,
            "LastModifiedDate": "2020-02-25T16:00:58.946000-05:00",
            "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id"
        },
        {
            "Name": "/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_name",
            "Type": "String",
            "Value": "amazon-eks-node-1.14-v20200122",
            "Version": 6,
            "LastModifiedDate": "2020-02-25T16:00:58.984000-05:00",
            "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_name"
        },
        {
            "Name": "/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/schema_version",
            "Type": "String",
            "Value": "1",
            "Version": 6,
            "LastModifiedDate": "2020-02-25T16:00:58.912000-05:00",
            "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/schema_version"
        }
    ]
}
```

In the Terraform AWS Provider, we provide end-to-end testing for that parameter. This testing is currently hardcoded because there does not appear to be a lookup mechanism in SSM or the EKS API for an acceptable value:

https://github.com/terraform-providers/terraform-provider-aws/blob/2db63198564e911f320389268b8f46f53c9ca694/aws/resource_aws_eks_node_group_test.go#L271-L295

And after awhile the EKS API will complain about outdated values:

```
--- FAIL: TestAccAWSEksNodeGroup_ReleaseVersion (1225.88s)
    testing.go:654: Step 0 error: errors during apply:
        
        Error: error creating EKS Node Group (tf-acc-test-9113909416381506697:tf-acc-test-9113909416381506697): InvalidParameterException: Requested Node Group release version 1.14.7-20190927 is invalid. Allowed release version is 1.14.8-20191213
```

Having the SSM Parameter available seems like the easiest path, however we are really looking for any lookup mechanism. Operators would then be able to use changes in this value to automatically trigger EKS Node Group upgrades.

Thanks!

**Additional References**:

- Similar ask for full Kubernetes version in SSM: https://github.com/awslabs/amazon-eks-ami/issues/339
- Containers roadmap ask for Describe API call (since there is a delay between releases and API accepted values): https://github.com/aws/containers-roadmap/issues/771
- Terraform AWS Provider testing manual update example: https://github.com/terraform-providers/terraform-provider-aws/pull/12172

**Comment by mikestef9** [comment]
This has been added. Ex

aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/release_version

**Comment by bflad** [comment]
@mikestef9 Awesome! I'll double check this shortly. 😄
