### ISSUE TITLE
kubernetes_version=1.14.6 vesion in v20200122 release

### ISSUE THREAD

**Issue by awsant** [awslabs/amazon-eks-ami#426]
**What happened**:
According to https://github.com/awslabs/amazon-eks-ami/releases/tag/v20200122
"Bumped kubelet version to match newer available EKS CP version.    1.14.9"

**What you expected to happen**:
to have 1.14.9 version in https://github.com/awslabs/amazon-eks-ami/blob/v20200122/Makefile#L54
as it done in master branch https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L50

**Comment by aissarmurad** [comment]
I'm facing the same issue with v20200507

**What happened:**
The Makefile doesn't contain instructions to build version 1.16

https://github.com/awslabs/amazon-eks-ami/blob/v20200507/Makefile

Commit tagged with `v20200507`
https://github.com/awslabs/amazon-eks-ami/commit/7d4aae8b6787ecfe36ecc0bc45f8118de1dde370

But master branch has it
https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L60

**What you expected to happen:**

The latest tag needs contain changes announced in release notes.
ex: change in the Makefile to build 1.16 version

* amazon-eks-node-1.16-v20200507
* amazon-eks-gpu-node-1.16-v20200507
* amazon-eks-arm64-node-1.16-v20200507 (Preview)

**Comment by ravisinha0506** [comment]
The [Makefile](https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L60) is updated to build latest version i.e; 1.21. Closing this issue. Please feel free to re-open if there are any concerns.
