### ISSUE TITLE
Moving kubelet binary for version 1.15.10 broke release v20200312

### ISSUE THREAD

**Issue by mnejat** [awslabs/amazon-eks-ami#434]
**What happened**:
Baking AMI for k8s version 1.15.10 using release v20200312 fails due to nonexistant kublet binary at https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/**2020-02-14**/bin/linux/amd64/kubelet
kubelet binary has been moved to https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/**2020-02-22**/bin/linux/amd64/kubelet folder
**What you expected to happen**:
install-worker.sh to be able to fetch the binary given right path vi variable declaration kubernetes_build_date in Makefile
**How to reproduce it (as minimally and precisely as possible)**:
Try to build k8s 1.15.10 using latest release  v20200312
**Anything else we need to know?**:
Branch master has been updated, but no new release has been created. 
**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by rtripat** [comment]
Taking a look

**Comment by jqmichael** [comment]
2020-02-14 was checked in incorrectly and was quickly fixed to 2020-02-22 in https://github.com/awslabs/amazon-eks-ami/commit/729dcb5f6dee3428e17c10b46c573c11802e4002. 

Please ensure you use the latest commit in the repo. Please let us know if you still have problem downloading the binary.

**Comment by mnejat** [comment]
Thanks for the follow-up. Will you be creating a new release with this fix since latest release (https://github.com/awslabs/amazon-eks-ami/blob/v20200312) is still broken

**Comment by heybronson** [comment]
The latest release (v20200507) has the correct binaries for it's release at  https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/
