### ISSUE TITLE
Unable to create a Nodegroup on EKS with an old release version 

### ISSUE THREAD

**Issue by dimara** [awslabs/amazon-eks-ami#435]
**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): m5.4xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.9
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.14

I am not sure if this the right place to raise this issue, but I tried to create a Nodegroup with a previous AMI version and failed:
```
aws eks create-nodegroup \
       --cluster-name $CLUSTERNAME \
       --nodegroup-name general-workers \
       --disk-size 200 \
       --scaling-config minSize=1,maxSize=3,desiredSize=3 \
       --subnets $SUBNETIDS  \
       --instance-types m5.4xlarge \
       --ami-type AL2_x86_64 \
       --node-role arn:aws:iam::$ACCOUNT:role/eksWorkerNodeRole \
       --labels role=general-worker \
       --tags kubernetes.io/cluster/$CLUSTERNAME=owned  \
       --release-version 1.14.8-20191213 \
       --kubernetes-version 1.14
An error occurred (InvalidParameterException) when calling the CreateNodegroup operation: Requested Nodegroup release version 1.14.8-20191213 is invalid. Allowed release version is 1.14.9-20200228
```
Is creating a Nodegroup with non-default AMI release version not possible? If so, this breaks
any reproducibility. For example if we want to test stuff against a specific kernel version, this is not possible once EKS adopts a new release version.

**Comment by rtripat** [comment]
Taking a look

**Comment by rtripat** [comment]
This is expected behavior in EKS Managed Nodegroup. We are evaluating allowing customer's to create a Nodegroup using all supported release versions.

**Comment by dimara** [comment]
@rtripat Thanks for looking into this!
We'd definitely like to see this feature because it is more that useful (if not necessary) for being able to have reproducible infrastructure. Do you have a timeframe for when this feature will be supported for EKS Managed Nodegroups?

**Comment by rtripat** [comment]
We are tracking this in our roadmap! I'm not able to provide a timeline right now but please follow that issue for updates and provide feedback

https://github.com/aws/containers-roadmap/issues/810
