### ISSUE TITLE
Setup CI for amazon-eks-ami project

### ISSUE THREAD

**Issue by Jeffwan** [awslabs/amazon-eks-ami#438]
**What would you like to be added**:
Setup CI to build AMI against all presubmit changes. 
Also consider to build nightly AMI for user to use. 

**Why is this needed**:
Currently, there's no CI setup and build AMI against PR changes. Some bad changes maybe merged into code base. It would be great to have a CI to protect the repo.

**Comment by cartermckinnon** [comment]
The team discussed this recently--it's something we're very interested in, but isn't currently scheduled. We'll keep you updated!

**Comment by bryantbiggs** [comment]
I believe this is also resolved @cartermckinnon
