### ISSUE TITLE
Ask for AMI release

### ISSUE THREAD

**Issue by regulusv** [awslabs/amazon-eks-ami#449]
The [commit](https://github.com/awslabs/amazon-eks-ami/commit/09a8fbe729c3694d000a309cda2a3873e43e77b8) adds inf1 instance support, there is release for new AMIs required to have the inf1 instance supported.

**Comment by mogren** [comment]
Released back in [v20200423](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20200423)
