### ISSUE TITLE
eks-log-collector script does not refer symbolic links while copying log files

### ISSUE THREAD

**Issue by balaji603** [awslabs/amazon-eks-ami#455]
**What happened**:
eks-log-collector Linux script is not copying log files from /var/log/pods directory.
Example: Consider kube-proxy and aws-node pod logs.
 
**What you expected to happen**:
Copy command includes (like -H) option to follow symbolic links also while copying the logs.

**How to reproduce it (as minimally and precisely as possible)**:
- Run the script as usual 
- Verify that contents of <.tar.gz>/var_log directory.
- It has just copied the symbolic link like below but does not copy the relevant files:
kube-proxy-45pk4_kube-system_kube-proxy-<>.log -> /var/log/pods/kube-system_kube-proxy-<>/kube-proxy/0.log

**Anything else we need to know?**:
NA

As the below details are not relevant I am not updating them. 
**Environment**:

- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by mogren** [comment]
Resolved in #475
