### ISSUE TITLE
Missing dns.yaml file in amazon-eks/cloudformation/2020-04-21

### ISSUE THREAD

**Issue by zacharyhumphrey27g** [awslabs/amazon-eks-ami#456]
What happened:
The dns.yaml file referenced here (https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) is missing in the latest set of yaml files in the s3 bucket.
This files does not exist: https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-04-21/dns.yaml

What you expected to happen:
Expect the file to exist.
![image](https://user-images.githubusercontent.com/61469686/80434916-b598a680-88c0-11ea-89db-1fe8b6d184fd.png)

How to reproduce it (as minimally and precisely as possible):
Check the s3 bucket.

Anything else we need to know?:
I assumed it was the same as the one found in 2020-03-23 so I am going to use that one for the time being.

**Comment by jqmichael** [comment]
Thanks for the report. This issue has been fixed. We are looking into how this happened in the first place and will add safe-guard on our side so it won't happen again.
