### ISSUE TITLE
Question on changing base AMI to Red Hat

### ISSUE THREAD

**Issue by nxf5025** [awslabs/amazon-eks-ami#46]
This is more of a question rather than an issue, but if we were to update the base AMI to Red Hat would:

A) EKS still function properly?
B) Be covered under AWS Enterprise support?

**Comment by micahhausler** [comment]
A) I don't honestly know. You'll have to try it.
B) I'm not sure, you'll have to ask your Enterprise support representative. I'm going to close this out, as this GitHub repository won't be the channel for supporting a different base AMI
