### ISSUE TITLE
m4.large has different pod limit than m3.large and m5.large

### ISSUE THREAD

**Issue by xaka** [awslabs/amazon-eks-ami#460]
According to https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt:

```
m1.large 29
m3.large 29
m4.large 20
m5.large 29
```

Is it a typo or m4.large is very special and cannot have as many pods as its predecessors?

**Comment by heybronson** [comment]
Thanks for asking. As per [AvailableIpPerENI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI) m4.large instances have a maximum of 2 ENIs and 10 IPv4 addresses per ENI. Using The function at the top of [eni-max-pods](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) (# of ENI * (# of IPv4 per ENI - 1)  + 2), m4.large instances can have a max of 20 pods.

**Comment by xaka** [comment]
Do you think there is chance it's a mistake on AvailableIpPerENI part? It looks very suspicious only m4.large is 20 while other ones (including much older) are all 29.
