### ISSUE TITLE
CNI binary download purpose and updates

### ISSUE THREAD

**Issue by cgswong** [awslabs/amazon-eks-ami#463]
What is the purpose of the CNI and CNI plugin binaries that are installed per [here](https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L176) please? Also, if their purpose is still relevant, why have they not been updated to reflect the latest version (which since v0.6.1 the plugin binaries are in a different repo with latest v0.8.5). In reviewing my EKS 1.14 cluster node I am not seeing a `/opt/cni/bin` directory.

**Comment by mogren** [comment]
Hi @cgswong, 

This is a relic from older times. All it does it to copy the binaries from containernetworking, like `loopback` and `cnitool` to the base image. They can be useful when testing networking stuff on a worker node. You should definitely have a `/opt/cni/bin` folder on your workers. If not, I assume you are using some custom worker node, or another CNI. Check `/etc/cni/net.d` to see what CNI config you have and where the binary it refers to is located.

The only CNI plugin that is actually used by the AWS VPC CNI, `portmap`, is [copied in by the CNI](https://github.com/aws/amazon-vpc-cni-k8s/blob/24878035114c447f8bafc7326f740a9edcbcb182/scripts/entrypoint.sh#L67) when it is starting up.

Also, I have a PR to use an init container for the CNI instead, to copy in the latest version of the plugins we need: https://github.com/aws/amazon-vpc-cni-k8s/pull/955

**Comment by cgswong** [comment]
Thanks for the informative response.
