### ISSUE TITLE
Support for IMDSv2

### ISSUE THREAD

**Issue by marcus-bynder** [awslabs/amazon-eks-ami#469]
**What would you like to be added**:
Bash script modified to support IMDSv2

**Why is this needed**:
SSRF attacks can use IMDS prior to v2 to expose IAM creds, etc.  It seems as though it will be commonplace soon to use IMDSv2 with security tokens, etc.  So updating the script to leverage IMDSv2 would be prudent, especially in environments where security policies mandate/enforce IMDSv2

**Comment by heybronson** [comment]
We're currently working on IMDSv2 support.
