### ISSUE TITLE
Upgrading to latest ami in ap-south-1 breaks all regional endpoint networking

### ISSUE THREAD

**Issue by rverma-jm** [awslabs/amazon-eks-ami#470]
**What happened**:
Immediately after upgrading to latest ami, all our services were started crashing with errors like 
```
Caused by: java.net.UnknownHostException: jm-audit-spinnaker.s3.ap-south-1.amazonaws.com
```
```
Caused by: java.net.UnknownHostException: ec2.ap-south-1.amazonaws.com
```
```
Caused by: java.net.UnknownHostException: redis.audit.internal
which points to jm-spinnaker-redis.k6r58l.ng.0001.aps1.cache.amazonaws.com
```

**What you expected to happen**:
Smooth migration

**How to reproduce it (as minimally and precisely as possible)**:
Try depoyling app using aws sdk

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-south-1
- Instance Type(s): m5a.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.16
- AMI Version: ami-054767c3238094200
- Kernel (e.g. `uname -a`): Linux ip-192-168-22-124.ap-south-1.compute.internal 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):
```
BASE_AMI_ID="ami-0ab1913ead3883bb5"
BUILD_TIME="Thu Apr 23 17:45:51 UTC 2020"
BUILD_KERNEL="4.14.173-137.229.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cb-salaikumar** [comment]
Is there any update on  this issue? We are facing similar situation as well.

**Comment by heybronson** [comment]
Taking a look at this. Is this also an issue with the latest releaseVersion (20200507)?

**Comment by ravisinha0506** [comment]
@rverma-jm Could you please verify if this issue still exists on the latest AMIs?
