### ISSUE TITLE
kubelet fails to start due to not being able to list instances

### ISSUE THREAD

**Issue by micsafi** [awslabs/amazon-eks-ami#472]
**What happened**:
While starting a worker node for EKS with eks-ami using the bootstrap.sh script, I am getting following error from the kubelet service:
```
May 13 13:24:09 ip-10-150-60-118 systemd: Starting Kubernetes Kubelet...
May 13 13:24:09 ip-10-150-60-118 systemd: Started Kubernetes Kubelet.
May 13 13:24:09 ip-10-150-60-118 systemd: Started Kubernetes systemd probe.
May 13 13:24:09 ip-10-150-60-118 systemd: Starting Kubernetes systemd probe.
May 13 13:24:09 ip-10-150-60-118 kubelet: I0513 13:24:09.765893    2517 server.go:425] Version: v1.15.11-eks-af3caf
May 13 13:24:09 ip-10-150-60-118 kubelet: W0513 13:24:09.766680    2517 plugins.go:118] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
May 13 13:24:09 ip-10-150-60-118 kubelet: I0513 13:24:09.766790    2517 aws.go:1209] Zone not specified in configuration file; querying AWS metadata service
May 13 13:24:09 ip-10-150-60-118 kubelet: I0513 13:24:09.768554    2517 aws.go:1243] Building AWS cloudprovider
May 13 13:24:09 ip-10-150-60-118 kubelet: F0513 13:24:09.770889    2517 server.go:273] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0bc529351d56be2fe: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""
May 13 13:24:09 ip-10-150-60-118 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
```

**What you expected to happen**:
I expected kubelet to start and register the instance as an worker node.

**How to reproduce it (as minimally and precisely as possible)**:
Launch worker node with similar configuration.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1 (Ireland)
- Instance Type(s): t3.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.15
- AMI Version: amazon-eks-node-1.15-v20200507
- Kernel (e.g. `uname -a`): ``Linux ip-10-150-60-118.eu-west-1.compute.internal 4.14.177-139.253.amzn2.x86_64 #1 SMP Wed Apr 29 09:56:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux``
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0ab1913ead3883bb5"
BUILD_TIME="Thu May  7 16:49:08 UTC 2020"
BUILD_KERNEL="4.14.177-139.253.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by heybronson** [comment]
Do you have an InstanceProfile attached to your node? The following Managed Policies need to be attached to your node:
- AmazonEKSWorkerNodePolicy
- AmazonEKS_CNI_Policy
- AmazonEC2ContainerRegistryReadOnly

You can find more information in the official [AWS EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html).

**Comment by micsafi** [comment]
Yes, these 3 policies are attached to the IAM role for the worker node. Initially they were missing, but I have added them since and re-launched the nodes multiple times with the issue still standing.

My next idea is to try a older version of the AMI to see whether that helps.

**Comment by heybronson** [comment]
Do you have the following tag on your nodes?
```
key: kubernetes.io/cluster/${clusterName}
value: owned
```
Kubelet will not be able to discover the instance if it does not have this tag.

**Comment by micsafi** [comment]
Yes, also the tags are in place. Both for the nodes as well as for the VPC/subnets.

**Comment by micsafi** [comment]
This issue can be closed. The problem has solved, the problem was with the IAM Role associated to the worker nodes. Even through the 3 mentioned policies were attached to the role, the role itself was allowed to be assumed by EC2 instance. This kind of role can be attached to a EC2 instance without any warnings, but it seems that any policies given by the role make no difference.
Fixing the role fixed also the kubelet.

**Comment by jontambi** [comment]
Hi @micsafi I am facing kind of same error on private worker nodes:
Mar 04 19:59:23 ip-10-1-30-189.mycorp.corp kubelet[4056]: F0304 19:59:23.617456    4056 server.go:265] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-017b926b2b66c48db: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post \\\"https://ec2.us-east-1.amazonaws.com/\\\": dial tcp: lookup ec2.us-east-1.amazonaws.com on 10.1.30.2:53: no such host\""

1. Have attached 3 Managed Policies mentioned before
2. Tag my worker nodes as kubernetes.io/cluster/${clusterName} owned
3. My cluster is a private EKS, deploying worker nodes on private network with NAT Gateway to reach Internet
4. I am able to reach any domain in the instace:
![image](https://user-images.githubusercontent.com/4682216/110028647-81bcb780-7d01-11eb-8d30-5b9f7e750211.png)
5. But not ec2.us-east-1.amazonaws.com
[root@ip-10-1-30-189 ~]# nslookup ec2.us-east-1.amazonaws.com
Server:         10.1.30.2
Address:        10.1.30.2#53

Non-authoritative answer:
*** Can't find ec2.us-east-1.amazonaws.com: No answer

6. I am able to reach that name only when I add nameserver 8.8.8.8 in /etc/resolv.conf and kubelet is able to reach the instance to initiate the process.

Any suggestion, and how I could solve it?

Thanks.

**Comment by ngocketit** [comment]
Same issue here. Have you @jontambi figured out the cause?

**Comment by ngocketit** [comment]
Ok so my issue was related to VPC endpoint security group and I got it fixed now

**Comment by andreyprezotto** [comment]
> Ok so my issue was related to VPC endpoint security group and I got it fixed now

@ngocketit do mind giving more details of how you fixed your VPC endpoint, please?

**Comment by andreyprezotto** [comment]
thanks @ngocketit !
