### ISSUE TITLE
M6g support

### ISSUE THREAD

**Issue by jayzalowitz** [awslabs/amazon-eks-ami#473]
**What would you like to be added**:
Support for the arm instances (m6g)

**Why is this needed**:
Generally, we can literally take cities off the electrical grid if we start leveraging this in some instances.
(https://itnext.io/building-an-arm-kubernetes-cluster-ef31032636f9)

**Comment by rtripat** [comment]
This is being tracked in [containers roadmap](https://github.com/aws/containers-roadmap/issues/264)
