### ISSUE TITLE
/var/log/messages keeps growing

### ISSUE THREAD

**Issue by DocX** [awslabs/amazon-eks-ami#477]
Hi. We have couple of nodes that keep growing their `/var/log/message` to the point it consumes almost the whole node and Kubernetes keeps failing to free space:

<img width="540" alt="Screenshot 2020-05-21 at 10 54 52" src="https://user-images.githubusercontent.com/132277/82550847-7841d480-9b5f-11ea-89d3-cf65edc08442.png">

I wonder is there logrotate configured for this log files? Should it be added to the AMI? Or can we somehow configure it ourselves?

Or is there another issue with that these files should not be growing that much?

Thank you

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): c5n.2xlarge
- EKS Platform version: eks.8
- Kubernetes version: 1.14
- AMI Version: amazon-eks-node-1.14-v20200312 (ami-0d373fa5015bc43be)
- Kernel (e.g. `uname -a`): `Linux ip-172-31-103-194.ec2.internal 4.14.171-136.231.amzn2.x86_64 #1 SMP Thu Feb 27 20:22:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):
```
BASE_AMI_ID="ami-0e50648bfc0a7d87a"
BUILD_TIME="Thu Mar 12 23:37:33 UTC 2020"
BUILD_KERNEL="4.14.171-136.231.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by heybronson** [comment]
I've opened https://github.com/awslabs/amazon-eks-ami/pull/479 to address this for future AMI releases. 

As an immediate fix for future log rotation on your nodes, you can uncomment `compress` in `/etc/logrotate.conf` on your node, and/or change the number of weeks of logs to keep in that same file.

**Comment by heybronson** [comment]
Addressed by https://github.com/awslabs/amazon-eks-ami/pull/479 for future AMI releases.
