### ISSUE TITLE
Fetch more instance metadata

### ISSUE THREAD

**Issue by mogren** [awslabs/amazon-eks-ami#480]
**What would you like to be added**:
A few more curl requests in the [`eks-log-collector.sh`](https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh#L190-L193) to fetch ENI and IP data as well. Data that would be helpful:
* `instance-type`
* everything under `network`

**Why is this needed**:
We have had multiple issues where an out-of-date IMDS has caused issues. This would help us rule out the local instance metadata being a problem. 

(Ping @nithu0115)

**Comment by nithu0115** [comment]
Working on this issue
