### ISSUE TITLE
Add ARM bare metal a1 and m6g instances

### ISSUE THREAD

**Issue by nucleusv** [awslabs/amazon-eks-ami#482]
**What would you like to be added**:
Please add support for nodegroups with a1.metal and m6g.metal instances

**Why is this needed**:
These instances are much cheaper

**Comment by heybronson** [comment]
Hello, ARM support can be tracked in our AWS containers roadmap: https://github.com/aws/containers-roadmap/issues/264

**Comment by mogren** [comment]
These instance types was added back in #378, but just recently added to the drop-down in #523 and will be in the next release.
