### ISSUE TITLE
container-selinux

### ISSUE THREAD

**Issue by spensireli** [awslabs/amazon-eks-ami#493]
**What happened**:
On latest version of AMI creation SELinux is no longer working. 

**What you expected to happen**:
SELinux to operate as previous versions have worked with SELinux enabled. It appears the package container-selinux is missing from the system and repos. 

**How to reproduce it (as minimally and precisely as possible)**:
Create worker nodes with SELinux in an enforcing state. I.e. seconfig

vi /etc/selinux/config

SELINUX=enforcing 
SELINUXTYPE=targeted

**Anything else we need to know?**:
Workaround:
```
sudo yum -y install selinux-policy-devel policycoreutils
cat << EOF > local_runc.te
module local_runc 1.0;
require {
type unlabeled_t;
type unconfined_service_t;
class key create;
}
allow unconfined_service_t unlabeled_t:key create;
EOF
make -f /usr/share/selinux/devel/Makefile local_runc.pp
sudo semodule -i local_runc.pp
```

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): m5.large
- EKS Platform version: eks.1
- Kubernetes version : 1.16
- AMI Version: amazon/amazon-eks-node-1.16-v20200507

**Comment by cartermckinnon** [comment]
My understanding is this should be resolved; If this is still an issue on the latest AMI's, please open a new issue with updated `Environment`.
