### ISSUE TITLE
Automatically create node labels.

### ISSUE THREAD

**Issue by dennisjohnson** [awslabs/amazon-eks-ami#5]
Autoscaling is a problem when using node selector, affinity or anti-affinity.
Scaling a group up would not make more pods availible, replacing unhealthy instances could leave a pod with no valid node.
A feature allowing node labels to be created when new instances were created by autoscaling would be ideal.
One possibility is to use the existing tags resource, used in a similar way, and just duplicate what's there as labels for the node inside Kubernetes. Autoscaling group tags would appear as labels on newly registered nodes.

**Comment by micahhausler** [comment]
Thanks for opening this issue. We're tracking this in upstream kubernetes https://github.com/kubernetes/kubernetes/issues/63022 so I'll close this request out here.
