### ISSUE TITLE
amazon-eks-node-v24 Changelog?

### ISSUE THREAD

**Issue by pahud** [awslabs/amazon-eks-ami#50]
As the latest EKS-Optimized AMI goes to **[v24](https://aws.amazon.com/marketplace/pp/B07GRHFXGM)** now, can we update the Changelog?

https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md

thanks

**Comment by max-rocket-internet** [comment]
That AMI is not the from this repo. See details here: https://github.com/awslabs/amazon-eks-ami/issues/45

**Comment by micahhausler** [comment]
We’ll update the change log later today. Thanks!

**Comment by micahhausler** [comment]
Completed with 6a34b7b
