### ISSUE TITLE
Add support for r6* instance series

### ISSUE THREAD

**Issue by Sceat** [awslabs/amazon-eks-ami#502]
**What would you like to be added**:

I'd like to deploy r6g.* in my EKS cluster

**Why is this needed**:

To host in memory database efficiently

**Comment by mogren** [comment]
Hi @Sceat 

Updated limits for `r6g` and `r6gd` was added in #516 and will be included in the next worker AMI release.

**Comment by Sceat** [comment]
when is the release scheduled ?

**Comment by heybronson** [comment]
https://github.com/awslabs/amazon-eks-ami/pull/516 was merged, closing issue.
