### ISSUE TITLE
EFS Supporting

### ISSUE THREAD

**Issue by romanpanov1** [awslabs/amazon-eks-ami#504]
**What would you like to be added**:
Support for EFS. Can be installed by "yum -y install amazon-efs-utils"

**Why is this needed**:
EFS doesn't work on EKS Managed Node Groups, until you install this package. Such as we don't manage these AMI and nodes, it would be good to have such package inside AMI and on the nodes.

**Comment by mikestef9** [comment]
Hey @romanpanov1, efs-utils is included as part of installing the EFS CSI driver

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/Dockerfile#L28

**Comment by romanpanov1** [comment]
I faced with issues like that 
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/192
And it was resolved by installing amazon-efs-utils on nodes.

But after your answer, I investigated additionally and tried to use another version of EFS CSI driver release and it works now. Thank you.
