### ISSUE TITLE
Latest eni-max-pods.txt has errors

### ISSUE THREAD

**Issue by Airwise** [awslabs/amazon-eks-ami#515]
For example it lists a t2.medium as supporting a max of 8 pods:
![Untitled](https://user-images.githubusercontent.com/4911412/88592734-51969300-d013-11ea-98bc-196ef5bd0cc2.jpg)

But a run of the formula from the top of the document results in:
`3 ENIs * (6 - 1) IPv4s +2 = 17 max pods`

**Comment by mogren** [comment]
@Airwise Thanks for reporting! It was my mistake when merging #510, the diff in that PR was right, but the checked in file wrong. Regenerated the file and merged a fix.

**Comment by Airwise** [comment]
Thank YOU, @mogren for maintaining/fixing.  You are appreciated!
