### ISSUE TITLE
Cannot copy AMI amazon-eks-node (permission denied)

### ISSUE THREAD

**Issue by jigiro** [awslabs/amazon-eks-ami#52]
Hi folks, 

I'm sorry if this is not the right place for posting this question/issue.

I need to copy the AMI id ami-0440e4f6b9713faf6 (amazon-eks-node-v24) to encrypt the copy using my own KMS master key but I get the following error. I'm trying to copy it inside the same region (us-east-1). 

"You do not have permission to access the storage of this ami"

Is this something you can help me with?
My user has Admin permissions to do the copy and, in fact, I'm not having issues copying other AMIs, like the Amazon Linux 2 AMI. 

Appreciate your help.
Thanks,

**Comment by micahhausler** [comment]
Thanks for the issue! We were not modifying the AMI snapshot to be public, so I've updated our release tooling to call [`modify-snapshot-attribute`](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-snapshot-attribute.html) for future releases, and made the snapshots for v24 public.

**Comment by jigiro** [comment]
Thanks, @micahhausler. Everything is ok. 
Appreciate your help on this.
