### ISSUE TITLE
Where are older versions of the AMI published?

### ISSUE THREAD

**Issue by wskinner-eml** [awslabs/amazon-eks-ami#53]
I can't find them here or on https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html.

**Comment by micahhausler** [comment]
@wskinner-eml we don't publish a l list on our docs, but as @deiwin pointed out, you can query the EC2 API to see previous versions.

**Comment by zoharme** [comment]
hi @micahhausler 
is there a way I can query for latest recommended images for eks?

This is not exactly correct:
aws ec2 describe-images --filters "Name=name,Values=*eks*" "Name=is-public,Values=true" --query "sort_by(Images, &CreationDate)[].[Name,ImageId]"

Thanks

**Comment by SbgMartin** [comment]
Hi @zoharme ,

you need to have the asterisk before and after the eks name value.

aws ec2 describe-images --filters "Name=name,Values=***eks***" "Name=is-public,Values=true" --query "sort_by(Images, &CreationDate)[].[Name,ImageId]"

Cheers,
Martin

**Comment by zoharme** [comment]
thanks @SbgMartin 

I found this, I think it's good enough:
https://aws.amazon.com/blogs/opensource/improvements-eks-worker-node-provisioning/
