### ISSUE TITLE
Is launching privileged container allowed?

### ISSUE THREAD

**Issue by vincentzhou2013** [awslabs/amazon-eks-ami#54]
I'm trying to run docker in docker or mount host's docker socket. But it looks like the -privileged flag is broken because of the app armor.  Is there any way to enable it? Thanks.

**Comment by micahhausler** [comment]
The [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) needs the `--allow-privileged` flag enabled.

You can pass that down using the `BootstrapArguments` parameter in the CloudFormation template

```
--kubelet-extra-args '--allow-privileged=true'
```

**Comment by dmarkey** [comment]
Does this affect the supportability of the EKS cluster from Amazons point of view?

**Comment by micahhausler** [comment]
@dmarkey can you clarify what you mean by supportability?
