### ISSUE TITLE
NodeGroup not applying kubelet and system reserved resources

### ISSUE THREAD

**Issue by v1ctorrhs** [awslabs/amazon-eks-ami#545]
**What happened**:
Creating a cluster which runs very memory intensive jobs I need to decrease the kubelet and system reserved memory so the pods dont get killed.

**What you expected to happen**:
I expect the allocatable memory to increase. However, on a c5.9xlarge the allocatable memory is still the same as default (69GB)
**How to reproduce it (as minimally and precisely as possible)**:
- Create an EKS cluster
- Create a nodegroup with the following user data in the launch templates
```#!/usr/bin/env bash

set -xe

/etc/eks/bootstrap.sh --b64-cluster-ca 'CLUSTER_CA' \
                      --apiserver-endpoint 'API_ENDPOINT'  \ 
                      --kubelet-extra-args "--hostname-override='' --kube-reserved memory=0.5Gi,ephemeral-storage=1Gi --system-reserved memory=0.5Gi,ephemeral-storage=1Gi --eviction-hard memory.available<200Mi,nodefs.available<10%" 'CLUSTER_NAME'
```
- check allocatable memory on node when it comes up
```
▶ k get node <node> -o json | grep allocatable -A 15
        "allocatable": {
            "attachable-volumes-aws-ebs": "25",
            "cpu": "35840m",
            "ephemeral-storage": "192188443124",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "69029676Ki",
            "pods": "234"
        },
        "capacity": {
            "attachable-volumes-aws-ebs": "25",
            "cpu": "36",
            "ephemeral-storage": "209702892Ki",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "72028972Ki",
```
**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-2
- Instance Type(s): c5.9xlarge
- EKS Platform version: eks.4
- Kubernetes version: 1.15
- AMI Version: amazon-eks-node-1.15-v20200507 (ami-0c1bd9eca9c869a0d)
- Kernel: 4.14.177-139.253.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0ab1913ead3883bb5"
BUILD_TIME="Thu May  7 16:49:08 UTC 2020"
BUILD_KERNEL="4.14.177-139.253.amzn2.x86_64"
ARCH="x86_64"
```

## **UPDATE:** 
I noticed one of my mistakes - the outdated AMI, so i updated to amazon-eks-node-1.15-v20201002. Then i observed the following behavior.
- Running with the same userdata results in the same behavior - (originally listed)
- Updating the `kubeReserved` section in `/etc/kubernetes/kubelet/kubelet-config.json` and restarting the kubelet results in the desired behavior.  However i want this to happenu using `bootstrap.sh` 

```
▶ k get nodes <node> -o json | grep -i allocatable -A 15
        "allocatable": {
            "attachable-volumes-aws-ebs": "25",
            "cpu": "35840m",
            "ephemeral-storage": "18242267924",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "70877984Ki",
            "pods": "234"
        },
        "capacity": {
            "attachable-volumes-aws-ebs": "25",
            "cpu": "36",
            "ephemeral-storage": "20959212Ki",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "72028960Ki",
```

**Comment by v1ctorrhs** [comment]
I'm getting closer to the solution. I think this is caused by several things:
 - When I put the user-data in the launch template, the quotes are modified by AWS and end up being executed like this in cloud-init
```
+ /etc/eks/bootstrap.sh --b64-cluster-ca <cluster_ca> --apiserver-endpoint <apiserver-endpoint) --kubelet-extra-args '--hostname-override='\'''\'' --kube-reserved memory=0.3Gi,ephemeral-storage=1Gi --system-reserved memory=0.2Gi,ephemeral-storage=1Gi --eviction-hard memory.available<200Mi,nodefs.available<10%' <cluster_name>
 ```

In `bootstrap.sh`  the extra args are extracted and sent to a systemd env file. Notice the single quotes and the single quotes that come from the user data? I think the two combined are what ends up breaking the config.
```
    322 if [[ -n "$KUBELET_EXTRA_ARGS" ]]; then
    323     cat <<EOF > /etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
    324 [Service]
    325 Environment='KUBELET_EXTRA_ARGS=$KUBELET_EXTRA_ARGS'
    326 EOF
    327 fi
``` 
If i modify the file like this and restart the kubelet it works as expected.

```
[root@ip-10-23-39-9 kubelet]# cat /etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
[Service]
Environment="KUBELET_EXTRA_ARGS=--hostname-override='' --kube-reserved memory=0.3Gi,ephemeral-storage=1Gi --system-reserved memory=0.2Gi,ephemeral-storage=1Gi --eviction-hard memory.available<200Mi,nodefs.available<10%"
```

**Comment by AJ-ajay-AY** [comment]
I am also facing a similar issue . Curious how you resolved it .

I am using terraform to run my user script in

`      pre_bootstrap_user_data = templatefile("templates/bootstrap.sh.tpl", {
        cluster_name = local.cluster_name
      })`

Also this is how my bootstrap script looks like

`#!/bin/bash
/etc/eks/bootstrap.sh ${cluster_name} \
	--kubelet-extra-args "--max-pods=70 --system-reserved cpu=350m,memory=200Mi,ephemeral-storage=1Gi --kube-reserved cpu=350m,memory=500Mi,ephemeral-storage=3Gi"
`

I am noticing similar behaviour like you while running 

` "allocatable": {
            "cpu": "7910m",
            "ephemeral-storage": "95551679124",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "31482324Ki",
            "pods": "58"
        },
        "capacity": {
            "cpu": "8",
            "ephemeral-storage": "104845292Ki",
            "hugepages-1Gi": "0",
            "hugepages-2Mi": "0",
            "memory": "32499156Ki",
            "pods": "58"
        },`

can you see an obvious issue in my approach here . Also looked into the node noticing that the user script has no effect .
