### ISSUE TITLE
AWS image builder

### ISSUE THREAD

**Issue by yanivpaz** [awslabs/amazon-eks-ami#548]
**What would you like to be added**:
Support for https://aws.amazon.com/image-builder/

**Why is this needed**:
- Simplify the build process of AMI
- Have better integration to AWS services 
- Avoid maintaining separate EC2 with packer

**Comment by yanivpaz** [comment]
closed by mistake

**Comment by yanivpaz** [comment]
@micahhausler can we leverage AWS AMI  builder and the new [refresh ASG](https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/) feature to simplify the upgrade of ec2 worker nodes?

**Comment by grgizem** [comment]
@yanivpaz something that we have been working on, EKS AMI prep using Image builder service: https://github.com/sufleio/amazon-eks-ami based on this repository. hope this helps

**Comment by yanivpaz** [comment]
Thanks @grgizem  !

**Comment by cartermckinnon** [comment]
We don't have any current plans to rewrite this AMI template using Image Builder. We'll reopen this issue if that changes.
