### ISSUE TITLE
AMI release name should be unique if 2 AMIs are released on the same day

### ISSUE THREAD

**Issue by rajakshay** [awslabs/amazon-eks-ami#551]
**What would you like to be added**:
The [ami name](https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L12-L15) has year, month, and date in it, and does not go any granular than that. I'd request adding hour, min, and seconds to the AMI name to make it unique in case 2 AMIs are released on the same day.
**Why is this needed**:
Our automation relies on getting the latest AMI based on the release name for the AMI. 
```
data "aws_ami" "eks_worker" {
  owners      = ["602401143452"]
  most_recent = true

  filter {
    name   = "name"
    values = [var.ami_name]
  }
}
```
This would be a problem if there were 2 AMIs released on the same day (say, for urgent security fixes, etc.). The AMIs names would not be unique. And there's a slight chance that someone ran validations on a different AMI, and then, the AMIs changed when they were rolling out the changes to prod. We'd like to avoid this scenario, and ensure consistency b/w validations and rolling out changes. 

An alternate way is to maintain a hard-coded list of AMI IDs for each region (we are multi-region), but, that's an unnecessary load on ops team to maintain. 

I am happy to send an MR for this.

**Comment by mikestef9** [comment]
Have you looked the EKS AMI SSM parameters?

https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html

**Comment by rajakshay** [comment]
Hi @mikestef9 
Yes, that's where we are grabbing the AMI id from right now. But, It'd be nice to be able to do this just in terraform. I noticed today that the same problem is described here as well: https://github.com/aws/containers-roadmap/issues/319#issuecomment-505021871

**Comment by cartermckinnon** [comment]
The good news is the issue described in the linked comment (two AMI's named `amazon-eks-gpu-node-1.13-v20190614`) isn't possible in our current release process (which has changed significantly over the last 3 years).

While my instinct is to make the naming convention more granular, this amounts to a public API change and will likely break many of our users. In practice; building, testing, distributing, and releasing two AMI's globally on the same UTC date is not necessarily realistic. In the event of an emergency, such as the log4j fiasco last year, other mechanisms would likely be used for mitigation during the first 24 hours.

All this is to say: I agree with you, but I don't think it's particularly pressing to change this today.
