### ISSUE TITLE
kubelet.service can't restart if I use Kill -9 

### ISSUE THREAD

**Issue by stevensu1977** [awslabs/amazon-eks-ami#553]
**What happened**:
kubelet.service can't restart if I use Kill -9 

**What you expected to happen**:
If found AMI use restart plolicy follow this:

Restart=on-failure
RestartForceExitStatus=SIGPIPE
RestartSec=5
KillMode=process

this means systemd can't catch SIGKILL, may be we can add SIGKILL to  RestartForceExitStatus
RestartForceExitStatus=SIGPIPE  SIGKILL

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
      cn-north-1
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.4
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):1.15

```
```

**Comment by mmerkes** [comment]
This sounds reasonable to me. If you're intention is to actually stop kubelet, you should be using `systemctl` anyway, so restarting on `kill -9` makes sense to me.

**Comment by heybronson** [comment]
https://github.com/awslabs/amazon-eks-ami/pull/554 has been merged, closing issue.
