### ISSUE TITLE
Add more docker logging to Linux log collector

### ISSUE THREAD

**Issue by finchd** [awslabs/amazon-eks-ami#555]
**What would you like to be added**:

Please add these two files to the Linux log collector script:

- containerd: e.g. `journalctl -u containerd > containerd.log`
- docker trace: e.g. `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine\?debug\=2 > docker-goroutine.debug`

**Why is this needed**:

I have seen multiple instances where kubelet times out talking to docker.sock, which should have had dockerd respond. These become visible as PLEG timeouts.
Dockerd does not have an "access log" of what requests it received on the docker.sock normally.
However, dockerd could have gotten the request and sent it to containerd.sock, which didn't respond instead. So containerd logs would be useful to see if kubelet requests are reaching containerd.

The dockerd goroutine trace has been asked for in the moby/moby and docker/for-linux repos when they are troubleshooting issues with dockerd. We should include this as well to make it easy to gather and include with any upstream issues that may need to be made.

**Comment by nzoueidi** [comment]
sounds reasonable for me. I was willing to open an issue but I found this already.

**Comment by heybronson** [comment]
This was addressed in https://github.com/awslabs/amazon-eks-ami/pull/619 which has been merged. Closing issue.
