### ISSUE TITLE
Recommended SSM Parameter Out of Date

### ISSUE THREAD

**Issue by bflad** [awslabs/amazon-eks-ami#559]
**What happened**:

Currently, the `recommended` release version parameter (at least for 1.16) is out of date with what the EKS API accepts:

```console
$ aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/release_version
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/release_version",
        "Type": "String",
        "Value": "1.16.13-20201007",
        "Version": 15,
        "LastModifiedDate": "2020-10-09T16:24:21.116000-04:00",
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/release_version",
        "DataType": "text"
    }
}
```

```
InvalidParameterException: Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107
{
RespMetadata: {
StatusCode: 400,
RequestID: "17a52d81-285a-4e03-924c-874d3d895e3b"
},
```

**What you expected to happen**:

Available SSM Parameter to always return a valid release version.

**How to reproduce it (as minimally and precisely as possible)**:

Example snippet of Terraform configuration (only relevant piece is `release_version` argument and its value):

```terraform
data "aws_ssm_parameter" "test" {
  name = "/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/release_version"
}

resource "aws_eks_node_group" "test" {
  cluster_name    = aws_eks_cluster.test.name
  node_group_name = "test"
  node_role_arn   = aws_iam_role.node.arn
  release_version = data.aws_ssm_parameter.test.value
  subnet_ids      = aws_subnet.test[*].id
  version         = aws_eks_cluster.test.version

  scaling_config {
    desired_size = 1
    max_size     = 1
    min_size     = 1
  }
}
```

**Anything else we need to know?**:

- [Original issue to create SSM Parameter](https://github.com/awslabs/amazon-eks-ami/issues/423)
- [EKS User Guide](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html) is also out of date.
- [Containers Roadmap issue to create EKS API call](https://github.com/aws/containers-roadmap/issues/771)

**Environment**:

- AWS Region: `us-west-2`

**Comment by rtripat** [comment]
Can you retry this now?

**Comment by bflad** [comment]
Hi @rtripat this is still occurring with newer versions:

```console
$ aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.18/amazon-linux-2/recommended/release_version
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.18/amazon-linux-2/recommended/release_version",
        "Type": "String",
        "Value": "1.18.9-20201126",
        "Version": 5,
        "LastModifiedDate": "2020-11-30T16:11:41.600000-05:00",
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.18/amazon-linux-2/recommended/release_version",
        "DataType": "text"
    }
}
```

```
InvalidParameterException: Requested Nodegroup release version 1.18.9-20201126 is invalid. Allowed release version is 1.18.9-20201207
{
RespMetadata: {
StatusCode: 400,
RequestID: "7307c311-9006-4346-9851-7bd23cd41974"
},
ClusterName: "tf-acc-test-2065180901557413293",
Message_: "Requested Nodegroup release version 1.18.9-20201126 is invalid. Allowed release version is 1.18.9-20201207",
NodegroupName: "tf-acc-test-2065180901557413293"
}
```

**Comment by rtripat** [comment]
> ```
> aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.18/amazon-linux-2/recommended/release_version
> ```

Taking a look. Can you provide details on how you are creating the Nodegroup? CLI command, eksctl or Console?

**Comment by rtripat** [comment]
@bflad I see that you are in Hashicorp which is an EKS partner. You have access to pre-released AMI versions.

`20201207` is an AMI staged for release in production and can only be used by partners (for testing of features) and our internal test infrastructure. Can you try to create the nodegroup without specifying the release version at all? If you have further questions, feel free to reach out to AWS via support.

**Comment by bflad** [comment]
This is end-to-end testing for the Terraform AWS Provider `aws_eks_node_group` resource on behalf of all AWS customers:

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group
- https://github.com/hashicorp/terraform-provider-aws/blob/7900b33d47fe9f26c0fb23f9672f3354dce7b734/aws/resource_aws_eks_node_group_test.go#L479-L512
- https://github.com/hashicorp/terraform-provider-aws/blob/7900b33d47fe9f26c0fb23f9672f3354dce7b734/aws/resource_aws_eks_node_group_test.go#L1580-L1607

I'll create a support request, but we will want to know a correct way for this type of account with access to staged AMIs to fetch an acceptable release version and create/update an EKS Node Group.

**Comment by bflad** [comment]
Resolved out of band, thank you so much, @rtripat 👍
