### ISSUE TITLE
us-west-2 is missing amazon-eks-node-1.16-v20201117 AMI

### ISSUE THREAD

**Issue by niroowns** [awslabs/amazon-eks-ami#565]
**What happened**: Although just released (< ~20 min ago), I am unable to see the AMI (amazon-eks-node-1.16-v20201117) in region us-west-2 (Oregon).  It appears to be in other regions I spot checked.

**Environment**:
- AWS Region: us-west-2

cc: @abeer91

**Comment by abeer91** [comment]
Hi, Can you check again? This is what I'm seeing on my side


```
(cli-ve) ➜  bin git:(mainline) aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/image_id --region us-west-2                      [20/11/18| 8:49AM]
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-009250020daac8145",
        "Version": 19,
        "LastModifiedDate": 1605699163.342,
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}
(cli-ve) ➜  bin git:(mainline) aws ec2 describe-images --image-id ami-009250020daac8145                                                                                     [20/11/18| 8:49AM]
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-11-18T00:52:02.000Z",
            "ImageId": "ami-009250020daac8145",
            "ImageLocation": "amazon/amazon-eks-node-1.16-v20201117",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "602401143452",
            "PlatformDetails": "Linux/UNIX",
            "UsageOperation": "RunInstances",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-08df40f110d048714",
                        "VolumeSize": 20,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                }
            ],
            "Description": "EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.16.15, docker:19.03.6ce-4.amzn2)",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "Name": "amazon-eks-node-1.16-v20201117",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }
    ]
}
```

**Comment by niroowns** [comment]
So odd, I am getting the same results using the CLI - but the AWS console is not listing it.  Might be a delay there?

**Comment by aquam8** [comment]
I have the same problem in `ap-southeast-2`. I did not think of checking with CLI but my console only list v20201112 as latest image. Same for 1.18 image which is what I use.

**Comment by rtripat** [comment]
Can you please post a screenshot of console where you are seeing `v20201112` ? My checked again and Console is recommending an Update for all nodegroups created on `v20201112` and new nodegroup was created on `v20201117`

**Comment by niroowns** [comment]
Sure...

here is us-east-1:

![image](https://user-images.githubusercontent.com/19827675/99730037-d22d4380-2a89-11eb-96c5-013feabb4d87.png)

same in us-west-2 returns nothing:
![image](https://user-images.githubusercontent.com/19827675/99730095-e5401380-2a89-11eb-8519-dbe0e7897d57.png)

**Comment by rtripat** [comment]
> Sure...
> 
> here is us-east-1:
> ![image](https://user-images.githubusercontent.com/19827675/99730037-d22d4380-2a89-11eb-96c5-013feabb4d87.png)
> 
> same in us-west-2 returns nothing:
> ![image](https://user-images.githubusercontent.com/19827675/99730095-e5401380-2a89-11eb-8519-dbe0e7897d57.png)

interesting. This is an issue with Ec2 console and we are digging into it further. However, if you create or upgrade a managed nodegroup in any region, you will get the latest AMI `v20201117`.

If you are using self manage nodegroups, then please use the SSM parameter to get the AMI id.

**Comment by rtripat** [comment]
This has been an issue in the Ec2 console and they are deploying a fix. Resolving.
