### ISSUE TITLE
Binaries missing/incorrect release notes for v20201117 release

### ISSUE THREAD

**Issue by janbeerden** [awslabs/amazon-eks-ami#567]
From the release notes:
```
Binaries used to build these AMIs are published :
s3://amazon-eks/1.18.9/2020-11-07/
s3://amazon-eks/1.17.12/2020-11-07/
s3://amazon-eks/1.16.15/2020-11-07/
s3://amazon-eks/1.15.12/2020-11-07/
```

Neither one of the K8s version directories contains a `2020-11-07` subdirectory, only a `2020-11-02` subdirectory is present.

Are the binaries missing or are the references in the release notes incorrect?

**Comment by janbeerden** [comment]
@vishalkg, I see you updated the changelog for v20201117, perhaps you can identify what the problem is here?

**Comment by vishalkg** [comment]
@janbeerden We have fixed the bucket name.

**Comment by janbeerden** [comment]
@vishalkg, awesome, thanks!
