### ISSUE TITLE
rngd not running

### ISSUE THREAD

**Issue by casperbiering** [awslabs/amazon-eks-ami#572]
**What happened**:
After an upgrading our ASGs Launch Template from `amazon-eks-node-1.16-v20201007 (ami-0b0dffffb5ba92f97)` to `amazon-eks-node-1.16-v20201117 (ami-05be81cd1ee691209)` we saw a serious drop in entropy levels, and noticed that `rngd` wasn't running on the new AMI.

**What you expected to happen**:
`rngd` to be present and running on the node.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a new instance with `ami-05be81cd1ee691209` on us-east-1, SSH to it, run `pstree`.

**Anything else we need to know?**:

I noticed that running `systemctl status rngd` I got:
```
● rngd.service - Hardware RNG Entropy Gatherer Daemon
   Loaded: loaded (/usr/lib/systemd/system/rngd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Nov 23 20:23:05 localhost systemd[1]: Job rngd.service/start deleted to break ordering cycle starting with sysinit.target/start
```

I've tested that rngd is running on `amazon-eks-node-1.16-v20201112 - ami-0eac1642207d31d74` (the release in between the two mentionen above)

**Environment**:
- AWS Region: us-east-1, eu-west-1
- Instance Type(s): c5.2xlarge, t2.micro etc
- EKS Platform version: eks.3
- Kubernetes version: 1.16
- AMI Version: ami-05be81cd1ee691209
- Kernel: Linux ip-10-XX-XX-XX.ec2.internal 4.14.203-156.332.amzn2.x86_64 #1 SMP Fri Oct 30 19:19:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-020d00da3ecaa9ae5"
BUILD_TIME="Tue Nov 17 21:32:11 UTC 2020"
BUILD_KERNEL="4.14.203-156.332.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by rtripat** [comment]
Thank you for reporting the issue. We have root caused it to the base Amazon Linux 2 AMI. We are working with them on a fix.

**Comment by heybronson** [comment]
This has been addressed in the latest AMI release https://github.com/awslabs/amazon-eks-ami/releases/tag/v20201211

**Comment by casperbiering** [comment]
I can confirm that it's fixed
