### ISSUE TITLE
About adding curl commands retries in bootstrap.sh

### ISSUE THREAD

**Issue by hiraken-w** [awslabs/amazon-eks-ami#577]
**What would you like to be added**:

I would like to request retry function of curl commands for instance metadata on bootstrap.sh.

**Why is this needed**:

On bootstrap.sh, curl commands for instance metadata are executed.
But requesting to instance metadata is not always successful.It may result in an error.
Therefore, I believe that retry processing is necessary for the case of failure.

[amazon-eks-ami/bootstrap.sh at master · awslabs/amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami/blob/ab3245f5ac0f2d434d4401c8f312a0f79abb1ad8/files/bootstrap.sh#L206)

```
TOKEN=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 600" "http://169.254.169.254/latest/api/token")
```

**Comment by mmerkes** [comment]
Sounds reasonable.

**Comment by hiraken-w** [comment]
The following pull request fix this issue.
https://github.com/awslabs/amazon-eks-ami/pull/596a

**Comment by heybronson** [comment]
https://github.com/awslabs/amazon-eks-ami/pull/596 has been merged. Closing issue.
