### ISSUE TITLE
fail to create image:  /tmp/script_8155.sh: line 288: syntax error near unexpected token `done'

### ISSUE THREAD

**Issue by pierrchen** [awslabs/amazon-eks-ami#581]
**What happened**:
failed to create the AMI. the `install-work.sh provisioner` seems failed at the last step.

[see here for the complete log](https://gist.github.com/pierrchen/1e4a2b193116199027f062df5c637de0)
```
    amazon-ebs: /tmp/script_8155.sh: line 288: syntax error near unexpected token `done'
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored after 5 minutes 41 seconds: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]
```
**What you expected to happen**:

successfully created the image.

**How to reproduce it (as minimally and precisely as possible)**:
1. git clone the repo
2. replace m4.large with t2.mciro in Makefile
3. make

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): t2.micro
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by tibin-mfl** [comment]
@ericlarssen-wf 
It's a code bug here https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L288
closing if condition

**Comment by pierrchen** [comment]
@tibin-mfl  Thanks, that fixed it.
https://github.com/awslabs/amazon-eks-ami/pull/582

**Comment by mmerkes** [comment]
Tx for finding. PR merged.
