### ISSUE TITLE
Documentation to correlate EKS AMI and Amazon Linux 2?

### ISSUE THREAD

**Issue by lancehunt** [awslabs/amazon-eks-ami#586]
Given an EKS AMI, where can I find the Amazon Linux 2 version it is using?

I'm guessing that the Packer build uses `eks-worker-al2.json` as input and selects the AL2 version via the `source_ami_id` but it is empty and there is no obvious place to find what is used here.

Furthermore because of the `scripts/upgrade_kernel.sh` which updates the kernel its even more non-deterministic what a given AMI's kernel version is beyond launching an instance of the AMI.

Can someone connect the dots for me?

As with several other issues like #245 and #99 I need to be able to determine the risk exposure of any given EC2 instance inclusive of EKS nodes and to be able to evaluate any new linux CVE's as they occur.

**Comment by mmerkes** [comment]
@lancehunt Sorry for the late response. I [added more information into the README](https://github.com/awslabs/amazon-eks-ami/pull/602) about how the process works. I believe that will answer your questions, but let me know if you need more information.
