### ISSUE TITLE
[question] Enable kernel live-patching?

### ISSUE THREAD

**Issue by heidemn** [awslabs/amazon-eks-ami#605]
**Environment**:
- AWS Region: eu-west-1, us-east-1
- Instance Type(s): t3.small, t3.medium, m5.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.16
- AMI Version: v20210125
- Kernel (e.g. `uname -a`): `4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
```

I was recently looking into Amazon Linux 2 [kernel live patching](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/al2-live-patching.html).

It's not enabled in this EKS AMI, probably to keep it as minimal as possible.
I considered to manually enable it in the EC2 userdata script, with the commands from above link.
This would avoid the need to replace or reboot instances for kernel updates.

So my userdata script would be something like:
```
1. /etc/eks/bootstrap.sh ...
2. <install SSM agent>
3. <enable kernel live patching>
```

Is that a stupid idea?
Would you expect that Kubernetes stuff regularly breaks when live-patching a kernel?
Any experiences or thoughts?

Thanks!

**Comment by rtripat** [comment]
You can enable kernel live patching using userdata as you have found. The primary thing to be aware of is that live patching is not a replacement for traditional reboot the kernel to get all the security updates along with bug fixes and features.  Live patching only addresses security fixes that are rated important.

**Comment by heidemn** [comment]
Okay thanks - then I'll give it a try within the next days, and post some results here.

**Comment by mmerkes** [comment]
Generally speaking, I wouldn't expect kernel patches to break kubernetes-related things on the nodes, but it wouldn't go through the same validation that a new AMI released by EKS with the patches would, so we couldn't guarantee that. Also, it looks like live patching only works for 3 months after a kernel is released, so you'd still need to replace them at some frequency.

Hope your experiment went well. Closing this issue, but feel free to post any results here.

**Comment by heidemn-faro** [comment]
I've enabled live patching two weeks ago in staging.
Two live patches are currently active on each node (-> `yum updateinfo list | grep -i livepatch`).

No issues observed so far, everything runs smoothly.
Thanks again for your help :-)

**Comment by jasonstitt** [comment]
The current EKS AMI uses kernel 5.4.x, while the live patching docs specify 5.10+

I tried the steps anyway on a dev instance and it doesn't appear any live patches were applied, although there should be one available for a current open CVE
