### ISSUE TITLE
Patching nodes failing for non GPU instance

### ISSUE THREAD

**Issue by AshokMishra** [awslabs/amazon-eks-ami#606]
**What happened**: Using the latest aws eks ami cause the node patching to fail with below error

`Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.
nvidia-smi found
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
Exited with error on line 354
Feb 02 21:37:14 cloud-init[5087]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [9]
Feb 02 21:37:14 cloud-init[5087]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Feb 02 21:37:14 cloud-init[5087]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Feb 02 21:37:14 cloud-init[5087]: util.py[WARNING]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) failed
Cloud-init v. 19.3-5.amzn2 finished at Tue, 02 Feb 2021 21:37:14 +0000. Datasource DataSourceEc2.  Up 71.89 seconds`

**What you expected to happen**: Expected output is mentioned below
`Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.
+ /opt/aws/bin/cfn-signal -e 0 --stack INFRA-***-EKS-****-NODEGROUP --resource NodeGroup --region <REGION>
Feb 02 21:37:14 cloud-init[5113]: util.py[WARNING]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) failed
Cloud-init v. 19.3-3.amzn2 finished at Thu, Feb 02 21:37:14 +0000. Datasource DataSourceEc2.  Up 110.80 seconds`

**How to reproduce it (as minimally and precisely as possible)**: Try to patch a `m4.xlarge` EKS nodegroup

**Anything else we need to know?**: 

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): m4.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.5
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.15.12
- AMI Version: ami-0c35898bc619d2965
- Kernel (e.g. `uname -a`): kernel-4.14.214-160.339.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
```
**Probable Solution:**
Lines https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L417-L442 have to be updated to take into consideration for non GPU instances as mentioned below

`if  command -v nvidia-smi &>/dev/null ; then
  echo "nvidia-smi found"
  nvidia-smi -q > /tmp/nvidia-smi-check
  if [ "$?" = "0" ] ; then
    sudo nvidia-smi -pm 1 # set persistence mode
    sudo nvidia-smi --auto-boost-default=0
    GPUNAME=$(nvidia-smi -L | head -n1)
    echo $GPUNAME
    # set application clock to maximum
    if [[ $GPUNAME == *"A100"* ]]; then
      nvidia-smi -ac 1215,1410
    elif [[ $GPUNAME == *"V100"* ]]; then
      nvidia-smi -ac 877,1530
    elif [[ $GPUNAME == *"K80"* ]]; then
      nvidia-smi -ac 2505,875
    elif [[ $GPUNAME == *"T4"* ]]; then
      nvidia-smi -ac 5001,1590
    elif [[ $GPUNAME == *"M60"* ]]; then
      nvidia-smi -ac 2505,1177
    else
      echo "unsupported gpu"
    fi
  else
    cat /tmp/nvidia-smi-check
  fi
else
    echo "nvidia-smi not found"
fi`

**Comment by heybronson** [comment]
Thanks for bringing this up. We'll be working on a fix.

**Comment by AshokMishra** [comment]
@heybronson Thanks for getting back. Yes, it a GPU AMI. We are using a mix and match of both GPU and non GPU instances. To make our life easier with patching we use 1 AMI for both categories of instances. Due to recent changes done in the `bootstrap.sh` script our patching process is breaking. Would request you to include an extra validation condition in the bootstrap script mentioned above. It will greatly help us.

Thanks

**Comment by heybronson** [comment]
@AshokMishra We'll be working to make this more resilient and are looking to fix this by the next AMI release.

**Comment by heybronson** [comment]
Fix has been merged and will be picked up in the next AMI release.
