### ISSUE TITLE
ALAS2-2021-1588

### ISSUE THREAD

**Issue by daemienb** [awslabs/amazon-eks-ami#608]
Hi Team,

when will amazon-eks-ami include the above vul fix?

Thanks,
Daemien

**Comment by mmerkes** [comment]
Thanks for reaching out. We have released updated AMIs everywhere except China regions that include the `4.14.214` Linux kernel, which includes the patch for [this CVE](https://alas.aws.amazon.com/AL2/ALAS-2021-1588.html). If you update nodes to use the latest AMIs, `v20210208`, they should have the appropriate patch.

You can get the latest AMIs by following [this guide](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html). For example:

```
aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.18/amazon-linux-2/recommended/image_id --region us-east-2 --query "Parameter.Value" --output text
```

**Comment by daemienb** [comment]
Prefect thanks
