### ISSUE TITLE
Makefile is wrong for 1.19

### ISSUE THREAD

**Issue by caphrim007** [awslabs/amazon-eks-ami#615]
**What happened**:

The makefile for 1.19 is incorrect

**What you expected to happen**:

Expect `make 1.19` to work

**How to reproduce it (as minimally and precisely as possible)**:

Makefile line here is indented too far (and line below it)
https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L63

Also, 1.19 is missing from here (but that's not as big an issue)
https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L32

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by alex-ferener** [comment]
It works after you fix the spacing issue on L63 and L64

**Comment by mmerkes** [comment]
Fixed by PR #616

**Comment by mmerkes** [comment]
Tx for pointing that out.
