### ISSUE TITLE
Can't attach an EKS node to the cluster 1.17

### ISSUE THREAD

**Issue by resworld** [awslabs/amazon-eks-ami#618]
**What happened**:

Attaching an EKS node to the cluster with maximum characters for hostname (64), but it's failing to attach to the cluster because of limit of 63 symbols for hostname:
```
"causes": [
                {
                    "reason": "FieldValueInvalid",
                    "message": "Invalid value: \"i-xxxxxxxxxxxxxxxxx-xxx-xxxxxxx-xxxx-xxxxxxxxxx-1-17-xxxx-xxxxxx\": must be no more than 63 characters",
                    "field": "metadata.labels"
                }
            ]
```
**What you expected to happen**:

Expecting to attach the cluster when hostname = 64 symbols long.

**How to reproduce it (as minimally and precisely as possible)**:

Change instance's hostname with name long 64 symbols and try to attach it to the cluster

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): c5.2xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.5"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.17
- AMI Version:  amazon-eks-node-1.17-v20201126
- Kernel (e.g. `uname -a`):  Linux xxxx 4.14.203-156.332.amzn2.x86_64 #1 SMP Fri Oct 30 19:19:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-020d00da3ecaa9ae5"
BUILD_TIME="Thu Nov 26 00:57:53 UTC 2020"
BUILD_KERNEL="4.14.203-156.332.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by mmerkes** [comment]
According to [the Kubernetes names doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names), `Some resource types require their names to follow the DNS label standard` and `contain at most 63 characters`. This is a limit enforced by Kubernetes upstream, so EKS clusters will enforce the same limits. You'll have to choose a hostname 63 characters or less.
