### ISSUE TITLE
What does it replace exactly ?

### ISSUE THREAD

**Issue by zanoubia** [awslabs/amazon-eks-ami#62]
https://github.com/awslabs/amazon-eks-ami/blob/eb0239fb52f524d8c1da2bb91d4c9df1190e1e29/files/bootstrap.sh#L98

**Comment by deadlytea** [comment]
That command looks like it replaces the string `CLUSTER_NAME` with the ENV var `$CLUSTER_NAME` at https://github.com/awslabs/amazon-eks-ami/blob/eb0239fb52f524d8c1da2bb91d4c9df1190e1e29/files/kubelet-kubeconfig#L23

**Comment by micahhausler** [comment]
This inserts the cluster name into the kubeconfig so authenticator knows which cluster to authenticate to
