### ISSUE TITLE
Template format error: YAML not well-formed. (line 91, column 65)

### ISSUE THREAD

**Issue by jijoosper** [awslabs/amazon-eks-ami#621]
**What happened**:
Following https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html, getting "Template format error: YAML not well-formed. (line 91, column 65)" in step 5
**What you expected to happen**:
Proceed to Specify stack details when clicking next
**How to reproduce it (as minimally and precisely as possible)**:
Following https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html, step 1-5
curl -o amazon-eks-nodegroup.yaml https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml
Open the AWS CloudFormation console at https://console.aws.amazon.com/cloudformation
Choose Create stack and then select With new resources (standard).
For Specify template, select Upload a template file and then select Choose file. Select the amazon-eks-nodegroup.yaml file that you downloaded in step 2 and then select Next.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
![eks-etcd](https://user-images.githubusercontent.com/56539305/108739243-7677c800-755a-11eb-9981-696db900f5cb.png)

- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by mmerkes** [comment]
I was able to repro as well. The problem is that it's downloading the HTML, not the yaml. I'll get that fixed.

**Comment by mmerkes** [comment]
PR opened. If you change the link as done in the docs PR, it should resolve the issue for you.

**Comment by jijoosper** [comment]
Issue fixed with raw URL and I see the doc is updated. Thank you!
