### ISSUE TITLE
Make gp3 the default EBS volume type

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#626]
**What would you like to be added**:

In December 2020, [Amazon EBS announced gp3 volumes](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/), the next generation of general purpose volumes. gp3 volumes are more performant, flexible and have lower costs than gp2 volumes, the current default, and they are available in all commercial and govcloud regions.

We should verify that there are no downsides to this and would not impact any existing customers, but seems like a reasonable change.

Changing it [here](https://github.com/awslabs/amazon-eks-ami/blob/850e0029c34c0dfcb8788a1433759d1cc8cef2b2/eks-worker-al2.json#L63-L71) would make it the default, and we should consider adding a new user variable to set the volume type to simplify it for customers who want to use a different volume type.

And probably update the [CFN template](https://github.com/awslabs/amazon-eks-ami/blob/f85cf415b90acaafb2aebc1cf845b6a2282a0ada/amazon-eks-nodegroup.yaml#L629).

**Why is this needed**:

gp3 volumes are the latest generation of EBS volumes and offer benefits over gp2 AMIs.

**Comment by mmerkes** [comment]
We've discussed this issue, and we want to do some additional validation and performance testing before we make gp3 volumes the default for AMIs. Once we are able to do that, we will add additional details here, including the results.

**Comment by hlakkala** [comment]
Any updates on this topic? Hopefully you've had time to test gp3 volumes by now, and they could be made the default type for new Instances.

**Comment by eins** [comment]
any updates on this topic folks ?

**Comment by eins** [comment]
> any updates on this topic folks ?
any updates on this topic now?

**Comment by shinebayar-g** [comment]
To make this happen they just need to deploy https://github.com/kubernetes-sigs/aws-ebs-csi-driver by default just like vpc-cni-k8s, coredns, kube-proxy. Looks like they're not interested in this unfortunately :(

**Comment by cartermckinnon** [comment]
I'm on board. Because gp3 can have (sometimes subtle) performance differences, we'll probably make the change starting with a Kubernetes version like 1.26. I'll put together a PR.
