### ISSUE TITLE
EKS cluster gives no resource found message though the cluster is in active state

### ISSUE THREAD

**Issue by rajputvishwas** [awslabs/amazon-eks-ami#627]
**What happened**:  I have deployed few services on AWS EKS cluster which works as expected. Our admin team starts and stops the cluster on daily basis. I am using aws cli -2 to access EKS cluster and deploy services. From last two days, the admin starts the cluster and server comes in active state but I am not able to find any nodes. It shows me no resources 

**What you expected to happen**: Once admin starts the cluster, I should able to see the nodes if cluster is in active state

**How to reproduce it (as minimally and precisely as possible)**: I am not sure 

**Anything else we need to know?**: The cluster is in active state, and I can see EC2 instances related to cluster are in running state. We did try restarting cluster multiple times. But it didn't help. On console everything looks ok but not able to access through cli. Even other members and admin team also not able to see the nodes on the cluster trough cli.

**Environment**: AWS EKS
- AWS Region: us-east-1
- Instance Type(s): t3.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): NA
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.18
- AMI Version: NA
- Kernel (e.g. `uname -a`): NA
- Release information (run `cat /etc/eks/release` on a node):

```
```

![image](https://user-images.githubusercontent.com/15668995/109113232-f15eff80-7761-11eb-80ec-e11633272f03.png)

**Comment by mmerkes** [comment]
What do you mean by "starts and stops the cluster?" Do you mean starts and stops the nodes and the nodes don't rejoin the cluster? Are you starting and stopping via the EC2 console or APIs? I'll need more information before I can help you, including what you're specifically doing.

**Comment by rajputvishwas** [comment]
Actually my admin used to scale up and down the nodes from EKS console on regular basis, that's how we start and stop the cluster. But since couple of days nodes are not able to rejoin the cluster.

**Comment by heybronson** [comment]
In order to further debug this issue, we'll need the cluster ARN. Please create a support case with AWS and add the relevant details there.
