### ISSUE TITLE
Increase kubelet klog verbosity 

### ISSUE THREAD

**Issue by heybronson** [awslabs/amazon-eks-ami#628]
**What would you like to be added**:
The Kubernetes community recommends a [logging verbosity of 2](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md) for most systems. Today, we use the default V(0), unless a different verbosity is explicitly passed via userData as an extra Kubelet argument.

We should set the logging verbosity to V(2) by default in our AMIs to follow the recommendation. 

**Why is this needed**:
Increasing Kubelet verbosity will help when reading Kubelet logs while debugging issues. Increased verbosity may also decrease the resolution time on support tickets.

**Comment by abeer91** [comment]
It would be interesting to see if there's feedback around changing the default value here. Some things Bronson and I have discussed:

1. Today we manage log rotation through journald and we set the max usage to 15% of disk space. This isn't changing.
2. We do not configure a max retention time, this won't be changing?
3. It would be interesting to learn about how users set up agents to export logs - fluentbit / fluentd and if this change affects their log aggregation process?
4. There is still a way to change the logging to the earlier default level of 0 by passing kubelet-args.

**Comment by mmerkes** [comment]
I'd be interested in customer feedback as well. Customers who replace nodes regularly may not have gotten anywhere near the 15% disk usage and may start to see it now. Customers will potentially see a surprise increase in expense or compute needs to manage the logs, though I'm not sure how much of a difference we're talking about, if it's minor or significant.

**Comment by mmerkes** [comment]
Before we resolve this issue, let's add a short section to the README on how customers can override the kubelet verbosity in userdata.

**Comment by heybronson** [comment]
https://github.com/awslabs/amazon-eks-ami/pull/629 was merged. Closing issue.
