### ISSUE TITLE
How to pass arbitrary additional cmd line arguments to the custom eks-ami

### ISSUE THREAD

**Issue by D2809** [awslabs/amazon-eks-ami#64]
How can I pass node-labels to the existing custom eks-ami kubelet script so that later we can use K8s nodeSelector spec to assign certain pods to specific set of EC2 nodes.

**Comment by delgod** [comment]
you need to pass `--node-labels=key=value` as argument to `bootstrap.sh`

**Comment by micahhausler** [comment]
See also #29
