### ISSUE TITLE
Link to CVE descriptions in Release Notes

### ISSUE THREAD

**Issue by forsberg** [awslabs/amazon-eks-ami#643]
**What would you like to be added**:

In the Release Descriptions for new release of this project, I often see CVE IDs about security patches incorporated in the release. I would like to see links to the descriptions of each CVE, or the title of each CVE, or a combination.

**Why is this needed**:

This would help in assessing the urgency of upgrading EKS clusters using these AMIs.

**Comment by heybronson** [comment]
Thanks for the feedback. We'll incorporate this into release notes going forward.
