### ISSUE TITLE
Incorrect ephemeral capacity detected by kubelet when using large EBS volumes

### ISSUE THREAD

**Issue by chaosun-cs** [awslabs/amazon-eks-ami#647]
**What happened**:
`1Ti` EBS is configured to be mounted as / file system for ephemeral storage usage. When node is up, `kubectl describe node` shows it only has `4Gi` ephemeral storage capacity.

**What you expected to happen**:
EKS node can detect correct ephemeral storage capacity

**How to reproduce it (as minimally and precisely as possible)**:
Configure `1Ti` EBS to mount to EKS node as / file system, and check for ephemeral storage capacity

**Anything else we need to know?**:
Restarted kubelet process and it worked. Tried to lower the size to `800Gi` and it also worked. Possibly a racing issue that kubelet started before EBS volume is formatted and mounted properly.

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): m5.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.5
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.17
- AMI Version: amazon-eks-node-1.17-v20210310
- Kernel (e.g. `uname -a`): Linux ip-10-4-98-45.ec2.internal 4.14.219-164.354.amzn2.x86_64 #1 SMP Mon Feb 22 21:18:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):

```BASE_AMI_ID="ami-0a1ccc021b9016ec9"
BUILD_TIME="Wed Mar 10 19:46:36 UTC 2021"
BUILD_KERNEL="4.14.219-164.354.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by chaosunsfx** [comment]
we tried to check `df` output in userdata, and this is the result
```
+ lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  1.1T  0 disk
├─nvme0n1p1   259:1    0  1.1T  0 part /
└─nvme0n1p128 259:2    0    1M  0 part
+ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           3.8G  272K  3.8G   1% /run
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1  4.0G  1.7G  2.4G  42% /
+ echo 'sleeping for 30 seconds'
sleeping for 30 seconds
+ sleep 30
+ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           3.8G  264K  3.8G   1% /run
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1  1.1T  2.9G  1.1T   1% /
```
`4G` is the initial size, which is also shown as ephemeral storage capacity, while the requested size is `1T` and it was able to show correctly after some time

**Comment by PerGon** [comment]
We've experienced the exact same thing. I believe this statement here is correct:

> Possibly a racing issue that kubelet started before EBS volume is formatted and mounted properly.

We did a small hack to fix it, which was to change the userdata and add a "sleep 30" before bootstrap of the node
```
sleep 30

# Bootstrap and join the cluster
/etc/eks/bootstrap.sh --b64-cluster-ca (...)
```

Haven't had the time to look how a proper fix would look tho.

**Comment by cartermckinnon** [comment]
To clarify, kubelet does become aware of the new device after it's attached, correct? I'm not sure blocking kubelet startup on EBS mounts is desirable, because kubelet can do other things while this EBS volume is being mounted (like pulling a user's workload images, system images, running pods that have no storage requirement, etc.). EBS mounts are intentionally async, IIUC.

If a pod's containers have an `ephemeral-storage` request, the pod won't be scheduled until a node has resources that satisfy it; that seems like the proper solution here.

Additionally, I don't think #663 would help here, because that's just adding a dependency on the short-lived (<5 second) `cloud-init init` call, it's not capturing the EBS mount process.

**Comment by PerGon** [comment]
> To clarify, kubelet does become aware of the new device after it's attached, correct?

Eventually, yes. But given a big enough EBS volume, the mounting can take enough time that kubelet will start scheduling pods in the node. When such thing happens, the kubelet will be fail to schedule the pod and the retry mechanism takes a long time.
We were getting messages like this:
```
ip-10-15-24-201 kubelet: E1022 12:55:37.096972    4924 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "travis-job-<redacted>(8c523353-1465-11eb-ba3b-02547028e36e)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "travis-job-<redacted>": Error response from daemon: Conflict. The container name "/k8s_POD_travis-job-<redacted>_travis-pro_8c523353-1465-11eb-ba3b-02547028e36e_0" is already in use by container "ba0d3f34ef5c2ec8d48d
```
The pod would eventually be scheduled but would take 10+ minutes.
I believe this behaviour might have been improved in k8s 1.22 as per https://github.com/kubernetes/kubernetes/issues/94557

> Additionally, I don't think https://github.com/awslabs/amazon-eks-ami/pull/663 would help here, because that's just adding a dependency on the short-lived (<5 second) cloud-init init call

Not sure if I agree 🤔 
I kind of feel that it's best to start the kubelet once the node fully initiated - as ready as possible to start it's most important service. Also, if it's a short-lived call (<5 seconds) why not ensure the node is best prepared to execute the kubelet?

> it's not capturing the EBS mount process.

According to [these docs](https://cloudinit.readthedocs.io/en/latest/topics/boot.html#network) that cloud-init service does take care of mounting the EBS.
![image](https://user-images.githubusercontent.com/725020/183081284-49e25784-8905-427d-b51b-c56a7e443d69.png)
