### ISSUE TITLE
Provide ability to install packages or skip logs if not needed

### ISSUE THREAD

**Issue by jdb-at-aws** [awslabs/amazon-eks-ami#657]
**What would you like to be added**:

Not everyone requires the IP tables logs. The script currently requires iptables to be installed and if it isn't, the script fails. Instead, if /iptables installed/then send logs/else skip logs.

**Why is this needed**:

Some customers are locked down and cannot install iptables on their hosts and don't need those particular logs to debug all issues.

**Comment by mmerkes** [comment]
Are you talking about the log collector script? iptables comes standard in AmazonLinux AMIs, so it should be present in the majority of AMIs. That being said, I don't think it's unreasonable to add a branch to the log collector script to check if iptables is there before doing anything that expects it to be.

**Comment by ttres** [comment]
@jdb-at-aws `iptables` will be used only if available, and the script will not fail otherwise. See the [get_iptables_info](https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh#L302) function.

Can we set this issue as resolved?
