### ISSUE TITLE
Enable Linux PSI metrics

### ISSUE THREAD

**Issue by jacknagel** [awslabs/amazon-eks-ami#660]
**What would you like to be added**:
Enable kernel [PSI metrics](https://facebookmicrosites.github.io/psi/docs/overview.html) on EKS AMIs.

**Why is this needed**:
We would like to collect PSI metrics using node-exporter. This feature is present, but not enabled, on the latest EKS AMI:

```
$ cat /proc/pressure/cpu
cat: /proc/pressure/cpu: Operation not supported
$ uname -a
Linux ip-10-210-10-154.ec2.internal 5.4.110-54.182.amzn2.x86_64 #1 SMP Fri Apr 9 17:56:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /boot/config-`uname -r` | grep PSI
CONFIG_PSI=y
CONFIG_PSI_DEFAULT_DISABLED=y
```

**Comment by ellistarn** [comment]
+1, this would be super nice for monitoring tools, especially when combined with cgroupsv2

**Comment by sidewinder12s** [comment]
@cartermckinnon Any update on if this can be enabled out of the box since we should be able to get something on the older kernel the AMI currently uses?

**Comment by cartermckinnon** [comment]
No concerns from me, tested with 1.24 (on the 5.4 kernel) and seems fine. Opened #1161 .
