### ISSUE TITLE
Containerd version upgrade to 1.4.4

### ISSUE THREAD

**Issue by amine250** [awslabs/amazon-eks-ami#665]
**What happened**:
We ran into the following bug : https://github.com/containerd/containerd/issues/4837

When running a docker build inside a Gitlab CI `docker service`, the process exits with the error:
```
io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/597/oom_score_adj: invalid argument
```

Apparently, this bug is fixed in containerd v1.4.4. However, the latest EKS-optimized AMI is still using containerd v1.4.1:
```sh
sh-4.2$ containerd --version
containerd github.com/containerd/containerd 1.4.1 c623d1b36f09f8ef6536a057bd658b3aa8632828
```

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): m5.2xlarge
- EKS Platform version: eks.1
- Kubernetes version: 1.19
- AMI Version: v1.19.6-eks-49a6c0 - AMI ID: ami-0175f435d86f1453d
- Kernel: Linux ip-10-xx-xx-xx.eu-west-1.compute.internal 5.4.110-54.189.amzn2.x86_64 #1 SMP Mon Apr 26 21:25:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Release information :

```
BASE_AMI_ID="ami-004a571bc4ab7023a"
BUILD_TIME="Wed May 12 16:45:14 UTC 2021"
BUILD_KERNEL="5.4.110-54.189.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by pavan-tri** [comment]
Similar issue with Layer as well If the image has more layer we hit the issue mentioned [here](https://github.com/containerd/containerd/issues/4684). 1.4.4 is becoming more relevant.

**Comment by pavan-tri** [comment]
I guess https://github.com/awslabs/amazon-eks-ami/commit/3b732a4a564acabe1ea262f04555d92766d794db seals the deal.  Thanks for the update.

**Comment by abeer91** [comment]
Closing this issue as the version of containerd has been upgraded in the latest release - https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210720

**Comment by noose** [comment]
@abeer91 it's still happening. 
I'm trying to deploy bitbucket runner on EKS ( v1.21.2-eks-55daa9d -  ami:amazon-eks-node-1.21-v20210830)
``` {"message":"io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/570/oom_score_adj: invalid argument\n: exit status 1: unknown"}```
