### ISSUE TITLE
make 1.20 packer unable to find subnet by tag or id

### ISSUE THREAD

**Issue by awkmon** [awslabs/amazon-eks-ami#667]
**What happened**:
Using environment variables for make authentication, packer is able to connect to AWS through profile under assumed role and finds ami successfully, but is unable to find the subnet by subnet-id or tag.

      "source_ami_filter": {
        "filters": {
          "name": "{{user `source_ami_filter_name`}}",
          "architecture": "{{user `arch`}}",
          "root-device-type": "ebs",
          "state": "available",
          "virtualization-type": "hvm"
        },
      "subnet_filter": {
        "filters": {
           "tag:Name": "xxxx3-1c-ts"
        }
      },

ERROR:
==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: amazon-eks-node-1.20-v20210519
    amazon-ebs: Found Image ID: removed
==> amazon-ebs: No Subnets was found matching filters: {
==> amazon-ebs:   Filters: [{
==> amazon-ebs:       Name: "tag:Name",
==> amazon-ebs:       Values: xxxx3-1c-ts"]
==> amazon-ebs:     },{
==> amazon-ebs:       Name: "state",
==> amazon-ebs:       Values: ["available"]
==> amazon-ebs:     }]
==> amazon-ebs: }
Build 'amazon-ebs' errored after 3 seconds 304 milliseconds: No Subnets was found matching filters: {
  Filters: [{
      Name: "tag:Name",
      Values: ["xxxx3-1c-ts"]
    },{
      Name: "state",
      Values: ["available"]
    }]
}

The aws cli command works  - 
aws ec2 describe-subnets --region us-east-1 --profile rr --filters Name=tag:Name,Values="xxxx3-1c-ts"
SUBNETS False   us-east-1c      use1-az4        248     x.x.x.x/24   False   False   False   666666666    available       arn:aws:ec2:us-east-1:66666666:subnet/subnet-42      subnet-42        vpc-42
TAGS    aws:cloudformation:logical-id   TestSubnet
TAGS    Account DELETED
TAGS    Class   build
TAGS    aws:cloudformation:stack-name   networks
TAGS    Name    xxxx3-1c-ts
TAGS    Environment     ts
TAGS    Owner   Network

**What you expected to happen**:
I would expect the packer calls using the eks-worker-al2.json file to work for the ami, as well as the subnet and not fail on subnet.

**How to reproduce it (as minimally and precisely as possible)**:
Master pull this morning.
json file updated with these parameters and filters.
Use a profile with an assumed role that works from aws cli v2+.

**Anything else we need to know?**:
Not that I can think of.

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): Not getting far enough to matter, but using default.
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):  not making that far, but will be eks.1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.20
- AMI Version: Attempting RHEL 8, but can't get past subnet.
- Kernel (e.g. `uname -a`): 5.8.0-53-generic
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by awkmon** [comment]
Forgot to mention that I'm using packer 1.7.2 and GNU make 4.2.1

**Comment by mmerkes** [comment]
A few things on this:

1. Are you using the same IAM role/user for building the AMI as you are with the `aws ec2 describe-subnets` call?
  - As a sanity check, you can stick a [get-caller-identity](https://docs.aws.amazon.com/cli/latest/reference/sts/get-caller-identity.html) in one of the build scripts to confirm that it's the role you expect.
2. Does the role/user have sufficient permissions to call EC2?
3. The default region is [us-west-2](https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L3). Are you overriding that to `us-east-1` when you're running make?

**Comment by awkmon** [comment]
1. Yes, same role. There is no other one available, since I am building from a non-AWS environment (my local laptop).
2. Yes, I'm actually building with my full Cloud Admin role from my local Ubuntu 20.04 VM with the aws cli configured to operate as myself. The environment variables being used during make came from my personal keys and token in the RR profile.
3. Yes, i am setting region to us-east-1 and it finds/verifies the source AMI, then never is able to validate subnet by any means.

Why it obeys the environment upon initial call for the non-default local profile and then takes a turn, I am not sure. I suspect it is using another profile for the subsequent call after validating the source AMI, but I have not been able to prove it.

**Comment by mmerkes** [comment]
Have you tried passing in the [subnet ID as an argument](https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L33)?

**Comment by awkmon** [comment]
as an argument to the packer command in the Makefile? No, I have not.

**Comment by awkmon** [comment]
Passing in the subnet_id as an argument had no effect. CloudTrail confirmed that the SESSION was being ignored. I switched providers to static, instead of environment. Usin the assume_role section to hard code the session and role_arn worked.

"assume_role": {
    "role_arn"    :  "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME",
    "session_name":  "SESSION_NAME",
    "external_id" :  "EXTERNAL_ID"
}
