### ISSUE TITLE
How to add two node labels to bootstrap arguments using --kubelet-extra-args

### ISSUE THREAD

**Issue by D2809** [awslabs/amazon-eks-ami#67]
I am trying doing this
ParameterKey: "BootstrapArguments", ParameterValue: "--kubelet-extra-args --node-labels=MyKey=MyValue,MyKey2=MyValue2"
But this is not working.
If I try adding only one key pair value then node labels are gettig attached to the node.
What is the error that I am doing

**Comment by emman27** [comment]
Not sure what bootstrap arguments are, but here's my userdata script on my EKS worker nodes:

```
#!/bin/bash -xe

/etc/eks/bootstrap.sh cluster_name --kubelet-extra-args '--node-labels=something=hello,somethingelse=bye --register-with-taints=taint1=true'

```

**Comment by micahhausler** [comment]
As @emman27 you can surround the arguments with a single quote

**Comment by adv4000** [comment]
This didn't worked for me:
`"--node-labels=node.kubernetes.io/lifecycle=normal,role=general"`

This Worken for me:
`"'--node-labels=node.kubernetes.io/lifecycle=normal,role=general'"`
