### ISSUE TITLE
Amazon EC2 High Memory Instances not available in amazon-eks-nodegroup.yaml

### ISSUE THREAD

**Issue by svadda** [awslabs/amazon-eks-ami#673]
Amazon EC2 High Memory Instances not available in amazon-eks-nodegroup.yaml

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): u-6tb1.56xlarge, u-6tb1.112xlarge, u-9tb1.112xlarge, u-12tb1.112xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.4
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.16
- AMI Version: CentOS release 6.10
- Kernel (e.g. `uname -a`): Linux idb-api-576cbc9d59-99dbb 4.14.177-139.253.amzn2.x86_64 #1 SMP Wed Apr 29 09:56:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node): 

```
```

**Comment by mmerkes** [comment]
Looks like they [became available May 12th](https://aws.amazon.com/about-aws/whats-new/2021/05/four-ec2-high-memory-instances-with-up-to-12tb-memory-available-with-on-demand-and-savings-plan-purchase-options/). We should be able to add them easy enough.

**Comment by svadda** [comment]
Thank You Matt!

**Comment by svadda** [comment]
Any ETA on when this can be added? Thanks!

**Comment by svadda** [comment]
@mmerkes, Thanks for the updates.
