### ISSUE TITLE
Please upstream the gpu AMI creation code

### ISSUE THREAD

**Issue by anish** [awslabs/amazon-eks-ami#674]
**What would you like to be added**:
The code that is used to build gpu eks nodes should be visible in this repo

**Why is this needed**:
We use this repo to build our own EKS AMIs, recently when we started exploring GPU workloads, we noticed the code was missing. This requires reverse engineering of official images or guessing the right commands to run, we would like to avoid drift from the official images as far as possible

**Comment by OysteinVesth** [comment]
Are there any plans to add this @cartermckinnon?

**Comment by 3r1co** [comment]
Hello, do you have any plan to share the GPU AMI creation code?

**Comment by schibrikov** [comment]
Interested in this as well. Would be nice to have an easy way to slightly customise the GPU-enabled AMI.
