### ISSUE TITLE
Error when pulling items from bucket specified in binary_bucket_region

### ISSUE THREAD

**Issue by geoffo-dev** [awslabs/amazon-eks-ami#678]
**What happened**:

When trying to run the packer 'make' it tries to download some of the binaries from this address:

https://amazon-eks.s3.eu-west-2.amazonaws.com/1.15.12/2020-11-02/bin/linux/amd64/kubelet

However it doesn't properly redirect to 

https://amazon-eks.s3-us-west-2.amazonaws.com/1.15.12/2020-11-02/bin/linux/amd64/kubelet

This appears to both an issue with the default location (which is pulled during the make) and a change to the url from **s3.** to **s3-**

**What you expected to happen**:

Should download the correct url

**How to reproduce it (as minimally and precisely as possible)**:

Run the make command once it is downloaded

**Anything else we need to know?**:

Changing line 177 to:

`
S3_URL_BASE="https://$BINARY_BUCKET_NAME.s3-$BINARY_BUCKET_REGION.$S3_DOMAIN/$KUBERNETES_VERSION/$KUBERNETES_BUILD_DATE/bin/linux/$ARCH"<br class="Apple-interchange-newline">`

in

https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh 

appears to correct the issue.

**Environment**:
- AWS Region: eu-west-2
- Instance Type(s): any

**Comment by cartermckinnon** [comment]
This should be resolved by https://github.com/awslabs/amazon-eks-ami/commit/acf0d78478346de4dfd3b18aef396a483a3443a3.
