### ISSUE TITLE
Add rootless buildkit support for EKS nodes.

### ISSUE THREAD

**Issue by smothiki** [awslabs/amazon-eks-ami#683]
**What would you like to be added**:
Add `user.max_user_namespaces=28633` to `/etc/sysctl.conf (or /etc/sysctl.d)` and run `sudo sysctl -p `
needs to be run to enable overlayfs snapshotter for amazon eks node. 

**Why is this needed**:
after Kubernetes 1.20. Kubernetes is dropping support for docker as the default container runtime. Since docker will be removed after 1.20. The user who is leveraging Docker for container builds within the node leveraging docker socket mount will not be able to do that. To get buildkitd working in EKS k8s  the above-mentioned changes are needed. To allow users to perform incluster container builds.

**Comment by pavan-tri** [comment]
scripts/install-worker.sh has examples of how to update sysctl.conf

**Comment by cartermckinnon** [comment]
We plan to remove `docker` from the AMI entirely for an upcoming Kubernetes version (though admittedly we've kicked that can a couple times already); so it probably doesn't make sense to make a docker-specific change right now.

If you want to add more details on how `user.max_user_namespaces=28633` relates to buildkit, we could reopen this.

**Comment by steved** [comment]
For what it's worth, the context is that to allow `buildkit` to run "rootless" on Red Hat < 8,  this workaround must be applied: https://github.com/moby/buildkit/blob/v0.10.6/docs/rootless.md#rhelcentos-7 (if the direct link doesn't work, open "Old distributions"). If it isn't applied, `buildkit` must run as `0` and `privileged`.

**Comment by steved** [comment]
Nope, that's accurate. Looks like it's not an issue with user namespacing, but rather with the current kernel version and [user-namespaced support for mounting overlayfs](https://github.com/torvalds/linux/commit/459c7c565ac36ba09ffbf24231147f408fde4203). Thanks for the tip, sorry for the noise!
