### ISSUE TITLE
AWS custom AMI bootstrap.sh troubleshoot 

### ISSUE THREAD

**Issue by tppalani** [awslabs/amazon-eks-ami#686]
**What happened**:

EKS cluster not able to join to the cluster. 
1. VPC verified 
2. security group verified 
3. EKS cluster security group & subnet are same both cluster and node group.

**What you expected to happen**:

1. how to check my bootstrap.sh script is executed or not?
2. ssh into node group
3.  Executing below command  no response from the terminal
```
journalctl -f -u kubelet
-- Logs begin at Mon 2021-06-28 12:00:11 UTC. --
```

**How to reproduce it (as minimally and precisely as possible)**:

1.  Launch template created with custom AMI.
2. bootstrap.sh file created based my endpoint and CA values

```
#!/bin/bash
set -ex
B64_CLUSTER_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSRTR4cWRPTmFBM1NLaGt3b3QwK0thUFlTcHRjWApBT3lZMUl6ME9mZTA4dXJlNWVmM0IyTDdpQVBkQTJBWUhMbURienk5T1l4S2g0SDM3TjgwOWl4OENjMFh0ckhyClZjRE1QVis3ZUVwWEhERDEwS0R1aEpLRG43cUR4NVhFTHRxU2txTFoxZmdoa2NNSWFFVTVkSjIvanBzaE5UUFYKT0puUWw3Z1Y1TGNSZlpJeStRcWZUcjQxOEdQbWorMGdWdVJJYm40MW5ySEVab3hzaWlZS2JoT1dtYzFVSGxhNwpXSFJkK3dsYlE3K241VmRYczhXQ01vUUFtNWZmVktVN1lqdU5Uak9YMFlkenZFMzFtTURsV2ZuVStJVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
API_SERVER_URL=https://504E9A153B3F63259E9F92706.sk1.us-west-2.clusters.wesley.amazonaws.com
/etc/eks/bootstrap.sh mycluster --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL
```
3. From AWS console - node group created using launch template version.
4.  after 20 min Node group not able to join EKS cluster.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-central-1
- Instance Type(s): a1.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.1"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.20
- AMI Version: 
- Kernel (e.g. `uname -a`):  ```Linux ip-10-176-17-50 4.14.232-176.381.amzn2.x86_64 #1 SMP Wed May 19 00:31:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
- 
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-03192d23e906cf923"
BUILD_TIME="Tue Jan 12 22:52:08 UTC 2021"
BUILD_KERNEL="4.14.209-160.339.amzn2.aarch64"
ARCH="aarch64"
```

**Comment by uddr** [comment]
I have the same issue with K8s 1.19

**Comment by tppalani** [comment]
Could you please some one help on this.

**Comment by tppalani** [comment]
Just Adding one point my custom image has MFA authentication enabled, when the node group trying to join EKS cluster will this cause any issue?

**Comment by mmerkes** [comment]
Sorry for the delay. Let me take a look.

I see that you're running the 4.14 kernel. Did build the image explicitly with that or downgrade the kernel from 5.4?

To see if the bootstrap script run, you should be able to check `/var/log/cloud-init.log` for the userdata output. Perhaps, there's interesting data in there?
