### ISSUE TITLE
Add a primary subnet ID label to the Kubernetes node at bootstrap

### ISSUE THREAD

**Issue by stevehipwell** [awslabs/amazon-eks-ami#690]
**What would you like to be added**:
The Kubernetes node to be given a label containing the primary ENI subnet ID.

**Why is this needed**:
When using the aws-vpc-cni in custom networking mode in a VPC with the AWS recommended public/private subnet split there is no suitable default node label to support using a different secondary subnet per public/private split (the docs have a manual action here). If the node is labelled with the primary ENI subnet ID we can use this to make sure that the secondary subnets are separated by public/private subnets.

Related to https://github.com/bottlerocket-os/bottlerocket/issues/1647.

**Comment by dlaidlaw** [comment]
Any time you add a label to a node you really have to consider how this is going to affect the cluster-autoscaler. The cluster-autoscaler can be configured to balance similar node groups, and uses labels to do the grouping. To be considered similar, the labels of the nodes must match. Only some of the labels are ignored on the cluster-autoscaler.

The cluster-autoscaler includes the ability to add labels to the ignored label list, but the ignored labels are passed to the cluster autoscaler on the command line. Adding another label can break existing cluster autoscaler deployments.

**Comment by stevehipwell** [comment]
@dlaidlaw thanks for this information; but I still think that this is required for the correct functionality of the aws-vpc-cni with custom networking. The current zone labels must be ignored so this would be another label that needed ignoring.

**Comment by cartermckinnon** [comment]
Seems like this could be handled by the node controller in https://github.com/kubernetes/cloud-provider-aws instead of the bootstrap script. Has anything changed since you opened this issue?

**Comment by stevehipwell** [comment]
@cartermckinnon we no longer need this as we changed our architecture, so I'm happy for you to close it. If this issue was going to be solved it'd be better done at the VPC CNI level with an auto discovery tagging scheme.
