### ISSUE TITLE
Update Makefile default AMI to LTS AL2 AMI

### ISSUE THREAD

**Issue by jhaynes** [awslabs/amazon-eks-ami#7]
Today, the [Makefile](https://github.com/awslabs/amazon-eks-ami/blob/19279be9fa95dce0057474609fc28f094fa4cf6d/Makefile#L4) references the AL2 Candidate AMI as the default. We should update that to reference the latest [LTS AL2 release](https://aws.amazon.com/amazon-linux-2/release-notes/).

**Comment by mbartsch** [comment]
the other issue I saw, is that the Makefile will only work in a us-west-2 region. I made a few changes to allow to pass the region as an option to make
make REGION=[us-east-1|us-west-2] ami
