### ISSUE TITLE
Version 1.21 AMI target not specified in Makefile

### ISSUE THREAD

**Issue by caphrim007** [awslabs/amazon-eks-ami#707]
**What happened**:

Makefile targets for version 1.21 of the k8s is missing from the makefile

**What you expected to happen**:

Target should exist

**Comment by hcampbel** [comment]
Same issue here. Our Jenkins pipeline for EKS v1.21 is failing due to the lack of target in the Makefile

```
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] sh
+ cp -f pipelines/packer/eks-worker-al2-121.json pipelines/amazon-eks-ami/eks-worker-al2.json
[Pipeline] sh
+ cd pipelines/amazon-eks-ami
+ make 1.21
make: *** No rule to make target '1.21'.  Stop.
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test)
Stage "Test" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Review)
Stage "Review" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy)
Stage "Deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 2
Message :Build FAILED for task jenkins-Base_Images-SecureBaseImage_AWS_EKS_121-1
```

**Comment by ravisinha0506** [comment]
The [PR](https://github.com/awslabs/amazon-eks-ami/pull/708) is merged now, could you please retry?

**Comment by hcampbel** [comment]
Confirmed successful build for us now with the merge in place 👍

**Comment by caphrim007** [comment]
confirming it works for me too

**Comment by anish** [comment]
@ravisinha0506 any idea when this will be part of release ?

**Comment by ravisinha0506** [comment]
@anish This change is already [merged](https://github.com/awslabs/amazon-eks-ami/pull/708). Please let us know if you are still seeing any issue.

**Comment by anish** [comment]
@ravisinha0506 not seeing an issue, I meant more of this release https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210720

claims to have 1.21 support but does not have the makefile patch. I would prefer it to be part of the actual release and not require a cherry pick

**Comment by cartermckinnon** [comment]
Just an FYI -- we will no longer add a new `make` target for every Kubernetes version. There is a new `make` variable that can be used to specify the version instead, for example:
```
# old way
make 1.28
# new way
make k8s=1.28
```

Similarly, the latest binaries for the specified Kubernetes minor version will be retrieved, so the latest bug and security fixes are included. The `kubernetes_version` and `kubernetes_build_date` is no longer hard-coded in the Makefile. More on that here: https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#choosing-kubernetes-binaries
