### ISSUE TITLE
Creating containerd flavored AMIs

### ISSUE THREAD

**Issue by dany74q** [awslabs/amazon-eks-ami#710]
**What would you like to be added**: The ability to toggle between dockerd and containerd as a CRI is awesome ! I think that it would make it more accessible if there were containerd flavored pre-backed AMI-s (i.e. `amazon-eks-node-1.20-v20210720-containerd`).

**Why is this needed**: This is especially useful when utilizing managed node groups, spawning them from IaC frameworks a-la terraform; in those cases, changing the user data of the default launch template is a bit hacky.

This is also useful in cases where third party tools manage AKS clusters for other accounts - where if those lack the `ec2:RunInstances` action, they would not be able to patch the underlying ASG to use a new launch template version.

As this feature is probably not going to be exposed in the node group API in the upcoming future, this might be a simple yet very helpful alternative.

Thanks !

**Comment by mikestef9** [comment]
We do not plan on adding this flag to the MNG API, or building a separate AMI, given that it is a temporary transition to containerd, and not a long term scenario of having multiple container runtime choices. More details [here](https://github.com/aws/containers-roadmap/issues/313#issuecomment-831617671).
