### ISSUE TITLE
EKS bootstrap: --enable-docker-bridge is not working 

### ISSUE THREAD

**Issue by dschunack** [awslabs/amazon-eks-ami#715]
**What happened**:

With the release of v20210716 or newer is the bootstrap option "--enable-docker-bridge" no longer working.
The bootstrap script was changed to integrate[ containerd support](https://github.com/awslabs/amazon-eks-ami/commit/af6a02dec0171bae7a20605e1427ba4d9e051bc2#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2R422-L410) and the restart of the docker daemon was replaces with a start of the docker daemon, but docker is enabled and running by default after the installation. Means the start command doesn't have any impact and the docker0 bridged will not be activated due to an missing restart to load the new docker daemon.json config. The code in the docker daemon.json is OK and a manual restart of the docker daemon activates the docker0 bridge. Looks like that the new bootstrap scripts was not 100% tested before it was released.

**What you expected to happen**:
docker0 bridge is activated and used by the docker daemon.

**How to reproduce it (as minimally and precisely as possible)**:

Start a new EKS Node with AMI Image v20210716 or newer and use the "--enable-docker-bridge true" for the bootstrap of the node. Use "ip a s docker0" to check if the docker0 bridge was created. 
```
~]# ip a s docker0
Device "docker0" does not exist.
```

Execute "systemctl restart docker" and check it again. After the restart of the service is the docker0 bridge available. 

```
~]# ip a s docker0
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:38:08:2b:a4 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
```

**Anything else we need to know?**:

You can disabled docker by default if you build the AMI images or you change the the following line [L439](https://github.com/awslabs/amazon-eks-ami/blob/0a532cf9cc998a6d4779c9f9a8fc57b02ed5194f/files/bootstrap.sh#L429) with a restart instead of a start.

**Environment**:
- AWS Region: all
- Instance Type(s): all
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): all
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): all
- AMI Version: v20210716 or newer
- Kernel (e.g. `uname -a`): 5.4.129-63.229.amzn2.x86_64 #1 SMP Tue Jul 20 21:22:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-01e809b6b105324b3"
BUILD_TIME="Thu Jul 22 16:13:01 UTC 2021"
BUILD_KERNEL="5.4.129-63.229.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by ravisinha0506** [comment]
Ack. Looking into this.

**Comment by ravisinha0506** [comment]
The change is merged to the master branch.

**Comment by ravisinha0506** [comment]
Hi @mrparkers, we have made few ami releases which contain this fix. Please use the [latest release](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210830) and let us know if any issues are found.

**Comment by dschunack** [comment]
Hi,

Patch is available since AMI release v20210813, but it's not described in any of the release notes. If you publish new releases it make sense to add also the fixed issues in the comments of the release.

**Comment by mrparkers** [comment]
Thanks for the new release, the newest AMIs have resolved the issue for me 👍

**Comment by saurav-agarwalla** [comment]
Resolving since this is fixed now. I'll make sure that we put these fixes in the release notes in the future.
