### ISSUE TITLE
Add retry logic around `aws eks wait cluster-active` in bootstrap.sh script

### ISSUE THREAD

**Issue by nithu0115** [awslabs/amazon-eks-ami#720]
**What would you like to be added**:
Add retry logic around `aws eks wait cluster-active` in bootstrap.sh script

**Why is this needed**:
Launching 400 nodes resulted in `Waiter ClusterActive failed: Too Many Requests`

**Comment by aws-tatarkin** [comment]
Line 312 https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L312

**Comment by nithu0115** [comment]
I see retry logic already there. Closing the issue.
