### ISSUE TITLE
EKS Log Collector SSM document broken

### ISSUE THREAD

**Issue by sidewinder12s** [awslabs/amazon-eks-ami#725]
**What happened**:

Provided SSM document for collecting logs does not work.

**How to reproduce it (as minimally and precisely as possible)**:

Run SSM document on an EKS 1.19 node

**Anything else we need to know?**:

Appears the awscli install is not working as expected. 
It is installed after running the SSM document, but at `/usr/bin/aws`

```bash
sh-4.2$ which aws
/usr/bin/aws
```

Updating the document to use that explicit location of awscli, and it works.

Annoyingly SSM reports the Command run as successful as well.

```log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18191  100 18191    0     0  1184k      0 --:--:-- --:--:-- --:--:-- 1184k
Unsupported Python version detected: Python 2.7
To continue using this installer you must use Python 3.6 or later.
For more information see the following blog post: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/

/var/lib/amazon/ssm/instance-id/document/orchestration/ff98188f-38e0-4659-8816-ae6d30330dda/PatchLinux/_script.sh: line 15: /usr/local/bin/aws: No such file or directory
/var/lib/amazon/ssm/instance-id/document/orchestration/ff98188f-38e0-4659-8816-ae6d30330dda/PatchLinux/_script.sh: line 18: /usr/local/bin/aws: No such file or directory
```

**Environment**:
- AWS Region: us-east-1
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.19
- AMI Version: v20210526
- Release information (run `cat /etc/eks/release` on a node):
```
BASE_AMI_ID="ami-004a571bc4ab7023a"
BUILD_TIME="Wed May 26 18:04:12 UTC 2021"
BUILD_KERNEL="5.4.117-58.216.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by sidewinder12s** [comment]
Looks like this is also still installing v1 of the CLI, maybe should just be updated to v2: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install

**Comment by oussama-mechlaoui** [comment]
Updating AWS CLI to v2 resolved the issue for me.

**Comment by cartermckinnon** [comment]
Closing this as resolved.
