### ISSUE TITLE
Make Loglevel configurable in bootstrap.sh

### ISSUE THREAD

**Issue by steveizzle** [awslabs/amazon-eks-ami#733]
**What would you like to be added**:

The Verbosity of kubelet logs is hard coded in bootstrap.sh 
https://github.com/awslabs/amazon-eks-ami/blob/5d109a125ef3876209850d0d4308d1a77ddf601c/files/bootstrap.sh#L396

I would like to configure the verbosity of the logs (kubelet --v flag) dynamically without having to rewrite the 10-kubelet-args.conf file and reload the daemon.

Is there a reason why this is hard coded? Could it not stay in the default loglevel (dont know what that is..) and when needed change with kubelet-extra-args?

An easy solution would also be to simply add a new parameter with default=2. I would be glad to add this.

**Why is this needed**:

It seems like a parameter which should be configurable. Also i opened a support case and i was asked to set the loglevel more verbose, which seems a little complicated. I always try to change the least possible and stay in the best supported state.

**Comment by steveizzle** [comment]
I added the loglevel  as extra-arg and now have two --v flags in the running kubelet process. It seems that the latter one is used, which means it currently works. But it seems a little hacky to have a process running with the same flag twice with two differnet values

**Comment by dschunack** [comment]
Make absolutely sense for me to implement a parameter to configure it directly in the bootstrap and not as double parameter.
