### ISSUE TITLE
Release kubelet version 1.20.7 

### ISSUE THREAD

**Issue by kakarotbyte** [awslabs/amazon-eks-ami#743]
Currently for 1.20 cluster EKS uses kubelet version 1.20.4. 

There's a bug in kubelet 1.20.4 which doesn't respect the ExecProbeTimeout Featuregate for dockershim 

https://github.com/kubernetes/kubernetes/pull/100200
https://github.com/kubernetes/kubernetes/issues/100198

and kubelet 1.20.7 has a fix for this bug. Therefore I request this to be added.

**Comment by arpanadhikari** [comment]
@abeer91 do we have an ETA on this? 

We're currently waiting for this version to be available to upgrade our EKS to 1.20

**Comment by abeer91** [comment]
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210830

Release has upgraded kubelet version to 1.20.7 , please let us know if this doesn't solve your problem.
