### ISSUE TITLE
/etc/sysctl.conf symlinked to /etc/sysctl.d/99-sysctl.conf

### ISSUE THREAD

**Issue by mikhailadvani** [awslabs/amazon-eks-ami#746]
**What happened**: Configuration changes made in /etc/sysctl.conf override configurations made in 99-kubernetes-cri.conf.

We had some legacy hardening configurations that set `net.ipv4.ip_forward = 0` in the /etc/sysctl.conf file in our AMI build which is based on the EKS optimised AMI. Though 99-kubernetes-cri.conf tries to override it by setting `net.ipv4.ip_forward = 1` it did not work since 99-kubernetes-cri.conf is alphabetically before 99-sysctl.conf and this led to coredns and other apps not able to communicate with the API server.

**What you expected to happen**: The /etc/sysctl.conf should be the base file and be overrideable by files in /etc/sysctl.d

**How to reproduce it (as minimally and precisely as possible)**: 

1. Create an AMI with `net.ipv4.ip_forward = 0` in /etc/sysctl.conf
2. Create a nodegroup with the AMI and choose container-runtime as containerd using the user data flags

Workloads on the new node will fail to communicate with the API server.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): any
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.20
- AMI Version: AMI Release v20210720
- Kernel (e.g. `uname -a`): 5.4.129-63.229.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by jeff-armis** [comment]
> According to the [sysctl manpage](https://man7.org/linux/man-pages/man8/sysctl.8.html), the expected behavior is that the entries within a given file are applied in order, and overwrite any value given to the same setting previously.
> 
> The order that the files are read are listed below: /etc/sysctl.d/_.conf /run/sysctl.d/_.conf /usr/local/lib/sysctl.d/_.conf /usr/lib/sysctl.d/_.conf /lib/sysctl.d/*.conf /etc/sysctl.conf
> 
> Because /etc/sysctl.conf is the final configuration read, it is processed unconditionally (i.e. an identically-named file or value in an earlier directory doesn’t override it).

That makes sense, but if `net.ipv4.ip_forward = 0` is required, why not make `install-worker.sh` more robust and actually update `/etc/sysctl.conf`? Would this change be accepted if we present a PR?

**Comment by jonpaul** [comment]
I'm encountering this issue as well and would like to understand if AWS is interested in fixing this.

**Comment by cartermckinnon** [comment]
> That makes sense, but if net.ipv4.ip_forward = 0 is required, why not make install-worker.sh more robust and actually update /etc/sysctl.conf? Would this change be accepted if we present a PR?

That would be a breaking change, because the value could no longer be overridden by a drop-in. I'll try to get this into our AL2023 template from the outset.

We try to make the AMI template compatible with the wide-array of base AMIs folks use in the wild, but it's not always possible. In this case the fix has to happen downstream, either in the base AMI or with a custom provisioner in your Packer template.

**Comment by varun-armis** [comment]
> 
> That would be a breaking change, because the value could no longer be overridden by a drop-in. I'll try to get this into our AL2023 template from the outset.
> 
> We try to make the AMI template compatible with the wide-array of base AMIs folks use in the wild, but it's not always possible. In this case the fix has to happen downstream, either in the base AMI or with a custom provisioner in your Packer template.

I'm trying to understand why the result of this issue is that the fix should happen downstream. My understanding is that without `net.ipv4.ip_forward = 1`, pod networking would not work and the EKS node would not be healthy. I think it would make sense that this value could not be overridden. Is there a configuration where `net.ipv4.ip_forward = 0` and the node still be healthy?

**Comment by cartermckinnon** [comment]
If you want to open a PR to make this change only for upcoming Kubernetes versions (1.30+), I think that would be reasonable. It just doesn't make sense for us to take any amount of risk on a change that comes with no benefit for the vast majority of our users (on existing release channels).
