### ISSUE TITLE
Documentation max number of pods / instance

### ISSUE THREAD

**Issue by elgamal2020** [awslabs/amazon-eks-ami#753]
https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

# Mapping is calculated from AWS EC2 API using the following formula:
# * First IP on each ENI is not used for pods
# * +2 for the pods that use host-networking (AWS CNI and kube-proxy)
#
#   # of ENI * (# of IPv4 per ENI - 1) + 2

This need to be re-written in a better understandable format 

The question here , can pods using multiple ENIs , do they belong to the same subnet or different subnet ?

Then why we reduce only one , as for the other 2 ENIs , there will be IPs dedicated as first IPs so we should reduce 3 ?

**Comment by jsamuel1** [comment]
And how does this calculation change when using Pod Security Groups?
