### ISSUE TITLE
kubelet version upgrade for not reflected in makefile, or changelog is incorrect for v20210830

### ISSUE THREAD

**Issue by anish** [awslabs/amazon-eks-ami#755]
Per this commit https://github.com/awslabs/amazon-eks-ami/pull/751/files

kubelet versions were upgraded as follows
```
1.17.12 -> 1.17.17
1.20.4 -> 1.20.7
```
in this release [20210830](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210830)
however this change is still missing from top of tree at https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L56-L68

The changelog also seems to have been updated (and incorrectly) 5 days after the release

**Comment by visunali** [comment]
merged https://github.com/awslabs/amazon-eks-ami/commit/d03b2ac370f473ddfd1f2d11d5ba93ecb5c1ec19
