### ISSUE TITLE
m6i instance type fails to join cluster

### ISSUE THREAD

**Issue by vedantzeb** [awslabs/amazon-eks-ami#757]
**What happened**:
m6i instance types in ap-southeast-1 region fail to join the EKS cluster(v1.21) with the error:

```
[   14.739700] cloud-init[2780]: + /etc/eks/bootstrap.sh <clustername> --kubelet-extra-args --node-labels=eks.amazonaws.com/nodegroup-image=ami-016e739e57ea162d9,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=<test> --b64-cluster-ca <redacted> --apiserver-endpoint <redacted> --dns-cluster-ip 172.20.0.10
[   14.857588] cloud-init[2780]: No entry for type 'm6i.xlarge' in /etc/eks/eni-max-pods.txt
``` 

This issue occurs in both cases when trying to add instances via EKS nodegroups with and without launch templates, as well as directly via auto-scaling groups.
 
**What you expected to happen**:
node should join the cluster

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an EKS cluster(v1.21) in ap-southeast-1 region.
2. Try to add EC2 instances via nodegroups or ASG

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-southeast-1
- Instance Type(s): m6i.xlarge, m6i.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- AMI Version: ami-016e739e57ea162d9
- Kernel (e.g. `uname -a`): 
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by treyhyde** [comment]
I think you are looking for #736 which hasn't yet made it into a released AMI.

**Comment by vedantzeb** [comment]
When is it planned for release?

**Comment by treyhyde** [comment]
> When is it planned for release?

I certainly would love to know.  I can't find a rhyme or reason on the release dates... the last release happened days after this patch was accepted but for an older commit.    Bottlerocket is in the same boat.   Change was accepted long ago but infrequent releases are holding these platforms back.  https://github.com/bottlerocket-os/bottlerocket/issues/1720

**Comment by tomharrisonjr** [comment]
For others reading this, I am having the same error in us-west-2 as well.

**Comment by recipedude** [comment]
same error us-east-1

**Comment by brianannis** [comment]
I think this release should resolve https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210914. FWIW I had to update the `aws-node` image to v1.9.1 as well for an m6i instance to join the cluster.

**Comment by abeer91** [comment]
As brianannis@ mentioned, you'll need a newer version of the AMI which support m6i instances and also need to update the CNI plugin.

**Comment by alisei** [comment]
For others reading this, you need to upgrade the CNI plugin to the latest version and make sure you use the latest AMI with support for this instance types.

**Comment by thunder-spb** [comment]
Another note. If you use cluster-autoscaler with --aws-use-static-instance-list=true you need to either disable this or bump to the latest version.
