### ISSUE TITLE
Option Max pods doesn't take into account the actual number of interfaces

### ISSUE THREAD

**Issue by alexvanbelle** [awslabs/amazon-eks-ami#76]
**Problem:**
- The bootstrap script enable to specify the option "use-max-pods" .
- these values are the maximum if and only if instances have the maximum number of ENI which is not what is defined in the getting started tutorial (single interface)
- it creates a bad user experience: pod scheduling error when no more IP is available for the actual ENI

**Version:**
- EKS K8S: 1.10
- AMI v14

**Reproduce:**
- Create an EKS cluster with one worker nodes t3.micro deployed with an Auto Scaling group
- Schedule a single container pod (without any resource request) and 4 replicas.
- 2 of them can't succeed and you'll get an error on IP attachment.

**Solution:**
Different approaches:
- Let the user set --use-max-pods 'false' and add another option: --use-max-pods-value (name can be better :) )
- Automatically detect the number of interfaces and adapt the max pod accordingly
- Add an option to the bootstrap script to specify the number of interfaces and adapt the max pod accordingly
- (out of scope of this project) Make Autoscaling group enable to manage multiple ENI ([currently, a workaround exists with a lambda function](https://aws.amazon.com/premiumsupport/knowledge-center/attach-second-eni-auto-scaling/))

**Comment by micahhausler** [comment]
> these values are the maximum if and only if instances have the maximum number of ENI which is not what is defined in the getting started tutorial (single interface)

Can you explain what you mean by this? The max-pods calculation comes from [/files/eni-max-pods.txt](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt), and calculates how many extra IPs the instance type can handle.

> AMI v14

Do you mean v24?

> Schedule a single container pod (without any resource request) and 4 replicas.
2 of them can't succeed and you'll get an error on IP attachment.

For a t3.micro, you're going to get a max-pods of `4`, but 2 of those pods are going to AWS CNI and kube-proxy. This leaves you with capacity for 2 running pods, which is what you are seeing. This is the intended behavior, as any additional pods won't get an IP assigned for this instance type.

If you want to set your own max-pods setting, you can use the following bootstrap.sh arguments 
```
--use-max-pods false --kubelet-extra-args --max-pods=123
```

Does that help?

**Comment by micahhausler** [comment]
The [AWS CNI provider](https://github.com/aws/amazon-vpc-cni-k8s) will [add ENI's](https://github.com/aws/amazon-vpc-cni-k8s/blob/9a4a0183db2a75fdb07114c7c1f0a13eab783c2f/pkg/awsutils/awsutils.go#L606-L637) and [assign IPs](https://github.com/aws/amazon-vpc-cni-k8s/blob/9a4a0183db2a75fdb07114c7c1f0a13eab783c2f/pkg/awsutils/awsutils.go#L804-L824) as necessary. Is this not working for you? If it is not, can you [file an issue on the CNI repo](https://github.com/aws/amazon-vpc-cni-k8s/issues/new)?

**Comment by alexvanbelle** [comment]
Ok. I didn't understood that the AWS CNI provider will do that automatically. I had the error and I just came to the conclusion it was because of a lack of ENI.

I'm closing this issue and try to get clear repros steps for filing an issue on the CNI repo.

Thanks for your help, it's really appreciated.
