### ISSUE TITLE
Update release notes BEFORE pushing new AMIs to EKS

### ISSUE THREAD

**Issue by llamahunter** [awslabs/amazon-eks-ami#769]
You continue to push new EKS AMI versions to SSM prior to updating their release notes. Please first update release notes before updating recommended version in SSM.
`/aws/service/eks/optimized-ami/<kube-version>/amazon-linux-2/recommended/release_version`

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): m5.2xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.20
- AMI Version: 1.20.7-20211001
- Kernel (e.g. `uname -a`): 
```Linux ip-10-191-144-183.ec2.internal 5.4.141-67.229.amzn2.x86_64 #1 SMP Mon Aug 16 12:51:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
- Release information (run `cat /etc/eks/release` on a node): 

```
BASE_AMI_ID="ami-01725fc47587f08fc"
BUILD_TIME="Tue Sep 14 00:50:32 UTC 2021"
BUILD_KERNEL="5.4.141-67.229.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by mmerkes** [comment]
We've updated our release to do this.
