### ISSUE TITLE
issue: aws cloudformation create-stack: Parameter validation failed

### ISSUE THREAD

**Issue by Vadim-Zenin** [awslabs/amazon-eks-ami#77]
Hello,

`aws cloudformation create-stack` command with multi labels `--kubelet-extra-args --node-labels=nodesgroup=main,subnets=private` return message
`Parameter validation failed:
Unknown parameter in Parameters[10]: "subnets", must be one of: ParameterKey, ParameterValue, UsePreviousValue, ResolvedValue`
Command:
```bash
    aws cloudformation create-stack \
  --stack-name ${EKS_NAME}-${EKS_NODE_GROUP01_NAME}  \
  --template-body file://amazon-eks-nodegroup.yaml \
        --capabilities CAPABILITY_IAM \
        --parameters \
      ParameterKey=NodeInstanceType,ParameterValue=${EKS_NODE_TYPE} \
      ParameterKey=NodeImageId,ParameterValue=${EKS_WORKER_AMI} \
      ParameterKey=NodeGroupName,ParameterValue=${EKS_NODE_GROUP01_NAME} \
      ParameterKey=NodeAutoScalingGroupMinSize,ParameterValue=${EKS_NODE_GROUP01_MIN} \
      ParameterKey=NodeAutoScalingGroupMaxSize,ParameterValue=${EKS_NODE_GROUP01_MAX} \
      ParameterKey=ClusterControlPlaneSecurityGroup,ParameterValue=${EKS_SG_CONTROLPLANE} \
      ParameterKey=ClusterName,ParameterValue=${EKS_NAME} \
      ParameterKey=Subnets,ParameterValue=${EKS_PRIVATE_IDS//,/\\,} \
      ParameterKey=VpcId,ParameterValue=${EKS_VPC_ID} \
      ParameterKey=KeyName,ParameterValue=${AWS_KEY_PAIR_NAME} \
      ParameterKey=BootstrapArguments,ParameterValue="--kubelet-extra-args --node-labels=nodesgroup=main,subnets=private"
```
`ParameterKey=BootstrapArguments,ParameterValue="--kubelet-extra-args --node-labels=nodesgroup=main` works without issues.

Reference: [BootstrapArguments parameter](https://aws.amazon.com/blogs/opensource/improvements-eks-worker-node-provisioning/)

Best regards,
Vadim Zenin

**Comment by micahhausler** [comment]
As the error CloudFormation gave you said, it looks like the `Subnets` parameter needs a value. Are you sure you have a value for `$EKS_PRIVATE_IDS`?

**Comment by Vadim-Zenin** [comment]
I have value for `$EKS_PRIVATE_IDS`.
If I changed 
`ParameterKey=BootstrapArguments,ParameterValue="--kubelet-extra-args --node-labels=nodesgroup=main,subnets=private"`
to
`ParameterKey=BootstrapArguments,ParameterValue="--kubelet-extra-args --node-labels=nodesgroup=main`
the stack could be created.

**Comment by micahhausler** [comment]
This sounds like you have a escaping problem with your shell, can you use single quotes instead of double quotes?

**Comment by Vadim-Zenin** [comment]
Thanks for idea, but result is the same:
`ParameterKey=BootstrapArguments,ParameterValue='--kubelet-extra-args --node-labels=nodesgroup=proxy,subnets=public'`
Parameter validation failed:
Unknown parameter in Parameters[11]: "subnets", must be one of: ParameterKey, ParameterValue, UsePreviousValue, ResolvedValue

**Comment by micahhausler** [comment]
Its a shot in the dark, but can you escape the double quotes?

```
ParameterKey=BootstrapArguments,ParameterValue=\"--kubelet-extra-args --node-labels=nodesgroup=main,subnets=private\"

```

Can you use the JSON syntax?

```
       --parameters (list)
          A list of Parameter structures that specify input parameters for the
          stack. For more information, see the Parameter data type.

       Shorthand Syntax:

          ParameterKey=string,ParameterValue=string,UsePreviousValue=boolean,ResolvedValue=string ...

       JSON Syntax:

          [
            {
              "ParameterKey": "string",
              "ParameterValue": "string",
              "UsePreviousValue": true|false,
              "ResolvedValue": "string"
            }
            ...
          ]
```

**Comment by micahhausler** [comment]
Closing with no response in 2 weeks.

**Comment by 0verc1ocker** [comment]
Proper escaping in bash helped me solve my problems with this CF template. Thank you @micahhausler . :+1:
