### ISSUE TITLE
containerd 1.4.4 errors out with "Selinux is not supported" due to missing build tags

### ISSUE THREAD

**Issue by anusha-ragunathan** [awslabs/amazon-eks-ami#775]
**What happened**:
Created a cluster with containerd as CRI. 
Enabled selinux with `enable_selinux = true` (in /etc/containerd/config.toml) 
SELinux does not work.

containerd version baked in the AMI is `1.4.4`

```
# cat /etc/containerd/config.toml 
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
plugin_dir = ""
disabled_plugins = []
required_plugins = []
oom_score = 0

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    enable_selinux = true
```

However, containerd spits out a warning in /var/log/messages like so:

```
Aug 27 18:38:51 ip-10-225-48-48 containerd: time="2021-08-27T18:38:51.407197323Z" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc DefaultRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} UntrustedWorkloadRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} Runtimes:map[runc:{Type:io.containerd.runc.v2 Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:0xc0003dee10 PrivilegedWithoutHostDevices:false BaseRuntimeSpec:}] NoPivot:false DisableSnapshotAnnotations:true DiscardUnpackedLayers:false} CniConfig:{NetworkPluginBinDir:/opt/cni/bin NetworkPluginConfDir:/etc/cni/net.d NetworkPluginMaxConfNum:1 NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.intuit.com:{Endpoints:[https://docker.intuit.com https://docker-readonly.intuit.com]} docker.io:{Endpoints:[https://registry-1.docker.io]}] Configs:map[] Auths:map[] Headers:map[]} ImageDecryption:{KeyModel:} DisableTCPService:true StreamServerAddress:127.0.0.1 StreamServerPort:0 StreamIdleTimeout:4h0m0s EnableSelinux:true SelinuxCategoryRange:1024 SandboxImage:k8s.gcr.io/pause:3.2 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false MaxConcurrentDownloads:3 DisableProcMount:false UnsetSeccompProfile: TolerateMissingHugetlbController:true DisableHugetlbController:true IgnoreImageDefinedVolumes:false} ContainerdRootDir:/var/lib/containerd ContainerdEndpoint:/run/containerd/containerd.sock RootDir:/var/lib/containerd/io.containerd.grpc.v1.cri StateDir:/run/containerd/io.containerd.grpc.v1.cri}"
Aug 27 18:38:51 ip-10-225-48-48 containerd: time="2021-08-27T18:38:51.407381546Z" level=warning msg="Selinux is not supported" <====
```

Further more, verified that the process and filesystem labels expected on Pods (an example nginx deployment) is not set:

```
# listing from within the nginx container
# ls -Z /usr/sbin/nginx
system_u:object_r:container_var_lib_t:s0 /usr/sbin/nginx

# listing from the node where SELinux is enabled on containerd
# ps -eZ
LABEL                              PID TTY          TIME CMD
system_u:system_r:spc_t:s0           1 ?        00:00:00 nginx
system_u:system_r:spc_t:s0          31 ?        00:00:00 nginx
system_u:system_r:spc_t:s0          32 pts/0    00:00:00 sh
system_u:system_r:spc_t:s0         422 pts/0    00:00:00 ps
```

**What you expected to happen**:
containerd supports Selinux without warnings/errors

**Anything else we need to know?**:
It's possible that the Amazon Linux version of containerd does not build with Golang BUILD_TAGS set to `selinux`. This is  essential to get SELinux support. Else, only stubbed out Go methods are built as part of containerd, which results in the "Selinux is not supported" error.

I built containerd 1.4.4 from source and this version works fine. Simply issuing `make` on https://github.com/containerd/containerd/tree/v1.4.4 should be good.

Deploying an nginx Daemonset on the node with the containerd fix shows the tests work as expected. 

The process labels show up as expected. This is the process listing on the node.
```
# ps -eZ | grep nginx
system_u:system_r:container_t:s0:c511,c746 286060 ? 00:00:00 nginx
system_u:system_r:container_t:s0:c511,c746 286118 ? 00:00:00 nginx
```

The file labels show up as expected. This is from inside the container.
```
$ k exec -it  nginx-daemon-set-pzhlj -- bash
root@nginx-daemon-set-pzhlj:/# which nginx
/usr/sbin/nginx
root@nginx-daemon-set-pzhlj:/# ls -Z /usr/sbin/nginx
system_u:object_r:container_file_t:s0:c511,c746 /usr/sbin/nginx
```

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): Issue seen across several instances such as t2.large, m5.xlarge and m5.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.6"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.19"
- AMI Version: custom built
- Kernel (e.g. `uname -a`): 5.4.141-67.229.amzn2.x86_64 SMP Mon Aug 16 12:51:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):
```
# cat /etc/eks/release 
BASE_AMI_ID="ami-015412692e01778b4"
BUILD_TIME="Fri Sep 10 01:53:55 UTC 2021"
BUILD_KERNEL="5.4.141-67.229.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by anusha-ragunathan** [comment]
Verified that a yum install of containerd version 1.4.6-5 available via `amzn2-extras.repo` has fixed this issue and provides SELinux support.

**Comment by jj-fontana** [comment]
Hi,
facing the same issue here but the only version I can find on amzn2 repo is the 1.4.6-3.amzn2. 
I tested the centos package containerd.io.x86_64-1.4.12-3.1.el8 and it seems to work fine but I rather like use a amzn package here..
