### ISSUE TITLE
Update kubelet minor version with every AMI release

### ISSUE THREAD

**Issue by llamahunter** [awslabs/amazon-eks-ami#778]
**What would you like to be added**:

Update the kubelet version in some way when updating the AMI so that when looking at nodes via kubectl it is apparent which one is running which AMI.  For instance, right now, the `1.20.7-20210914` and `1.20.7-20211004` AMIs both display version `v1.20.7-eks-135321` when using `kubectl get no`.  Maybe it should be `v1.20.7-eks-135321-20211003` or something.

**Why is this needed**:

It's difficult to figure out which nodes are updated and which ones are not. The information is not easily available anywhere in the AWS EKS console or kubectl.

**Comment by sidewinder12s** [comment]
Could also attach AMI ID as a node label, but this would be easier for everyone.

**Comment by cartermckinnon** [comment]
The AMI ID *is* labelled on the node: `eks.amazonaws.com/nodegroup-image`.

The kubelet binary doesn't change in every release, and I'm not sure it makes sense to provide a new set of binaries just to report a different version string to the control plane. I think labeling is the right approach.
