### ISSUE TITLE
Kubelet cluster-dns parameter is set incorrectly

### ISSUE THREAD

**Issue by wskinner-eml** [awslabs/amazon-eks-ami#78]
The IP address of the `kube-dns` service is picked according to the IP address of the node: https://github.com/awslabs/amazon-eks-ami/blob/v24/files/bootstrap.sh#L105

Normally this works fine, but on one of my clusters, the `kube-dns` was running on `172.20.0.10`, and the kubelets were configured to point at `10.100.0.10`. I'm not sure how `kube-dns` decides which IP address to use, but however that works, the kubelet should use the exact same logic to pick IP address to use for `cluster-dns`.

**Comment by micahhausler** [comment]
What is the CIDR range of your VPC? Are you doing any VPC peering?

**Comment by wskinner-eml** [comment]
There are two CIDRs:
10.121.140.0/24
100.124.0.0/16

No VPC peering. Though I'm curious what would happen if we did do VPC peering.

**Comment by lzhengqc** [comment]
For current setup, we have both CIDRs in the same VPC. 
We expended the VPC after 10.x range IP run out and added 100.x range to the same VPC.
The route table is updated too. We are able to ping and ssh between instances launched in both (10.x and 100.x) ranges.

**Comment by micahhausler** [comment]
For your nodes launched in the subnets within `10.121.140.0/24` CIDR, what is the value for `--cluster-dns=` on the kubelet? ( Run `systemctl cat kubelet`)

What is the value for your nodes in the `100.124.0.0/16` subnets?

**Comment by wskinner-eml** [comment]
@micahhausler Closing this because we ended up tearing down that VPC and creating a new one with only private subnets. Will reopen if I see this again in the future.
