### ISSUE TITLE
Release notes do not match Makefile for v20211004

### ISSUE THREAD

**Issue by anish** [awslabs/amazon-eks-ami#780]
The release notes https://github.com/awslabs/amazon-eks-ami/releases/tag/v20211004
claim the following binaries 
```
s3://amazon-eks/1.21.2/2021-04-12/
s3://amazon-eks/1.20.7/2021-04-12/
s3://amazon-eks/1.19.13/2021-01-05/
s3://amazon-eks/1.18.20/2020-11-02/
s3://amazon-eks/1.17.17/2020-11-02/
s3://amazon-eks/1.16.15/2020-11-02/
```

Actual binaries used in the images https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L46-L68
indicate the correct version is `2021-09-02`. Please publish updated release notes. This issue seems to have existed from the previous release

**Comment by cartermckinnon** [comment]
I fixed this a while back, thanks for pointing it out.
