### ISSUE TITLE
ContainerD - Kubelet service failed to start when Node is rebooted

### ISSUE THREAD

**Issue by hemanth-avs** [awslabs/amazon-eks-ami#784]
**What happened**: 
Provisioned 1.21 Cluster with ContainerD runtime. When the Node is rebooted, K8S node failed to get back to Ready Status, It stays in Non Ready Status.  
Reason - Kubelet service in the node failed to start. ( sandbox-image.service – Failed )
bootstrap.sh Script has symbolic link /run/dockershim.sock to /run/containerd/containerd.sock but link is lost when node restarts

**What you expected to happen**:
K8S Node is expected to get back to Ready Status after rebooted

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Cluster 1.21 with ContainerD Runtime
2. Reboot a worker node

**Anything else we need to know?**:
As a workaround, Updated /etc/eks/containerd/pull-sandbox-image.sh  with the symlink ln -sf /run/containerd/containerd.sock  /run/dockershim.sock
eksctl config file - overrideBootstrapCommand - sed -i '3 i\ln -sf /run/containerd/containerd.sock  /run/dockershim.sock' /etc/eks/containerd/pull-sandbox-image.sh  

**Environment**:
- AWS Region: us-west-2
- Instance Type(s):  t3.small
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- AMI Version: ami-0738a2139e5c14787
- Kernel (e.g. `uname -a`): 5.4.149-73.259.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):  

```
BASE_AMI_ID="ami-01725fc47587f08fc"
BUILD_TIME="Mon Oct  4 23:40:17 UTC 2021"
BUILD_KERNEL="5.4.149-73.259.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by marcinosesek** [comment]
Hello

It looks that symlink is missing after reboot
ln -sf /run/containerd/containerd.sock /run/dockershim.sock

Regards Marcin

**Comment by cartermckinnon** [comment]
Thanks for bringing this to our attention!

This is a result of `/run` being mounted as a temporary filesystem (`mount | grep "/run"`). A simple solution is to replace `/run/dockershim.sock` with `/run/containerd/containerd.sock` in `pull-sandbox-image.sh`. I'll work on getting a fix in for this.
