### ISSUE TITLE
AWS EKS build ami error

### ISSUE THREAD

**Issue by wjl120wjl** [awslabs/amazon-eks-ami#789]
**What happened**:
I change region of  eks-worker-al2.json 
export ENV aksk and region
exec below command :
make 1.21 

I found error:

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: amazon-eks-node-1.21-v20211020
    amazon-ebs: Found Image ID: ami-07b9f5c379cdf61b7
==> amazon-ebs: Creating temporary keypair: packer_616ff6e5-4ac9-f1a4-fd86-82e80e2aed01
==> amazon-ebs: Error tagging key pair: Error processing tag: creator:{{user `creator`}} - template: root:1:2: executing "root" at <user `creator`>: error calling user: test
Build 'amazon-ebs' errored after 1 second 146 milliseconds: Error tagging key pair: Error processing tag: creator:{{user `creator`}} - template: root:1:2: executing "root" at <user `creator`>: error calling user: test

==

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s):m4
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):1.21
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version: amazon-eks-node-1.21-v20211013
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by ezestan** [comment]
Hi,
I build a new image for EKS 1.21 and having same issue:

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: amazon-eks-node-1.21-v20211021
    amazon-ebs: Found Image ID: ami-03d1a3241e5a8XXXX
==> amazon-ebs: Creating temporary keypair: packer_6170e747-2a95-9a1b-4eb4-d92926f6609f
==> amazon-ebs: Error tagging key pair: Error processing tag: creator:{{user `creator`}} - template: root:1:2: executing "root" at <user `creator`>: error calling user: test
Build 'amazon-ebs' errored after 845 milliseconds 57 microseconds: Error tagging key pair: Error processing tag: creator:{{user `creator`}} - template: root:1:2: executing "root" at <user `creator`>: error calling user: test

I notice a step before i did was to update the packer to:
Packer v1.7.7

==
Action Taken
I downgraded the packer back to version **Packer v1.7.4** and it works
===


==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: amazon-eks-node-1.21-v20211021
    amazon-ebs: Found Image ID: ami-03d1a3241e5a8XXXX
==> amazon-ebs: Creating temporary keypair: packer_6170ee11-6519-cf54-f29e-5d5d96597586
==> amazon-ebs: Creating temporary security group for this instance: packer_6170ee12-98da-d7ec-e538-1447e797c63c
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "creator": "ec2-user"
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-064e8c0e70b3c9d5d
==> amazon-ebs: Waiting for instance (i-064e8c0e70b3XXXX) to become ready...
==> amazon-ebs: Using SSH communicator to connect: 13.251.XXX.XXX
==> amazon-ebs: Waiting for SSH to become available...

**Comment by pkit** [comment]
@ezestan FYI, fixed in `packer == 1.7.8`
