### ISSUE TITLE
IP_FAMILY not backwards compatible?

### ISSUE THREAD

**Issue by caphrim007** [awslabs/amazon-eks-ami#791]
**What happened**:

Running newest image produces following error which stops kubelet from booting

```
+ [[ -z '' ]]
/etc/eks/bootstrap.sh: line 384: DESCRIBE_CLUSTER_RESULT: unbound variable
++ awk '{print $2}'
+ IP_FAMILY=
++ err_report 384
```

**What you expected to happen**:

kubelet would boot

**How to reproduce it (as minimally and precisely as possible)**:

A new parameter was introduced a little less that 2 weeks ago; --ip-family. It is not mentioned in any changelog. It defaults to nothing; `IP_FAMILY="${IP_FAMILY:-}"`

If it's not set, which it isn't be deult, this conditional is encountered

```
if [[ -z "${IP_FAMILY}" ]]; then
      IP_FAMILY=$(cat $DESCRIBE_CLUSTER_RESULT | awk '{print $2}')
fi
```

The variable referenced is set only if the conditional above the previous is met

```
if [[ -z "${B64_CLUSTER_CA}" ]] || [[ -z "${APISERVER_ENDPOINT}" ]]; then
    DESCRIBE_CLUSTER_RESULT="/tmp/describe_cluster_result.txt"
```

For ages (at least since 1.16), we've been bootstrapping our clusters with

```
/etc/eks/bootstrap.sh --b64-cluster-ca 'LSTiB...S0tLQo=' --apiserver-endpoint 'https://2462...019.yl4.us-east-1.eks.amazonaws.com'  --kubelet-extra-args "" 'cluster1'
```

Ergo, we do not meet the conditional, and therefore the IP_FAMILY attempts to cat the output of a file which doesnt exist.

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1 and us-west-2, but its unimportant
- Instance Type(s): c5.4xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.6"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.19"
- AMI Version: 
- Kernel (e.g. `uname -a`): `Linux ip-10-11-171-109.ec2.internal 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0fc6bb86ee7c7948e"
BUILD_TIME="Sat Oct 23 18:45:37 UTC 2021"
BUILD_KERNEL="5.4.149-73.259.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by ravisinha0506** [comment]
Hi  caphrim007@,

Are you seeing this error with EKS optimized AMI with latest bootstrap.sh? I tried reproducing this issue locally but couldn't do it. This is the configuration I used: 

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=LS0t******==
API_SERVER_URL=https://11111******.gr7.us-west-2.eks.amazonaws.com
clusterName=dev

/etc/eks/bootstrap.sh $clusterName --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL 
--//--
```

Please let me know if I am not following the steps correctly.

**Comment by caphrim007** [comment]
@ravisinha0506 i think you're right. i must have snipe'd the release before that follow-up fix i see in the bootstrap file went in. the current file looks correct. the file that i have in my ami's is incorrect. will update.
