### ISSUE TITLE
support new c6i instance type

### ISSUE THREAD

**Issue by azhurbilo** [awslabs/amazon-eks-ami#793]
**What would you like to be added**:

support c6i instances https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-c6i-instances/

**Why is this needed**:

to get better performance

**Comment by ismailyenigul** [comment]
Still no support on EKS 1.21
```
{"level":"error","ts":"2022-08-19T07:24:22.747Z","caller":"ipamd/ipamd.go:323","
msg":"Failed to get hypervisor info due to unknown instance type c6i.xlarge"}
```

**Comment by dmegyesi** [comment]
> Still no support on EKS 1.21
> 
> ```
> {"level":"error","ts":"2022-08-19T07:24:22.747Z","caller":"ipamd/ipamd.go:323","
> msg":"Failed to get hypervisor info due to unknown instance type c6i.xlarge"}
> ```

Maybe this could help you until they add the support in the CNI plugin: https://github.com/aws/amazon-vpc-cni-k8s/issues/1716#issuecomment-964644793

**Comment by ismailyenigul** [comment]
Thanks
it was an issue with aws vpc cni version 1.9.  
c6i is supported in cni v1.10 release
