### ISSUE TITLE
Sandbox image prefetch bug

### ISSUE THREAD

**Issue by jrieck1991** [awslabs/amazon-eks-ami#795]
Now that containerd socket file location has changed, I think there is a bug with the sandbox-image service which is required for kubelet to start with containerd.

config.toml: https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet-containerd.service#L13
sandbox-image.service script path: https://github.com/awslabs/amazon-eks-ami/blob/ec53e9657510a7ffe57601f403f9df2616734094/files/pull-sandbox-image.sh#L16

This causes kubelet to fail to start

**Comment by ravisinha0506** [comment]
Hi @jrieck1991,

Thanks for opening this issue.  I tried reproducing this issue locally but couldn't do it. Could you please share the steps to reproduce this issue with some other details like the error message, AMI name etc.

Thanks,
Ravi

**Comment by ravisinha0506** [comment]
We are unable to re-produce this issue, hence closing it. Please feel free to re-open it or create a new one if this issue still persists.

**Comment by jihed** [comment]
I have the same issue while using an EKS 1.21 behind a proxy.
