### ISSUE TITLE
prjquota enabled on root filesystem

### ISSUE THREAD

**Issue by rubroboletus** [awslabs/amazon-eks-ami#799]
**What would you like to be added**:
enable project quota add prjquota to mount options for root filesystem

**Why is this needed**:

we need to use quotas on emptyDir PVCs, where are 2 possible solutions. One uses periodic scanning (du -s ...), second, much better from performance point of view, uses filesystem project quota. It needs ext4 or xfs filesystem on worker node volume and for ext4 project quotas enabled (tune2fs -O project -Q prjquota VOLUME; mount volume with prjquota option), see [https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage)

**Comment by sidewinder12s** [comment]
This does require the Alpha feature gate be enabled on the Cluster, which generally is not allowed in most EKS clusters. There are also some Alpha flags that EKS has enabled before they hit beta for users. 

However this would still be useful to enable by default so users could get metrics from node_exporter.

**Comment by cartermckinnon** [comment]
Change sounds interesting to me; though the feature doesn't seem to be getting much TLC (it's been alpha since 1.15). Have you tested this? Feel free to PR it.

**Comment by cartermckinnon** [comment]
I'm going to close this issue, this can be done in user data until/unless we find its useful for the majority of our users.
