### ISSUE TITLE
Add retry logic on `aws eks wait cluster-active` to `/etc/eks/bootstrap.sh`

### ISSUE THREAD

**Issue by cucxabong** [awslabs/amazon-eks-ami#803]
**What would you like to be added**:
I get error `Waiter ClusterActive failed: Too Many Requests` when launch cluster with 400 Node, only 256 Node registered with the master and no more

**Why is this needed**:
Adding logic to retry on `aws eks wait cluster-active` the same way we did with `aws eks describe-cluster`

**Comment by suket22** [comment]
As a possible workaround, you could pass the API Server endpoint and the Cluster certificate data to the bootstrap script and avoid the EKS API calls

**Comment by l1n** [comment]
Any updates on this? Would be pretty useful.

**Comment by cartermckinnon** [comment]
The best solution here is to avoid the `eks:DescribeCluster` call entirely by passing the cluster CA and endpoint to the bootstrap script.
