### ISSUE TITLE
AWS Windows AMI Bootstrap Script should support ServiceCidr as a parameter

### ISSUE THREAD

**Issue by backjo** [awslabs/amazon-eks-ami#805]
**What happened**:
The EKS Windows AMI allows users to pass information such as the cluster name, base64 CA data, and api server endpoint to the bootstrap script, to avoid looking this information up during the startup process. Unfortunately, when passing this data, it causes the bootstrap script to fallback to the default calculation logic for determining the service CIDR range of the cluster, which may not be correct. This, in turn, configures the CNI with a potentially incorrect value.

**What you expected to happen**:
The AMI should allow the ServiceCIDR to be passed in by the user, so that the correct range could be used. 
**How to reproduce it (as minimally and precisely as possible)**:
Use a service CIDR like 172.16.0.0/12 on an EKS Cluster, and run Windows nodes where the cluster name, api endpoint, and CA data are passed into the bootstrap script via userdata. 

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-west-2
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- AMI Version: latest
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
We don't track issues for the Windows AMI here, please open an issue on [`aws/container-roadmap`](https://github.com/aws/containers-roadmap) (I can't transfer the issue for you because that repo is in a different GitHub organization, sorry).
