### ISSUE TITLE
Add support for g3s.xlarge instances

### ISSUE THREAD

**Issue by emman27** [awslabs/amazon-eks-ami#81]
Self-explanatory, I believe! Will give us good options for GPUs on EKS

**Comment by ozzieba** [comment]
Is there any way to actually use g3 / g3s instances on EKS? AFAICT the GPU [AMIs](https://aws.amazon.com/marketplace/pp/B07GRHFXGM) are only available for P2 and P3 instances.

**Comment by emman27** [comment]
@ozzieba you could build your own AMI using this as source

**Comment by emalihin** [comment]
@micahhausler are there any blockers for g3s instances to support `EKS-optimized AMI with GPU Support`?
