### ISSUE TITLE
[Question] install docker when runtime is containerd

### ISSUE THREAD

**Issue by yongzhang** [awslabs/amazon-eks-ami#821]
Hi, 

Just a question to verify, for https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L115-L116, looks like `INSTALL_DOCKER` is always `true`, do we still need docker when runtime is containerd?

**Comment by ravisinha0506** [comment]
Hi @yongzhang, 
Docker is installed on the node when `INSTALL_DOCKER` is set as true. However, docker is not enabled when runtime is `containerd`.

**Comment by cartermckinnon** [comment]
Just a heads-up, the `docker` CLI and `dockerd` will no longer be available in our 1.22 (and later) releases.
