### ISSUE TITLE
Add support for M6a

### ISSUE THREAD

**Issue by martinpapez** [awslabs/amazon-eks-ami#825]
**What would you like to be added**:
Newly released.

Support for M6a instance types. https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6a-instances-powered-by-3rd-gen-amd-epyc-processors/

**Why is this needed**:
Currently, we have to update files like ` /etc/eks/eni-max-pods.txt` with bootstrap scrip for the M6a instance type.

**Comment by ares-team-acn** [comment]
M6i is not working too

**Comment by suket22** [comment]
We've released a set of AMIs to address this - https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
