### ISSUE TITLE
Error eks-ssm-content.json JSON not well formed

### ISSUE THREAD

**Issue by Nuru** [awslabs/amazon-eks-ami#828]
**What happened**:
Following [instructions](https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script/linux#collect-eks-logs-using-ssm-agent) for collecting EKS logs using SSM agent:

```
$ aws ssm create-document --name "EKSLogCollector" --document-type "Command" --content https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/log-collector-script/linux/eks-ssm-content.json

An error occurred (InvalidDocumentContent) when calling the CreateDocument operation: JSON not well-formed. at Line: 1, Column: 6
```

**What you expected to happen**:
Command to succeed

**Anything else we need to know?**:

Same as #716

**Environment**:
- AWS Region: me-south-1
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.3"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0f2eb599f16eb7ac7"
BUILD_TIME="Wed Nov 17 23:55:27 UTC 2021"
BUILD_KERNEL="5.4.156-83.273.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by sidewinder12s** [comment]
Also same as #725

**Comment by cartermckinnon** [comment]
I was able to reproduce this, and have reopened the original issue. Please track progress there.
