### ISSUE TITLE
Enable eBPF support

### ISSUE THREAD

**Issue by Chili-Man** [awslabs/amazon-eks-ami#829]
**What would you like to be added**:
Would like to have eBPF support enabled by default on the AMI. This would involve mounting the bpf file system. 

**Why is this needed**:
We would like to use some of the extended features of Calico that make use of eBPF. However, many other products are now also supporting eBPF only features such as DataDog, Sysdig, etc .

**Comment by rubroboletus** [comment]
duplicate to #728

**Comment by cartermckinnon** [comment]
Closing as duplicate, please track the main issue.
