### ISSUE TITLE
Newer Docker version

### ISSUE THREAD

**Issue by pietervogelaar** [awslabs/amazon-eks-ami#83]
At the moment Docker version 17.06* is installed.

However the chown parameter for the COPY command is available since version 17.09.0.
See https://stackoverflow.com/a/44766666/948378

When will at least this version become available in this AMI?

**Comment by pietervogelaar** [comment]
Executing chown during RUN as workaround is possible, but that always seem to invalidate the cache of layers below that command. So the chown parameter for the COPY comman would be very welcome.

**Comment by kinghajj** [comment]
Do you need this because you're piggy-backing on the Docker engine of nodes for use in a build system?

**Comment by pietervogelaar** [comment]
Yes, that's correct.

**Comment by micahhausler** [comment]
The [Kubernetes 1.10 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#external-dependencies) specify that v1.10 is tested with Docker 17.03.x. EKS has chosen and validated Docker 17.06. With future releases of Kubernetes, we'll be upgrading to the community recommended version of docker.
