### ISSUE TITLE
Encrypted EBS Option

### ISSUE THREAD

**Issue by khacminh** [awslabs/amazon-eks-ami#84]
Hi,

Does AWS has an `Encrypted Amazon EKS-optimized AMI` or I have to create one? I searched on the market place and could not find one (region us-east-1). EKS is now HIPAA Eligible, but the information of EKS is not defined on **AWS HIPAA White Paper**.

Many Thanks.

**Comment by micahhausler** [comment]
You’ll have to create your own encrypted AMI. If we tried to share an encrypted AMI, you wouldn’t be able to decrypt it without the KMS key we used for encryption. If we shared that key publicly, that would defeat the purpose :)

In regard to the white paper, it’s probably just out of date. I’ll see who can update that
