### ISSUE TITLE
How to enable `containerd` when using EKS managed node group

### ISSUE THREAD

**Issue by bryantbiggs** [awslabs/amazon-eks-ami#844]
I know this may not be the best place to ask, but I wanted to give it a shot anyways. 

Is there a way to simply just set environment variables when using EKS managed node groups (*WITHOUT specifying a custom AMI ID and therefore relying on the default user data bootstrap script provided by the EKS managed node group) and still enable `contianerd`?

You can see more details [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1770#issuecomment-1014644200), but it looks like in order to get `containerd` we have to go into some bash fu in the user data that we/users provide that gets pre-pended to the user data that the EKS managed node group service provides in order to get this to work:

```bash
#!/bin/bash
set -ex
cat <<-EOF > /etc/profile.d/bootstrap.sh
export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false
export KUBELET_EXTRA_ARGS="--max-pods=110"
EOF
# Source extra environment variables in bootstrap script
sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
```

I just wanted to see if it were possible to do the following instead do (at least, thats what the "API" looks like when viewing the [`bootstrap.sh` script](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L120-L132):
```bash
export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false
export KUBELET_EXTRA_ARGS="--max-pods=110"
```

thank you!

**Comment by cartermckinnon** [comment]
For this specific case, yes; this is the best way to accomplish it. The upcoming 1.22 release will make such workarounds unnecessary, as `containerd` will become the default runtime.

**Comment by cartermckinnon** [comment]
Sorry, my info was outdated -- the change to `containerd` has been pushed to the 1.23 release; there is more context available [in the docs](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html).

**Comment by stevehipwell** [comment]
@bryantbiggs @cartermckinnon I'm planning on opening a PR in this repo to update _bootstrap.sh_ with a known file to source when present. This will be a no-op unless someone creates the file to set these variables (or other variables such as dynamic labels).

**Comment by lobeck** [comment]
This does not seem to work anymore.

It only uses the args passed through the call to bootstrap.sh and the environment variable gets overwritten.

**Comment by stevehipwell** [comment]
@lobeck take a look at https://github.com/awslabs/amazon-eks-ami/pull/855. You need to modify bootstap.sh until this capability is added, either to source another persisted file or to directly set the variable.

**Comment by lobeck** [comment]
@stevehipwell thank you. got it working with

    sed -i 's/KUBELET_EXTRA_ARGS=$2/KUBELET_EXTRA_ARGS="$2 $KUBELET_EXTRA_ARGS"/' /etc/eks/bootstrap.sh

It's not nice, but get's the job done

**Comment by stevehipwell** [comment]
That's what #855 is meant to make a lot cleaner by allowing the passing of env variables between cloud init steps.

**Comment by lobeck** [comment]
I know and that patch is already in place.

    cat <<-EOF > /etc/profile.d/bootstrap.sh
    export CONTAINER_RUNTIME="containerd"
    export KUBELET_EXTRA_ARGS="--runtime-request-timeout 600s"
    EOF
    # Source extra environment variables in bootstrap script
    sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
    sed -i 's/KUBELET_EXTRA_ARGS=$2/KUBELET_EXTRA_ARGS="$2 $KUBELET_EXTRA_ARGS"/' /etc/eks/bootstrap.sh

Unfortunately with terraform and EKS itself, it needs to merge both environment variables and command line arguments.

I added stuff through the environment variables and EKS injects all the labels as command line flags on bootstrap.sh

My sed only patches the line in the argument parser, so that in case both are specified, they get merged. If there are no flags set, the environment variable will be used.

**Comment by stevehipwell** [comment]
@lobeck if you look at https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1789, specifically the new [linux_mng_merge_user_data.tpl](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cf2772a52072c428282109b5e0efd637ca38439c/templates/linux_mng_merge_user_data.tpl) file you'll see my updated version of how this should work; effectively you just need to set env variables to fully configure bootstrap. The code in the initial issue comes from the implementation I added to an earlier version of the `terraform-aws-eks` module which was designed to work with other implementations.

**Comment by lobeck** [comment]
Awesome, can't wait for this to get merged, so I can remove my crufty patches :D

**Comment by rshad** [comment]
This should be tricked by adding the following line to the user data:
```
sed -i 's/CONTAINER_RUNTIME:-dockerd/CONTAINER_RUNTIME:-containerd/' /etc/eks/bootstrap.sh
```

**Comment by Ga13Ou** [comment]
> ```shell
> #!/bin/bash
> set -ex
> cat <<-EOF > /etc/profile.d/bootstrap.sh
> export CONTAINER_RUNTIME="containerd"
> export USE_MAX_PODS=false
> export KUBELET_EXTRA_ARGS="--max-pods=110"
> EOF
> # Source extra environment variables in bootstrap script
> sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
> ```

Did anyone had the Disk capacity warning problem when tried to migrate to Containerd. Every solution I use I get this error 
![image](https://user-images.githubusercontent.com/37796504/209940553-86903d2b-a75c-44fa-b3f1-4f8af42129ed.png)

`Warning  InvalidDiskCapacity      9m25s                  kubelet          invalid capacity 0 on image filesystem`
