### ISSUE TITLE
How to ensure sticky bit is set on all world-writable directories

### ISSUE THREAD

**Issue by Icestar0401** [awslabs/amazon-eks-ami#846]
When I run CIS Kubernetes benchmark scanner kube-bench on my EKS nodes, one of the findings it reports is this:

1.1.21 Ensure sticky bit is set on all world-writable directories (Scored)

We have tried editing the AMI/User Data, however, during scanning we still found sticky bit not set for some folders that are volumes for the pods
We think it is because when start spinning up pods in eks, those folders will then be created. 

I'm wondering if AWS has any suggestion/guidance on how to make our EKS nodes in compliance with it?

Reference link: https://secscan.acron.pl/centos7/1/1/21 
Region: us-east-1

**Comment by cartermckinnon** [comment]
This is the standard behavior of Kubernetes, you can get more background here: https://github.com/kubernetes/kubernetes/issues/76158
