### ISSUE TITLE
Add ability to customize containerd-config.toml

### ISSUE THREAD

**Issue by anusha-ragunathan** [awslabs/amazon-eks-ami#848]
**What would you like to be added**:

Today, a default [containerd-config.toml](https://github.com/awslabs/amazon-eks-ami/blob/master/files/containerd-config.toml) is made available via [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L465)
Add the ability to pass a custom container config to bootstrap.sh

A similar option is available when using docker as the CRI implementation via $DOCKER_CONFIG_JSON. Expose something like that for containerd as well.

**Why is this needed**:

Needed so custom containerd configurations can be passed to EKS bootstrapper.

**Comment by bryantbiggs** [comment]
relates to #790

**Comment by cartermckinnon** [comment]
We've added the ability to import a `containerd` config file from a known directory: https://awslabs.github.io/amazon-eks-ami/usage/al2/#customizing-containerd-config

We've further improved this with `NodeConfig` on our AL2023-based AMI's, which accept arbitrary `containerd` config as input and merge it as necessary with our defaults.

**Comment by anish** [comment]
hey @cartermckinnon sorry to bump an old thread, but do we have to worry about this when using `NodeConfig` to override containerd config ? https://github.com/containerd/containerd/issues/5837#issuecomment-894840240

**Comment by ndbaker1** [comment]
hey @anish, we actually sorted this exact issue out awhile back in https://github.com/awslabs/amazon-eks-ami/pull/1780 giving you a raw unstructured merge with the data you provide to the `NodeConfig`

**Comment by anish** [comment]
that's awesome ! thank you @ndbaker1
