### ISSUE TITLE
`make` doesn't understand `launch_block_device_mappings_volume_size` variable

### ISSUE THREAD

**Issue by deepankarm** [awslabs/amazon-eks-ami#849]
**What happened**:
`launch_block_device_mappings_volume_size` variable is not accepted when passed using make command like

```bash
make k8s ... launch_block_device_mappings_volume_size=10 ...
```
I had to change the `eks-worker-al2.json` file to the desired value. I'm guessing this is because it is not added here? 

https://github.com/awslabs/amazon-eks-ami/blob/52c8b01ad7fe55b825a4072111eac5f1d918124c/Makefile#L2

**Comment by cartermckinnon** [comment]
I agree, feel free to open a PR with your fix; otherwise I'll try to get to this soon.

**Comment by cartermckinnon** [comment]
We removed this manually-maintained list of variables, now everything in the Packer template will be discovered by the Makefile.
