### ISSUE TITLE
wrong tag name in the latest release

### ISSUE THREAD

**Issue by matti** [awslabs/amazon-eks-ami#852]
capital V:

<img width="911" alt="Tags_·_awslabs_amazon-eks-ami" src="https://user-images.githubusercontent.com/3893/150766620-b3b62daf-72f7-4922-88bc-71ca134455fb.png">

this causes issues in https://github.com/weaveworks/eksctl/issues/4674

ping @prasad0896

**Comment by matti** [comment]
https://github.com/aws/amazon-ec2-instance-selector/issues/111

**Comment by prasad0896** [comment]
Updated the release tag
