### ISSUE TITLE
Troubleshooting  DiskPressure

### ISSUE THREAD

**Issue by Harshitha99** [awslabs/amazon-eks-ami#856]
I'm curious about troubleshooting disk pressure, let's suppose if an alarm is triggered for high disk utilization on a worker node and logs are getting rotated and kubelet is up and running, in this situation do we have to delete anything manually or the node heals itself?
any suggestions, please

**Comment by cartermckinnon** [comment]
The kubelet will proactively evict greedy pods to prevent starvation; and in general you shouldn't need to intervene or modify the default thresholds to keep your cluster healthy. However, the cause of disk pressure is almost always related to your specific workload, and you may need to tune your cluster accordingly. You can read more [in the Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/).
