### ISSUE TITLE
Upgrade Linux Kernel to 5.10

### ISSUE THREAD

**Issue by DavidSpek** [awslabs/amazon-eks-ami#857]
**What would you like to be added**:
Upgrade the Linux kernel to 5.10

**Why is this needed**:
[Amazon Linux 2 AMI has been upgraded to Linux 5.10](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/), so I believe the EKS AMI should also be upgraded. This is also necessary as some features of Calico and Cilium, like WireGuard for encrypting traffic, require a newer version of the Linux kernel, as mentioned in [this](https://github.com/awslabs/amazon-eks-ami/issues/727) issue.

**Comment by learhy** [comment]
Hi there! I'm wondering if there is a public timeline as to when the linked PR might be merged. Thanks!

**Comment by khacminh** [comment]
Hi @cartermckinnon,

Because [GPU AMI doesn't come with Kernel 5.10](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230217), IMO, this issue should be re-open.

**Comment by cartermckinnon** [comment]
@khacminh I've opened a new issue to track this, #1222 .
