### ISSUE TITLE
EKS CoreDNS

### ISSUE THREAD

**Issue by Icestar0401** [awslabs/amazon-eks-ami#858]
From this link, https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html#adding-coredns-eks-add-on
The CoreDNS version should be 1.8.4 for EKS 1.21.

However the latest version of CoreDNS is 1.8.7. 

Question: should we update CoreDNS to the latest 1.8.7 ? Or keep it as 1.8.4 like the documentation suggested?

**Comment by ravisinha0506** [comment]
Hi,

As mentioned [in this doc](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html), 1.8.4 is the recommended version for EKS 1.21. There shouldn't be any issues with 1.8.7, however the recommendation is to stay on 1.8.4 if there isn't any particular feature you want to use in 1.8.7. 

Please let us know if you have any follow up questions.
