### ISSUE TITLE
For new EKS node AMI

### ISSUE THREAD

**Issue by tsmgeek** [awslabs/amazon-eks-ami#86]
Can the CF template be altered so that new nodes will be spun up with all yum updates applied.

ie
```
#!/bin/bash

yum check-update
yumcheck_exit=$?
if [ $yumcheck_exit -eq 100 ]; then
  yum update -y
  shutdown -r now
  rm /var/lib/cloud/instances/*/sem/config_scripts_user
  exit $yumcheck_exit
fi

set -o xtrace
/etc/eks/bootstrap.sh <cluster name> --kubelet-extra-args "--node-labels=spot=<is spot>"
/opt/aws/bin/cfn-signal --exit-code $? \
         --stack  <stack name> \
         --resource NodeGroup  \
         --region <region>
```

**Comment by max-rocket-internet** [comment]
I think most people will definitely not want this because you will end up with nodes running in the same cluster but with different patch levels depending on their age.

**Comment by micahhausler** [comment]
Users can add this to their user-data script if they want, but we won't be adding this to the CF template. We want users to know what version of libraries are running when they launch an instance.
