### ISSUE TITLE
Add support for M5a instances

### ISSUE THREAD

**Issue by arjanschaaf** [awslabs/amazon-eks-ami#87]
I tested the latest AMI with the newly release m5a instance family. My setup works with m5 instances, but the kubelet fails to start automatically. It seems to work after restarting it by hand using `sudo systemctl start kubelet` though.

**Comment by micahhausler** [comment]
I haven't had any issues starting kubelet on m5a, but the CNI provider doesn't seem to support it yet. Did you do any modification to the AMI?

**Comment by arjanschaaf** [comment]
I create a launch config like so:
```
aws autoscaling create-launch-configuration --launch-configuration-name eks-test-nodes-14112018 --iam-instance-profile eks-node --image-id ami-00c3b2d35bddd4f5c --instance-type m5a.large --key-name eks --ebs-optimized --security-groups <security-group-id> --user-data file://eks-test-nodes-userdata.sh --block-device-mappings "[{\"DeviceName\": \"/dev/xvda\",\"Ebs\":{\"VolumeSize\":64,\"VolumeType\":\"gp2\"}}]"
```

The contents of the user-data file are:
```
#!/bin/bash -xe
/etc/eks/bootstrap.sh --kubelet-extra-args --node-labels=nodegroup=test-nodes my-kubernetes-cluster
```

Then I launch the autoscaling group:
```
aws autoscaling create-auto-scaling-group --auto-scaling-group-name eks-test-nodes --launch-configuration-name eks-test-nodes-14112018 --min-size 1 --desired-capacity 1 --max-size 1 --vpc-zone-identifier <subnet-id> --tags Key=Name,Value=eks-test-node,PropagateAtLaunch=true Key="kubernetes.io/cluster/my-kubernetes-cluster",Value=shared,PropagateAtLaunch=true
```

If you login to this new node and check the status of:
- docker.service : active
- kubelet.service : dead
- multi-user.target: active

To answer your questions:

- What specific instance type are you launching?
m5a.large
- What region are you launching it in?
eu-west1
- What version of the EKS AMI are you using?
ami-00c3b2d35bddd4f5c
- Are the --node-labels the only extra args you are passing to the kubelet?
No other arguments then the `--node-labels` you see in the user-data

**Please note** : If I launch an autoscaling group with the exact same configuration expect for one change: use the **m5.large** instance type instead of **m5a.large** the kubelet is started as expected. Hence my conclusion that the m5a instance family is somehow not supported yet.

**Comment by ejfinkel** [comment]
I am also seeing this issue in `us-east-1`. My launch configuration uses `m5.large` instances with the v25 AMI, and they are able to join the cluster without issue. After changing the instance type to `m5a.large`, the instances are unable to join the cluster, even after I ssh into the node and run the bootstrap script manually.
```
sudo /etc/eks/bootstrap.sh --apiserver-endpoint <ENDPOINT> --b64-cluster-ca <CA>  <NAME>
```

A colleague of mine tried spinning up a cluster with eksctl and m5a.large instances, and ran into the same problem with the instances not being able to join the cluster.
```
eksctl create cluster --node-type m5a.large --name <NAME> --ssh-access --ssh-public-key <KEY>
```

**Comment by micahhausler** [comment]
I'm able to reproduce this with the configuration you provided. I am still able to get nodes to join correctly with my configuration, so I'll get the relevant folks and see what we can find.

Here are the last few lines of `/var/log/cloud-init-output.log`:
```
Cloud-init v. 18.2-72.amzn2.0.6 running 'modules:final' at Wed, 14 Nov 2018 17:45:11 +0000. Up 23.61 seconds.
+ /etc/eks/bootstrap.sh --kubelet-extra-args --node-labels=nodegroup=test-nodes eks-mhausler-11-14-2018
Cluster "kubernetes" set.
Nov 14 17:45:17 cloud-init[3449]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Nov 14 17:45:17 cloud-init[3449]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Nov 14 17:45:17 cloud-init[3449]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 18.2-72.amzn2.0.6 finished at Wed, 14 Nov 2018 17:45:17 +0000. Datasource DataSourceEc2.  Up 29.77 seconds
```

**Comment by micahhausler** [comment]
Figured it out: so in the v25 AMI, the m5a instance types are not present in the `"/etc/eks/eni-max-pods.txt` file, and we have a `set -e` and `set -o pipefail` in the bootstrap script. 

This causes
```
MAX_PODS=$(grep $INSTANCE_TYPE $MAX_PODS_FILE | awk '{print $2}')
```
to exit and error.

The max-pods file was updated in #93 to add m5a instance types, but there isn't yet a release of our CNI plugin to support m5a either. Until the CNI plugin supports m5a, you can use m5 instance types

I'll also fix the bootstrap.sh script to be more graceful about handling new instance types

**Comment by devkid** [comment]
I think this is fixed by https://github.com/awslabs/amazon-eks-ami/commit/f27bc2e32d65861b7f967f49ef67417e6e55faff.

**Comment by micahhausler** [comment]
This instance type is now supported
