### ISSUE TITLE
Logrotate config files have incorrect permissions, which makes logrotate ignore them and do nothing

### ISSUE THREAD

**Issue by dryewo** [awslabs/amazon-eks-ami#883]
**What happened**:
Log rotation is not happening on EKS nodes. Files under `/var/log/` (especially `/var/log/messages`) grow indefinitely, which eventually leads to node running out of disk space and a lot of pods being evicted because of DiskPressure.

**What you expected to happen**:
Log rotation works, log files are split by day or by week, older files archived and eventually deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Start an instance using the AMI (version below), SSH into it, run this command as root (this is the same command that cron runs, plus the `-d` switch):
```
# /usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf -d
error: Ignoring /etc/logrotate.conf because of bad file mode - must be 0644 or 0444.
Allocating hash table for state file, size 15360 B

Handling 0 logs
```
Check permissions of logrotate configs, note the files with `-rw-rw-r--` (0664):

```
# ls -la /etc/logrotate*
-rw-rw-r-- 1 root root 495 Jun 29  2021 /etc/logrotate.conf

/etc/logrotate.d:
total 28
drwxr-xr-x  2 root root   63 Jun 29  2021 .
drwxr-xr-x 82 root root 8192 Dec 22 17:03 ..
-rw-r--r--  1 root root  160 Oct  7  2020 chrony
-rw-r-wr--  1 root root   95 Jun 29  2021 kube-proxy
-rw-r--r--  1 root root  224 Jun 16  2020 syslog
-rw-r--r--  1 root root  100 Feb 25  2021 yum
```

**Anything else we need to know?**:

**Environment**:
- AWS Region: `us-east-1`
- Instance Type(s): `m5.2xlarge` (but any type really)
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `eks.3`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): `1.20`
- AMI Version: `amazon-eks-node-1.20-v20210629`
- Kernel (e.g. `uname -a`): `Linux ip-111-222-333-444.ec2.internal 5.10.35-31.135.amzn2.x86_64 #1 SMP Tue May 11 22:05:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0231cda408ca5a617"
BUILD_TIME="Tue Jun 29 11:34:19 UTC 2021"
BUILD_KERNEL="5.4.117-58.216.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
I'm not able to reproduce this on the latest AMI's (`v20220629`). Please @mention me if you're still seeing this on recent releases.

```
> cat /etc/eks/release 
BASE_AMI_ID="ami-09db9da37d31787f3"
BUILD_TIME="Wed Jun 29 02:44:57 UTC 2022"
BUILD_KERNEL="5.4.196-108.356.amzn2.x86_64"
ARCH="x86_64"

> ls -la /etc/logrotate*
-rw-r--r-- 1 root root 495 Jun 29 02:42 /etc/logrotate.conf

/etc/logrotate.d:
total 28
drwxr-xr-x  2 root root   63 Jun 29 02:44 .
drwxr-xr-x 80 root root 8192 Jul 25 23:32 ..
-rw-r--r--  1 root root  160 Oct  7  2020 chrony
-rw-r--r--  1 root root   95 Jun 29 02:42 kube-proxy
-rw-r--r--  1 root root  224 May 16 20:52 syslog
-rw-r--r--  1 root root  100 Feb 25  2021 yum
```
