### ISSUE TITLE
Provide support for x2iden instance types

### ISSUE THREAD

**Issue by MalPunch3r** [awslabs/amazon-eks-ami#891]
**What would you like to be added**:
Please add support for x2iedn instance types. 

**Why is this needed**:
These instance types are useful for the memory to cpu ratio that they have for our given workload. 

Seems like it's just missing entries here: https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

**Comment by cartermckinnon** [comment]
This change has been merged and will be released in the next AMI, later this week. I'll update this issue once it's available.

**Comment by cartermckinnon** [comment]
This change is available in [v20220523](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220523).
