### ISSUE TITLE
Cannot build the image with runc 1.0.3-2.amzn2

### ISSUE THREAD

**Issue by szymonpk** [awslabs/amazon-eks-ami#896]
**What happened**:

I have tried to build the image with packages versions as stated in [last the changelog](https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md#ami-release-v20220406). Mainly with runc 1.0.3

**What you expected to happen**:

Successful image build.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use `1.0.3-2.amzn2` as [runc version](https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L18).
2. Build the image as stated in [the readme](https://github.com/awslabs/amazon-eks-ami#building-the-ami).

**Anything else we need to know?**:

Log from the `make`:

```
...
    amazon-ebs: No package runc-1.0.3-2.amzn2 available.
    amazon-ebs: Error: Nothing to do
...
```

If I boot the instance with v20220406 image package comes from 'somewhere' though:

```
$ yum info runc
Loaded plugins: priorities, update-motd, versionlock
Installed Packages
Name        : runc
Arch        : x86_64
Version     : 1.0.3
Release     : 2.amzn2
Size        : 11 M
Repo        : installed
Summary     : CLI tool for spawning and running containers according to the OCI specification
License     : Apache 2.0 and MIT
Description : runc is a command line client for running applications packaged according to
            : the Open Container Initiative (OCI) format and is a compliant implementation of the
            : Open Container Initiative specification.
```

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): n/a
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.7
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.19
- AMI Version: n/a
- Kernel (e.g. `uname -a`): n/a
- Release information (run `cat /etc/eks/release` on a node): n/a

**Comment by abeer91** [comment]
Hi, EKS has used internally available artifacts to build this AMI. We are working with Amazon Linux to push these artifacts upstream so we can make these changes to the builder scripts as well. We'll keep this issue open, and provide an ETA once we have one.

**Comment by prasad0896** [comment]
PR to fix this has been merged
