### ISSUE TITLE
EKS ami 1.18 20220406 general pod failure

### ISSUE THREAD

**Issue by Carles-Figuerola** [awslabs/amazon-eks-ami#899]
**What happened**:

In us-east-1, upon upgrading from `amazon-eks-node-1.18-v20220123` to `amazon-eks-node-1.18-v20220406` we started noticing lots of failures on several sides of eks. One of the most noticeable ones was `aws-node` pods failing with:

```
aws-node-6kgps aws-node {"level":"info","ts":"2022-04-15T16:14:59.235Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
aws-node-6kgps aws-node {"level":"info","ts":"2022-04-15T16:14:59.236Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
aws-node-6kgps aws-node {"level":"info","ts":"2022-04-15T16:14:59.257Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the backgro
und ... "}
aws-node-6kgps aws-node {"level":"info","ts":"2022-04-15T16:14:59.261Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ...
"}
aws-node-6kgps aws-node runtime: failed to create new OS thread (have 22 already; errno=11)
aws-node-6kgps aws-node runtime: may need to increase max user processes (ulimit -u)
aws-node-6kgps aws-node fatal error: newosproc
aws-node-6kgps aws-node
aws-node-6kgps aws-node runtime stack:
aws-node-6kgps aws-node runtime.throw(0x559aa06ca345, 0x9)
aws-node-6kgps aws-node         /usr/local/go/src/runtime/panic.go:1116 +0x74
aws-node-6kgps aws-node runtime.newosproc(0xc000d92000)
aws-node-6kgps aws-node runtime.newm1(0xc000d92000)
aws-node-6kgps aws-node         /usr/local/go/src/runtime/proc.go:1785 +0xde
aws-node-6kgps aws-node runtime.newm(0x559aa124d450, 0xc000076000, 0x15)
aws-node-6kgps aws-node         /usr/local/go/src/runtime/proc.go:1764 +0x9d
...
```

other errors also showed up like this event from a pod starting:
```
  Warning  FailedCreatePodSandBox  24m   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start
sandbox container for pod "aws-node-plxpv": Error response from daemon: runtime: failed to create new OS thread (have 6 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x9216fb, 0x9)
  /usr/lib/golang/src/runtime/panic.go:1117 +0x72
```

or mounting volumes on pods:
```
MountVolume.SetUp failed for volume "secrets" : mount failed: fork/exec /usr/bin/systemd-run: resource temporarily unavailable Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/b6775b1d-2e55-41c3-8a1e-980e317c6d48/volumes/kubernetes.io~empty-dir/secrets --scope -- mount -t tmpfs tmpfs /var/lib/kubelet/pods/b6775b1d-2e55-41c3-8a1e-980e317c6d48/volumes/kubernetes.io~empty-dir/secrets Output:
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "mydeployment-7949bbdff4-jhb8c": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/d24045f116b7ac6261d36ab82d1bb9c873c850204af8e79b73f6639745fab2df/log.json: no such file or directory): fork/exec /usr/sbin/runc: resource temporarily unavailable: unknown
```

After rolling back to `amazon-eks-node-1.18-v20220123`, all the errors went away.

In us-west-2, the ami: `amazon-eks-node-1.19-v20220406` works fine and we've had a cluster running stable for 6+ days.

**What you expected to happen**:

Cluster should be stable and pods should not restart citing `ulimit` problems

**How to reproduce it (as minimally and precisely as possible)**:

Run an eks cluster using ASG nodes with ami: `amazon-eks-node-1.18-v20220406` in us-east-1

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): c5.12xlarge
- EKS Platform version: eks.9
- Kubernetes version: 1.18
- AMI Version: ami-0de537e93c519f366
- Kernel (e.g. `uname -a`): 
- Release information (run `cat /etc/eks/release` on a node): (we don't have any of the bad nodes running anymore :( 

```
```

**Comment by cartermckinnon** [comment]
I verified that our `ulimit`-s haven't changed between the `v20220123` and `v20220406` releases, so I'll need some more information about your workload to reproduce this.

You noted that you observed this in `us-east-1`, but I want to note that `amazon-eks-node-1.18-v20220406` is identical in all commercial regions (i.e. we should be able to reproduce this in any region).

**Comment by cartermckinnon** [comment]
@expchrbrown and @DerrekWoodworth -- if either of you have experienced this as well, please share any steps to reproduce that you can 🙏 .

**Comment by cartermckinnon** [comment]
I'm going to close this issue -- don't hesitate to @mention me with an update if you have one. We currently haven't seen any other reports of this issue, so don't have reason to believe there was a regression in our `ulimit`-s.
