### ISSUE TITLE
April ami ephemeral port kernel bug

### ISSUE THREAD

**Issue by jfdoube** [awslabs/amazon-eks-ami#908]
There was an issue my kernel version 5.4.176-91.338.amzn2 (some ami prior to march 9th) where the ephemeral port range was starting from 0 to 65535. They should be starting above 32768

This was fixed is subsequent release (march 9th and later). 

Since the introduction of kernel version 5.4.188-104.359.amzn2 on April 6th, the issue is occurring again.

**Comment by cartermckinnon** [comment]
Can you provide an AMI ID that exhibits this? I assume you're doing something like:
```
sysctl net.ipv4.ip_local_port_range 
```
to make this determination?

**Comment by cartermckinnon** [comment]
I'm closing this as stale; please open a new issue with details like a specific AMI ID if this is still a problem.
