### ISSUE TITLE
i4i support in eks ami

### ISSUE THREAD

**Issue by korjek** [awslabs/amazon-eks-ami#910]
**What would you like to be added**:

i4i support in eks ami.

i4i instances are not listed in https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

**Why is this needed**:

it would be great to be able to use i4i as eks node to get all benefits provided by this instance type.

**Comment by cartermckinnon** [comment]
This change has been merged and will be released in the next AMI, later this week. I'll update this issue once it's available.

**Comment by cartermckinnon** [comment]
This change is available in [v20220523](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220523).
