### ISSUE TITLE
Status of pods can become "OutOfCpu" when many pods are created and completed in a short time on the same node

### ISSUE THREAD

**Issue by owengo** [awslabs/amazon-eks-ami#914]
**What happened**:
This is a bug introduced with k8s 1.22 which affects EKS images.

**What you expected to happen**:

Have a patched kubelet to fix the bug.

**How to reproduce it (as minimally and precisely as possible)**:

Issue is explained at length here: [Status of pods can become "OutOfCpu" when many pods are created and completed in a short time on the same node](https://github.com/kubernetes/kubernetes/issues/106884)

**Anything else we need to know?**:

A fix is backported for k8s 1.22.9:
[https://github.com/kubernetes/kubernetes/pull/108749](https://github.com/kubernetes/kubernetes/pull/108749)

Could you please apply it to eks amis ?

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): any 
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): any
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.22.6
- AMI Version: ami-0808f507c5d46608c
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by cartermckinnon** [comment]
Thanks for making us aware of this and providing the details, really appreciate it.

We're working on pulling in several commits on other release lines, so I'll try to get this addressed in that same effort.

**Comment by Kydybets** [comment]
team, when it could be fixed? 
we are running a lot of jobs each minute, so this cause a lot of pods with such error, 
for the EKS version 1.21 we are not facing such issues

**Comment by mikutas** [comment]
As a workaround, we rolled back worker nodes to 1.21 [specifying AMI ID in launch template](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami) since with 1.22 cluster we can't specify releaseVersion to 1.21 in CreateNodegroup / UpdateNodegroupVersion API .

**Comment by cartermckinnon** [comment]
@mikutas you can specify a release version as it appears in our SSM parameters, e.g. 1.21.6-20220526. More info here: https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters-eks.html
