### ISSUE TITLE
EKS AMI with cuda 11.6

### ISSUE THREAD

**Issue by rodrigoscferraz** [awslabs/amazon-eks-ami#915]
**What would you like to be added**: cuda 11.6 support for accelerated EKS AMI

**Why is this needed**: Some of our machine learning apps already use 11.6 version but I didn't find a way to upgrade the AMI( I don't even know if it is possible)

**Comment by BrewedCoffee** [comment]
Did you ever find a way to upgrade CUDA?

**Comment by singhnix** [comment]
few more customers looking for this version to be added in the repository.

**Comment by korjek** [comment]
we are also interested in getting AMI with a newer version of cuda (at least 11.6)
