### ISSUE TITLE
kubelet cluster-dns flag

### ISSUE THREAD

**Issue by manojbadam** [awslabs/amazon-eks-ami#92]
Just wanted to double check, If I read the bootstrap [script](https://github.com/awslabs/amazon-eks-ami/blob/cae0ac43912deea6c78da869e53328376410535b/files/bootstrap.sh#L104-L106) correctly, kube-dns will always be having either of these IP's (172.20.0.10, 10.100.0.10). So EKS takes care of setting up these kube-dns svc ClusterIP ? What happens if I have a VPC with CIDR blocks ?

Also any suggestions on how to approach if we were to use coreDNS instead of kube-dns ?

**Comment by micahhausler** [comment]
Yes, EKS coordinates one of these IP's based on your network space. 

You can't have a VPC with both those network blocks in the same VPC, so it shouldn't be a problem. 

You are free to use coreDNS, there shouldn't be a problem, but you will need to coordinate setting the DNS service IP for your nodes. You could just update the kube-dns service to use a different label selector and point it at your coreDNS pods instead of kube-dns.

**Comment by cpoole** [comment]
Sorry to revive this old question but I'd like some clarity here. 

To my knowledge the only method to ensure a service has a "static" cluster IP is to specify the `clusterIP` field in the service spec.  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#servicespec-v1-core

however, if I export the kube-dns service configured by EKS the clusterIP is not present.

```spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

If I am understanding this correctly deleting this service for any reason and recreating it would hose my cluster until I provide this in the spec. 

This seems surprisingly fragile, am I missing something?

**Comment by dominik-ba** [comment]
> 
> 
> Sorry to revive this old question but I'd like some clarity here.
> 
> To my knowledge the only method to ensure a service has a "static" cluster IP is to specify the `clusterIP` field in the service spec. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#servicespec-v1-core
> 
> however, if I export the kube-dns service configured by EKS the clusterIP is not present.
> 
> ```
>   ports:
>   - name: dns
>     port: 53
>     protocol: UDP
>     targetPort: 53
>   - name: dns-tcp
>     port: 53
>     protocol: TCP
>     targetPort: 53
>   selector:
>     k8s-app: kube-dns
>   sessionAffinity: None
>   type: ClusterIP
> status:
>   loadBalancer: {}
> ```
> 
> If I am understanding this correctly deleting this service for any reason and recreating it would hose my cluster until I provide this in the spec.
> 
> This seems surprisingly fragile, am I missing something?

If that is your complete .spec then that is correct.
If you missed a few lines copying, then that would explain confusions:

```
spec:
  clusterIP: 172.20.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```
