### ISSUE TITLE
Clarification on 5/13 Rollback AMI version

### ISSUE THREAD

**Issue by dgresh1** [awslabs/amazon-eks-ami#924]
Can someone please confirm what is the latest AMI version to use?   
getting these results for us-east-1, us-east-2 and us-west2.  Just want to make sure which ami date to specify.

aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-0fb604efcd6aaf3d5",
        "Version": 29,
        "LastModifiedDate": "2022-05-19T14:31:36.154000-05:00",
        "ARN": "arn:aws:ssm:us-east-1::parameter/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}

aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-09dd25549dd970de5",
        "Version": 29,
        "LastModifiedDate": "2022-05-19T14:26:19.487000-05:00",
        "ARN": "arn:aws:ssm:us-east-2::parameter/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}

aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id
{
    "Parameter": {
        "Name": "/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "Type": "String",
        "Value": "ami-07b7ea65cbbc3dc71",
        "Version": 29,
        "LastModifiedDate": "2022-05-19T14:26:31.343000-05:00",
        "ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id",
        "DataType": "text"
    }
}

**Comment by cartermckinnon** [comment]
The `v20220513` release inadvertently changed the format of the `release_version` found in our SSM parameters. This was the result of changes in our release process. The `v20220513` AMI is available in all regions and is safe to use. However, it will not be the default AMI used when creating nodegroups, and (as you noted) the values of our SSM parameters have been rolled back as part of our recovery process. To maximize backward compatibility, the `v20220429` release remains our recommended AMI.

We have corrected the issue in our release process, and will release an AMI that supersedes `v20220513` in the next few days.

**Comment by cartermckinnon** [comment]
I'm going to leave this issue open for the time being, in case there are any other questions we can answer. Sorry about the confusion!

**Comment by cartermckinnon** [comment]
The recalled release has been superseded by [v20220523](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220523), which contains all the fixes slated for the recalled release.
