### ISSUE TITLE
yum update broken

### ISSUE THREAD

**Issue by jhoovermitre** [awslabs/amazon-eks-ami#946]
**What happened**:  `sudo yum update` fails on fresh EC2 worker node.

**What you expected to happen**: The yum package to update successfully.

**How to reproduce it (as minimally and precisely as possible)**:  Spin up a new EKS worker node, SSH into it, attempt to run `sudo yum update`

**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): r6i.4xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.22
- AMI Version: amazon/amazon-eks-node-1.22-v20220526
- Kernel (e.g. `uname -a`): Linux ip-172-18-7-135.ec2.internal 5.4.190-107.353.amzn2.x86_64 #1 SMP Wed Apr 27 21:16:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-095b768df7dd20eee"
BUILD_TIME="Thu May 26 19:21:18 UTC 2022"
BUILD_KERNEL="5.4.190-107.353.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
@jhoovermitre can you provide more information about the error you're seeing? The full console output would be ideal.

**Comment by jhoovermitre** [comment]
Here is the full console output:
```
[ec2-user@ip-172-18-7-135 ~]$ sudo yum update
Loaded plugins: priorities, update-motd, versionlock
Resolving Dependencies
--> Running transaction check
---> Package python-devel.x86_64 0:2.7.18-1.amzn2.0.4 will be updated
---> Package python-devel.x86_64 0:2.7.18-1.amzn2.0.5 will be an update
--> Processing Conflict: python-devel-2.7.18-1.amzn2.0.5.x86_64 conflicts python < 2.7.18-1.amzn2.0.5
--> Finished Dependency Resolution
Error: python-devel conflicts with python-2.7.18-1.amzn2.0.4.x86_64
 You could try using --skip-broken to work around the problem
** Found 11 pre-existing rpmdb problem(s), 'yum check' output follows:
dracut-033-535.amzn2.1.6.x86_64 is a duplicate with dracut-033-535.amzn2.1.5.x86_64
libgcc-7.3.1-15.amzn2.x86_64 is a duplicate with libgcc-7.3.1-14.amzn2.x86_64
libstdc++-7.3.1-15.amzn2.x86_64 is a duplicate with libstdc++-7.3.1-14.amzn2.x86_64
2:microcode_ctl-2.1-47.amzn2.0.12.x86_64 is a duplicate with 2:microcode_ctl-2.1-47.amzn2.0.11.x86_64
1:openssl-libs-1.0.2k-24.amzn2.0.3.x86_64 is a duplicate with 1:openssl-libs-1.0.2k-24.amzn2.0.2.x86_64
python-2.7.18-1.amzn2.0.5.x86_64 is a duplicate with python-2.7.18-1.amzn2.0.4.x86_64
python-libs-2.7.18-1.amzn2.0.5.x86_64 is a duplicate with python-libs-2.7.18-1.amzn2.0.4.x86_64
systemd-219-78.amzn2.0.18.x86_64 is a duplicate with systemd-219-78.amzn2.0.16.x86_64
systemd-libs-219-78.amzn2.0.18.x86_64 is a duplicate with systemd-libs-219-78.amzn2.0.16.x86_64
2:vim-data-8.2.4857-1.amzn2.0.1.noarch is a duplicate with 2:vim-data-8.2.4428-1.amzn2.0.3.noarch
2:vim-minimal-8.2.4857-1.amzn2.0.1.x86_64 is a duplicate with 2:vim-minimal-8.2.4428-1.amzn2.0.3.x86_64

```

**Comment by cartermckinnon** [comment]
My best guess is that a version-locked package is preventing its python dependency from being updated, causing this conflict. Removing the version-lock may be fine, depending on your use-case; but you may see instability as a result. Please update this issue if you're still seeing this on the latest AMI release.
