### ISSUE TITLE
Update aws-iam-authenticator Binary to 0.5.9

### ISSUE THREAD

**Issue by chickenbeef** [awslabs/amazon-eks-ami#966]
**What happened**:

A security bulletin was posted on 2022/07/11 noting a vulnerability in the aws-iam-authenticator. The recommendation is to update to aws-iam-authenticator v0.5.9 or later.

https://aws.amazon.com/security/security-bulletins/AWS-2022-007/

While the issue identified in the bulletin only affects the server side implementation, it would be great if the aws-iam-authenticator in the EKS AMI can be updated at regular intervals. If there is a vulnerability found on the client side on an older version of the authenticator, it means that we'll have a number of EKS AMI releases being affected when we could have reduced the blast radius by keeping the dependencies in the AMI updated.

The latest release of the EKS AMI (v20220629) still references aws-iam-authenticator v0.5.0 - this version was released in Jan 2020. The latest version of the aws-iam-authenticator at present is v0.5.9.

**What you expected to happen**:

The latest version of the aws-iam-authenticator should be installed.

**How to reproduce it (as minimally and precisely as possible)**:

Build an AMI and the version of the aws-iam-authenticator that is installed is v0.5.0.

The binary is downloaded from this URL:
https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.15/2022-06-20/bin/linux/amd64/aws-iam-authenticator

I could not find a newer binary by playing around with the dates and versions in the URL.

**Anything else we need to know?**:

Once a new binary is published, the EKS documentation can also be updated with a new URL pointing to the 0.5.9 binary:
https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html

**Environment**:
- AWS Region: All
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): All
- AMI Version: v20220629

**Comment by cartermckinnon** [comment]
My understanding is [this issue](https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/415bb8d71e08b41e2c57071c4abdc08ea210afaa) was in `aws-iam-authenticator server`, not the client-side operation used in this AMI. Using the older version on your nodes is not a security risk, though we'll update this in a future AMI release to stay up-to-date.

**Comment by cartermckinnon** [comment]
This was addressed in https://github.com/awslabs/amazon-eks-ami/releases/tag/v20221112 and with the `2022-10-31` batch of binaries.
