### ISSUE TITLE
[EKS Windows][Feature Request]:: Collecting windows containerd logs using eks log collector 

### ISSUE THREAD

**Issue by angelaaaaaaaw** [awslabs/amazon-eks-ami#977]
**What would you like to be added**:

Collecting containerd logs while running eks log collector for windows,  Please see the sample code attached here - https://raw.githubusercontent.com/angelaaaaaaaw/windows-containerd/main/windows-eks-logcollector-contained.ps1

**Why is this needed**:

Windows support for containerd runtime on EKS starting with Kubernetes 1.21, customer has been adopting contained as runtime, however eks log collector script as of now only collects docker log but not collecting containerd runtime log.

**Comment by cartermckinnon** [comment]
This repo is dedicated to the AL2-based EKS AMI; please open an issue on https://github.com/aws/containers-roadmap 

(I'm not able to transfer the issue for you, because that repo is in a different GitHub org).
