### ISSUE TITLE
Bring back EKS AMI versions in AWS documentation

### ISSUE THREAD

**Issue by cg-lkusnadi** [awslabs/amazon-eks-ami#996]
I used to be able to visit https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html to get a list of valid AMI versions for EKS.

Now, the list is gone.

I have to visit https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md, do information stitching with trial and error to get the right AMI versions.

Example:
What's the corresponding version for AMI Release v20220811?

To figure out major and minor version of supported k8s, I need to get it from S3 location: s3://amazon-eks/1.22.12/2022-07-27/

Thus, a valid version is: 1.22.12-20220811.

Why this version is important?

CDK EKS Cluster class has an implementation add_nodegroup_capacity that  supports release_version.
We need to make it easy to find out what version is available. Above method IS NOT easy.

**Comment by cartermckinnon** [comment]
You can fetch the `release_version` from [our SSM parameters](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html), like:
```
aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.23/amazon-linux-2/recommended/release_version
```

Or, you can omit the `release_version` from [the nodegroup options](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.NodegroupOptions.html) and the latest AMI for your cluster's k8s version will be selected.

I think it makes sense to include the `release_version` in our GitHub release notes, too; I'll see what I can do. 👍

**Comment by cg-lkusnadi** [comment]
Thanks @cartermckinnon
